- seeds/breadboard-cli-tools/package.json
- seeds/breadboard-cli-tools/src/commands/lib/utils.ts
- seeds/breadboard-cli-tools/src/commands/make-graph.ts
- seeds/breadboard-cli-tools/src/commands/mermaid.ts
- seeds/breadboard-cli-tools/src/commands/run.ts
- seeds/breadboard-cli-tools/src/index.ts
Adds the ability to pass in a typescript file (it will use `esbuild` to convert to js). If this is used, then you also need to pass in `--output` so you can direct where the converted file will be saved.
This is then essentially hot-module reload.
> [breadboard-cli-tools] Can now import typescript, and hot-reload

- seeds/breadboard-ui/src/input.ts
- seeds/breadboard-ui/src/ui-controller.ts
Working on #160 a bit. This PR adds expand-collapse behaviors for the sidebar so that you can toggle the visibility of inputs, outputs, and history. I also reordered them so it's inputs, outputs, and history in that order. Feels a little more intuitive.
> [breadboard-ui] Tweak sidebar

- seeds/breadboard-ui/src/ui-controller.ts
Fixes a little oopsie where the node info was being retained when the board changed.
> [breadboard-ui] Remove node info when board changes

- seeds/breadboard-cli-tools/README.md
- seeds/breadboard-cli-tools/src/commands/debug.ts
- seeds/breadboard-cli-tools/src/commands/lib/utils.ts
- seeds/breadboard-cli-tools/src/commands/make-graph.ts
- seeds/breadboard-cli-tools/src/commands/mermaid.ts
- seeds/breadboard-cli-tools/src/commands/run.ts
- seeds/breadboard-cli-tools/src/index.ts
+ Debug server can now accept a list of boards from a directory
+ Debug server can watch for changes in the inputted file or boards and refresh the dropdown (on-reload)
+ Debug should also convert TS on the fly
Other
====
+ Refactored fs.watch to be shared across commands
+ Reformatted code.
> [breadboard-cli-tools] watch and debug server

- seeds/breadboard/breadboard.schema.json
- seeds/breadboard/package.json
Adds `breadboard.schema.json`, a JSON schema that describes breadboard graph JSON files.
A few things to note:
- Identifiers must match the pattern `^[a-zA-Z_][a-zA-Z0-9_-]*$`. This applies to node IDs, node types, input/output ports, and graph IDs. This is similar to valid JS identifiers, but adds `-` because we're already using `-` in our auto-generated node IDs.
- It's strict about what are valid `in` and `out` arrangements. Either both are identifiers, both are empty/undefined, or `in` is `*` and `out` is empty/undefined.
- I'm using the word "port" to refer to node inputs/outputs, as in "I wired the foo port of X to the bar port of Y".
- I'm using the GitHub raw endpoint as the ID. If we get a domain we might want to publish it there as `<our-domain>/schema.json` or something to make …
> Add a Breadboard JSON schema

- package-lock.json
- seeds/breadboard-cli/boards/echo.yaml
- seeds/breadboard-cli/package.json
- seeds/breadboard-cli/src/commands/lib/loader.ts
- seeds/breadboard-cli/src/commands/lib/loaders/index.ts
- seeds/breadboard-cli/src/commands/lib/loaders/javascript.ts
- seeds/breadboard-cli/src/commands/lib/loaders/json.ts
- seeds/breadboard-cli/src/commands/lib/loaders/typescript.ts
- seeds/breadboard-cli/src/commands/lib/loaders/yaml.ts
- seeds/breadboard-cli/src/commands/lib/utils.ts
- seeds/breadboard-cli/src/commands/make-graph.ts
The utils file was getting messy.
We can now quickly load new types of formats that store board information.  In this PR we also had in a YAML loader (as mentioned in #219) as an experiment.
> [breadboard-cli] Refactoring the Loaders.

- seeds/breadboard-cli/src/commands/lib/loader.ts
- seeds/breadboard-cli/src/commands/make-graph.ts
- seeds/breadboard-cli/src/commands/mermaid.ts
- seeds/breadboard-cli/src/commands/run.ts
+ removing requirement for `-o` when compiling to TS.
+ make graph can input YAML
+ ensure that the temp file being created isn't already a directory.
> [breadboard-cli] Removing the requirement for `-o` when compiling TS

- packages/breadboard/src/new/runner/kits.ts
- packages/breadboard/src/new/runner/node.ts
- packages/breadboard/src/new/runner/scope.ts
- packages/breadboard/src/new/runner/types.ts
- packages/breadboard/tests/helpers/_test-kit.ts
- packages/breadboard/tests/new/recipe-grammar/serialize-and-run-with-old-runner.ts
- packages/breadboard/tests/new/runner/default-schemas.ts
When the input and output nodes don't have schemas, derive them from the graph, calling its neighboring nodes' describe functions.
Implements #155.
> [breadboard/new] automatically derive missing input/output schemas

- packages/breadboard-web/public/graphs/openai-gpt-35-turbo.json
- packages/breadboard-web/public/graphs/openai-gpt-4-vision.json
- packages/breadboard-web/public/graphs/tour-guide-writer.json
- packages/breadboard/tests/new/runner/default-schemas.ts
These are for internal lambdas, so don't affect execution in the web ui.
> [breadboard-web] add automatically derived schemas

- packages/breadboard-web/docs/graphs/openai-gpt-35-turbo.md
- packages/breadboard-web/docs/graphs/openai-gpt-4-vision.md
- packages/breadboard-web/public/graphs/openai-gpt-35-turbo.json
- packages/breadboard-web/public/graphs/openai-gpt-4-vision.json
- packages/breadboard-web/src/boards/openai-chunk-transformer.ts
- packages/breadboard-web/src/boards/openai-gpt-35-turbo.ts
- packages/breadboard-web/src/boards/openai-gpt-4-vision.ts
- packages/breadboard/src/new/recipe-grammar/node.ts
- packages/breadboard/src/new/recipe-grammar/recipe.ts
- packages/breadboard/src/new/recipe-grammar/types.ts
- packages/breadboard/tests/new/recipe-grammar/lambdas.ts
When passing a lambda that is a self-contained recipe, then no longer add extra lambda nodes.
This allows `import { aRecipe } from "elsewhere"` and then using that recipe, either as is or as lambda in a new board.
Note that if one imports an actual closure like this, then you are creating a closure by using it and right now it'll serialize everything that is connected. In practice there should be no need to include closures like this (instead the entire closure should be wrapped in a recipe), so this should probably produce an error on serialize. That is, we allow serializing self-contained recipes that are defined outside of the scope of the serialized recipe, but we don't allow including _nodes_ that are outside a serialized recipe. Note that the regular way to serialize a closure is to …
> [breadboard/new] don't use lambda nodes for non-closures

- packages/breadboard/src/new/recipe-grammar/node.ts
- packages/breadboard/src/new/runner/scope.ts
- packages/breadboard/tests/new/recipe-grammar/invoke-by-await.ts
- packages/breadboard/tests/new/runner/no-infinite-runs.ts
(Instead of just never returning!)
Returns $error noting
- the last node actually ran,
- nodes that were adjacent to invoked nodes with their missing inputs
Fixed missing error handling as well.
> [breadboard/new] add useful debug information when not reaching an output node.

- package-lock.json
- packages/breadboard-web/src/boards/gemini-pro-vision.ts
- packages/breadboard-web/src/boards/mock-text-generator.ts
- packages/breadboard-web/src/boards/palm-text-generator.ts
- packages/breadboard-web/src/boards/text-generator.ts
- packages/breadboard-web/src/boards/tour-guide-writer.ts
- packages/breadboard/src/index.ts
- packages/breadboard/src/new/recipe-grammar/recipe.ts
- packages/breadboard/tests/new/recipe-grammar/invoke-by-await.ts
- packages/breadboard/tests/new/recipe-grammar/recipe-as-code.ts
- packages/breadboard/tests/new/recipe-grammar/recipe-overloads.ts
- packages/breadboard/tests/new/recipe-grammar/serialize-and-run-with-old-runner.ts
removed all other variants, now it's just `recipe` and `code`:
Use `recipe` for graphs (runs at serialization time), `code` for anything else (runs only at runtime).
> [breadboard/new] renamed `recipeForCode` to `code`

- packages/breadboard/src/new/recipe-grammar/node.ts
- packages/breadboard/src/new/recipe-grammar/recipe.ts
- packages/breadboard/src/new/recipe-grammar/types.ts
- packages/breadboard/src/new/runner/node.ts
- packages/breadboard/src/new/runner/scope.ts
- packages/breadboard/src/new/runner/types.ts
- packages/breadboard/tests/new/recipe-grammar/recipe-overloads.ts
- packages/breadboard/tests/new/runner/pinning-scopes.ts
the function passed to recipe() can now accept a second parameter `base` that is a base kit.
if using that to create a graph, then there is no longer any need to return something.
> [breadboard/new] allow recipe construction without return value

- packages/breadboard-ui/src/diagram.ts
Realised I was asserting when I should just exit a function. This PR fixes that.
> [breadboard-ui] Fix incorrect assertion

- packages/breadboard/src/new/recipe-grammar/node.ts
- packages/breadboard/src/new/recipe-grammar/recipe.ts
- packages/breadboard/src/new/recipe-grammar/scope.ts
- packages/breadboard/src/new/recipe-grammar/types.ts
- packages/breadboard/src/new/runner/node.ts
- packages/breadboard/src/new/runner/scope.ts
- packages/breadboard/src/new/runner/types.ts
- packages/breadboard/tests/new/recipe-grammar/lambdas.ts
- packages/breadboard/tests/new/recipe-grammar/recipe-as-code.ts
Nested `recipe()` calls can now refer to nodes from upper scopes and
the framework will automatically wire the underlying lambdas together.
E.g. see how `bar` is defined at the top, but not passed through the caller,
which calls the lambda? That is now happening under the hood:
```ts
const graph = recipe(({ foo, bar }) => {
const lambda = recipe(({ foo }) => testKit.noop({ foo, bar }));
const caller = recipe(({ lambda, foo }) => {
return lambda({ foo });
});
return caller({ lambda, foo });
});
```
> [breadboard/new] automatically wire closure wires

- packages/breadboard-ui/src/input.ts
- packages/breadboard-ui/src/load.ts
- packages/breadboard-ui/src/output.ts
- packages/breadboard-ui/src/ui-controller.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/harness/diagnostics.ts
- packages/breadboard/src/harness/local-harness.ts
- packages/breadboard/src/harness/secrets.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/harness/worker-harness.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/src/utils/async-gen.ts
- packages/breadboard/src/worker/protocol.ts
- packages/breadboard/src/worker/worker-runtime.ts
- packages/breadboard/tests/board.ts
- packages/breadboard/tests/utils/async-gen.ts
- Nicer types. So nice.
- Remove spurious logging.
- Introduce Diagnostics probe and start using it.
- Teach asyncGen to handle non-awaited 'next' invocations.
- Wire up 'diagnostics' config value.
- Don't listen to diagnostic results in LocalHarness.
> [breadboard-web] Nicer types and diagnostics.

- packages/breadboard-web/src/index.ts
- packages/breadboard/src/harness/local-harness.ts
- packages/breadboard/src/harness/result.ts
- packages/breadboard/src/harness/secrets.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/harness/worker-harness.ts
- packages/breadboard/src/worker/protocol.ts
- Fold 'url' into HarnessConfig.
- Separate load and run in Harness.
- Teach LocalHarness about 'shutdown' result.
- Tighten up types.
- Remove 'shutdown' message, since it's not useful anymore.
- Turn 'load' method into a simple async call.
> [breadboard/harness] Separate 'load' and 'run' calls.

- packages/breadboard-ui/src/history-entry.ts
- packages/breadboard-ui/src/types.ts
- packages/breadboard-ui/src/ui-controller.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/harness/diagnostics.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/remote/protocol.ts
- packages/breadboard/src/remote/run.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/src/types.ts
- packages/breadboard/src/worker/controller.ts
- packages/breadboard/tests/remote/transport.ts
- Plumb through invocationId.
- Remove unused #pending property.
- Move worker communication logging to debug level.
- Oops, add missing invocationId.
- Remove spurious logging.
- Plumb 'beforehandler' and 'afterhandler' to UI Controller.
- Added some rudimentary UI code.
> [breadboard-web] Compose richer history of the run.

- packages/breadboard-ui/src/history-entry.ts
- packages/breadboard-ui/src/index.ts
- packages/breadboard-ui/src/types.ts
- packages/breadboard-ui/src/ui-controller.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/harness/diagnostics.ts
- packages/breadboard/src/harness/local-harness.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/remote/protocol.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/src/types.ts
- packages/breadboard/src/worker/protocol.ts
- packages/breadboard/src/worker/worker-runtime.ts
- packages/core-kit/src/nodes/map.ts
- Minor style tweaks to probe invocations.
- Introduce Probe interface and start reporting stuff.
- Plumb graphstart/graphend to harnesses.
- Retool for invocationPath, rather than invocationId.
- Rename HarnessEventType to HistoryEventType.
- Change historyEntry controller methods to deal with obj args.
- Add GRAPHSTART and GRAPHEND history events.
- Type-fu.
- Start using path for generating HistoryEntry ids.
> [breadboard] Introduce 'graphstart' and 'graphend' results.

- packages/breadboard-cli/src/commands/lib/verbose-logging-probe.ts
- packages/breadboard-cli/src/commands/mermaid.ts
- packages/breadboard-cli/src/commands/run.ts
- packages/breadboard-cli/src/index.ts
Adds a simple Probe to the CLI.
Adds a command `-v` or `--verbose` and it will output all of the log events to `STDOUT`
This should also work well with `--watch` so as you edit the board you will see your fixes process.
> [breadboard-cli] Adding --verbose logging to the run command

- packages/breadboard/src/remote/index.ts
- packages/breadboard/src/remote/worker.ts
- packages/breadboard/src/stream.ts
- packages/breadboard/src/types.ts
- packages/breadboard/src/worker/controller.ts
- packages/breadboard/tests/stream.ts
- Rip out some never-realized early ideas about syntax.
- Sketch out WorkerClientTransport and WorkerServerTransport.
- Patch up MessageController to work with new transports.
- Introduce 'streamsToAsyncIterable' helper.
> [breadboard/remote] Add Worker transports.

- packages/breadboard-ui/src/history-entry.ts
- packages/breadboard-ui/src/types.ts
- packages/breadboard-ui/src/ui-controller.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/harness/diagnostics.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/harness/worker-harness.ts
- packages/breadboard/src/new/runner/runner.ts
- packages/breadboard/src/remote/protocol.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/src/types.ts
- packages/breadboard/src/worker/index.ts
- packages/breadboard/src/worker/protocol.ts
- packages/breadboard/tests/remote/transport.ts
- packages/graph-playground/src/index.ts
- Rename 'beforehandler' to 'nodestart'.
- Rename 'afterhandler' to 'nodeend'.
> [breadboard] 'beforehandler', 'afterhandler' -> 'nodestart', 'nodeend'.

- packages/breadboard-server/tests/writer.ts
- packages/breadboard-ui/src/input.ts
- packages/breadboard/src/bubble.ts
- packages/breadboard/src/remote/run.ts
- packages/breadboard/src/run.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/src/types.ts
- Start emitting 'nodestart' and 'nodeend' for input/output nodes.
- Fix a typo in Breadboard UI 'input' element.
> [breadboard] Emit `nodestart` and `nodeend` results for inputs and outputs.

- packages/breadboard/src/remote/protocol.ts
- packages/breadboard/src/remote/proxy.ts
- packages/breadboard/src/remote/worker.ts
- packages/breadboard/src/stream.ts
- packages/breadboard/tests/helpers/_test-transport.ts
- packages/breadboard/tests/remote/proxy.ts
- packages/breadboard/tests/remote/transport.ts
- packages/breadboard/tests/remote/worker.ts
- packages/breadboard/tests/stream.ts
- Introduce 'streamFromReader'.
- Introduce 'streamFromWriter'.
- Switch WorkerClientTransport to retain readers/writers.
- Introduce 'createMockWorkers' and replace 'MockWorkerTransport' with it.
- Introduce 'portFactoryToStreams'.
- Teach WorkerServerTransport to use portFactoryToStreams.
- Teach Worker transports to work with proxy.
- Add ability to shutdown ProxyServer from ProxyClient.
> [breadboard] Tech up Worker transports and Proxy machinery.

- packages/breadboard-ui/src/deprecated-ui-controller.ts
- packages/breadboard-ui/src/index.ts
This deprecates the old UI controller because it's not needed. I didn't remove it because I want to give it a once over tomorrow and just check that all the functionality has been brought over to the new UI controller.
> [breadboard-ui] Deprecate old UI controller

- packages/breadboard/src/new/recipe-grammar/node.ts
- packages/breadboard/src/new/recipe-grammar/types.ts
- packages/breadboard/src/new/recipe-grammar/value.ts
- packages/breadboard/src/new/runner/node.ts
- packages/breadboard/src/new/runner/scope.ts
- packages/breadboard/src/new/runner/types.ts
- packages/breadboard/tests/new/recipe-grammar/serialize-and-run-with-old-runner.ts
- packages/breadboard/tests/new/runner/default-schemas.ts
Example:
```
recipe(({ a, b }) => {
const { c, d } = core.passthrough({ c: a.isNumber(), d: b.isString() });
return { c: c.isNumber(), d: d.isString() };
});
```
Adds a type annotation on the `a` and `b` inputs and `c` and `d` outputs, which will be reflected in the inferred schema.
(Next up is inferring c, d automatically)
> [breadboard/new] Add .is<String|Number|...> to wires, use to infer schemas

- packages/breadboard/src/new/recipe-grammar/types.ts
- packages/breadboard/src/new/recipe-grammar/value.ts
- packages/breadboard/tests/new/runner/default-schemas.ts
In addition to .isString(), etc. this allows setting title and descriptions of the schema.
This should now be enough to no longer need to pass a whole `schema` to `input` and `output` and instead derive the schema from the connected wires. Types are still quite basic, but it should be easy to add the next set of needed features.
> allow .title() and .description() on values, use in schema inference

- packages/breadboard/src/new/runner/scope.ts
- packages/breadboard/tests/helpers/_test-kit.ts
- packages/breadboard/tests/new/runner/default-schemas.ts
`describe` functions on handlers now receive schemas placed via `.isString()`, `.title()`, etc. on their incoming and outgoing wires.
> Pass wire schemas to describe

- packages/breadboard-ui/src/history-tree.ts
- packages/breadboard-ui/src/ui.ts
- packages/breadboard-web/src/index.ts
This fixes a couple of issues, namely:
1. We weren't creating history entries for `graphstart`, which meant that sometimes we'd have a child node with no parent. This resulted in out-of-order listings.
2. Expand-collapse behavior of the history tree didn't honor the parent node status, which meant that you could collapse a grandparent but still see the grandchildren because the parent node was still set to visible.
This PR also introduces a depth color, the idea being that the deeper a node's path, the more saturated its row color is. This seems to be quite a useful visual marker for subgraphs.
@dglazkov I noticed in Board Caller that we get `nodestart` and `graphstart` paths that are identical, which seems a bit unusual to me. For example, I'd see a subgraph start and there'd be a …
> [breadboard-ui/-web] Tweaks to history UI

- packages/breadboard-web/src/worker.ts
- packages/breadboard/src/harness/worker-harness.ts
- packages/breadboard/src/remote/index.ts
- packages/breadboard/src/remote/run.ts
- packages/breadboard/src/remote/worker.ts
- packages/breadboard/src/worker/controller.ts
- packages/breadboard/tests/remote/http.ts
- packages/breadboard/tests/remote/proxy.ts
- packages/breadboard/tests/remote/transport.ts
- packages/breadboard/tests/remote/worker.ts
- Introduce PortDispatcher.
- Switch to use PortDispatcher.
- Remove 'proxy' TODO from RunClient.
> [breadboard] Introduce `PortDispatcher` to handle multiple worker client/servers."

- packages/breadboard-ui/src/history-tree.ts
- packages/breadboard-ui/src/types.ts
- packages/breadboard-ui/src/ui.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/index.ts
- packages/breadboard/src/remote/protocol.ts
- packages/breadboard/src/types.ts
Having spoken with @dglazkov I realised that `nodestart` is the "key" event through which we can drive the history log. In other words the `input`, `output`, and `secret` events that were being created as a side effect of the other UI work can be removed.
This PR makes a few changes:
1. It removes the any entry that isn't `nodestart|end` or `graphstart|end`.
2. It uses the state object from the `nodestart` to populate an "input" area in the entry's value field. (There isn't any corresponding state in the `nodeend` for us to update the "output" side as yet.
3. It moves each `graphstart` event before its neighboring `nodestart` event. Right now we emit the `graphstart` after the `nodestart` for a subgraph, and that makes things look a bit peculiar; intuitively I think you want to see …
> [breadboard-ui] Dedupe input/output/secret log entries

- packages/breadboard-ui/src/types.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/index.ts
- packages/breadboard/src/remote/protocol.ts
- packages/breadboard/src/types.ts
- packages/breadboard/src/worker/controller.ts
- packages/breadboard/src/worker/index.ts
- packages/breadboard/src/worker/protocol.ts
- packages/breadboard/tests/remote/transport.ts
- Trim `MessageController` to size.
- Make `MessageController` more forgiving.
- Rename `InputPromiseResponse*` to `InputResponse*`.
- Clean up unused types.
- Move data types from `remote` to `types`.
- Continue massaging response types.
- Just export all types in `breadboard/src/types.ts`.
> [breadboard] Massage and align types a bit.

- packages/breadboard-ui/src/history-tree.ts
- packages/breadboard-ui/src/ui.ts
- packages/breadboard-web/src/index.ts
I noticed that we don't update the last event time in the `#updateHistoryEntry` function, which we should. This means that we don't get live updates to the history in every case. We also need to key the JSON view off the last updated time so that Lit knows to re-render.
> [breadboard-ui] Include last event time in updates

- packages/breadboard/src/new/recipe-grammar/node.ts
- packages/breadboard/src/new/runner/node.ts
- packages/breadboard/src/new/runner/runner.ts
- packages/breadboard/src/new/runner/scope.ts
- packages/breadboard/src/new/runner/state.ts
- packages/breadboard/src/new/runner/types.ts
- packages/breadboard/tests/new/runner/state.ts
Refactored state out of `Node` classes, which is cleaner, but also necessary because the same node instance could appear in different concurrent dynamic scopes down the road.
Now all the logic about triggering nodes, moving data between nodes, etc. are all in one place.
> Extract state from node

- packages/breadboard/src/new/recipe-grammar/node.ts
- packages/breadboard/src/new/runner/node.ts
- packages/breadboard/src/new/runner/runner.ts
- packages/breadboard/src/new/runner/scope.ts
- packages/breadboard/src/new/runner/types.ts
- packages/breadboard/tests/new/runner/abort-early-in-invokeOnce.ts
- packages/breadboard/tests/new/runner/pinning-scopes.ts
`invokeOneRound` (formerly `invokeOnce`) accepts and returns `$state` to enable calling a recipe over multiple rounds.
Currently returns after the first output, next up is
- switch that to returning `$state` when hitting an input after hitting any output (i.e. a complete round), or nothing when done
- (much later, once parallel running works well): Change invoking of graphs so that any output's node data will be immediately distributed, not just when they are all combined
> [breadboard/new] Return $state after each round

- packages/breadboard-web/docs/graphs/agent.md
- packages/breadboard-web/public/graphs/agent.json
- packages/breadboard-web/public/local-boards.json
- packages/breadboard-web/src/boards/agent.ts
- packages/breadboard/src/new/recipe-grammar/types.ts
- packages/breadboard/src/new/recipe-grammar/value.ts
- Add support for `examples` Schema field.
- Add the seedling of an agent.
- Teach agent to assemble full context.
> [breadboard-web] Add a simple agent board.

- .github/workflows/publish.yml
- Specify the registry during setup-node step
- Pin to specific actions versions.
- Don't run the sync command.
> Misc changes for publish workflow

- packages/breadboard-ui/src/ui.ts
This adds a little more info when we receive `nodestart` and `nodeend` events in the UI
> [breadboard-ui] Log node info

- packages/breadboard-ui/src/ui.ts
Fixes a minor issue where the toasts weren't showing.
> [breadboard-ui] Show Toasts atop other elements

- packages/breadboard-ui/src/input-list.ts
- packages/breadboard-ui/src/ui.ts
I was basing the inputs on `nodestart` nodes, but it turns out it's better to use `inputArguments` from the `input` nodes. So that's what this PR changes.
> [breadboard-ui] Use inputArguments for inputs

- packages/breadboard-ui/src/history-tree.ts
- packages/breadboard-ui/src/timeline-controls.ts
I noticed that the default rendering of a large timeline wasn't particularly performant, mostly because we're there are style properties that aren't necessarily cached, and which cause a re-render. This PR adds a guard around both the tracks and the marker so that they are only re-rendered when absolutely necessary.
On a related note, I really like Lit Element and how much easier it makes doing this kind of work 💖
> [breadboard-ui] Performance improvements

- packages/breadboard/src/new/recipe-grammar/base.ts
- packages/breadboard/tests/new/recipe-grammar/serialize-and-run-with-old-runner.ts
Fixes #369 (`base.input()`, `output()` should not require parameters)
> [breadboard/new] input and output don't require config

- packages/breadboard/src/serialization.ts
There was a circular dependency caused by this import chain:
`board.ts > runner.ts > serialization.ts > index.ts > board.ts` (a few other paths too, but the `serialization.ts > index.ts` import is the culprit in all cases).
This could cause errors like:
```
export class Board extends BoardRunner {
^
ReferenceError: Cannot access 'BoardRunner' before initialization
```
because depending on where you enter that loop, you could end up executing `board.js` before `runner.js`.
This fix is to import `MachineResult` and `TraversalMachine` directly from their source files, instead of via `index.js.
> Break circular dependency in import graph

- packages/breadboard-ui/src/elements/diagram/diagram.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.styles.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-ui/src/types/types.ts
- packages/breadboard-web/index.html
- packages/breadboard-web/src/index.ts
Use [Visual Blocks](https://github.com/google/visualblocks) to display the graph of a breadboard. For now, you need to manually add the url query parameter `&visualizer=visualblocks` to activate the new visualizer, but we can add a button to switch between them.
Also, there's a known issue with the Visual Blocks custom element where you need to reload the page after switching graphs. This should be fixed soon.
> Add a visualizer based on Visual Blocks to breadboard-web

- .gitignore
- package-lock.json
- packages/breadboard-cli/package.json
- packages/breadboard-cli/src/commands/debug.ts
- packages/breadboard-cli/src/debugger/index.html
- packages/breadboard-cli/src/debugger/preview.html
- packages/breadboard-cli/src/debugger/worker.ts
- packages/breadboard-cli/tsconfig.json
- packages/breadboard-cli/vite.config.ts
- packages/breadboard-web/package.json
- packages/breadboard-web/src/config.ts
- packages/breadboard-web/tsconfig.json
- packages/breadboard/src/harness/index.ts
We currently copy in the `dist` from breadboard-web into `dist/ui` so that we can run the debugger. This PR changes things so that we now have an additional vite-backed build that generates `dist/debugger`. I've created three entry points: `index.html`, `preview.html` and `worker.ts` and, inside each, I pull in the parts of `breadboard-web` that are needed. 
This allows us to treat `breadboard-web` as an "out-of-tree" dependency if we so desire.
> [breadboard-cli] Use debugger/web as a dependency

- packages/breadboard-cli/package.json
- packages/breadboard-cli/src/bundle/index.html
- packages/breadboard-cli/src/bundle/worker.ts
- packages/breadboard-cli/src/commands/bundle.ts
- packages/breadboard-cli/src/index.ts
- packages/breadboard-web/src/preview.ts
Adds the ability to call `breadboard bundle /path/to/board.json`. This will create a deployable web app based on the Debugger's Preview view.
> [breadboard-cli] Add bundle option

- packages/breadboard-cli/vite.config.ts
It turns out that `import.meta.resolve` is only available in node 20.6+. For now I'll pop a warning in to let a developer know that building without `resolve` might cause issues.
> [breadboard-cli] Add warning for nodejs

- packages/breadboard-cli/src/commands/debug.ts
- packages/breadboard-cli/vite.config.ts
This fixes a couple of issues:
1. For older nodejs installations we now use [createRequire](https://nodejs.org/docs/latest-v19.x/api/module.html#modulecreaterequirefilename) to try and get to the `breadboard-web` dir.
2. The serving of the debugger was failing on the index because of the `cleanUrls` flag - it should now work
> [breadboard-cli] Fix resolver & URLs

- packages/breadboard-cli/src/commands/debug.ts
- packages/breadboard-cli/src/debugger/index.html
- recipes/use-case/fetch-atom/index.js
- recipes/use-case/fetch-rss/index.js
- recipes/use-case/search-google/index.js
Loads the boards so whatever is input is accessible via the temp server.
Also fixes some boards that used `recipe(async ...`
> [breadboard-cli] Tweaks to debug

- packages/breadboard-server/tests/writer.ts
- packages/breadboard-ui/src/elements/history-tree/history-tree.ts
- packages/breadboard-ui/src/elements/input/input-list/input-list.ts
- packages/breadboard-ui/src/elements/output/output-list/output-list.ts
- packages/breadboard-ui/src/elements/timeline-controls/timeline-controls.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-ui/src/types/types.ts
- packages/breadboard/src/bubble.ts
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/harness/worker.ts
- packages/breadboard/src/index.ts
- packages/breadboard/src/remote.ts
- packages/breadboard/src/remote/protocol.ts
- packages/breadboard/src/remote/run.ts
- packages/breadboard/src/run.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/src/serialization.ts
- packages/breadboard/src/stack.ts
- packages/breadboard/src/traversal/machine.ts
- packages/breadboard/src/types.ts
- packages/breadboard/tests/remote/transport.ts
- Sketch out StackManager.
- Shape the `stack.state()` a bit.
- Rename `prepareToSafe` to `prepareToSave`.
- Switch `state` to be on `MessageProbe`.
- Unify state under `RunState` type.
- Move `RunState` to `breadboard/src/types.ts`.
- Switch to use stack-based RunState.
- Start using the new RunState.
> [breadboard] Implement stack-based 'RunState'.

- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
When switching graphs, ui-controller tries to load visual-breadboard again, which throws an error since that custom web component is already loaded from the previous graph. Check if the `visual-breadboard` component already exists in the custom component registry before loading it.
Also, update to a newer visual-breadboard build that fixes css issues and properly wraps incoming calls in ngzone.
> Fix registering visual-breadboard multiple times

- packages/breadboard/docs/tutorial/README.md
Made two changes:
- turned the relative path into an absolute one to avoid worrying about the fact that Board.load() uses relative paths from the node module instead of the script to execute
- added the missing dependencies on PaLMKit and config() to get the secrets so that this code runs in a separate file
> Fixing the code in Tutorial 4

- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
I noticed earlier when @dglazkov was showing me something that the graph was re-rendering unnecessarily. This adds a guard around it to prevent that from happening.
> [breadboard-ui] Add guard around VB render

- package-lock.json
- packages/breadboard-web/src/boards/math-imperative.ts
- packages/core-kit/README.md
- packages/core-kit/src/index.ts
- packages/json-kit/src/index.ts
- packages/template-kit/README.md
- packages/template-kit/src/index.ts
- Tighten up some types and write docs.
- Express `invoke` inputs more accurately.
> [breadboard] Tighten some types in new-syntax kits.

- packages/breadboard-extension/src/breadboard-loader.ts
- packages/breadboard-extension/src/extension.ts
Since I now have code that can convert TS to the graph JSON on the fly, I'm moving it to a separate file. That way I can reuse it in the Debugger Runtime and allow it to run from TS files like the renderer does.
> [breadboard-extension] Move transpilation out

- .changeset/honest-cups-glow.md
- package-lock.json
- packages/breadboard-ui/src/elements/input/input-list/input-list.ts
In the `input-list` we work through all the messages we've received so far. We do this so that we create the UI entirely from the messages received and we don't base it on any internal state. So that we can stack newer inputs first we work through the list backwards. When we find an input we then track forwards again to see if there are any subsequent messages we received that tell us what the input value should be. So, for example, an input in the middle of the messages that has already been answered by the user will have a subsequent message with its value set. We use that to populate the field and make it readonly.
There was a bug in the code where we do that, and it wasn't traversing correctly. As such it would mistakenly switch off inputs we'd already seen because it would find an …
> [breadboard-ui] Fix for inputs failing to ask for data

- .changeset/spicy-peas-film.md
- .gitignore
- packages/breadboard-extension/package.json
- packages/breadboard-extension/src/breadboard-debug-runtime.ts
- packages/breadboard-extension/src/breadboard-debug-session.ts
- packages/breadboard-extension/src/breadboard-loader.ts
- packages/breadboard-extension/src/extension.ts
To try and smooth things out a bit for choosing sub boards I've added a user configuration option. When a user runs the extension for the first time (or if they clear the setting), the extension will ask them where the JSON boards are located. It then uses this path whenever it encounters an input value whose default ends in `.json`.
It would be good to figure out a neater way to encode the location of sub boards, though, as this approach is somewhat brittle and will only work if the user is asked for a particular board location as part of the outer board's execution.
> [breadboard-extension] Add user setting for board locations

- .github/workflows/deploy-website.yml
- packages/website/package.json
- packages/website/src/_includes/docs.njk
- packages/website/src/index.html
- packages/website/src/js/header.ts
- packages/website/src/js/pages/docs.ts
- packages/website/src/playground.html
Whenever we merge to main, `packages/website` will now be built, and deployed to GitHub pages, visible at https://breadboard-ai.github.io/breadboard/
> [website] Add GitHub Action to deploy documentation website to GitHub pages on merge to main

- .changeset/bright-guests-clean.md
- .changeset/clever-days-crash.md
- .changeset/itchy-carrots-deny.md
- .changeset/rich-lamps-sin.md
- packages/breadboard-cli/CHANGELOG.md
- packages/breadboard-cli/package.json
- packages/breadboard-ui/CHANGELOG.md
- packages/breadboard-ui/package.json
- packages/breadboard-web/CHANGELOG.md
- packages/breadboard-web/package.json
- packages/create-breadboard/CHANGELOG.md
- packages/create-breadboard/package.json
- packages/hello-world/CHANGELOG.md
- packages/hello-world/package.json
- packages/website/CHANGELOG.md
- packages/website/package.json
Releases:
@google-labs/breadboard-web@1.0.3
@google-labs/breadboard-ui@0.0.5
@google-labs/breadboard-cli@0.2.1
@google-labs/breadboard-website@2.0.0
@google-labs/create-breadboard@1.0.0
@google-labs/breadboard-hello-world@1.0.0
[skip ci]
> RELEASING: Releasing 6 package(s)

- .changeset/light-beers-crash.md
- packages/create-breadboard/src/projects/index.ts
Because we don't want users to get the same `git+https://github.com/breadboard-ai/breadboard.git` repository that our own packages have.
> [create-breadboard] Clear out the repository field

- packages/breadboard-web/src/make-graphs.ts
Unblocks developers that don't have a Python environment set up that can run breadboard-python.
> [breadboard-web] Stop raising exception if Python boards fail to load

- packages/breadboard-web/src/index.ts
Fixes #637 
We were restarting the harness but not creating a new UI when switching between Build & Preview. This caused the UI to receive a new set of messages from the new harness which, in most cases, would be duplicates of the original harness. And in turn that caused duplicate inputs as logged in #637. 
This PR fixes it by tracking the board ID so that we avoid starting a new harness if we've not changed boards. The net effect is that Build holds onto the current state of the world whereas Preview is a fresh copy every time we switch to it. I _think_ that's the right behavior here, because intuitively going to the Preview feels like something you do when you're wanting to run through a journey from the start... but I can change that if needed.
> [breadboard-web] Fix duplicate UI

- .changeset/brave-moles-explode.md
- package-lock.json
- packages/agent-kit/package.json
- packages/agent-kit/src/boards/instruction.ts
- packages/agent-kit/src/boards/worker.ts
- packages/agent-kit/src/index.ts
- packages/agent-kit/src/kit.ts
- packages/agent-kit/src/samples/poet.ts
- packages/breadboard-web/package.json
- packages/breadboard-web/src/config.ts
- Start using Agent Kit in debugger
- Establish a way to build + use agent kit.
- Make context output port explicit.
- A non-working poet that uses `instruction` node.
- Make poet work with `instruction`.
- docs(changeset): Introduce "Agent Kit" to the Breadboard Kit family.
> use agent kit

- package-lock.json
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/elements.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-web/src/index.ts
I'm exploring the idea of creating a board in the debugger / playground UI. For that to work, however, we need to be able to boot the Build view without a URL set. This PR shouldn't affect the current approach, which is to say:
1. If no board URL is set, we will show the List view of boards.
2. If a board is clicked in the list we will switch to the Build view and autorun the board.
3. If the debugger is loaded with a board URL set, we will switch to the Build view and autorun the board.
But now there is an additional option:
4. If the user clicks on "New board" in the List view (or deeplinks to `?mode=build&visualizer=editor`) we load the Build view with the editor UI (to be built) and the debugger does not attempt to run the board.
> [breadboard-web/-ui] Enable unstarted, blank boards

- packages/breadboard/src/harness/secrets.ts
- packages/breadboard/src/new/grammar/node.ts
- packages/breadboard/src/new/grammar/scope.ts
- packages/breadboard/src/new/runner/node.ts
- packages/breadboard/src/new/runner/scope.ts
- packages/breadboard/tests/type-checks.ts
Found these imports when working my ephemeral deployment.
@dglazkov is/was there a reason for them being like this?
> fix some strange imports

- packages/website/src/docs/happy-path.md
Specified a directory in the `npm init @google-labs/breadboard` command to set up the project in the [Breadboard Happy Path](https://breadboard-ai.github.io/breadboard/docs/happy-path/) doc because it fails without it ("Must provide directory as an argument.").
> Updated happy path doc init command to specify folder.

- packages/breadboard-cli/src/commands/bundle.ts
detected previously, but most recently here: https://github.com/breadboard-ai/breadboard/actions/runs/7835167140/job/21379970219?pr=628#step:8:48
> [TS2774](https://github.com/microsoft/TypeScript/blob/main/src/compiler/diagnosticMessages.json#L3414-L3417)
> This condition will always return true since this function is always defined.
> Handle ts2774 error in breadboard-cli bundle.ts

- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-web/src/index.ts
This adds drag and drop nodes for invoke/input/output (yet to be configurable!), and allows for rewiring of the edges. There are a few things that this has highlighted, such as:
1. We could probably do with a board modifier (maybe on the inspector?)
2. We could probably do with being able to run a board with a runner passed to the config.
Sure there are other things that will come out in the mix.
> [breadboard-ui/-web] Add basic edge rewiring

- packages/breadboard-web/src/config.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/harness/index.ts
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/harness/run.ts
One of the challenges I've run into with visual editing is that our board runner expects a URL. In the case where we're modifying a board "in memory", we don't have a JSON board to load via fetch. What I've done here, which might not be the right way (in which case we can just close this PR), is to allow a `BoardRunner` in the config. If that's set it's used in preference to the URL for `run`. This just means I can do something like the following:
```ts
const runner = await BoardRunner.fromGraphDescriptor(
this.loadInfo.graphDescriptor
);
const config = createRunConfig(this.loadInfo.graphDescriptor.url);
config.remote = false;
config.proxy = [];
config.runner = runner;
```
And now I can run a modified board locally. @dglazkov is there a better way to do this?
> [breadboard] Allow pre-existing runners

- .changeset/hot-games-smoke.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard/src/inspector/graph.ts
- packages/breadboard/src/inspector/node.ts
- packages/breadboard/src/inspector/schemas.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/tests/inspector/describe.ts
- packages/breadboard/tests/inspector/traversal.ts
- packages/json-kit/src/nodes/jsonata.ts
- packages/json-kit/tests/jsonata.ts
- Make '*" ports explicit
- Simplify schema-creating code in inspector API.
- Light renaming.
- Ccombine as-wired and config schemas for inputs/outputs.
- Sketch out `node.ports`.
- Start using `node.ports` in editor.
- Handle star edges correctly.
- Undo schema merging in inputs.
- docs(changeset): Introduce `InspectableNode.ports`, which enumerates ports of a node.
> star edges

- .changeset/real-maps-try.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard/src/index.ts
- packages/breadboard/src/inspector/graph.ts
- packages/breadboard/src/inspector/index.ts
- packages/breadboard/src/inspector/node.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/src/types.ts
- packages/breadboard/tests/inspector/describe.ts
- packages/breadboard/tests/inspector/node.ts
- packages/breadboard/tests/inspector/traversal.ts
- packages/core-kit/src/nodes/invoke.ts
- packages/website/src/docs/concepts.md
- packages/website/src/docs/inspector.md
- Tweak docs a bit.
- More doc tweaks.
- Teach `invoke` to properly describe itself.
- Update docs.
- Remove `containsGraph` and `subgraph` APIs.
- Start using `ports` directly in the editor.
- docs(changeset): Taught `core.invoke` to describe its own subgraphs.
> more inspector

- .changeset/wise-ghosts-draw.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard/src/inspector/graph.ts
- packages/breadboard/src/inspector/ports.ts
- packages/breadboard/src/inspector/schemas.ts
- packages/breadboard/src/schema.ts
- packages/breadboard/src/types.ts
- packages/breadboard/tests/inspector/describe.ts
- packages/breadboard/tests/schema.ts
- Remove unused import.
- Pass `outerGraph` in `NodeDescriberContext`.
- Teach `output` node to expect a schema input.
- Handle `Indeterminate` state.
- docs(changeset): Fix various bugs in inspector API.
> even more inspector

- packages/breadboard-ui/src/elements/editor/editor.ts
I noticed a couple of things that needed fixing:
1. Graph node positions were being retained across graphs. We now reset them when the URL changes.
2. Deleting edges sometimes didn't work correctly. This was due to a simple oopsie in the logic that's now fixed.
> [breadboard-ui] Minor editor fixes

- .changeset/quick-spoons-grab.md
- packages/agent-kit/src/hacks.ts
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-web/public/graphs/list-files.json
- packages/breadboard/src/inspector/graph.ts
- packages/breadboard/src/inspector/kits.ts
- packages/breadboard/src/inspector/ports.ts
- packages/breadboard/src/inspector/types.ts
- packages/node-nursery-web/src/index.ts
- packages/website/src/docs/inspector.md
- First cut of `InspectableGraph.kits()`.
- Add built-in Kit.
- Remove spurious imports.
- Pretty things up a bit.
- Write docs.
- docs(changeset): Introduce a way to inspect kits.
> inspectable kits

- package.json
- packages/agent-kit/package.json
- packages/breadboard-cli/package.json
- packages/breadboard-extension/package.json
- packages/breadboard-server/package.json
- packages/breadboard-ui/package.json
- packages/breadboard-web/package.json
- packages/breadboard/package.json
- packages/cloud-function/package.json
- packages/coffee-bot-board/package.json
- packages/core-kit/package.json
- packages/create-breadboard-kit/package.json
- packages/create-breadboard/package.json
- packages/discovery-types/package.json
- packages/gemini-kit/package.json
- packages/graph-integrity/package.json
- packages/graph-playground/package.json
- packages/graph-runner/package.json
- packages/hello-world/package.json
- packages/json-kit/package.json
- packages/llm-starter/package.json
- packages/node-nursery-web/package.json
- packages/node-nursery/package.json
- packages/node-proxy-server/package.json
- packages/palm-kit/package.json
- packages/pinecone-kit/package.json
- packages/schema/package.json
- packages/template-kit/package.json
- packages/website/package.json
- templates/blank/package.json
allows npmjs.com to navigate to the correct directory when browsing to the repository from the registry see [here](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository:~:text=If%20the%20package.json%20for%20your%20package%20is%20not%20in%20the%20root%20directory%20(for%20example%20if%20it%20is%20part%20of%20a%20monorepo)%2C%20you%20can%20specify%20the%20directory%20in%20which%20it%20lives%3A)
> Add Package repository directories

- packages/breadboard/src/new/grammar/node.ts
Fixes a bug where constant wires for `code` nodes were written into the subgraph instead of the invoke node.
also changing `path` to `$board` to reduce the chance of namespace collisions.
> [breadboard] put node configuration on invoke node

- .changeset/strong-sloths-relax.md
- packages/breadboard-ui/src/elements/editor/graph-edge.ts
- packages/breadboard-ui/src/elements/editor/graph-node.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
This allows a GraphNode to set the outgoing edge color. Hopefully it'll help disambiguate wires in a few cases.
> [breadboard-ui] Color-code wires

- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
- packages/breadboard-ui/src/elements/splitter/splitter.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
This fixes a couple of minor things:
1. We don't render the node highlight until the targeted node has non-zero dimensions.
2. The splitter doesn't schedule another Lit render when it restores the values from session storage.
> [breadboard-ui] Fix various small issues

- .changeset/witty-seas-try.md
- packages/breadboard/package.json
- packages/breadboard/src/harness/url.ts
- Check for window in globalThis instead of self, since self doesn't exist in Node
- Re-run breadboard tests when JSON data files change
> Fix self not defined error, and re-run tests when JSON datafiles change

- packages/website/filter-toc.cjs
- packages/website/src/docs/editor.md
- packages/website/src/docs/inspector.md
- packages/website/src/docs/io.md
- packages/website/src/docs/kits/agents.md
- packages/website/src/docs/kits/core.md
- packages/website/src/docs/kits/json.md
- packages/website/src/docs/kits/template.md
- packages/website/src/docs/python.md
- packages/website/src/static/docs.css
There were some missing TOCs in some of the docs pages because of an erroneous `hide_toc` in the YAML front matter. This PR removes those and also tweaks the styles for super long TOCs so they don't run off the bottom of the screen.
> [website] Restore TOC; tweak styles

- packages/breadboard-ui/src/elements/editor/graph-node.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/interaction-tracker.ts
I had a slight regression where a) wires/edges weren't snapping when you hovered over a port, and b) the ports weren't lighting up on hover. This PR fixes both of those issues.
> [breadboard-ui] Highlight nodes and snap wire

- .changeset/quick-donuts-kneel.md
- packages/core-kit/src/nodes/passthrough.ts
- packages/core-kit/src/nodes/reflect.ts
`passthrough` and `reflect` had the `describe` attribute mispelt.
> Fix - Typo "describe"

- .changeset/late-knives-prove.md
- packages/breadboard-cli/package.json
It is a little bizarre as the addition of the `bundleDependencies` was to try and remove this issue in the first place
see pipeline: https://github.com/ExaDev-io/breadboard/actions?query=branch%3Afix-cli-dependency-bundling
branched from https://github.com/breadboard-ai/breadboard/pull/789
> Fix cli dependency bundling

- .changeset/modern-rivers-act.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-web/src/index.ts
- **Change `loadInfo` object identity to trigger Lit element refresh.**
- **docs(changeset): Use object identity to trigger graph update.**
> lit object rerender

- .changeset/healthy-baboons-accept.md
- packages/breadboard-cli/src/commands/lib/debug-server.ts
- packages/breadboard-cli/src/commands/lib/kits.ts
- packages/breadboard-cli/src/index.ts
- packages/breadboard/src/kits/load.ts
- **Move kits bits to own file**
- **Rename KitData.code to KitData.data**
- **Use KitData in debug-server.**
- **Implement importing from URLs.**
- **Add command line help blurb.**
- **Support kit manifests.**
- **docs(changeset): Support loading kits via URL (both heavy and light kits)**
> manifest kits

- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.styles.ts
Should improve the situation for #926 inasmuch as pinch zoom shouldn't apply to the canvas. I suspect we'll need to add actual pinch zoom support for touch/mobile at some stage.
This PR also includes a fix for overscrolling, since I noticed that the outputs were causing a scrollbar to appear at the top level element.
> [breadboard-ui] Small UI tweaks

- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-ui/src/events/events.ts
When the user is on the Selected Node or History tab and an input is needed, we now switch back to the Board tab and fade the input background a little to let them know.
> [breadboard-ui] Get the user's attention when an input is needed

- .changeset/four-stingrays-accept.md
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard/src/inspector/event.ts
- packages/breadboard/src/inspector/path-registry.ts
- packages/breadboard/src/inspector/types.ts
- **Clean up traversal a bit.**
- **Make `PathRegistry` an `Entry`.**
- **Working `nested` runs.**
- **Organize event-getting logic.**
- **Remove `markEventsAsDirty`.**
- **Get rid of `PathRegistryEntryUpdater`.**
- **Split the `Entry` API to `find` and `create`.**
- **Shift more stuff to `event.ts`.**
- **Minor tweaks.**
- **docs(changeset): Implement handling subgraphs in Run Inspector API.**
> neural activity

- .changeset/modern-gorillas-listen.md
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-ui/src/types/types.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/inspector/event.ts
- packages/breadboard/src/inspector/graph-store.ts
- packages/breadboard/src/inspector/path-registry.ts
- packages/breadboard/src/inspector/run.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/src/types.ts
- **Move sidecars to the front of the queue.**
- **Create UUIDs for graphs.**
- **Get rid of `InspectableRun.id`.**
- **Introduce `InspectableGraphStore`.**
- **Plumb `InspectableGraphStore` to the top.**
- **docs(changeset): Start using UUIDs for graphs.**
> know graphs

- .changeset/mean-shoes-rest.md
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/inspector/event.ts
- packages/breadboard/src/inspector/graph-store.ts
- packages/breadboard/src/inspector/path-registry.ts
- packages/breadboard/src/inspector/run.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/src/kits/load.ts
- **Teach GraphManifest loader to make better URLs.**
- **Use graph URLs as keys in GraphStore.**
- **Introduce URL-based `GraphUUID`.**
- **Add `version` param to `InspectableGraphStore.add`.**
- **Plumb graph start and end timestamps.**
- **Introduce `NestedRun` class and clean up a bit.**
- **Rename `nested` to `runs`.**
- **docs(changeset): Improve graph unique id generation and various cleanups.**
> graph hashing

- .changeset/large-berries-guess.md
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-web/public/graphs/error.json
- packages/breadboard-web/public/local-boards.json
- packages/breadboard-web/src/boards/error.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/harness/error.ts
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/index.ts
- packages/breadboard/src/inspector/event.ts
- packages/breadboard/src/inspector/index.ts
- packages/breadboard/src/inspector/path-registry.ts
- packages/breadboard/src/inspector/run.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/src/remote/run.ts
- **Introduce `RunObserver` and start using it.**
- **Remove unused APIs.**
- **Stop using `InspectableRunEvent.result`.**
- **Remove `InspectableRunEvent.result`.**
- **Add an error-throwing board.**
- **Put error events at the end of the run.**
- **Handle errors consistently in worker and local harness.**
- **docs(changeset): Get the Run Inspector API ready to ship**
> inspectable run

- .changeset/gorgeous-snails-beam.md
- packages/breadboard-web/src/config.ts
- packages/breadboard-web/src/index.ts
- **Switch breadboard-web to not use worker by default.**
- **docs(changeset): Switch breadboard-web to not use worker by default.**
> run locally

- package-lock.json
- packages/build/package.json
- packages/build/src/definition.ts
- packages/build/src/test/define_test.ts
- packages/build/tsconfig.json
`defineNodeType` now returns a `NodeHandler`, meaning it has an `invoke` and `describe` function that will work with other Breadboard systems like the runner and kit builder.
Since `defineNodeType` currently only supports static/monomorphic nodes (polymorphic coming in a follow-up), the schema is completely pre-determined from the configuration.
> [build] Generate invoke and describe functions

- .changeset/funny-bikes-provide.md
- packages/breadboard-ui/src/elements/input/input.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-ui/src/types/types.ts
work by @alexandraM98 to expose UI component configuration for use externally
relates to:
- https://github.com/breadboard-ai/breadboard/issues/877
- https://github.com/breadboard-ai/breadboard/issues/722
- https://github.com/breadboard-ai/breadboard/issues/885
- define error type to be able to identify specific errors
- errors for passing to and handling in react component
- create interface for Lit components to implement which specifies the onError handler, which can then be accessed by react components (and others in the future)
- add interface implementation on `input` Lit component
- within the input component, wrap likely causes of errors in try...catch
> begin to expose UI component configurability for use externally

- packages/build/src/definition.ts
- packages/build/src/instance.ts
- packages/build/src/port.ts
- packages/build/src/test/define_test.ts
Nodes must now be instantiated with all input values fulfilled; either by concrete values (e.g. an actual string, number, etc.), or an output port of the same type.
Example:
```ts
const definitionA = defineNodeType(
{},
{
out1: {
type: "string",
},
out2: {
type: "number",
},
},
() => {
return {
out1: "foo",
out2: 123,
};
}
);
const definitionB = defineNodeType(
{
in1: {
type: "string",
},
in2: {
type: "number",
},
},
{},
() => {
return {};
}
);
const instanceA = definitionA();
const instanceB = definitionB({
in1: "foo",
in2: instanceA.outputs.out2,
});
```
> [build] Strong types for instantiating nodes

- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-node.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-web/src/index.ts
This is the first bit of work to persist node positions in the board/graph descriptor. When a node is moved its position is now held in the `metadata.visual` section. Next steps:
1. Apply the visual information to the node when it's received.
2. Emit visual information in more cases (initial layout, node added).
> [breadboard-ui] Store metadata for node positions on move

- packages/build/src/board.ts
- packages/build/src/index.ts
- packages/build/src/port.ts
- packages/build/src/test/board_test.ts
- packages/build/src/test/define_test.ts
Adds a `board()` function to `@breadboard-ai/build`. It takes the input ports/output ports from nodes in that board which should be exposed as input/output nodes on that board.
Example:
```ts
...
export const recipeMaker = board(
{dish: prompt.inputs.recipe},
{recipe: llm.outputs.completion}
);
```
> [build] Add board function

- packages/build/src/board.ts
- packages/build/src/definition.ts
- packages/build/src/instance.ts
- packages/build/src/port.ts
- packages/build/src/test/define_test.ts
Allows annotating an output port as `primary`, which means that the node that owns the port will itself act like the primary port in contexts where output ports are expected. (Will add input ports in a follow up, primary output ports seem a bit more useful).
Example:
```ts
import { defineNodeType, board } from "@breadboard-ai/build";
const template = defineNodeType(..., {
result: {
type: "string",
primary: true
}
}, ...);
const prompt = template(...);
const recipe = gemini({prompt});
export const board({dish: prompt.inputs.dish}, {recipe});
```
> [build] Add "primary" setting which allows nodes to be wired more concisely

- packages/build/src/instance.ts
- packages/build/src/test/define_test.ts
Bugfix for the type system for `@breadboard-ai/build`. Previously nodes *without* an annotated primary output would still act like they were output ports.
> [build] Nodes without primary outputs should never be OutputPortReferences

- packages/build/src/board.ts
- packages/build/src/definition.ts
- packages/build/src/instance.ts
- packages/build/src/port.ts
- packages/build/src/test/define-polymorphic_test.ts.ts
- packages/build/src/test/define-primary-port_test.ts
- packages/build/src/test/define_test.ts
- packages/build/src/type.ts
Add to the `@breadboard-ai/build` package the ability to use `"*"` (syntax subject to change!) to declare a node that can dynamically receive input ports when it is instantiated.
Example:
```ts
import {defineNodeType} from '@breadboard-ai/build';
const template = defineNodeType(
{
template: {
type: "string",
},
"*": {
type: string"
}
},
{
result: {
type: "string"
}
},
({template, ...rest}) => {
return ...
}
const prompt = template({
template: "Write a recipe for the dish {{dish}}",
dish: "Mashed potatoes"
});
prompt.inputs.dish; // string
```
> [build] Support for polymorphic inputs

- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-web/src/index.ts
Fixes a bug where the node positions weren't resetting properly when the board changed
> [breadboard-ui] Reset node positions based on board ID

- packages/build/src/definition.ts
- packages/build/src/test/define-primary-port_test.ts
- packages/build/src/type-util.ts
Don't allow more than one primary output port when defining a node.
> [build] Check for multiple primary output ports

- packages/build/src/definition.ts
- packages/build/src/test/define_test.ts
- packages/build/src/test/type_test.ts
- packages/build/src/type.ts
Adds an `anyOf` function that allows defining ports that are allowed to have more than one type. For example, `anyOf("string", "number")` will generate the TypeScript type `string|number`, and also the JSON schema `{anyOf: [{type: "string"}, {type: "number"}]`.
Also adds an `escapeHatch` function that allows defining arbitrary TypeScript + JSON Schema mappings for port types. Useful for when none of the other type utilities we have will suffice. For example: `escapeHatch<MyWeirdType>({my: {weird: {jsonSchema}}})`.
> [build] add `anyOf` and `escapeHatch`

- packages/breadboard-ui/src/elements/nav/nav.ts
- packages/breadboard-web/src/file-storage/file-storage.ts
I noticed that files would fail to load from a mounted a folder with capital letters in its name. Because URL creation converts to lowercase it meant that we were failing to match the location portion of the URL with the folder name. Now we always store the location as lowercase, but we query the handle's name for the title in the nav.
> [breadboard-ui] Fix case sensitivity of file URLs

- packages/breadboard-web/src/file-storage/file-storage.ts
Following on from earlier, any special characters (like spaces) also need URI encoding so that they match with the URL. So now the location path that is stored uses `encodeURIComponent`.
> [breadboard-web] Use URI Component for paths

- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
I was assuming that if `visual` existed on `metadata` that we were dealing with a node which had an icon. In fact it may just be that the node has `[x, y]` coordinates. This PR changes things so we confirm that there is an icon before we set the class and icon value in Activity Log
> [breadboard-ui] Check for icons

- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
I noticed that when a node is deleted it might still be the selected node. This watches for delete events on the editor and deselects the node if need be.
> [breadboard-ui] Deselect a node when it is deleted

- .changeset/empty-vans-sip.md
- packages/breadboard-web/src/file-storage/file-storage.ts
- packages/breadboard-web/src/index.ts
With this change you can now open a blank file (or any non-FS-backed board) and hit the "Save button". This will trigger the "Save file" flow. If you save a file to an existing sources we'll pick it up, otherwise the file will be fairly similar to an export.
> [breadboard-ui] Allow saving of non-FS boards

- packages/build/src/define.ts
- packages/build/src/definition-polymorphic.ts
- packages/build/src/definition.ts
- packages/build/src/json-schema.ts
- packages/build/src/test/monomorphic_test.ts
- packages/build/src/test/polymorphic_test.ts
- packages/build/src/type.ts
Limitations:
- Only works for input ports (for now)
- Only static inputs are passed to describe function (probably will change this)
> [build] Allow custom describe function for polymorphic nodes

- .changeset/nine-melons-confess.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/node-info/node-info.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard-web/src/preview-run.ts
- packages/breadboard/src/editor/graph.ts
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/harness/run.ts
- packages/breadboard/src/index.ts
- packages/breadboard/src/inspector/graph.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/src/runner.ts
- packages/core-kit/src/load-board.ts
- packages/core-kit/src/nodes/import.ts
- packages/core-kit/src/nodes/include.ts
- packages/core-kit/src/nodes/invoke.ts
- **Remove a few more `BoardRunner.load` call sites and simplify it too,**
- **Switch `breadboard-web` away from `Board.load`.**
- **Start using one loader instance for all loads.**
- **Switch to use one instance of `GraphLoader`.**
- **Remove spurious import.**
- **docs(changeset): Bring loader machinery closer to cacheable load state.**
> simpler loader

- packages/breadboard-ui/src/elements/node-info/node-info.ts
Since we only use the Schema Editor for inputs & outputs, we no longer look for `.properties` to decide whether or not to show the schema editor, but instead we use the node type.
> [breadboard-ui] Only use Schema Editor for inputs & outputs

- packages/breadboard-cli/src/debugger/provider.ts
- packages/breadboard-ui/src/elements/nav/nav.ts
- packages/breadboard-web/index.html
- packages/breadboard-web/src/index.ts
- packages/breadboard-web/src/providers/examples.ts
- packages/breadboard-web/src/providers/file-system.ts
- packages/breadboard-web/src/providers/indexed-db.ts
- packages/breadboard/src/loader/default.ts
- packages/breadboard/src/loader/types.ts
I used the constructor name for the providers, but that doesn't work when the classes are minified and their names change! This PR introduces a name property for each provider, which we can use even if the class name is changed.
> [breadboard-ui] Name providers

- .changeset/wise-lobsters-impress.md
- packages/breadboard/src/handler.ts
- packages/breadboard/src/inspector/graph.ts
- packages/build/src/compatibility.ts
- packages/build/src/index.ts
- packages/build/src/test/compatibility_test.ts
Nodes defined with the `@breadboard-ai/build` package are now compatible with the Breadboard runner and inspector API.
Just required a small tweak to the way those APIs check whether something looks like a node type. Previously there were short-circuits for when something was a function, but since `@breadboard-ai/build` node definitions are themselves functions (for use with its `board` API), we instead now just look for an `invoke` or `describe` property.
This also adds a new `NodeFactoryFromDefinition` type utility, which generates a signature for a node type so that it doesn't need to be written out manually when building kits.
Also added integration tests.
> [build] Compatibility with runner and inspector

- .changeset/chatty-seals-shop.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/structured-worker.ts
- packages/breadboard-ui/src/elements/node-info/node-info.ts
- packages/breadboard-ui/src/elements/schema-editor/schema-editor.ts
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard-web/public/graphs/json-agent.json
- packages/breadboard-web/src/boards/json-agent.ts
- packages/breadboard/src/inspector/graph.ts
- packages/breadboard/src/inspector/node.ts
- packages/breadboard/src/inspector/ports.ts
- packages/breadboard/src/inspector/schemas.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/src/schema.ts
- packages/breadboard/tests/inspector/describe.ts
- packages/build/src/test/compatibility_test.ts
- packages/core-kit/src/nodes/invoke.ts
- packages/gemini-kit/src/boards/gemini-generator.ts
- packages/gemini-kit/src/boards/gemini-pro-vision.ts
- **Make `InspectablePort.schema` never return `null'.**
- **Add `llm-content` and `json-schema` hints all over.**
- **Teach `bb-schema-editor` to start with no schema.**
- **Introduce `InspectablePort.value`.**
- **Don't add `$error` ports to input and output nodes.**
- **Removes `schema` from invoke.**
- **Make `$board` an `object` type.**
- **docs(changeset): Various quality improvements to schemas and Graph Inspector API.**
- **Combine schemas properly.**
> schemaaaaa

- packages/build/README.md
- packages/build/src/index.ts
- packages/build/src/internal/type-system/object.ts
- packages/build/src/test/type_test.ts
Adds an `object` Breadboard Type utility that can be used like this:
```ts
import {defineNodeType, object, anyOf} from '@breadboard-ai/build';
export const someNodeTypeThatTakesAnObject = defineNodeType({
inputs: {
foo: {
type: object({
foo: "string",
bar: anyOf("string", "number"),
}),
},
},
...
});
```
cc @Mearman
> [build] Add `object` utility to type system

- packages/breadboard-cli/src/commands/run.ts
Fixes #1210 
This was originaly added to enable boards to run that had been saved from the `openapi` board of boards. It would save the inputs to the lambda in the `args` property. With the new import method in the CLI this is no longer needed.
> [breadboard-cli] Remove support for reading a boards `{args}`.

- .changeset/unlucky-dolls-remember.md
- packages/breadboard-ui/src/elements/node-info/schema-editor.ts
When the user sets the type as `string` they can also predefine a set of values.
> [breadboard-ui] Teach node editor about enumerations

- packages/breadboard-web/src/providers/file-system.ts
I noticed that FS API labels can have capitals, but because we use URLs (which generally converts components to lower case) we were failing to match. One option was to do a second pass with case insensitivity when we fail to find a match between the URL and the FS API label, but in the end I opted for lowercasing the file name. This will have the corresponding effect of erroneously deduping FS API labels when files share the name but are differentiated by casing, e.g., foo.json and FOO.json, but hopefully that won't occur often enough to be problematic.
> [breadboard-web] Enforce lowercase entry names

- .changeset/tricky-sloths-report.md
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
I noticed we were passing `loadInfo` through to Activity Log, but this is no longer necessary since Activity Log is populated by the current `run`. This PR removes it.
> [breadboard-ui] Remove loadInfo from Activity Log

- packages/build/src/internal/define/definition-monomorphic.ts
- packages/build/src/internal/define/definition-polymorphic.ts
- packages/build/src/internal/type-system/type.ts
- packages/build/src/test/type_test.ts
This adds a new `JsonSerializable` type which is now the base type that all `BreadboardType`'s must be convertible to. This e.g. eliminates `undefined` as a possible value, since that's not JSON serializable. We want everything to be JSON serializable so that we can easily support save/restore for runs.
> [build] Require all concrete values to be JSON serializable

- packages/build/src/internal/board/board.ts
- packages/build/src/internal/common/instance.ts
- packages/build/src/internal/common/port.ts
- packages/build/src/internal/define/definition-monomorphic.ts
- packages/build/src/internal/define/definition-polymorphic.ts
- packages/build/src/test/board_test.ts
- packages/build/src/test/monomorphic-primary_test.ts
- packages/build/src/test/monomorphic_test.ts
- packages/build/src/test/polymorphic-primary_test.ts
- packages/build/src/test/polymorphic_test.ts
- packages/build/src/test/serialize_test.ts
This simplifies IDE tooltips a bunch, e.g. instead of `InputPort<{ type: "string"; }>` we now will just show `InputPort<string>`.
It also fixes an assignment bug in the type system, since we were previously asking the type system to understand that `{type: "string"}` was assignable to `{ type: anyOf("string", "number") }`, which it doesn't actually know; we have to convert to actual types first (since it does know that `string` is assignable to `string | number`).
> [build] Parameterize ports by actual type instead of port config type

- packages/build/src/internal/board/input.ts
- packages/build/src/test/input_test.ts
Adds an `input` function used for board inputs. Not yet hooked up to the `board` function or `serialize`.
> [build] Add input function

- .changeset/beige-rivers-explode.md
- packages/breadboard-ui/src/elements/editor/graph.ts
It turns out I had missed an important element of Dagre layout: it provides `x` and `y` coordinates of the middle of the node, not the top left. I am therefore adjusting the node position by half the `width` and `height` and things are now much better aligned.
> [breadboard-ui] Improved node placement in graph

- .changeset/moody-kids-sip.md
- packages/breadboard-cli/src/commands/lib/kits.ts
- packages/breadboard-cli/src/commands/lib/utils.ts
- **Avoid encoding `localhost` into a kit URL.**
- **docs(changeset): Avoid hard-coding `localhost` into a kit URL.**
> no localhost

- .changeset/old-turtles-unite.md
- .changeset/wise-ants-whisper.md
- packages/breadboard-web/public/graphs/build-example.json
- packages/breadboard-web/public/local-boards.json
- packages/breadboard-web/src/boards/build-example.ts
- packages/breadboard-web/src/build-example-kit.ts
- packages/breadboard-web/src/make-graphs.ts
- packages/build/src/index.ts
- packages/build/src/internal/board/board.ts
- packages/build/src/internal/board/input.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/internal/common/port.ts
- packages/build/src/internal/define/definition-polymorphic.ts
- packages/build/src/test/board_test.ts
- packages/build/src/test/input_test.ts
- packages/build/src/test/serialize_test.ts
Also:
- Export the new `board`, `input`, and `serialize` functions
- Fix a few bugs
- Update the `build` example graph to use the new `board` function
- Allow passing manifest metadata (`title`, `version`, `description`) to new `board` function
> [build] Support serializing build boards from web UI

- .changeset/fair-sheep-beam.md
- packages/build/README.md
- packages/build/src/internal/board/board.ts
- packages/build/src/internal/define/define.ts
- packages/build/src/test/board_test.ts
- packages/build/src/test/compatibility_test.ts
- packages/build/src/test/monomorphic-primary_test.ts
- packages/build/src/test/monomorphic_test.ts
- packages/build/src/test/polymorphic-primary_test.ts
- packages/build/src/test/polymorphic_test.ts
Also makes `name` required when calling `defineNodeType`, so that those nodes are always serializable.
> [build] Document `board` in the README

- .changeset/sharp-schools-hunt.md
- package-lock.json
- packages/breadboard-cli/package.json
- packages/breadboard-cli/src/commands/lib/loader.ts
- packages/breadboard-web/src/make-graphs.ts
You can now run/make boards defined using `@breadboard-ai/build` with the CLI.
> [cli] Add support for @breadboard-ai/build boards

- .changeset/three-plums-give.md
- packages/core-kit/src/nodes/invoke.ts
- **Do not throw when URL couldn't be loaded in `core.invoke` describer.**
- **docs(changeset): Do not throw in `invoke` describer when board couldn't be loaded.**
> happier invoke describer

- .changeset/unlucky-bikes-thank.md
- packages/build/src/index.ts
- packages/build/src/internal/board/placeholder.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/internal/common/port.ts
- packages/build/src/internal/define/definition-monomorphic.ts
- packages/build/src/test/compatibility_test.ts
- packages/build/src/test/placeholder_test.ts
- packages/build/src/test/serialize_test.ts
Placeholders can be used in place of real output ports for situations where it is not yet possible to provide an actual output port, most notably because of a cycle:
```ts
import {placeholder} from "@breadboard-ai/build";
const barPlaceholder = placeholder({type: "number"});
const cyclicNode = someNode({ foo: barPlaceholder });
barPlaceholder.resolve(node.outputs.bar);
```
> [build] Add placeholders for representing cycles

- .changeset/grumpy-needles-fly.md
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard/src/inspector/run/nested-run.ts
- packages/breadboard/src/inspector/run/run.ts
- packages/breadboard/src/inspector/types.ts
- **Remove the use of `messages` in `ui-controller`.**
- **Remove messages/currentNode from InspectableRun.**
- **Thank you NodeHighlighter. We love you.**
- **docs(changeset): Remove `messages` and `currentNode` from `InspectableRun`.**
> remove messages

- .changeset/cold-penguins-hug.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/node-selector.ts
- packages/breadboard-ui/src/elements/node-info/node-info.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-ui/src/types/types.ts
- packages/breadboard-web/src/index.ts
- **Remove `LoadArgs.title`.**
- **Remove `LoadArgs.diagram`.**
- **Remove `LoadArgs.description`.**
- **Remove `LoadArgs.version`.**
- **Remove `LoadArgs.nodes`.**
- **Remove `LoadArgs.url`.**
- **Turn `loadInfo` to be `GraphDescriptor` on `bb-main`.**
- **Reduce the use of `BoardRunner` in `bb-main`.**
- **Massage code a bit.**
- **Rename `loadInfo` to `loadedDescriptor` on `bb-main`.**
- **Wean `bb-ui-controller` off `LoadArgs`.**
- **Wean `bb-editor` off `LoadArgs`.**
- **Wean `bb-node-selector` off `LoadInfo`.**
- **Wean `bb-node-info` off `LoadArgs`.**
- **Remove last mentions of `loadInfo`.**
- **Rename `loadedDescriptor` to `graph` and remove `descriptor` property from `bb-main`.**
- **docs(changeset): Replace `LoadArgs` with just `GraphDescriptor`.**
> no load args

- .changeset/funny-pianos-admire.md
- packages/breadboard/src/editor/graph.ts
- packages/breadboard/src/editor/types.ts
- packages/breadboard/tests/editor/graph.ts
- packages/website/src/docs/editor.md
- **Switch to use `GraphDescriptor` in subgraph editing.**
- **Update docs.**
- **Tweak docs.**
- **docs(changeset): Switch to use `GraphDescriptors` in subgraph editing.**
> subgraph descriptors

- .changeset/empty-foxes-sniff.md
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/editor/graph.ts
- packages/breadboard/src/editor/index.ts
- packages/breadboard/src/editor/types.ts
- packages/breadboard/src/inspector/graph.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/tests/editor/graph.ts
- packages/breadboard/tests/editor/metadata.ts
- packages/website/src/docs/editor.md
- **Add `version` to `EditableGraph`.**
- **Start incrementing version.**
- **Introduce the concept of a `parent` graph in EditableGraph.**
- **Add comments about throwing.**
- **Teach `changeEdge` to handle alternatives.**
- **Implement `graphchange` event.**
- **Add docs.**
- **docs(changeset): Teach Editor API about versions and change events.**
> better editor

- .changeset/hungry-waves-begin.md
- packages/breadboard/src/inspector/edge.ts
- packages/breadboard/src/inspector/graph-store.ts
- packages/breadboard/src/inspector/graph.ts
- packages/breadboard/src/inspector/node.ts
- packages/breadboard/src/inspector/run/event-manager.ts
- packages/breadboard/src/inspector/run/run.ts
- packages/breadboard/src/inspector/types.ts
- **Rename `InspectableGraphStore` to `GraphDescriptorStore`.**
- **Rename `InspectableNodeCache` to `NodeCache`.**
- **Rename `InspectableEdgeCache` to `EdgeCache`.**
- **Add types for cache.**
- **Use `InspectableGraphCache` in Graph.**
- **Wean inspector edgy stuff off `InspectableGraph`.**
- **Introduce the idea of a `MutableGraph`.**
- **Minor massage.**
- **docs(changeset): Prepare InspectableGraph instances to have a mutable backing store.**
> graph cache

- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-ui/src/types/types.ts
- packages/breadboard-web/src/index.ts
Fixes #1335, but in a different way. We were capturing the settings, but not requesting a new copy of them on update. The "fix", small as it is, is to call `requestUpdate` on `<bb-main>`, which will re-run `render` and which will, in turn, fetch a new copy of the settings and pass them through to the UI.
> [breadboard-ui] Update secrets in UI

- .changeset/dull-snails-ring.md
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard/src/inspector/run/event-manager.ts
- packages/breadboard/src/inspector/run/nested-run.ts
- packages/breadboard/src/inspector/run/run-node-event.ts
- packages/breadboard/src/inspector/run/run.ts
- packages/breadboard/src/inspector/types.ts
- **Add ability to look up a graph for any `InspectableRunNodeEvent`.**
- **Implement and use `InspectableRun.currentNodeEvent`.**
- **docs(changeset): Implement `InspectableRun.currentNodeEvent`.**
> highlight well

- .changeset/light-zebras-visit.md
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/editor/graph.ts
- packages/breadboard/src/editor/types.ts
- **Introduce `GraphChangeEvent.visualOnly`.**
- **docs(changeset): Introduce `GraphChangeEvent.visualOnly` to indicate that only visual metadata was update.**
> visual only

- .changeset/brown-camels-melt.md
- packages/breadboard-ui/src/elements/node-info/array-editor.ts
- packages/breadboard-ui/src/elements/node-info/node-info.ts
Fixes #1356. This was a really subtle one – thanks for the super clear bug report, @PaulKinlan!
> [breadboard-ui] Handle strings in array-editor a little better

- .changeset/friendly-shirts-remember.md
- packages/breadboard-web/src/index.ts
- packages/breadboard-web/src/preview-run.ts
I noticed we were saving settings changes a little too eagerly; this fixes that
> [breadboard-ui] Only save to settings when a value is changed or added

- packages/breadboard-ui/src/elements/node-info/node-info.ts
It turns out that some of our `$boards` are set as objects. In those cases we shouldn't show the Board Selector.
> [breadboard-ui] Only show Board Selector for strings/URLs

- .changeset/four-steaks-clean.md
- packages/breadboard-ui/src/elements/node-info/node-info.ts
- packages/breadboard-ui/src/utils/board.ts
- packages/breadboard/src/capability.ts
- packages/breadboard/src/index.ts
- packages/breadboard/src/kits/ctors.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/src/types.ts
- packages/breadboard/tests/board.ts
- packages/breadboard/tests/helpers/_test-kit.ts
- packages/breadboard/tests/new/grammar/lambdas.ts
- packages/core-kit/src/nodes/curry.ts
- packages/core-kit/src/nodes/invoke.ts
- packages/core-kit/src/utils.ts
- **Introduce `path` and `url` in `BreadboardCapability`.**
- **Add path resolution for BreadboardCapability.**
- **Somewhat working.**
- **Be more forgiving about UnresolvedPathBoardCapability.**
- **Take care of strings and undefined.**
- **docs(changeset): Split run-time and build-time URL resolutions for loading graphs.**
> runtime urls

- packages/breadboard-ui/src/elements/editor/graph-edge.ts
The loopback rendering was a little out of keeping with the rest of the wire rendering, so I took a quick pass over it to tidy it up a bit.
> [breadboard-ui] Tidy up loopback rendering

- .changeset/twelve-paws-impress.md
- package-lock.json
- packages/json-kit/src/nodes/validate-json.ts
- packages/json-kit/tests/validate-json.ts
Fixes #1427
This will enable `validateJson`'s schema to be technically "invalid" - see https://ajv.js.org/options.html#strict (we just enable true/false/undefined, ignore log)
> [json-kit] Adding an option strict schema config to validateJson

- .changeset/blue-lemons-kneel.md
- .changeset/curly-laws-behave.md
- .changeset/slow-wombats-shop.md
- .changeset/spicy-flowers-hide.md
- .changeset/tasty-dots-vanish.md
- .changeset/witty-books-build.md
- packages/breadboard/src/new/grammar/node.ts
- packages/breadboard/src/new/runner/kits.ts
- packages/breadboard/src/new/runner/node.ts
- packages/build/README.md
- packages/build/src/internal/common/port.ts
- packages/build/src/internal/define/config.ts
- packages/build/src/internal/define/define.ts
- packages/build/src/internal/define/definition.ts
- packages/build/src/internal/define/json-schema.ts
- packages/build/src/internal/define/node-factory.ts
- packages/build/src/internal/type-system/any-of.ts
- packages/build/src/internal/type-system/object.ts
- packages/build/src/internal/type-system/type.ts
- packages/build/src/test/compatibility_test.ts
- packages/build/src/test/define_test.ts
- packages/build/src/test/type_test.ts
- Support returning dynamic port descriptions
- Simplify anyOf when all members are basic
- Simplify object when it has no properties
- Clone schemas so they can be mutated
- Add support for multiline string format hint
- Make the order of JSON schema properties a bit more natural
- Require that ports with type object({}) are plain objects, not number etc.
- Slightly loosen the constraints on NodeFactoryFromDefinition for better compatibility
- Update a few more spots where the breadboard package was confused about @breadboard-ai/build definitions
> [build] Various improvements needed while converting an existing node definition

- .changeset/curvy-ties-shake.md
- package-lock.json
- packages/breadboard-web/public/graphs/build-example.json
- packages/breadboard-web/src/build-example-kit.ts
- packages/template-kit/package.json
- packages/template-kit/src/index.ts
- packages/template-kit/src/nodes/prompt-template.ts
- packages/template-kit/src/nodes/url-template.ts
- packages/template-kit/tests/nodes/prompt-template.ts
- packages/template-kit/tests/nodes/url-template.ts
Converts `template-kit` to the new `@breadboard-ai/build` library. This shouldn't change any compatibility with existing boards, but has these advantages:
- The implementation of the template nodes are now more strictly type checked
- The implementation of the template nodes are quite a bit more concise
- template-kit can now be used with boards using the new syntax in `@breadboard-ai/build`
> [template-kit] Convert template-kit to use @breadboard-ai/build

- packages/build/src/internal/define/json-schema.ts
- packages/build/src/test/define_test.ts
Small followup to https://github.com/breadboard-ai/breadboard/pull/1446. If an input port has a default, then it shouldn't be `required` in the JSON schema.
> [build] Don't make inputs with defaults required

- .changeset/fast-mice-judge.md
- .changeset/hot-bugs-deny.md
- package-lock.json
- packages/build/src/internal/define/definition.ts
- packages/build/src/internal/define/json-schema.ts
- packages/build/src/test/compatibility_test.ts
- packages/build/src/test/define_test.ts
- packages/core-kit/package.json
- packages/core-kit/src/nodes/fetch.ts
Support for type-safety around `$error` and `stream` is not quite there yet. Those two features will need some additional handling in `build` (and I need to understand them a bit better before figuring out the API for that), but we can just cast for now.
> Convert fetch to @breadboard-ai/build

- .changeset/friendly-crabs-own.md
- packages/breadboard/src/harness/error.ts
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/types.ts
- **Make descriptor/inputs optional on ErrorObject.**
- **docs(changeset): Make `inputs` and `descriptor` optional for ErrorObject.**
> better errors

- .changeset/dry-suits-accept.md
- .changeset/honest-pens-tap.md
- .changeset/mighty-gifts-talk.md
- .changeset/perfect-shoes-complain.md
- .changeset/smooth-badgers-hug.md
- .changeset/strange-keys-watch.md
- .gitignore
- packages/build/README.md
- packages/build/package.json
- packages/build/src/internal/common/port.ts
- packages/build/src/internal/define/config.ts
- packages/build/src/internal/define/define.ts
- packages/build/src/internal/define/definition.ts
- packages/build/src/internal/define/json-schema.ts
- packages/build/src/test/compatibility_test.ts
- packages/build/src/test/define_test.ts
- packages/build/src/test/describe_test.ts
- packages/core-kit/tests/secrets.ts
- packages/template-kit/src/nodes/prompt-template.ts
- packages/template-kit/src/nodes/url-template.ts
- packages/template-kit/tests/nodes/prompt-template.ts
- Unify the config interfaces
- Fix some incorrect type errors from certain describe functions.
- Replace `multiline` field with `format`, which can be `multiline` or `javascript`
- Allow specifying behaviors
- Don't set properties on schema when it would be an empty object (just for cleaner formatting)
- Factor out `describe` tests
- `additionalProperties` is now set on generated port JSON schemas
- Add a coverage target
- Inbound edges, even if they don't have a value, now inform the auto generated input schema. 
- Automatically detected input ports are no longer `required`. Only static ones.
> [build] A bunch of improvements needed for migrating runJavascript

- .changeset/small-zebras-relax.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/super-worker.ts
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard/src/kits/load.ts
- packages/breadboard/src/new/grammar/board.ts
- packages/breadboard/src/new/grammar/scope.ts
- packages/breadboard/src/new/grammar/types.ts
- packages/breadboard/src/new/runner/node.ts
- packages/breadboard/src/new/runner/scope.ts
- packages/breadboard/src/new/runner/types.ts
- packages/breadboard/src/types.ts
- packages/schema/breadboard.schema.json
- packages/schema/src/graph.ts
- **Add `icon` to `GraphMetadata`.**
- **Plumb `GraphMetadata` to TS syntax.**
- **Add `smart-toy` icon to Super Worker.**
- **Plumb `icon` to `NodeHandlerMetadata`.**
- **docs(changeset): Support `icon` metadata on node types and graphs.**
> node type icon

- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
This brings it more in line with other tools, like the Chrome DevTools perf panel or Google Maps, inasmuch as scrolling down zooms out, and scrolling up zooms in. This is guaranteed to confuse me for a few days until I adjust! 😂
> [breadboard-ui] Reverse the scroll to zoom behavior

- .changeset/tough-kings-yell.md
- packages/build/src/index.ts
- packages/build/src/internal/define/define.ts
- packages/build/src/internal/define/definition.ts
- packages/build/src/internal/define/unsafe-schema.ts
- packages/build/src/test/describe_test.ts
Can be used in a node definition's `describe` function to directly specify some raw JSON schema, instead of a normal `@breadboard-ai/build` port configuration.
Useful for cases like the `invoke` node where we need to trust that the schema returned by some dynamically loaded board is valid.
> [build] Add unsafeSchema function

- .changeset/new-news-smile.md
- .changeset/nice-hotels-wash.md
- .changeset/wet-hounds-drum.md
- packages/breadboard-web/public/graphs/best-of-n.json
- packages/breadboard-web/public/graphs/nager.date/available-countries.json
- packages/breadboard-web/public/graphs/nager.date/country-info.json
- packages/breadboard-web/public/graphs/nager.date/long-weekend.json
- packages/breadboard-web/public/graphs/tour-guide-writer.json
- packages/build/src/internal/define/json-schema.ts
- packages/build/src/internal/type-system/object.ts
- packages/build/src/internal/type-system/type.ts
- packages/build/src/test/compatibility_test.ts
- packages/build/src/test/define_test.ts
- packages/build/src/test/describe_test.ts
- packages/build/src/test/type_test.ts
- packages/core-kit/src/nodes/fetch.ts
- packages/core-kit/tests/run-javascript.ts
- packages/core-kit/tests/secrets.ts
- packages/template-kit/src/nodes/prompt-template.ts
- packages/template-kit/tests/nodes/prompt-template.ts
- For `unknown`, we previously emitted `{}`, but now we emit `{type: ["array", "boolean", "null", "number", "object", "string"]}`. These are technically equivalent according to JSON schema, but since there is some other Breadboard code that treats `{}` as `string`, doing the verbose thing is a bit more compatible.
- Updated some `core-kit` and `template-kit` nodes to use `unknown` instead of `object`. In JSON Schema, `object` means a JSON object like `{foo}`, but not a basic type like `"foo"`. In these nodes, some inputs/outputs can be any kind of JSON, so this is now the more correct broader type.
> [build] [core-kit] [template-kit] Be more explicit & verbose with generated schemas

- .changeset/nice-carpets-repeat.md
- package-lock.json
- packages/core-kit/src/nodes/fetch.ts
Reverts breadboard-ai/breadboard#1535. I was way too hasty here -- this isn't the right fix. It looks like `fetch` doesn't actually stringify things and when this landed suddenly all fetch bodies were `[Object object]`.
> Revert "fetch body"

- .changeset/sweet-spoons-drive.md
- packages/build/src/internal/board/input.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/test/input_test.ts
- packages/build/src/test/serialize_test.ts
Inputs can now be used like this:
```ts
import {input} from "@breadboard-ai/build";
// These two inputs will end up on the same, default input node called "input-0":
const default1 = input();
const default2 = input({type: "number"})
// These two inputs will end up on the same custom input node called "my-special-input":
const custom1 = input({$id: "my-special-input");
const custom2 = input({$id: "my-special-input", type: "number"})
```
So, in this way, the `$id` field works kind of like the `name` field on HTML's `<input>`.
This lets you control exactly how many input nodes you get and how they are wired.
> [build] Allow setting id on inputs

- .changeset/modern-actors-worry.md
- packages/build/src/index.ts
- packages/build/src/internal/board/unsafe-cast.ts
- packages/build/src/test/serialize_test.ts
Add unsafeCast function as an escape hatch for when an output doesn't match a type but you're really really sure it's ok.
> [build] Add `unsafeCast` function

- .changeset/clean-schools-wait.md
- packages/build/README.md
- packages/build/src/internal/define/instance.ts
- packages/build/src/test/define_test.ts
- packages/build/src/test/serialize_test.ts
We have a few other "unsafe" functions which help identify escape hatches from strict typing. So, just keeping the naming scheme consistent.
> [build] Rename assertOutput to unsafeOutput

- .changeset/wild-trains-deliver.md
- packages/template-kit/package.json
Still prevents JS from actually being imported at runtime.
> [template-kit] Expand the exports to allow internal types to be referenced

- .changeset/eight-pigs-dream.md
- packages/breadboard-web/src/boards/build-example.ts
- packages/breadboard-web/src/boards/math.ts
- packages/breadboard-web/src/build-example-kit.ts
- packages/template-kit/package.json
- packages/template-kit/src/index.ts
- packages/template-kit/src/nodes/prompt-template-tag.ts
- packages/template-kit/src/nodes/prompt-template.ts
- packages/template-kit/tests/prompt-template-tag_test.ts
Adds a utility that makes it safer and more convenient to instantiate a `promptTemplate` node using JavaScript template string literals.
Usage:
```ts
import {prompt} from '@google-labs/template-kit';
import {input} from '@breadboard-ai/build';
const dish = input();
const steps = input({default: 10});
const instructions = prompt`Write a ${dish} recipe in under ${steps} steps`;
```
To customize the node id of the `promptTemplate` node that this function will create, you can use the `configure` method:
```ts
const instructions =
prompt`Write a ${dish} recipe in under ${steps} steps`.configure({
id: "recipe-template",
});
```
To customize the name of a parameter within the template, use the `promptPlaceholder` function to wrap the value:
```ts
import {prompt, promptPlaceholder} from …
```
> [template-kit] Add prompt tagged template literal function

- .changeset/little-turtles-relax.md
- packages/breadboard-web/src/index.ts
- packages/breadboard-web/src/preview-run.ts
- packages/breadboard/src/harness/run.ts
Make asking for secrets interactively an option. This used to be the default for breadboard-web.
> [breadboard] Interactive secrets option on `RunConfig`.

- .changeset/clever-carrots-exercise.md
- packages/breadboard-web/public/graphs/build-example.json
- packages/breadboard-web/public/local-boards.json
- packages/breadboard-web/src/boards/build-example.ts
- packages/core-kit/src/index.ts
- packages/core-kit/src/nodes/code.ts
- packages/core-kit/tests/code_test.ts
The `code` function creates a `runJavascript` Breadboard node in a
type-safe manner. Usage:
```ts
import {code} from "@google-labs/core-kit";
import {board, input} from "@breadboard-ai/build";
const forwards = input({ description: "A string to reverse" });
const reversed = code({ forwards }, { reversed: "string" }, ({ forwards }) => ({
reversed: str.split("").reverse().join(""),
}));
export board({forwards}, {reversed: reversed.outputs.reversed});
```
As a future improvement, we could make the `outputs` parameter optional, but we'd
have to be careful with schema. What we'd need to do if `outputs` is missing is:
1. Infer the output ports from `ReturnType<fn>` instead of from `outputs`.
2. Return a node that has a magic `outputs` object. This `outputs` object
would be a proxy that overloads …
> [core-kit] Add `code` function

- .changeset/tame-guests-flash.md
- packages/core-kit/src/index.ts
- packages/core-kit/src/nodes/secrets.ts
Adds a `secret` function which creates and configures a `secrets` node for just one secret, and returns the corresponding output port. A simpler way to get secrets in the API.
```ts
import {secret} from '@breadboard-ai/core-kit';
// OutputPort<string>
const geminiKey = secret('GEMINI_KEY');
```
> [core-kit] Add secret helper function

- .changeset/shaggy-seas-add.md
- packages/build/src/internal/common/type-util.ts
- packages/build/src/internal/define/define.ts
- packages/build/src/internal/define/definition.ts
- packages/build/src/internal/define/instance.ts
- packages/build/src/test/board_test.ts
- packages/build/src/test/define_test.ts
- packages/core-kit/src/nodes/code.ts
- packages/core-kit/tests/code_test.ts
Fix a bug in the @breadboard-ai/build type system that allowed node instances to be passed as board outputs even if they did not have a primary port.
> [build] Fix type bug relating to instances acting as outputs even when they have no primary port

- .changeset/tame-phones-flow.md
- packages/build/src/index.ts
- packages/build/src/internal/board/constant.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/test/serialize_test.ts
Add `constant` function which can be used to annotate edges that should get the `constant` bit (also known as memoize).
> [build] Add constant function

- .changeset/early-lamps-switch.md
- .changeset/grumpy-drinks-dance.md
- packages/build/src/internal/define/define.ts
- packages/build/src/internal/define/definition.ts
- packages/build/src/internal/define/describe.ts
- packages/build/src/test/define_test.ts
- packages/build/src/test/describe_test.ts
- packages/core-kit/src/nodes/secrets.ts
- packages/core-kit/tests/secrets.ts
Defaults are now always passed into the describe function, and types will be optional or not based on whether there is a default (default means it can never be undefined).
Also factors out a `describe.ts` file for better readability.
> [build] Improve handling of defaults in describe functions

- packages/build/src/internal/define/define.ts
- packages/build/src/internal/define/definition.ts
- packages/build/src/internal/define/describe.ts
- packages/build/src/internal/define/json-schema.ts
- packages/build/src/test/describe_test.ts
`describe` functions are now passed `inputSchema` and `outputSchema`. Unlike the previous `describe` signature, though, now those two properties are part of the `context`. This just makes the signature easier a bit easier to read, instead of passing those properties as their own parameters.
The schemas are converted to `PortConfig` objects, which are very similar, but use Breadboard Type Expressions as the `type` field, instead of JSON. The original schema is bundled into a special `unsafeType` wrapper so that it's preserved exactly if the describe-author decides to return the incoming schema unchanged.
> [build] Pass inputSchema and outputSchema to describe functions

- .changeset/modern-mugs-think.md
- packages/build/src/index.ts
- packages/build/src/internal/type-system/object.ts
- packages/build/src/test/type_test.ts
Example, the TypeScript:
```ts
import {object, optional} from "@breadboard-ai/build";
const obj = object({
req: "number",
opt: optional("number"),
});
```
... creates the TypeScript type:
```ts
{ req: number; opt?: number | undefined; }
```
... and the JSON Schema:
```json
{
"type": "object",
"properties": {
"opt": { "type": "number" },
"req": { "type": "number" }
},
"required": ["req"],
"additionalProperties": false
}
```
> [build] Allow declaring objects with optional properties

- .changeset/polite-masks-fly.md
- packages/core-kit/src/nodes/passthrough.ts
- packages/core-kit/tests/passthrough.ts
There is a change here, as shown by the tests, which I think is for the better. The output schema of `passthrough` is now taken from the connected `inputSchema` instead of just using the values. This preserves more information about the ports that are being passed-through.
> [core-kit] Convert passthrough to new API

- .changeset/lazy-birds-smile.md
- .changeset/small-news-report.md
- packages/build/src/internal/common/error.ts
- packages/build/src/internal/define/define.ts
- packages/build/src/internal/define/definition.ts
- packages/build/src/internal/define/instance.ts
- packages/build/src/test/define_test.ts
- packages/build/src/test/error_test.ts
- packages/json-kit/src/nodes/jsonata.ts
- packages/json-kit/tests/jsonata.ts
Node invoke functions can now return `{$error}`.
All node instances now automatically have an `outputs.$error`.
Throwing from an invoke function will now convert the exception to an `$error` result; the stack trace is logged to the server, but not shown to the end-user.
> [build] Support for $error

- packages/build/src/internal/type-system/annotate.ts
- packages/build/src/test/type_test.ts
Forgot to test that the types were preserved correctly in https://github.com/breadboard-ai/breadboard/pull/1703. They weren't!
> [build] Fix type behavior of annotate function

- packages/breadboard-ui/src/elements/editor/graph-node.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
Per https://pixijs.com/blog/pixi-v8-launches#-scene-upgrades we can use GPU for Container transforms... so why not?
> [breadboard-ui] Use GPU for transforms

- .changeset/funny-rockets-sing.md
- .changeset/thick-bikes-care.md
- packages/gemini-kit/src/boards/gemini-generator.ts
Both are to help the conversion to the new API, since I want to verify that the BGL outputs are identical. Streaming support isn't working anyway, so commenting it out simplifies things. Automatic node ID generation is a bit unreliable, so hard-coding those helps too.
> [gemini-kit] Remove streaming support and add node IDs

- .changeset/old-birds-pay.md
- packages/build/src/index.ts
- packages/build/src/internal/board/converge.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/internal/common/serializable.ts
- packages/build/src/internal/define/definition.ts
- packages/build/src/test/converge_test.ts
Previously, nodes could only be instantiated with a single input, meaning an input port could only have one incoming edge. Now using the `converge` function, you can pass multiple edges.
```ts
def({ foo: converge(a, b) }
```
The type of a convergence is the union of the input values, so `converge(input({type: "string"}), input({type: "number"}))` gives the type `string|number`. This is good because it  enforces that the invoke function you wire it up to can handle all of the possible value types from all of the possible incoming edges.
The alternative to this syntax was accepting arrays of input values. However, I think it's useful to have a clearly distinctive signature to remove any ambiguity between *an array of values intended to each be separately wired* (the convergence case), from …
> [build] Add converge function for ports with multiple incoming edges

- .changeset/dirty-mice-begin.md
- packages/build/src/internal/board/board.ts
- packages/build/src/internal/board/output.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/internal/common/port.ts
- packages/build/src/internal/common/serializable.ts
- packages/build/src/internal/define/definition.ts
- packages/build/src/internal/define/instance.ts
- packages/build/src/test/output_test.ts
When defining a board, you can now pass an array of objects. Previously you could only pass one object. When there are multiple outputs, that means multiple output nodes will be serialized, one each. The ID can be set with `$id`, or else it defaults to the `output-1`, `output-2`, etc. scheme.
```ts
export default board({
title: "My Board",
inputs: { ... }
},
outputs: [
{
$id: "my-output-node-1",
out1,
out2,
},
{
$id: "my-output-node-2",
$metadata: {
title: "My Title",
},
out2,
out3,
},
],
> [build] Support multiple output nodes

- .changeset/chatty-moons-buy.md
- packages/breadboard-web/public/graphs/build-example.json
- packages/core-kit/src/nodes/code.ts
- packages/core-kit/tests/code_test.ts
The core-kit code helper function now behaves exactly like the one in breadboard-ai in terms of the function name it selects for the code.
I'm not actually sure this is necessary, since I think we can just wrap any function (arrow or traditional) in parens and call it immediately (`(<fn>)()`); but in the immediate term matching the serialization behavior is nice because it makes comparing board conversions easier.
> [core-kit] Process function name in code helper

- .changeset/few-feet-hunt.md
- packages/build/src/internal/type-system/enumeration.ts
- packages/build/src/test/enumeration_test.ts
Not technically needed, but we have tended to do this in our manually written schema so it helps when comparing.
> [build] Set the "type" field when an enumeration is all of the same type

- .changeset/fuzzy-months-hear.md
- packages/build/src/internal/board/serialize.ts
- packages/build/src/test/serialize_test.ts
- packages/template-kit/tests/prompt-template-tag_test.ts
Pretty sure we don't want this ultimately, but mimicking the current serialization behavior for now to ensure we're compatible. The UI currently seems not to be able to read non-string values out of defaults/examples (at least in some cases).
> [build] Stringify all defaults and examples

- .changeset/green-yaks-visit.md
- packages/build/src/internal/board/converge.ts
- packages/build/src/test/converge_test.ts
Useful for defaults:
```ts
foo({
foo: converge({}, someOtherOutput)
});
```
> [core] Allow converge function to take raw values

- .changeset/angry-schools-poke.md
- packages/breadboard/src/inspector/bubbled-node.ts
- packages/breadboard/src/inspector/node.ts
- packages/breadboard/src/inspector/ports.ts
Before this PR, effectively saying that an output port was required meant "you must wire this up", since it would turn red in the UI if you didn't. However, really if an output port is required, it's just saying that it won't be undefined, and it has no bearing on how the caller choses to use it or not.
> [breadboard] Clarify meaning of required output ports

- .changeset/quick-steaks-search.md
- packages/build/src/internal/board/input.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/test/input_test.ts
Optional inputs are sort of interesting. They don't mean that the value can be undefined, they mean that the user will be prompted for the value if it's undefined.
> [build] Allow inputs to be optional

- .changeset/strange-tables-refuse.md
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
You can now:
1. Click and drag the cursor to select nodes and edges
2. Use the mouse wheel to move around the canvas
3. Use cmd/ctrl + mouse wheel to zoom in / out of the canvas
This brings the controls more in line with other canvas-centric apps
> [breadboard-ui] Allow box selection; change controls

- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-web/src/data/settings-store.ts
For whatever reason I like my scroll-to-zoom direction to be the opposite to the default, so here's a setting that allows the user to choose.
> [breadboard-ui] Add "invert scroll to zoom" setting

- .changeset/proud-snakes-help.md
- packages/breadboard-ui/src/elements/node-info/node-info.ts
- packages/breadboard/src/inspector/ports.ts
- packages/breadboard/src/inspector/types.ts
- **Actually initialize `InspectablePort.type`  🤦.**
- **docs(changeset): Actually initialize `InspectablePort.type`.**
> intialize inspectable port type

- packages/breadboard-ui/src/elements/input/input.ts
- packages/breadboard-web/public/graphs/super-worker-test.json
- packages/breadboard-web/src/boards/super-worker-test.ts
I noticed we had an array of LLM Contents as the examples for the specialist, i.e., examples is an array and the zeroth item itself was an array of LLM Contents... whereas the input itself is set to a single LLM Content. This meant that the LLM Input received an array when it expected an object.
> [breadboard-web] Fix specialist testing grounds

- .changeset/silly-moose-learn.md
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/editor/edge.ts
- packages/breadboard/src/editor/edit.ts
- packages/breadboard/src/editor/graph.ts
- packages/breadboard/src/editor/operations/add-edge.ts
- packages/breadboard/src/editor/operations/add-node.ts
- packages/breadboard/src/editor/operations/addedge.ts
- packages/breadboard/src/editor/operations/change-configuration.ts
- packages/breadboard/src/editor/operations/change-edge.ts
- packages/breadboard/src/editor/operations/change-graph-metadata.ts
- packages/breadboard/src/editor/operations/change-metadata.ts
- packages/breadboard/src/editor/operations/remove-edge.ts
- packages/breadboard/src/editor/operations/remove-node.ts
- packages/breadboard/src/editor/types.ts
- packages/breadboard/src/inspector/graph.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/tests/editor/graph.ts
- packages/breadboard/tests/editor/metadata.ts
- **Migrate `AddEdge` to an operation.**
- **Introduce `InspectableGraph.typeById`.**
- **Introduce `AddNode` operation.**
- **Introduce `RemoveNode` operation.**
- **Introduce `RemoveEdge` operation.**
- **Introduce `ChangeEdge` operation.**
- **Introduce `ChangeConfiguration` operation.**
- **Introduce `ChangeMetadata` operation.**
- **Introduce `ChangeGraphMetadata` operation.**
- **Remove helper methods.**
- **Use a routing map.**
- **docs(changeset): Switch to use edit operations machinery in Editor API internals.**
> operations

- .changeset/proud-crabs-breathe.md
- packages/breadboard/src/inspector/run/path-registry.ts
- **Only mark `events` as dirty when mutating path registry.**
- **docs(changeset): Don't update events when looking up event data.**
> fix event rerender

- packages/breadboard-web/src/index.ts
> [breadboard-ui] Only show history when focused on renderer

- packages/breadboard-ui/src/elements/editor/graph-node.ts
I noticed the ordering of ports wasn't stable when we went between hiding and showing "Advanced Ports"; this PR fixes that.
> [breadboard-ui] Sort port names in graph node

- .changeset/spotty-worms-reflect.md
- packages/core-kit/src/nodes/run-javascript.ts
- packages/core-kit/tests/run-javascript.ts
There is now an optional port called `schema` it accepts JSON schema. When populated it will create output ports of the correct name and type. There is no validation on the result of the `runJavascript`
Fixes #1930
> [runJavascript schema] Adds Schema support to runJavascript

- .changeset/silver-tigers-design.md
- .changeset/wet-moles-sin.md
- package-lock.json
- packages/breadboard-ui/package.json
- packages/breadboard-ui/src/contexts/data-store.ts
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-ui/src/elements/input/llm-input/llm-input.ts
- packages/breadboard-ui/src/elements/llm-output/llm-output.ts
- packages/breadboard-ui/src/types/types.ts
- packages/breadboard-ui/src/utils/llm-content.ts
- packages/breadboard/src/data.ts
- packages/breadboard/src/data/common.ts
- packages/breadboard/src/data/data.ts
- packages/breadboard/src/data/index.ts
- packages/breadboard/src/data/inflate-deflate.ts
- packages/breadboard/src/data/simple.ts
- packages/breadboard/src/data/types.ts
- packages/breadboard/src/index.ts
- packages/breadboard/src/types.ts
- packages/core-kit/src/index.ts
- packages/core-kit/src/nodes/deflate.ts
- packages/core-kit/src/nodes/fetch.ts
- **Aspirational `DataStoreProvider` API types.**
- **Gross hacks in `llm-input` and `llm-output` to make `StoredData` show up.**
- **Sketch working end to end.**
- **Move `inflateData` to `breadboard` package.**
- **Make text files work with stored data.**
- **Very basic `DataStore`.**
- **Remove spurious imports.**
- **Add `deflate` node to Core Kit.**
- **Move files around.**
- **Add thoughtful comment.**
- **Use Lit context to provide `DataStore` only to Activity Log.**
- **docs(changeset): Introduce `deflate` node.**
- **docs(changeset): Implement `DataStore` and a simple implementation.**
> data store

- package-lock.json
- packages/breadboard-ui/src/contexts/contexts.ts
- packages/breadboard-ui/src/contexts/environment.ts
- packages/breadboard-ui/src/elements/connection/connection-server.ts
- packages/breadboard-ui/src/elements/connection/connection-settings.ts
- packages/breadboard-ui/src/elements/elements.ts
- packages/breadboard-ui/src/elements/overlay/settings-edit.ts
- packages/breadboard-ui/src/index.ts
- packages/breadboard-ui/src/types/types.ts
- packages/breadboard-web/package.json
- packages/breadboard-web/src/data/settings-store.ts
- packages/breadboard-web/src/index.ts
- packages/connection-server/src/api/list.ts
Adds a "Connections" settings panel which talks to the Breadboard Connections Server and displays the list of available OAuth endpoints. It is not yet possible to actually *connect*, that will come in followups.
<hr>
I added two general-purpose features to facilitate this:
1. You can now render a completely custom settings panel UI. The connections panel is quite specialized, so it's nice to have full control over the UI instead of using the generic settings form/widgets.
```js
[BreadboardUI.Types.SETTINGS_TYPE.CONNECTIONS]: {
configuration: {
extensible: false,
description:
"Third-party services boards can access. When you are signed into a service, any board can access and modify your data on that service.",
nameEditable: false,
nameVisible: false,
customElement: …
```
> [connections] Adds a Connections settings panel

- .changeset/shiny-brooms-compete.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-web/src/index.ts
This is a pre-cursor to storing the collapse/expand state for nodes
> [breadboard-ui] Retire single node move event

- .changeset/grumpy-plums-help.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
- packages/breadboard-ui/src/events/events.ts
Working on #1753
Because this is now part of the metadata it also gets tracked as part of the undo/redo stack and also allows for some nodes being collapsed, and others being open.
> [breadboard-ui] Teach visual metadata about collapsed state

- .changeset/swift-colts-rhyme.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-web/src/index.ts
You can drop bgl.json files as before, but now you can also drop serialized runs from the Activity Log and they will load in 👍🏻
> [breadboard-ui] Support drag and drop of run data

- .changeset/short-falcons-appear.md
- packages/breadboard-ui/src/contexts/data-store.ts
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-ui/src/elements/input/llm-input/llm-input.ts
- packages/breadboard-ui/src/elements/llm-output/llm-output.ts
- packages/breadboard-ui/src/elements/node-info/node-configuration.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/data/inflate-deflate.ts
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/harness/run.ts
- packages/breadboard/src/types.ts
- packages/core-kit/src/nodes/deflate.ts
- packages/core-kit/src/nodes/fetch.ts
- **Plumb `DataStore` through `NodeHandlerContext`.**
- **Make it actually work.**
- **Use a single DataStore instance in the UI.**
- **Use a single DataStore instance in Breadboard Web.**
- **docs(changeset): Plumb `DataStore` throuh to `NodeHandlerContext`.**
> provide data store

- packages/breadboard-ui/src/elements/editor/graph.ts
> [breadboard-ui] Avoid wire creation when the user clicks on a port

- .changeset/strong-windows-bow.md
- .changeset/thin-gifts-wave.md
- packages/core-kit/src/nodes/run-javascript.ts
- packages/gemini-kit/src/boards/nano-generator.ts
- packages/gemini-kit/src/index.ts
- packages/gemini-kit/src/kit.ts
- **Deprecate Gemini Vision.**
- **Teach runJavascript to report errors.**
- **Throw an error when Prompt API is not available.**
- **docs(changeset): Teach runJavascript to report errors.**
- **docs(changeset): Better error messages and descriptions, also deprecate `vision`.**
> nano comments

- .changeset/unlucky-pens-decide.md
- package-lock.json
- packages/board-server/.gcloudignore
- packages/board-server/README.md
- packages/board-server/package.json
- packages/board-server/scripts/build.ts
- **Exclude `.wireit` from App Engine upload.**
- **Start using esbuild for building.**
- **docs(changeset): Use esbuild for building the server bits to allow bundling Breadboard in.**
> board server esbuild

- .changeset/pretty-penguins-warn.md
- README.md
- package-lock.json
- packages/breadboard-ui/package.json
- packages/breadboard-ui/rollup.config.js
- packages/breadboard/README.md
- packages/breadboard/docs/fodder/happy-path.md
- packages/breadboard/docs/tutorial/README.md
- packages/breadboard/package.json
- packages/breadboard/rollup.config.js
- packages/breadboard/src/runner.ts
- packages/breadboard/tests/board.ts
- packages/graph-playground/package.json
- packages/llm-starter/package.json
- packages/node-proxy-server/functions/package.json
- packages/schema/src/scripts/generate-schema-id.ts
- packages/schema/src/tests/main.test.ts
- packages/template-kit/README.md
- packages/template-kit/docs/README.md
- packages/template-kit/package.json
- packages/website/src/docs/happy-path.md
- **Update all mentions of Node v19 to v22.**
- **Replace import assertions with import attributes.**
- **Update docs/etc. to 20.14.0**
- **docs(changeset): Switch to Nodejs v20.14.0 as the baseline.**
> node 20.14

- .changeset/clever-stingrays-work.md
- package-lock.json
- packages/board-server/package.json
- packages/board-server/src/app/app.ts
- packages/board-server/src/index.ts
- packages/board-server/src/server/boards/index.ts
- packages/board-server/src/server/common.ts
- packages/board-server/src/server/errors.ts
- packages/board-server/src/server/proxy.ts
- packages/board-server/src/server/proxy/index.ts
- packages/board-server/src/server/proxy/secrets.ts
- packages/breadboard/src/data/common.ts
- packages/breadboard/src/remote/config.ts
- packages/breadboard/src/remote/proxy.ts
- packages/core-kit/src/nodes/fetch.ts
- **First sketch of Proxy Server API.**
- **Teach `fetch` to be more forgiving about the lack of data store.**
- **Teach NodeProxyConfig about DataStore.**
- **Teach app about URL search params.**
- **Teach data store to turn blobs into base64 in Nodejs.**
- **Loosely working node proxy server.**
- **Make app.ts forget about partDataURL cache (for now).**
- **Update package-lock.json.**
- **Remove spurious logging.**
- **Create a `secrets` node that uses Cloud Secret Manager.**
- **Grammar.**
- **Restrict access to proxy API via CORS for now.**
- **Better naming.**
- **docs(changeset): Teach Board Server to use Node Proxy Server**
> board server proxy

- package-lock.json
- package.json
- packages/breadboard-web/package.json
- packages/breadboard-web/src/embed.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard-web/src/preview.ts
- packages/breadboard-web/src/python-wasm-kit.ts
- packages/breadboard-web/vite.config.ts
- packages/python-wasm/.eslintrc
- packages/python-wasm/README.md
- packages/python-wasm/package.json
- packages/python-wasm/src/index.ts
- packages/python-wasm/src/run-python.ts
- packages/python-wasm/src/test/run-python_test.ts
- packages/python-wasm/tsconfig.json
It uses https://pyodide.org/ which is a Python WASM runtime that works in Node and on the Web.
> [python-wasm] Make a python-wasm node

- packages/breadboard-web/package.json
Adds option so that breadboard-web can be served with "npm run preview", using vite preview instead of vite dev.
preview serves the website from dist, which is more similar to how it will be served when deployed.
> [breadboard-web] Add vite preview option to scripts

- .changeset/neat-pandas-sniff.md
- .changeset/swift-kings-arrive.md
- packages/core-kit/src/index.ts
- packages/core-kit/src/nodes/fetch.ts
- packages/core-kit/src/nodes/unnest.ts
Adds a new `unnest` node to `core-kit`. It takes an object with N properties, and fans them out as output ports.
Also includes a type-aware utility for the build API. Sample usage:
```ts
const fileListType = object({
nextPageToken: optional("string"),
incompleteSearch: "boolean",
files: array(fileType),
});
const rawResponse = fetch({ url, headers });
const response = unsafeCast(rawResponse, fileListType);
const { files, incompleteSearch, nextPageToken } = unnest(response);
// Now we have 3 OutputPorts, which correspond to the 3 properties
// from the decoded fetch response. Types are all preserved.
```
> [core-kit] Add unnest node

- packages/breadboard-ui/src/elements/connection/connection-input.ts
After a refreshing an OAuth token automatically, we were returning the original token instead of the new one. We still saved the new one to local storage, so trying again would work, but now you don't need to.
> [connections] Fix bug with refreshing oauth token

- .changeset/silly-baboons-smell.md
- packages/build/src/internal/board/board.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/internal/common/serializable.ts
- packages/build/src/internal/define/define.ts
- packages/build/src/internal/define/definition.ts
- packages/build/src/internal/define/node-factory.ts
- packages/build/src/test/compatibility_test.ts
- packages/build/src/test/define_test.ts
- packages/build/src/test/nested-boards_test.ts
- packages/core-kit/tests/code_test.ts
Input ports with the "board" behavior can now receive board objects declared using the build API. This will be serialized as an embedded graph.
> [build] Serialize boards as subgraphs when passed as node inputs

- .changeset/silver-chicken-fix.md
- packages/breadboard-ui/src/elements/input/code-editor/code-editor.ts
- packages/breadboard-ui/src/elements/node-info/node-configuration.ts
Hopefully this fixes the remaining issues with CM's focus retention.
> [breadboard-ui] Unhook CodeMirror before DOM removal

- .changeset/plenty-ads-hunt.md
- packages/breadboard/src/loader/default.ts
This reverts commit 2411056c3080b2e192a98a55be7884b2fcd48f76.
> Revert "[breadboard] Add `credentials: include` to default loader's fetch."

- packages/breadboard-web/src/config.ts
- packages/breadboard-web/src/data/node-proxy-servers.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/harness/run.ts
- packages/breadboard/src/remote/proxy.ts
- packages/breadboard/tests/remote/proxy.ts
Adds a parameter proxy_url that allows a proxy url to be passed in.
This proxy url is used as an endpoint for proxy client.
> Add a Python proxy client for integrating with Python node proxy servers

- .changeset/flat-mirrors-love.md
- packages/breadboard-ui/src/elements/overflow-menu/overflow-menu.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.styles.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard-web/src/providers/indexed-db.ts
- packages/breadboard-web/src/providers/remote.ts
Including:
- Disabling overflow menu items when there is no loaded graph.
- Pointer cursor for overflow menu items.
- "Unable to load board" panel now fills the space.
- When pressing Cmd/Ctrl+S for a board without write permissions, we show the "Save as..." dialog.
- Added a "Delete Board..." option to the overflow menu.
- Provide a status update toast when deleting a board.
- Renaming of "Board Store" to "Browser Storage" for a bit of clarity.
> [breadboard-web/-ui] Various small UI tweaks

- .changeset/kind-cows-sip.md
- packages/breadboard-ui/src/elements/editor/graph-comment.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/website/src/js/board-embed.ts
Three fixes in one:
1. Uses an IntersectionObserver to handle rendering the embed. Fixes #2273.
2. Enables clicking on links on mobile devices. Fixes #2262.
3. Allows pinch-zoom and other, similar behaviors when in readOnly mode.
> [breadboard-ui/website] UI fixes for mobile

- .changeset/chilly-cobras-suffer.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-assets.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
Working on #2264
We weren't ensuring that the textures were loaded before the graph data was sent through. This meant that the icons were being assessed before the textures had loaded, the net result being nodes without icons.
This change largely involves awaiting the Pixijs app startup and texture loading code before sending any updated graph data through. The initialization code early exits on subsequent calls so it shouldn't cause multiple initializations.
> Ensure textures have loaded before graph data is sent through

- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-node.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
- packages/breadboard-ui/src/elements/editor/port-tooltip.ts
- packages/breadboard-ui/src/elements/editor/types.ts
- packages/breadboard-ui/src/elements/elements.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-web/src/data/settings-store.ts
Adds a new setting under General (off by default):
When checked, it enables a new tooltip that displays the raw schema when you hover over a port:
This makes it easy to see the low-level schema directly, so there's a bit more detail than you get on the RHS, and it's quicker since it pops up right where you're already looking with dense text. (Useful for me while I'm working on better schema validation).
Ugly since it's just for debugging (though could evolve into a prettier version potentially).
> [breadboard-web] Add setting for port hover tooltip (default off)

- packages/breadboard-ui/src/elements/editor/graph-node.ts
The local `port` variable we have might get out of date, so we need to grab the latest version on every mouseenter.
> [ui] Fix bug where port tooltips didn't update

- packages/breadboard-web/package.json
- packages/manifest/package.json
This improves caching in a few spots in the transitive build graph of the `npm run dev` command in `breadboard-web`. Changes to TypeScript files should usually now only trigger a single refresh instead of 2-3.
> [devx] Optimize breadboard-web build graph

- packages/breadboard-web/package.json
Follow up to https://github.com/breadboard-ai/breadboard/pull/2301 to improve stability. I removed some edges in that PR, but needed to add some more which were now no longer connected transitively.
> Add much more deps to genemanyrate:graphs

- .changeset/strange-files-deliver.md
- packages/breadboard/src/inspector/edge.ts
- packages/breadboard/src/inspector/types.ts
Adds a `validate` method to `InspectableEdge`. It grabs the schema for the from/to sides of the edge and calls `canConnect` to determine whether they are compatible. Includes a new Validation type so that we can add more structured data, detailed error messages, etc.
> [inspector] Add a validate method to InspectableEdge

- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-edge.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-web/src/data/settings-store.ts
Adds a new setting that displays wires in red if they are invalid. Wires are invalid if their from->to schemas are incompatible according to `canConnect` from the inspector API.
Defaults to OFF for now because I've seen some false-positives looking through example boards. After this PR I'll work on making sure `canConnect` covers all the cases, and then we can switch the default to ON after checking out a bunch of boards. There's probably also some things to fix in popular nodes & boards where we're actually configuring slightly wrong types.
> [ui] [web] New setting that displays wires in red if they are invalid

- .changeset/seven-donkeys-smoke.md
- packages/breadboard-cli/src/debugger/provider.ts
- packages/breadboard-ui/src/elements/nav/nav.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard-web/src/providers/examples.ts
- packages/breadboard-web/src/providers/file-system.ts
- packages/breadboard-web/src/providers/indexed-db.ts
- packages/breadboard-web/src/providers/remote.ts
- packages/breadboard/src/loader/default.ts
- packages/breadboard/src/loader/types.ts
We were waiting on board lists being restored before rendering the UI, which was slowing things down in the case of Board Servers particularly. This PR changes things so it eagerly renders while the Providers are restoring. To accommodate that change the main loader awaits the selected Provider's `ready` `Promise` before loading a board, and the nav similarly awaits the same before trying to render the item list.
> [breadboard-web] Unblock UI on providers

- .changeset/healthy-pets-rule.md
- package-lock.json
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-assets.ts
- packages/breadboard-web/src/index.ts
- **Remind breadboard-web to fall back to fetch when no provider found.**
- **Teach GraphAssets to be more loose about loading.**
> loading loading

- .changeset/orange-glasses-build.md
- packages/breadboard-web/package.json
- **Remind generate-graphs that it needs to build agent kit too**
- **docs(changeset): Remind generate-graphs that it depends on agent-kit**
> agent kit oops

- packages/manifest/bbm.schema.json
- packages/manifest/src/index.ts
- packages/manifest/src/isReference.ts
- packages/manifest/src/scripts/util/generate-schema-file.ts
- packages/manifest/src/tests/index.test.ts
- packages/visual-editor/src/providers/examples.ts
- merge after https://github.com/breadboard-ai/breadboard/pull/2362
> Update manifest with `GraphDescriptor` ref

- .changeset/cold-parrots-behave.md
- packages/visual-editor/package.json
- packages/visual-editor/src/index.ts
Since we have the dedicated "Board details" pane on the right hand side of the UI we no longer really need the edit button in the tab. So this PR changes the button to close the current board and return the user back to the Welcome Pane.
> [visual-editor] Change edit board to close board

- .changeset/rude-bananas-repair.md
- packages/visual-editor/package.json
- packages/visual-editor/src/index.ts
I noticed that when we delete a board we don't remove the board from the "Recent Boards" list, and the UI shows the tab _and_ the Welcome Pane.
This PR fixes both.
> [visual-editor] Clean up recent boards on delete

- .changeset/nasty-wombats-roll.md
- packages/visual-editor/src/ui/elements/editor/editor.ts
Noticed that comments from the parent graph were appearing after multi-edits on subgraphs. This PR fixes that.
> [visual-editor] Fix subgraph metadata/comments bug

- .changeset/few-garlics-flow.md
- package-lock.json
- packages/schema/package.json
- packages/schema/src/subschema.ts
- packages/schema/src/tests/subschema.test.ts
Given the JSON Schemas `a` and `b`, determine whether `a` is a sub-schema of `b`, and if not explain why.
We say that `a` is a sub-schema of `b` if every JSON Schema constraint in `b` is also present in `a` at an equal or higher strictness. Examples:
- If `b` enforces type `string OR number`, then `a` must enforce either `string`, `number`, or `string OR number`.
- If `b` enforces `maxLength` 4, then `a` must enforce `maxLength <= 4` .
> [schema] Add analyzeIsJsonSubSchema function

- .changeset/pink-doors-pay.md
- package-lock.json
- packages/breadboard/package.json
- packages/breadboard/src/inspector/ports.ts
- packages/breadboard/tests/inspector/ports.ts
Uses the new `analyzeIsJsonSubSchema` function from https://github.com/breadboard-ai/breadboard/pull/2394
> [inspector] Make canConnect smarter

- .changeset/stupid-clocks-sleep.md
- packages/visual-editor/src/index.ts
I noticed we were using a stale editor instance on occasion, which meant we'd get errors about non-existent nodes. This PR nulls out the editor instance as soon as we start a board.
> [visual-editor] Null out the editor earlier

- .changeset/sharp-zebras-battle.md
- packages/visual-editor/src/ui/elements/node-info/array-editor.ts
- packages/visual-editor/src/ui/elements/node-info/board-selector.ts
- packages/visual-editor/src/ui/elements/node-info/node-configuration.ts
Fixes #2332 
Fixes #2331 
We now only show tools in the board selector, and the embedded sub-boards show their title not their ID.
> [visual-editor] Tweak the board selector to only show tools

- packages/visual-editor/package.json
Likely to fix https://github.com/breadboard-ai/breadboard/issues/2402. I copied this script from another one, and forgot to fix the output files, so it's possible this was causing a race condition, clobbering the output of another script.
> [visual-editor] Fix the wireit config for copy-pyoide-assets

- .changeset/metal-hairs-smash.md
- .changeset/neat-trains-work.md
- .changeset/real-yaks-provide.md
- package-lock.json
- package.json
- packages/build/src/index.ts
- packages/build/src/internal/board/input.ts
- packages/build/src/internal/board/serialize.ts
- packages/core-kit/src/nodes/code.ts
- packages/core-kit/src/nodes/run-javascript.ts
- packages/core-kit/tests/code_test.ts
- packages/core-kit/tests/run-javascript.ts
- Adds `inputSchema` and `outputSchema` properties, to replace the now deprecated `schema` property (which is now the fallback for `outputSchema`).
- The `code` helper now automatically serializes both the input and output schemas.
- Fixes a bug relating to returning JSON Schema directly from `describe`, instead of wrapping it in `unsafeSchema`.
Fixes https://github.com/breadboard-ai/breadboard/issues/2396
Fixes https://github.com/breadboard-ai/breadboard/issues/2296
> [core-kit] Improve schema handling for runJavascript nodes

- .changeset/short-buttons-train.md
- packages/breadboard/src/inspector/kits.ts
- packages/breadboard/src/inspector/ports.ts
- packages/breadboard/src/inspector/types.ts
Add `kind` property to InspectablePort to tell you whether it's an input or output port.
> [inspector] Track whether InspectablePorts are input or output ports

- .changeset/polite-wolves-remember.md
- packages/visual-editor/src/ui/elements/editor/fancy-json.ts
- packages/visual-editor/src/ui/elements/elements.ts
Add fancy-json component for rendering JSON with configurable annotations. 
You give it a JSON value, and a list of annotations. The annotations are JSON paths (e.g. `["schema", "properties", 2, "type"]`) and some CSS part name. As we render values, we wrap them in `<span part="<PART>">` so that the parent component can then choose how to style those sub-trees.
> [visual-editor] Add Fancy JSON component

- .changeset/rich-lies-accept.md
- packages/breadboard/src/inspector/edge.ts
- packages/breadboard/src/inspector/ports.ts
- packages/breadboard/src/inspector/types.ts
Add analyzeCanConnect method to InspectablePort which is like canConnect but with detailed error messages.
> [inspector] Add analyzeCanConnect method

- .changeset/tender-jars-roll.md
- packages/visual-editor/src/ui/elements/editor/port-tooltip.ts
If a wire is invalid, and the "Show Port Tooltips" setting is enabled, then the port tooltip will now show which specific part of the schema is mismatched with the other port by rendering a red squiggly line under it.
> [visual-editor] Show red squigglies in port tooltips under mismatched schema constraints 

- .changeset/mean-shirts-relax.md
- packages/visual-editor/package.json
- packages/visual-editor/src/index.ts
> [visual-editor] Fall back to URL constructor for browsers without `canParse`

- .changeset/bright-eyes-unite.md
- packages/visual-editor/package.json
- packages/visual-editor/src/index.ts
Fixes #2423
We were overly eager with handling keyboard pastes at the root. Now we check to see if there's anything else in the composed path that would be better handling the paste first, and, if not, _then_ we go ahead and try to paste the board contents.
> [visual-editor] Improve paste handling

- .changeset/pretty-islands-prove.md
- packages/visual-editor/package.json
- packages/visual-editor/src/ui/elements/input/code-editor/code-editor.ts
- packages/visual-editor/src/ui/elements/node-info/node-configuration.ts
- packages/visual-editor/src/ui/elements/ui-controller/ui-controller.ts
Fixes #2412
It turns out there were still cases where focus was being locked by CodeMirror. Hopefully this set of changes fixes that.
> [visual-editor] Fix editor lock

- .changeset/large-cycles-refuse.md
- packages/breadboard/src/inspector/graph.ts
- packages/breadboard/src/types.ts
- packages/build/src/internal/define/definition.ts
- packages/build/src/test/describe_test.ts
- packages/core-kit/tests/invoke.ts
Add `wires` property to NodeDescriberContext which exposes a `describe()` function for getting the actual schema of a connected port if needed.
> [breadboard] Add "wires" property to NodeDescriberContext

- .changeset/selfish-mails-hear.md
- packages/google-drive-kit/src/list-files.ts
This improves type-safety in the visual editor when looking at the implementation of this board, because we now have a `cast` node which explicitly asserts the type for the `fetch` result, instead of wiring it up to outputs with no type checking.
> [google-drive-kit] Use new cast node

- .changeset/famous-ghosts-provide.md
- packages/core-kit/src/nodes/unnest.ts
The unnest node now uses the actual describe function of the connected node to discover the incoming schema, and sets the outgoing schema to match.
> [core-kit] Reflect incoming schema as output schema

- .changeset/lemon-radios-change.md
- packages/visual-editor/src/index.ts
As part of moving out the example boards to their own package I renamed the directory from which examples are served. So as not to break any old links this PR redirects any older /graphs/ URLs to the new /example-boards/ path.
> [visual-editor] Redirect older /graphs/ URLs to /example-boards/

- .changeset/thick-cameras-crash.md
- packages/build/src/internal/board/board.ts
- packages/build/src/internal/board/output.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/test/board_test.ts
Allows boards created with the `build` package to describe themselves as nodes.
> [build] Add describe function to Board component class

- .changeset/bright-eyes-unite.md
- .changeset/clean-kangaroos-wonder.md
- .changeset/cold-parrots-behave.md
- .changeset/four-dolls-provide.md
- .changeset/good-birds-brush.md
- .changeset/mean-shirts-relax.md
- .changeset/nasty-wombats-roll.md
- .changeset/ninety-bananas-argue.md
- .changeset/olive-trees-reply.md
- .changeset/orange-glasses-build.md
- .changeset/polite-wolves-remember.md
- .changeset/red-baboons-yell.md
- .changeset/rude-bananas-repair.md
- .changeset/sharp-zebras-battle.md
- .changeset/small-toys-cough.md
- .changeset/spotty-tips-knock.md
- .changeset/stupid-clocks-sleep.md
- .changeset/tasty-starfishes-repeat.md
- .changeset/tender-jars-roll.md
- .changeset/thirty-walls-sort.md
- .changeset/weak-files-beg.md
- packages/visual-editor/package.json
Also remove `publishConfig` from visual-editor package, (not needed for the `@breadboard-ai` npm namespace)
> Fix invalid changesets resulting from moved/archived packages

- .changeset/bright-islands-roll.md
- packages/build/src/index.ts
- packages/build/src/internal/kit.ts
Much simpler to make kits now. Just pass in the components to the `kit` function, be they discrete or boards, and get back a usable kit.
> [build] Make it much simpler to create kits

- .changeset/proud-jobs-eat.md
- packages/visual-editor/src/ui/elements/nav/nav.ts
- packages/visual-editor/src/ui/elements/overlay/provider.ts
I noticed that in fixing the nav scroll issue (which was essentially being overly keen to re-render the nav) we are now too keen in the other direction. This means that when a board is created or deleted, or when a provider is updated, we don't re-render the nav (even though we do perform the action).
This PR increases the set of things that will trigger a re-render of the nav.
> [visual-editor] Fix nav filter and delete behaviors

- package-lock.json
- package.json
- packages/board-server/package.json
Before, the process tree for `npm run s` (top-level script) looked like this:
```
- npm
- npm
- concurrently
- npm
- wireit
- server1
- npm
- wireit
- server2
```
Now it looks like this:
```
- npm
- wireit
- server1
- server2
```
The specific motivation for this was that `mprocs` wasn't working with `npm run s`. The reason for that was:
1. When you stop a script with `mprocs`, it sends `SIGTERM`
2. `concurrently` does not propagate `SIGTERM` to its children
npm and wireit do the right thing here, so now it should work fine.
Uninstalled concurrently as well, no need for it because wireit can already run things in parallel.
cc @timswanson-google
> [board-server] Simplify dev script configuration

- .changeset/fair-eyes-try.md
- packages/template-kit/src/nodes/url-template.ts
- packages/template-kit/tests/nodes/url-template.ts
Fixes #2486
Adding "number" type to wildcard input in Template Kit's `urlTemplate` node.
> Added "number" type to wildcard input

- packages/connection-server/package.json
Now if you make a file `secrets/local.json`, the `dev` script will pick it up automatically.
> [connections] Make connection server dev script use secrets/local.json if available

- packages/visual-editor/src/index.ts
- packages/visual-editor/src/ui/elements/connection/connection-common.ts
- packages/visual-editor/src/ui/elements/connection/connection-input.ts
- packages/visual-editor/src/ui/elements/connection/connection-signin.ts
- packages/visual-editor/src/ui/elements/connection/token-vendor.ts
- packages/visual-editor/src/ui/types/types.ts
Adds a `TokenVendor` class and Lit context, and refactors `connection-input` to use it. This piece will be useful for other elements that need to directly access OAuth tokens (like an upcoming Google Drive widget).
> [visual-editor] Refactor token handling logic to be more re-usable

- .changeset/purple-tips-matter.md
- package-lock.json
- packages/core-kit/src/nodes/run-javascript.ts
- packages/core-kit/tests/run-javascript.ts
- **Mark schema as deprecated on `runJavascript` component.**
- **docs(changeset): Mark `schema` as deprecated on `runJavascript`.**
> deprecate schema

- .changeset/fast-pillows-serve.md
- packages/core-kit/src/nodes/run-javascript.ts
- **Revoke worker URL after it's run in `runJavascript` component.**
- **docs(changeset): Stop leaking blob URLs in runJavascript.**
> fewer leaks

- packages/build/src/index.ts
- packages/build/src/internal/board/board.ts
- packages/build/src/internal/board/output.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/internal/common/value.ts
- packages/build/src/test/composition_test.ts
You can now instantiate a board as a component in the same way as a discrete component. Upon serialization, the inner board is added as a subgraph, and an `invoke` node is inserted to call it.
Fixes https://github.com/breadboard-ai/breadboard/issues/2571
> [build] Support board composition

- packages/website/src/static/boards/kits/core-unnest.bgl.json
Accidentally clobbered the `unnest` example in https://github.com/breadboard-ai/breadboard/pull/2619. Restoring the right now.
> [website] Fix unnest example BGL

- .changeset/neat-clouds-jog.md
- package-lock.json
- packages/agent-kit/package.json
- packages/agent-kit/src/context.ts
Converts most of the types to Breadboard Type Expressions so that they can be used with the Build API. Skipped a couple because we need a new `intersection` utility for `&` (which is like `allOf`, except for some tricky details around required properties).
> [agent-kit] Start converting agent kit types to Breadboard Type Expressions

- .changeset/small-comics-cry.md
- packages/agent-kit/package.json
- packages/breadboard-cli/package.json
- packages/core-kit/package.json
- packages/example-boards/package.json
- packages/gemini-kit/package.json
- packages/google-drive-kit/package.json
- packages/json-kit/package.json
- packages/python-wasm/package.json
- packages/template-kit/package.json
- packages/visual-editor/package.json
All of our `@breadboard-ai/build` version constraints were `0.7.1` instead of `^0.7.1`. Not sure why, but now they are fixed.
> Fix overly constrained version constraints

- .changeset/silver-pandas-applaud.md
- packages/json-kit/src/index.ts
Fixes #2547 
Added a line to export the `jsonata` node from the json kit. This node has already been migrated to the new Build API. Currently, the node cannot be imported directly and it has an unknown type when invoked from the kit, which causes errors when using in boards created with the Build API.
> Export jsonata node from json-kit

- .changeset/dirty-donkeys-try.md
- packages/board-server/src/server/boards/utils/run-board.ts
- packages/board-server/src/server/types.ts
- packages/board-server/tests/boards/many-outputs.bgl.json
- packages/board-server/tests/run-board.ts
- packages/breadboard/src/harness/index.ts
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/harness/run.ts
- packages/breadboard/src/harness/secrets.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/harness/url.ts
- packages/breadboard/src/harness/worker.ts
- packages/breadboard/src/remote/http.ts
- packages/breadboard/src/remote/index.ts
- packages/breadboard/src/remote/init.ts
- packages/breadboard/src/remote/proxy.ts
- packages/breadboard/src/remote/run.ts
- packages/breadboard/src/remote/types.ts
- packages/breadboard/src/remote/worker.ts
- packages/breadboard/tests/helpers/_test-transport.ts
- packages/breadboard/tests/remote/http.ts
- packages/breadboard/tests/remote/proxy.ts
- packages/breadboard/tests/remote/transport.ts
- **Flesh out the `RunBoardResult` type.**
- **Bring `breadboard/remote` types to follow the now-common pattern.**
- **Start sending out traversal state.**
- **Rename `state` to `saveState`.**
- **Introduce `RunConfig.resumeFrom`.**
- **Move `RunConfig` and friends to `types.ts`.**
- **Teach runBoard to resume.**
- **Build a nice `scriptedRun` test harness.**
- **Add test for multiple outputs.**
- **docs(changeset): Teach board-server run API endpoint to run simple boards.**
> board server run next

- .changeset/tricky-falcons-shout.md
- packages/connection-server/src/api/list.ts
- packages/visual-editor/src/ui/elements/connection/connection-common.ts
- packages/visual-editor/src/ui/elements/connection/connection-server.ts
- packages/visual-editor/src/ui/elements/connection/connection-signin.ts
- packages/visual-editor/src/ui/elements/connection/token-vendor.ts
Store the OAuth client ID locally, in addition to the token details. Useful for APIs that require the client ID to be provided.
Includes an automatic migration for existing stored oauth tokens to add in this field.
> [connections] [visual-editor] Store the OAuth client ID locally

- .changeset/many-eagles-brake.md
- packages/breadboard/src/inspector/ports.ts
- packages/breadboard/src/types.ts
- packages/visual-editor/src/ui/elements/elements.ts
- packages/visual-editor/src/ui/elements/google-drive/google-drive-file-id.ts
- packages/visual-editor/src/ui/elements/google-drive/google-drive-query.ts
- packages/visual-editor/src/ui/elements/input/user-input.ts
- packages/visual-editor/src/ui/utils/index.ts
Similar to the one for Google Drive Query, but for selecting exactly one file. Automatically populates the ID field from the picker result.
> [visual-editor] [breadboard] Behavior and picker component for Google Drive File ID

- .changeset/plenty-apricots-tie.md
- packages/google-drive-kit/src/components/export-file.ts
- packages/google-drive-kit/src/components/get-file-content.ts
- packages/google-drive-kit/src/components/list-files.ts
Annotate file ID/query inputs with new behaviors so that the dedicated input components will be used for them.
> [google-drive-kit] Annotate file ID/query inputs with new behaviors

- .changeset/stupid-books-bathe.md
- packages/google-drive-kit/src/internal/headers.ts
- packages/visual-editor/src/ui/elements/google-drive/google-drive-file-id.ts
- packages/visual-editor/src/ui/elements/google-drive/google-drive-query.ts
Switches from the Google Drive OAuth scope that requests full access, to the one that only requests access to files specifically shared with the app.
> [google-drive-kit] [visual-editor] Switch connection from `google-drive` to `google-drive-limited`

- .changeset/old-actors-carry.md
- .vscode/launch.json
- packages/board-server/src/server/boards/utils/run-board.ts
- packages/board-server/tests/boards/invoke-board-with-bubbling-input.bgl.json
- packages/board-server/tests/run-board.ts
- packages/breadboard/src/bubble.ts
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/run.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/src/stack.ts
- packages/breadboard/src/traversal/result.ts
- packages/breadboard/src/types.ts
- packages/breadboard/src/utils/async-gen.ts
- packages/core-kit/src/nodes/slot.ts
- **Tighten the types some more.**
- **Introduce the concept of `partialOutputs` and start resuming nested board.**
- **Modify the test to discern finishing the main board.**
- **Skip the test again.**
- **docs(changeset): Introduce the concept of `partialOutputs` to `TraversalState`, to convey outputs produced while processing bubbled inputs.**
> board server run invoke 2

- packages/core-kit/src/nodes/map.ts
- packages/core-kit/tests/data/boards/map-throw-error.bgl.json
Reverts breadboard-ai/breadboard#2629
I realized this weekend that this directly affects Specialist, since it uses `map` to invoke tools -- which mean that this removes the ability for tools to use the `Human` component. Whoops.
> Revert "map bubbling"

- .changeset/pretty-monkeys-roll.md
- packages/build/src/index.ts
- packages/build/src/internal/type-system/string.ts
- packages/build/src/test/type-expressions/string_test.ts
- packages/website/src/docs/build/type-expressions.md
```ts
import { string } from "@breadboard-ai/build";
const apiAddress = input({
type: string({ format: "uri", maxLength: 256 }),
});
```
> [build] Add support for JSON Schema string formatting options

- .changeset/spicy-jars-cross.md
- packages/breadboard/src/index.ts
- packages/breadboard/src/run/index.ts
- packages/breadboard/src/run/manager.ts
- packages/core-kit/src/nodes/map.ts
- packages/core-kit/tests/map.ts
- **Remove unused inputs.**
- **Remove tests that rely on GraphDescriptor actually being a BoardRunner.**
- **Refactor `map` to switch to serial mode when `RunStateManager` is present.**
- **docs(changeset): Refactor `map` to run serially when `RunStateManager` is present.**
> serial map

- packages/visual-editor/src/plugins/input-plugin.ts
- packages/visual-editor/src/ui/elements/input/delegating-input.ts
Part of https://github.com/breadboard-ai/breadboard/issues/2707. A new `bb-delegating-input` element which implements the `InputWidget` interface added in a previous PR. Its job is to look through all the plugins, find a suitable input element (which itself implements `InputWidget`), and then render that element.
> [visual-editor] Add a delegating-input element

- .changeset/khaki-rules-doubt.md
- .changeset/pink-steaks-roll.md
- packages/board-server/package.json
- packages/board-server/src/server/boards/index.ts
- packages/board-server/src/server/boards/run.ts
- packages/board-server/src/server/boards/utils/run-board.ts
- packages/board-server/src/server/boards/utils/verify-key.ts
- packages/board-server/src/server/info/index.ts
- packages/board-server/src/server/store.ts
- packages/board-server/src/server/types.ts
- packages/board-server/tests/run-board.ts
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/remote/types.ts
- packages/breadboard/src/run/reanimator.ts
- packages/breadboard/src/run/run-graph.ts
- packages/breadboard/tests/node/run/interruptible-run-graph.ts
- packages/website/src/docs/reference/board-run-api-endpoint.md
- **Remove unused types/imports.**
- **Switch to WritableStreamDefaultWriter to stream outputs.**
- **Sketch out `run` api endpoint.**
- **It's working!**
- **Pass next.**
- **Teach `end` result to provide last node.**
- **Teach resume to also adjust the invocation path.**
- **Start storing `ReanimationState` in firestore.**
- **Teach board store about TTL.**
- **Also display version on `/info` request.**
- **Update tests.**
- **Update more tests.**
- **Add docs.**
- **docs(changeset): Make sure that reanimator correctly adjusts invocationId when resuming.**
- **docs(changeset): Implement the `run` API endpoint.**
> interruptible run endpoint

- .changeset/cool-beers-mix.md
- packages/breadboard/src/loader/default.ts
- **Retry with credentials in default fetch for boards.**
- **docs(changeset): Retry with credentials when board fetch fails.**
> retry with credentials

- packages/breadboard/src/data/default-run-store.ts
- packages/breadboard/src/data/types.ts
- packages/breadboard/src/inspector/run/run.ts
- packages/breadboard/tests/inspector/default-run-store.ts
- packages/breadboard/tests/inspector/observer-load.ts
- packages/data-store/src/run/idb-run-store.ts
- packages/data-store/tests/run/idb-run-store.browser.test.ts
- packages/visual-editor/package.json
Fixes #2734
This ended up being a whopper of a fix! We now store runs per URL by timestamp, which means a couple of things:
1. We no longer "leak" inputs across runs when the board changes. (Previously if two boards had identically-named inputs we would pre-fill the input based on another unrelated run.)
2. The Run Observer restores the runs from the store before creating a new one, which means if a board is open in multiple browser tabs the Run Observer will pick up the runs created in other tabs automatically.
All tests are updated.
> [breadboard/data-store] Fix parallelism issues in Run Store

- .changeset/six-numbers-train.md
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/run/run-graph.ts
- packages/breadboard/src/traversal/index.ts
- packages/breadboard/src/traversal/iterator.ts
- packages/breadboard/src/traversal/machine.ts
- packages/breadboard/src/traversal/representation.ts
- packages/breadboard/src/types.ts
- packages/breadboard/tests/data/describe-start-tag-no-run.json
- packages/breadboard/tests/data/describe-start-tag-run.json
- packages/breadboard/tests/data/simple-start-tag.json
- packages/breadboard/tests/data/specified-start-tag.json
- packages/breadboard/tests/data/start-tag-in-the-middle.json
- packages/breadboard/tests/machine.ts
- packages/schema/breadboard.schema.json
- packages/schema/src/graph.ts
- **Remove `noParallelExecution` flag.**
- **Sketch out the basics.**
- **Allow starting from the middle of a graph.**
- **Allow simple start tags.**
- **Teach TraversalMachine to start with different labels.**
- **Plumb `StartLabel` to `RunArguments`.**
- **Plumb `StartLabel` to Run API.**
- **docs(changeset): Add support for multiple graph entry points and start tags.**
> start tags

- .changeset/smooth-lies-sniff.md
- packages/build/src/internal/type-system/annotate.ts
- packages/build/src/test/type-expressions/annotate_test.ts
So that you can annotate a type with an existing behavior and they will get merged together, instead of clobbered.
> [build] Make the annotate function additive

- .changeset/blue-sheep-smile.md
- .changeset/small-geese-dance.md
- packages/build/src/index.ts
- packages/build/src/internal/board/board.ts
- packages/build/src/internal/board/output.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/internal/common/serializable.ts
- packages/build/src/internal/common/type-util.ts
- packages/build/src/internal/common/value.ts
- packages/build/src/internal/define/definition.ts
- packages/build/src/internal/kit.ts
- packages/build/src/test/better-board_test.ts
- packages/build/src/test/board_test.ts
- packages/build/src/test/input_test.ts
- packages/build/src/test/output_test.ts
- packages/build/src/test/serialize_test.ts
- packages/core-kit/src/nodes/code.ts
- packages/core-kit/tests/code_test.ts
- packages/gemini-kit/src/boards/gemini-generator.ts
Introduces a change to the signature of `board` in the build API which brings better typing and clarity, especially for polymorphic boards.
You can now declare board inputs in one of 3 ways:
1. As a plain bag of inputs, which automatically creates a single input node:
```ts
board({inputs: {foo, bar}});
```
2. As an input node object, which lets you add metadata to it:
```ts
board({
inputs: inputNode(
{ foo, bar },
{
id: "my-inputs",
description: "My Inputs",
}
),
});
```
3. As an array of input nodes, which lets you have many input nodes (the `inputNode` wrapper is required in this case, because I think if you're doing more than one input node, we should encourage the use of descriptions to explain the polymorphism):
```ts
board({
inputs: [
inputNode({ foo }, { id: "inputs-a", …
```
> [build] New improved board function

- .changeset/rude-apricots-fly.md
- packages/board-server/src/server/boards/run.ts
- packages/board-server/src/server/boards/utils/run-board.ts
- packages/board-server/src/server/types.ts
- packages/board-server/tests/run-board.ts
- packages/breadboard-cli/tests/index.ts
- packages/breadboard/src/data/types.ts
- packages/breadboard/src/harness/error.ts
- packages/breadboard/src/harness/index.ts
- packages/breadboard/src/harness/local-runner.ts
- packages/breadboard/src/harness/remote-runner.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/remote/http.ts
- packages/breadboard/src/remote/index.ts
- packages/breadboard/src/remote/run-graph-server.ts
- packages/breadboard/src/remote/run.ts
- packages/breadboard/src/remote/types.ts
- packages/breadboard/src/run/run-graph.ts
- packages/breadboard/tests/editor/metadata.ts
- packages/breadboard/tests/node/run/local-runner.ts
- packages/breadboard/tests/node/run/remote-runner.ts
- packages/breadboard/tests/node/run/test-utils.ts
- packages/breadboard/tests/node/test-kit.ts
- packages/breadboard/tests/remote/transport.ts
- **Plumb diagnostic events through run-board.**
- **Sketch out RemoteRunner.**
- **Switch `end` to use EndResponseMessage.**
- **Switch `error` to use ErrorResponseMessage.**
- **Switch `skip` to use SkipMessage.**
- **Naming tweaks.**
- **Switch `graphstart` to use GraphStartRemoteMessage.**
- **Switch all but `input` to use *ResponseMessage.**
- **Massage types a bit.**
- **Remote type renames.**
- **Clip out RunState bits.**
- **Remove RunState from InputRemoteMessage.**
- **Switch `input` to use InputRemoteMessage.**
- **Remove RunBoardResult.**
- **Tweak type names.**
- **Another sketch of RemoteRunner.**
- **Start sketching out tests.**
- **Sketch out `handleRunGraphRequest`.**
- **Replace board server logic with the `handleRunGraphRequest` call.**
- **Polish.**
- **Add first …
> remote run

- packages/website/src/docs/build/build.md
Covers declaring outputs and boards, pulls things together with a full example, and refines some of the existing docs.
> [build] [website] More build API docs

- packages/board-server/package.json
The vite build wasn't building its dependencies
> [board-server] Add missing wireit deps

- packages/board-server/src/index.ts
- packages/board-server/src/router.ts
Part of #2896
This is a first step toward reworking the server routing logic for board server
to look more like connection server. The two servers employ very different
patterns. Especially if we want eventually to unify them, it would make sense to
have them follow the same basic patterns.
Next step is to create a Config object in board server similar to what
connection server uses. This is what would contain the ALLOWED_ORIGINS
environment variable.
> [board-server] Move routing logic into a router module

- .changeset/perfect-rice-destroy.md
- .changeset/stale-chefs-train.md
- packages/build/src/internal/define/definition.ts
- packages/build/src/internal/kit.ts
- packages/build/src/test/kit_test.ts
- packages/google-drive-kit/src/index.ts
- packages/python-wasm/src/index.ts
The `kit` function from the Build API already produces a kit that is backwards-compatible in terms of loading into the runtime/visual editor; but it can't yet be used within the old API. This would be helpful for incremental migration.
This PR is an initial step in that direction.
> [build] Incremental work towards better backwards compatibility for kits

- packages/board-server/package.json
Part of #2896
This value was set incorrectly in #2908. It needs to refer to the visual editor
origin, not the board server itself.
> [board-server] Use correct allowed origin in board server config

- .changeset/strange-cheetahs-admire.md
- packages/build/src/internal/kit.ts
- packages/build/src/test/kit_test.ts
This PR adds a `legacy()` function to the result of calling `kit()` in the Build API. It's a function that asynchronously returns a kit that is automatically built with and typed for the old API, allowing new API kits to be used directly in old boards.
Example of how it will be used:
```ts
import { board } from "@google-labs/breadboard";
import geminiKit from "@google-labs/gemini-kit";
const { geminiText } = await geminiKit.legacy();
export default await board(() => {
const result = geminiText({ prompt: "foo" });
return {
result: result.text,
};
});
```
> [build] Allow new kits to be used in old boards

- .changeset/nine-zoos-suffer.md
- packages/board-server/src/server/proxy/index.ts
- packages/board-server/src/server/proxy/secrets.ts
- packages/breadboard/src/harness/run.ts
- packages/breadboard/src/harness/secrets.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/loader/types.ts
- packages/breadboard/src/remote/proxy.ts
- packages/breadboard/src/remote/tunnel.ts
- packages/visual-editor/src/data/node-proxy-servers.ts
- packages/visual-editor/src/data/settings-store.ts
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/providers/remote.ts
- **Start reading secrets origin annotations.**
- **Require board API key for node proxy server.**
- **Build secrets tunnel from the list of secrets.**
- **Make sure to inflate inputs before sending to node proxy.**
- **Introduce `GraphProvider.canProxy` and start using it.**
- **Add a console message.**
- **Handle errors in secrets.**
- **Implement "fallback" mode for interactive secrets.**
- **Add a setting to ignore board server.**
- **docs(changeset): Teach Visual Editor to use board server's node proxy to run boards.**
> proxy origin tunnel

- archive/breadboard-extension/package.json
- archive/breadboard-server/package.json
- archive/create-breadboard-kit/package.json
- archive/create-breadboard/package.json
- archive/graph-integrity/package.json
- archive/graph-playground/package.json
- archive/node-nursery/package.json
- archive/pinecone-kit/package.json
- packages/agent-kit/package.json
- packages/breadboard-cli/package.json
- packages/breadboard/package.json
- packages/build-legacy/package.json
- packages/build/package.json
- packages/connection-server/package.json
- packages/core-kit/package.json
- packages/data-store/package.json
- packages/discovery-types/package.json
- packages/example-boards/package.json
- packages/gemini-kit/package.json
- packages/google-drive-kit/package.json
- packages/import/package.json
- packages/json-kit/package.json
- packages/node-nursery-web/package.json
- packages/node-proxy-server/package.json
- packages/palm-kit/package.json
- packages/python-wasm/package.json
- packages/template-kit/package.json
There was some bad lint caching behavior happening, because each package's lint command was only checking whether its own package files changed. We need to actually build the typescript of all dependencies first, or else when the linter reads the types of those deps, they might be out of sync. Depending on `tsc:build` is the easier way to do that.
> [all] [dev] Make linting depend on tsc

- .changeset/twelve-impalas-change.md
- packages/build/package.json
- packages/build/src/internal/board/board.ts
- packages/build/src/test/board_test.ts
The `describe()` function for boards created with the Build API didn't do a great job at expressing polymorphism (it just sort of naively flattened out all the properties). Now it does something a bit smarter.
> [build] Improve describe() behavior of polymorphic boards

- packages/board-server/Dockerfile
- packages/board-server/scripts/build.ts
Fixes #2945
```
$ docker run -d -p 3000:3000 --name board-server board-server
d6aa812d042f2fc98a67bedb124d80153d1429fda30e54f54fff3fc989a7c208
$ docker exec -it board-server /bin/bash
root@d6aa812d042f:/app# node dist/scripts/create-account.js wfaithfull
Created account for wfaithfull with API key:
bb-6e52o2r546q6cmu424m544d2p2195t3b444a4m6s2y5q2n2r61
```
> [board-server] improve board server dockerfile (#2945)

- .changeset/empty-guests-serve.md
- packages/build/src/index.ts
- packages/build/src/internal/board/board.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/internal/board/star-inputs.ts
- packages/build/src/internal/define/definition.ts
- packages/build/src/test/star-inputs_test.ts
- packages/website/src/docs/build/build.md
This is not currently supported in all positions, but does let you grab the `*` port of a board and wire that into a discrete component.
> [build] Add starInputs function to get a handle on the "*" input port of a board

- .github/workflows/docker.yml
Fixes #2948
- Builds containers for sqlite and firestore flavoured versions of the board server
- Tags with sha, short hash, board server semver and latest
- Publishes to: (may want to modify these to some existing google org repo?)
- ghcr.io/breadboard-ai/board-server-sqlite
- ghcr.io/breadboard-ai/board-server-firestore
- Generates attestations for the containers and also publishes these to ghcr
> [board-server] Adds github actions workflow for board server docker builds

- .changeset/plenty-lobsters-shop.md
- packages/shared-ui/src/elements/google-drive/google-drive-file-id.ts
- packages/shared-ui/src/elements/input/delegating-input.ts
A recent refactoring I did (adding `delegated-input`) broke some event handling around the Google Drive input widgets. This fixes it!
> [shared-ui] [drive] Fix bug related to event handling with Google Drive input widget

- .changeset/curly-garlics-train.md
- packages/build/src/internal/board/serialize.ts
- packages/build/src/test/star-inputs_test.ts
- packages/core-kit/tests/code_test.ts
If the input port is also "*", then the runtime seems to just stop. Only "" works. However, if you paste some BGL with "" into the Visual Editor it errors, and the docs say that star ports "can only be wired to other star ports". Seems a bit odd, but I'll go with the one that works in the runtime, which is empty string.
> [build] Set input port to empty string when wiring star ports

- .changeset/popular-sloths-hug.md
- packages/shared-ui/src/elements/input/schema-editor/schema-editor.ts
- packages/shared-ui/src/utils/mode.ts
- **Teach `filterConfigByMode` to be more loose with components unaware of `config` behavior.**
- **Add "Configured" checkbox to schema editor.**
- **Remove behavior property when empty.**
- **docs(changeset): Add support for "Configured" in property schema editor.**
> config unaware

- .changeset/grumpy-bananas-grin.md
- packages/breadboard/src/utils/throttler.ts
- packages/visual-editor/firebase.json
- **Teach throttler to not wait on new data if it already has cached result.**
- **docs(changeset): Teach Throttler to not wait on new data if it already has cached data.**
> throttler stale

- .changeset/chilly-gifts-push.md
- packages/board-server/src/app/elements/activity-log/activity-log-lite.ts
Noticed that the mobile view doesn't have enough scroll distance so the bottom of newest edge output is cropped. This PR fixes it.
> [board-server] Add a margin to the newest edge entry in the app view

- .changeset/shy-grapes-raise.md
- packages/shared-ui/src/elements/editor/graph-renderer.ts
- packages/shared-ui/src/elements/editor/graph.ts
I noticed that comments no drag as part of a group after a layout reset. It turns out we were removing all the layout information but only restoring the the non-comment nodes with dagre. Since the comments have no edges we can't use dagre, but we can just restore their existing layout info, which is what this PR does.
> [shared-ui] Fix layout reset bug

- packages/shared-ui/src/elements/editor/graph-edge.ts
Now that the nodes are a little wider this padding value needed a tweak
> [shared-ui] Tweak edge padding

- .changeset/rare-scissors-train.md
- packages/build/src/internal/type-system/any-of.ts
- packages/build/src/test/type-expressions/anyof_test.ts
Now, if you write `anyOf(foo, bar)`, and `foo` and `bar` both have the same `type` (e.g. `"type":"object"`), then that common `type` will get hoisted up. This is helpful for some code in Breadboard that assumes there is always a top-level `type`, even though JSON schema doesn't require that.
> [build] Hoist up common type for anyOf

- .changeset/thick-knives-sin.md
- packages/build/src/internal/board/board.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/internal/define/definition.ts
- packages/build/src/internal/define/instance.ts
- packages/build/src/internal/kit.ts
- packages/build/src/test/kit_test.ts
Components imported through kit objects are now serialized directly with `"type": "<name of node in kit>"` instead of via a generated invoke node.
> [build] Serialize nested components with their kit-name if they are instantiated via a kit

- .changeset/thick-knives-sin.md
- packages/build/src/internal/board/board.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/internal/define/definition.ts
- packages/build/src/internal/define/instance.ts
- packages/build/src/internal/kit.ts
- packages/build/src/test/kit_test.ts
Brings back https://github.com/breadboard-ai/breadboard/pull/3015 (reverted in https://github.com/breadboard-ai/breadboard/pull/3018) but with a fix for a bug.
The bug was that when building the kit, I was using the "id" property of the component object itself as the key, instead of the key that was used to initialize the component within the kit. Combined with a removed get proxy, this meant the key was either undefined, or potentially a different id from how the kit was initialized. Added tests and some safer typing around this.
> [build] Serialize nested components with their kit-name if they are instantiated via a kit (fixed version)

- .changeset/three-cheetahs-jog.md
- packages/breadboard/src/editor/operations/change-metadata.ts
- packages/breadboard/src/inspector/run/event-manager.ts
- packages/breadboard/src/inspector/run/nested-run.ts
- packages/breadboard/src/inspector/run/past-run.ts
- packages/breadboard/src/inspector/run/path-registry.ts
- packages/breadboard/src/inspector/run/run.ts
- packages/breadboard/src/inspector/run/serializer.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/src/types.ts
- packages/breadboard/tests/inspector/observer-load.ts
- packages/shared-ui/src/elements/activity-log/activity-log-lite.ts
- packages/shared-ui/src/elements/editor/editor.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/shared-ui/src/events/events.ts
- packages/shared-ui/src/types/types.ts
- packages/shared-ui/src/utils/top-graph-observer/comparable-edge.ts
- packages/shared-ui/src/utils/top-graph-observer/edge-entry.ts
- packages/shared-ui/src/utils/top-graph-observer/edge-value-store.ts
- packages/shared-ui/src/utils/top-graph-observer/index.ts
- packages/shared-ui/src/utils/top-graph-observer/node-entry.ts
- packages/shared-ui/src/utils/top-graph-observer/run-details.ts
- packages/shared-ui/src/utils/top-graph-observer/top-graph-observer.ts
- packages/shared-ui/src/utils/utils.ts
- packages/visual-editor/src/index.ts
- **Remove unused state.**
- **Split up files.**
- **Massage exports.**
- **Remove InspectableRun mentions from bb-ui-controler.**
- **Teach TGO about last run inputs.**
- **Add comment.**
- **Fix typos in comments.**
- **Plumb through runId.**
- **Factor out loading stored runs.**
- **Implement TGO.fromRun and start using it for run replay.**
- **Introduce `TopGraphRunResult.graph` and start using it.**
- **Add back ability to download run.**
- **Start saving edge data.**
- **Load edge values when replaying.**
- **Make error message a bit better.**
- **Propagate TGO change for loaded run results.**
- **Make runs loadable again.**
- **docs(changeset): Implement plumbing for visualizing runs as graphs.**
> tgo runs concert

- packages/website/src/docs/reference/run-api.md
Fixes #3062 
Just a fix for a small typo in the Run API doc where the `createRunner(...)` function needs to be passed the config object.
> Fixed typo in Run API doc

- .changeset/friendly-beds-sort.md
- packages/build/src/index.ts
- packages/build/src/internal/type-system/json-schema.ts
Adds a Breadboard Type Expression to represent JSON schema itself.
For now this is using our Schema type, and a generic object schema
with the json-schema behavior. In the future we can switch this to
the official JSON Schema types, and a {$ref} schema for the official
JSON Schema schema.
> [build] Add JSON Schema type

- .changeset/nervous-ads-raise.md
- packages/build/src/index.ts
- packages/build/src/internal/board/input.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/test/input_test.ts
Usually, inputs are created with the `input` and `inputNode` functions, which abstract Breadboard inputs to make them more powerful and ergonomic while using the Build API.
This `rawInput` function, in contrast, creates an input component that behaves like a totally normal component that happens to have the type "input".
This gives you full freedom to wire an input node up in arbitrary ways in a board, for example if you need the schema to be provided by the output of another component, rather than being statically defined.
Note that you will need to use `unsafeOutput` to access any output ports of this component.
> [build] Add rawInput function

- .changeset/lemon-numbers-fix.md
- packages/core-kit/src/index.ts
- packages/core-kit/src/nodes/code.ts
- packages/core-kit/tests/code_test.ts
The object you get back from `code` now includes a (properly typed) reference to the configured function that you can call with `codeComponent.test({...})`.
> [core-kit] Add `test` method to `code` result objects

- .changeset/olive-cycles-enjoy.md
- packages/shared-ui/src/utils/top-graph-observer/run-details.ts
- **When initalizing run details, recognize that previous runs might not exist.**
- **docs(changeset): Recognize that sometimes there are no prior runs when initializing RunDetails.**
> fix run details

- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/visual-editor/src/index.ts
Further tweaks:
1. Don't track runs in the recent boards list and don't update the board URL
2. Switch off the ability to run the board when the tab is read only
Improves #3153
> [shared-ui/visual-editor] Tweak readonly state

- .changeset/tricky-tools-reflect.md
- packages/shared-ui/src/elements/board-details/board-details.ts
- packages/shared-ui/src/elements/editor/editor.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/runtime/board.ts
- packages/visual-editor/src/runtime/types.ts
Includes a quick fix for switching off graph edit & board edit controls when in `readOnly` mode, too.
> [shared-ui/visual-editor] Teach runtime about tab types

- .changeset/bright-dolls-reflect.md
- packages/gemini-kit/src/boards/gemini-generator.ts
It only allowed string before, but parts are ok too.
> [gemini-kit] Expand the JSON schema type for gemini text instruction

- .changeset/healthy-suits-whisper.md
- packages/shared-ui/src/elements/editor/editor.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/visual-editor/src/providers/indexed-db.ts
Noticed that it was getting frustrating to switch off "follow run" whenever I booted up a new tab, so I've made it use local storage instead of session storage.
> [visual-editor] Switch follow to using Local Storage

- packages/board-server/Dockerfile
Copies the scripts folder into the docker build, so that (as per the ReadMe) you can run:
```
docker exec -it board-server /bin/bash
```
> [board-server] fix: copy `scripts` folder into docker build

- .changeset/happy-houses-shop.md
- packages/board-server/src/app/app.ts
- **Fix another bug found by dependabot.**
- **docs(changeset): Don't display title when the graph is title-less.**
> dependabot bug

- .changeset/sharp-carrots-drop.md
- packages/shared-ui/src/elements/editor/editor.ts
- packages/shared-ui/src/types/types.ts
- packages/shared-ui/src/utils/top-graph-observer/top-graph-observer.ts
- packages/visual-editor/package.json
- **Add TGO result `status` property which reflects the status of the run.**
- **docs(changeset): Provide accurate run status information via TopGraphObserver.**
> tgo result status

- packages/breadboard/src/loader/index.ts
- packages/breadboard/src/loader/loader.ts
Part of #3314 
This is a no-op change, since this is the only caller of the constructor for `Loader`
Add the DefaultGraphProvider in createLoader instead of the constructor for Loader. This allows us to add logic in `createLoader` which conditionally adds the default provider.
We're not copying `providers` in the constructor because `createLoader` is its only caller. It should be safe to store the original array without copying.
> [Breadboard] Move the provision of the default graph provider

- .changeset/fluffy-waves-exist.md
- packages/shared-ui/src/elements/activity-log/activity-log.styles.ts
- packages/shared-ui/src/elements/activity-log/activity-log.ts
Realized we offer the ability to describe nodes but we never use it anywhere. Well, now we do.
> [shared-ui] Show node description in Activity Log outputs

- .changeset/lucky-snails-repair.md
- package-lock.json
- packages/build-code/package.json
- packages/build-code/src/generate.ts
- packages/build-code/src/test/generate_test.ts
- packages/build-code/src/test/testdata/generated/regex.ts
- packages/build-code/src/test/testdata/generated/str-is-foo.ts
runJavascript doesn't support javascript modules, so we'll have to emit a legacy script for now. Doing this by asking esbuild for an iife. We also need to strip the iife wrapper from that output, because runJavascript also has some regexp logic (convertToNamedFunction) which I think mis-parses the iife wrapper and breaks the code.
Also adds a test that the generated boards are truly executable!
> [code-build] Emit a legacy script instead of module

- .changeset/flat-houses-cry.md
- packages/shared-ui/src/elements/editor/node-selector.ts
- **Pass `this.graph` to Task to avoid update death loop.**
- **docs(changeset): Fix the death loop with node selector in the new ribbon UI.**
> empty graph

- .changeset/rude-laws-swim.md
- packages/shared-ui/src/elements/input/user-input.ts
- **Provide a single empty LLMContent to `bb-llm-input-array` when no value is supplied.**
- **docs(changeset): Provide a single empty LLM Content to `bb-llm-input-array` when no default.**
> no default llm input array

- .changeset/curly-rabbits-end.md
- packages/breadboard/src/loader/index.ts
Change from `disableDefaultLoader` to `disableDefaultProvider` to match the vocabulary used in the codebase.
Fixes #3314
> [Breadboard] Change name of option to createLoader

- .changeset/cuddly-windows-glow.md
- packages/breadboard/src/harness/error.ts
- **Instead of checking for instance, check for shape when formatting errors.**
- **docs(changeset): Change for shape rather than instance when formatting errors.**
> format error better

- packages/shared-ui/src/elements/editor/graph-renderer.ts
- packages/shared-ui/src/elements/editor/graph.ts
Fixes #3477 but also:
1. You can use the middle mouse button to move the graph
2. You can now switch from selection to move mid-action and back again
3. `$error` outputs are excluded from node disambiguation overlays
> [shared-ui] Various fixes to graph rendering

- .changeset/rude-forks-speak.md
- packages/breadboard/src/kits/load.ts
- packages/breadboard/src/loader/default.ts
- packages/core-kit/src/nodes/run-javascript.ts
This allows Breadboard to be imported in webpack projects without causing module import errors in client-side code.
Fixes #3511
> Add webpackIgnore everywhere vite-ignore is used.

- .changeset/hip-guests-pretend.md
- packages/breadboard/src/inspector/run/run.ts
- **Be forgiving about group ids by the same name.**
- **docs(changeset): Fix the asBlob crash when replaying runs.**
> fix run blob crash

- .changeset/five-tools-vanish.md
- packages/shared-ui/src/elements/overlay/save-as.ts
- **Only show modifiable board servers in Save dialog.**
- **docs(changeset): Filter out board servers that can't be written into in Save overlay.**
> only modifiable in save

- .changeset/pink-bulldogs-refuse.md
- packages/visual-editor/src/data/settings-store.ts
- packages/visual-editor/src/index.ts
- **Move Google Drive Board Server from behind the flag.**
- **docs(changeset): Move Google Drive Board Server from behind the flag.**
> drive server no flag

- .changeset/strange-deers-raise.md
- package-lock.json
- packages/board-server/package.json
- packages/board-server/src/server/boards/utils/create-kits.ts
- packages/core-kit/src/index.ts
- packages/core-kit/src/sandboxed-run-module.ts
- packages/jsandbox/package.json
- packages/jsandbox/src/node-exports.ts
- packages/jsandbox/src/node.ts
- packages/jsandbox/src/web-exports.ts
- packages/visual-editor/src/runtime/board.ts
- packages/visual-editor/src/sandbox/index.ts
- **Export Node and Web sandboxes separately.**
- **Move `addSandboxedRunModule` to Core Kit.**
- **Teach board server about sandboxed runModule.**
- **docs(changeset): Teach Board Server about sandboxed runModule.**
> run module board server

- packages/connection-server/src/server.ts
Previously connection server was accepting all requests, but setting
Access-Control-Allowed-Methods to "GET". So it's clear that it's
intended only to be used with GET requests.
Arguably, however, `grant` and `refresh` requests should be POST
requests. They don't alter state on the connection server itself, but
they do cause outgoing POST requests, so it makes sense.
Also for `grant` requests specifically, the params include a refresh
token, which is a sensitive value that should not appear in the search
query of a URL. In the POST body it would be encrypted, and less
vulnerable to sniffing attacks.
Part of #3172
> [connection-server] Accept only GET requests

- .changeset/little-bees-dance.md
- packages/breadboard/src/traversal/iterator.ts
- packages/shared-ui/src/elements/module-editor/module-editor.ts
- **Allow `$error` to be a string.**
- **Start emitting js files so that we can read them back.**
- **docs(changeset): Feed compiled JS from TS compiler.**
> run module fixes

- .changeset/serious-eels-own.md
- package-lock.json
- package.json
- packages/breadboard-cli/package.json
- packages/breadboard/package.json
- packages/node-proxy-server/functions/package.json
- **Revert "build(deps): bump @rollup/rollup-linux-x64-gnu from 4.27.1 to 4.27.2 (#3800)"**
- **Revert "build(deps): bump rollup from 4.25.0 to 4.27.1 (#3793)"**
- **docs(changeset): Revert rollup bump 4.25.0 to 4.27.1, because it causes build to be super-slow.**
> revert rollup

- .changeset/silent-zoos-repeat.md
- packages/breadboard/src/editor/graph.ts
- packages/breadboard/src/editor/index.ts
- packages/breadboard/src/index.ts
- packages/breadboard/src/inspector/graph/edge.ts
- packages/breadboard/src/inspector/graph/mutable-graph.ts
- packages/breadboard/src/inspector/mutable-graph-store.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/tests/editor/graph.ts
- packages/breadboard/tests/editor/metadata.ts
- packages/breadboard/tests/helpers/_editor.ts
- packages/breadboard/tests/node/editor/test-graph.ts
- packages/jsandbox/src/capabilities.ts
- packages/jsandbox/src/node.ts
- packages/jsandbox/src/types.ts
- packages/jsandbox/src/web.ts
- packages/types/src/index.ts
- packages/types/src/uuid.ts
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/runtime/board.ts
- packages/visual-editor/src/runtime/edit.ts
- packages/visual-editor/src/runtime/runtime.ts
- packages/visual-editor/src/runtime/types.ts
- **Switch `Edge` to use `MutableGraph` instead of `NodeCache`.**
- **Move UUID type def to `types` package.**
- **Introduce `MutableGraphStore` and impl.**
- **Switch editable graph constructor to take `MutableGraph`.**
- **Introduce `GraphStore` (v2).**
- **Switch to use `GraphStore`.**
- **Deprecate `edit` API.**
- **docs(changeset): Introduce `GraphStore`: a top-level holder of all boards.**
> mutable graph holder

- package-lock.json
- packages/board-server/experimental/bbrt/index.html
- packages/board-server/vite.config.ts
- packages/visual-editor/.gitignore
- packages/visual-editor/app.test.yaml
- packages/visual-editor/app.yaml
- packages/visual-editor/experimental/bbrt/index.html
- packages/visual-editor/package.json
- packages/visual-editor/src/copy-bbrt-assets.ts
- packages/visual-editor/vite.config.ts
This is a pretty light integration for now, just serving at the same origin as the visual editor under `experimental/bbrt`, otherwise decoupled.
> [bbrt] Serve at <visual-editor>/experimental/bbrt/

- .changeset/lemon-cameras-look.md
- packages/shared-ui/src/elements/editor/editor.ts
Fixes #3899
Looks like the initial matrix calculation is off because of the render call order so it renders everything reallllllly small. This is a short-term fix for now because I'd like to get to the bottom of why this is happening.
> [shared-ui] Delay initial render

- .changeset/sour-clocks-begin.md
- packages/breadboard/src/inspector/graph-store.ts
- packages/breadboard/src/inspector/graph/describer-manager.ts
- packages/breadboard/src/inspector/graph/event.ts
- packages/breadboard/src/inspector/graph/graph.ts
- packages/breadboard/src/inspector/graph/mutable-graph.ts
- packages/breadboard/src/inspector/types.ts
- packages/shared-ui/src/elements/editor/editor.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/runtime/board.ts
- packages/visual-editor/src/runtime/events.ts
- packages/visual-editor/src/runtime/types.ts
- **Do not rebuild graph cache on every update.**
- **Fix a typo.**
- **Move Event dispatching to MutableGraphStore.**
- **Start using `update` event and `currentPorts` (yay) in `bb-editor`.**
- **Convert `bb-workspace-outline` to use `currentPorts`.**
- **docs(changeset): Start using `currentPorts` and `update` event in VE.**
> inspectable graph update event

- .changeset/dry-tables-study.md
- packages/breadboard/src/graph-based-node-handler.ts
- packages/breadboard/src/handler.ts
- packages/breadboard/src/inspector/graph-store.ts
- packages/breadboard/src/inspector/graph/describer-manager.ts
- packages/breadboard/src/inspector/graph/event.ts
- packages/breadboard/src/inspector/graph/kits.ts
- packages/breadboard/src/inspector/graph/virtual-node.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/tests/node/utils/snapshot-updater.ts
- packages/shared-ui/src/elements/editor/editor.ts
- packages/visual-editor/src/index.ts
- **Write more tests for SnapshotUpdater.**
- **Switch `GraphStore` to store Snapshotupdaters.**
- **Pass MutableGraphStore rather than MutableGraph to CustomNodeType.**
- **Split GraphBasedNodeHandler into separate class.**
- **Remove handler throttling and caching.**
- **Start dispatch update for node type metadata changes.**
- **Introduce and start using `currentMetadata`.**
- **docs(changeset): Make retrieving type metadata sync.**
> snapshot node type metadata

- packages/bbrt/src/components/driver-selector.ts
- packages/bbrt/src/components/main.ts
- packages/bbrt/src/drivers/driver-interface.ts
- packages/bbrt/src/drivers/gemini.ts
- packages/bbrt/src/drivers/openai.ts
- packages/bbrt/src/llm/conversation.ts
- packages/bbrt/src/tools/list-tools.ts
Introduces a `Driver` interface: an object that executes a turn (i.e. it provides the connection to the language model). For now, this just needs a name, an icon, and the ability to execute a turn. It is easier now to see how a Breadboard itself could be a Driver.
> [bbrt] Formalize Driver as the interface that drives the main conversation

- .changeset/chilled-baboons-sleep.md
- packages/breadboard/src/inspector/run/describe-cache.ts
- packages/visual-editor/src/index.ts
- **Elevate `graphTopologyUpdateId` to component state.**
- **Make sure that the snapshots created by runtime are inert (don't update topology)**
- **docs(changeset): Fix the update-loop-of-death**
> fix snapshot bugs

- packages/shared-ui/src/elements/editor/graph-renderer.ts
> [shared-ui] Avoid updating graph-renderer when the port tooltip changes

- .changeset/twelve-hounds-smile.md
- packages/shared-ui/src/elements/editor/graph-port-label.ts
- **Calculate dimensions when assigning ports on GraphPortLabel.**
- **docs(changeset): Calculate dimensions when assigning port in `GraphPortLabel`.**
> graph port label calc

- package-lock.json
- packages/bbrt/package.json
- packages/bbrt/src/breadboard/breadboard-tool.ts
- packages/bbrt/src/breadboard/make-tool-safe-name.ts
- packages/bbrt/src/breadboard/standardize-breadboard-schema.ts
- packages/bbrt/src/components/tool-call.ts
- packages/bbrt/src/drivers/adjust-schema-for-gemini.ts
- packages/bbrt/src/drivers/gemini-types.ts
- packages/bbrt/src/drivers/gemini.ts
- packages/bbrt/src/drivers/openai-types.ts
- packages/bbrt/src/drivers/openai.ts
- packages/bbrt/src/test/node/adjust-schema-for-gemini_test.ts
- packages/bbrt/src/test/node/standardize-breadboard-schema_test.ts
- packages/bbrt/src/tools/list-tools.ts
Now handles a wider range of schema, including the llm-content behavior, which gets expanded into full JSON schema.
Also adds more kits to the default set, and ensures that gemini function call IDs are <64 chars instead of <=64 chars.
> [bbrt] Much better schema handling

- .changeset/tall-adults-drop.md
- packages/shared-ui/src/elements/editor/editor.ts
- packages/shared-ui/src/elements/editor/graph-renderer.ts
- packages/shared-ui/src/elements/editor/graph.ts
- packages/shared-ui/src/elements/module-editor/module-editor.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts
- packages/visual-editor/src/index.ts
Given the bugs it's generating I'm feeling like we should remove the 'list' mode from the workspace outline and find better ways to keep top level graphs clean and clear.
To that end this PR removes the mode and also fixes the drag-to-subgraph bug.
Fixes: #3934
Fixes: #3905
> [shared-ui] Remove list mode

- packages/bbrt/src/app-state.ts
- packages/bbrt/src/breadboard/breadboard-tool-provider.ts
- packages/bbrt/src/components/chat-message.ts
- packages/bbrt/src/components/main.ts
- packages/bbrt/src/components/tool-call.ts
- packages/bbrt/src/components/tool-palette.ts
- packages/bbrt/src/drivers/driver-interface.ts
- packages/bbrt/src/drivers/gemini.ts
- packages/bbrt/src/drivers/openai.ts
- packages/bbrt/src/llm/conversation-restore.ts
- packages/bbrt/src/llm/conversation-serialization-types.ts
- packages/bbrt/src/llm/conversation-serialization.ts
- packages/bbrt/src/llm/conversation-types.ts
- packages/bbrt/src/llm/conversation.ts
- packages/bbrt/src/tools/activate-tool.ts
- packages/bbrt/src/tools/tool-provider.ts
- packages/bbrt/src/util/buffered-multiplex-stream.ts
This will need a big cleanup, and requires too much manual fiddling with serialization, but now the conversation is persisted across reloads in session storage (which is particularly useful during development, but will be useful in other ways later too).
> [bbrt] Persist conversation turns to session storage

- packages/bbrt/src/breadboard/breadboard-tool.ts
- packages/bbrt/src/components/error-message.ts
- packages/bbrt/src/llm/conversation-serialization-types.ts
- packages/bbrt/src/llm/conversation-serialization.ts
- packages/bbrt/src/llm/conversation-types.ts
- packages/bbrt/src/llm/conversation.ts
- packages/bbrt/src/tools/activate-tool.ts
- packages/bbrt/src/tools/list-tools.ts
- packages/bbrt/src/tools/tool.ts
- packages/bbrt/src/util/presentable-error.ts
Moves the logic that coerces a nice error out of the error-message component, because that's also good for serialization, so we should do the coercion earlier.
> [bbrt] Better error handling

- .changeset/rotten-lamps-jam.md
- packages/breadboard/src/inspector/graph/graph.ts
- packages/breadboard/src/inspector/run/conversions.ts
- packages/breadboard/src/inspector/run/serializer.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/src/sandboxed-run-module.ts
- packages/jsandbox/src/capabilities.ts
- packages/jsandbox/src/telemetry.ts
- packages/jsandbox/src/types.ts
- **Introduce `InspectableGraph.mainGraphDescriptor` and use it in inspect run API.**
- **Teach runModule machinery to correctly record telemetry.**
- **docs(changeset): Fix the replay and runModule telemetry bugs.**
> more fixes

- .changeset/wet-schools-thank.md
- packages/shared-ui/src/elements/editor/graph-renderer.ts
- **Copy the children array when removing graph renderer children.**
- **docs(changeset): Fix a bug with phantom subgraphs.**
> copy children

- packages/website/src/docs/guides/breadboard-from-scratch.md
The caller needs to request application-default credentials in order for
the operation to succeed.
Part of #2675
> [website] Add instructions for adding users to board server

- .changeset/famous-cats-turn.md
- packages/breadboard/src/inspector/graph-store.ts
- packages/breadboard/src/inspector/graph/kits.ts
- packages/breadboard/src/inspector/graph/mutable-graph.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/tests/node/inspect/graph-store.ts
- packages/breadboard/tests/node/test-kit.ts
- packages/manifest/bbm.schema.json
- packages/schema/breadboard.schema.json
- packages/shared-ui/src/elements/component-selector/component-selector.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/types/src/graph-descriptor.ts
- packages/visual-editor/src/runtime/board.ts
- packages/visual-editor/src/runtime/runtime.ts
- **First sketch of `GraphStore.graphs()`.**
- **Introduce `GraphStore.registerKit`.**
- **Move registering kits with GraphStore to runtime.**
- **Nicely dedupe the handlers.**
- **Move `deprecated` to a tag.**
- **Start using `GraphStore.graphs()`.**
- **Plumb `showExperimentalComponents` to `bb-component-selector`.**
- **docs(changeset): Introduce `GraphStore.graphs()`.**
- **Fix unit tests.**
> graph store graphs

- .changeset/eleven-berries-rhyme.md
- packages/shared-ui/src/elements/editor/graph-node-reference.ts
- packages/shared-ui/src/elements/editor/graph-node.ts
- packages/shared-ui/src/elements/editor/graph-renderer.ts
- packages/shared-ui/src/elements/editor/graph.ts
- packages/shared-ui/src/elements/editor/types.ts
- packages/shared-ui/src/utils/behaviors.ts
Fixes #3720
As of this change:
1. We only show configurable ports when:
a. the port represents a board/board array
b. the node is set to 'advanced'
c. there are edges attached to the port
2. We also prevent users from dragging to a configurable port unless the node is in 'advanced' mode
> [shared-ui] Prevent accidental wiring of configurable ports outside of "advanced" mode

- .changeset/cool-squids-happen.md
- packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts
- **Guard for undefined port value in workspace outline previews.**
- **docs(changeset): Guard for empty port values in workspace outline preview.**
> guard port value

- packages/shared-ui/src/elements/editor/graph-renderer.ts
Stops the graphs appearing to "jump". They still do but they're nearly invisible while that's happening.
> [shared-ui] Set graph alpha during set up

- .changeset/cuddly-toys-change.md
- packages/visual-editor/src/runtime/edit.ts
- **When creating a reference, convert it to an `UnresolvedPathBoardCapability`**
- **docs(changeset): Teach visual editor to create runtime-resolvable references.**
> reference unresolved capability

- .changeset/metal-bikes-push.md
- packages/breadboard/src/inspector/graph/describer-manager.ts
- **Undo the change in describer manager -- breaks Agent Kit.**
- **docs(changeset): Undo the change to use GraphStore for custom graph describers, as it breaks Agent Kit.**
> fixes upon fixes

- packages/website/src/docs/guides/breadboard-from-scratch.md
Part of #2675
* Link to `/billing/enable` explicitly, since the page at `/appengine`
no longer redirects to it if a billing account doesn't exist
* Create the App Engine project _before_ configuring the service
account, since the service account doesn't exist until the project is
created.
* Update the service account using the `gcloud` CLI instead of the Cloud
Console.
* Update the troubleshooting link, since the old one no longer mentions
the service account issue
> [website] Update App Engine setup instructions in breadboard-from-scratch

- .changeset/wild-plums-destroy.md
- package-lock.json
- packages/breadboard-cli/package.json
- packages/breadboard/src/editor/graph.ts
- packages/breadboard/src/editor/operations/toggle-export.ts
- packages/breadboard/src/editor/types.ts
- packages/breadboard/src/graph-based-node-handler.ts
- packages/breadboard/src/handler.ts
- packages/breadboard/src/inspector/graph-store.ts
- packages/breadboard/src/inspector/graph/graph-queries.ts
- packages/breadboard/src/inspector/graph/graph.ts
- packages/breadboard/src/inspector/graph/kits.ts
- packages/breadboard/src/inspector/types.ts
- packages/shared-ui/src/elements/overflow-menu/overflow-menu.ts
- packages/shared-ui/src/elements/overlay/board-details.ts
- packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts
- packages/shared-ui/src/events/events.ts
- packages/visual-editor/package.json
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/runtime/edit.ts
- **Make it possible to add/remove exports in BGL (and add a typical for me gross UI).**
- **Hacky support for exports in `GraphStore.graphs`.**
- **Add support for editing module metadata.**
- **Teach inspector to get metadata for sub-graphs and modules.**
- **Display both title and id for modules in project view.**
- **docs(changeset): Teach Breadboard to recognize and edit BGL exports.**
> bgl exports

- package-lock.json
- packages/bbrt/package.json
- packages/bbrt/src/breadboard/breadboard-component-tool.ts
- packages/bbrt/src/breadboard/breadboard-tool.ts
- packages/bbrt/src/breadboard/make-tool-safe-name.ts
- packages/bbrt/src/components/main.ts
Regular breadboard components (e.g. GeminiKit, GoogleDriveKit) can now be executed directly by the main conversation. (Boards from the board server could already be executed).
> [bbrt] Support running breadboard components directly

- packages/unified-server/Dockerfile
This value has to be set to "production" to prevent ViteExpress from
trying to use the Vite dev server to serve client-side artifacts.
Part of #3913
> [unified-server] Update NODE_ENV on Dockerfile

- .changeset/moody-olives-learn.md
- packages/board-server/experimental/editor.html
- packages/shared-ui/package.json
- packages/shared-ui/src/data/settings-store.ts
- packages/visual-editor/index.html
- packages/visual-editor/src/data/node-proxy-servers.ts
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/utils/secrets-helper.ts
- packages/visual-editor/src/utils/settings-helper.ts
It's a very useful class (I needed it for bbrt) and there's already some settings related stuff in shared-ui, so it seems to fit.
> [visual-editor, shared-ui] Move SettingsStore into shared-ui

- packages/bbrt/src/llm/conversation.ts
The model is now free to automatically send follow up tool calls after the first one completed (currently up to 5).
> [bbrt] Model can issue followup tool calls

- packages/bbrt/src/components/chat-message.ts
- packages/bbrt/src/components/prompt.ts
- packages/bbrt/src/tools/files/read-file.ts
- Capture errors from read-file correctly
- Fix missing margin between tool calls within a turn
- Show a subtle indicator of where hidden messages are
- Recompute prompt height when edit button is clicked
> [bbrt] Misc small fixes

- packages/bbrt/src/components/main.ts
- packages/bbrt/src/drivers/openai.ts
- packages/bbrt/src/instructions/bgl.ts
- packages/bbrt/src/instructions/system-instruction.ts
Some documentation about BGL is now virtually mounted to /docs/bgl/ so the model can call `read_file` to access files there. The system prompt tells the model when to do this. This allows the model to create plausible looking BGL files.
> [bbrt] Allow model to read BGL docs on-demand

- .changeset/twenty-years-leave.md
- packages/connection-server/src/index.ts
- packages/connection-server/src/server.ts
Change the startServer function to createServer, and then start it from
the main startup routine.
This allows the app creation to be accessed by external callers, who can
then embed it in other contexts (like the unified server)
Part of #3913
> [connection-server] Factor server creation into a function 

- package-lock.json
- packages/board-server/package.json
- packages/board-server/scripts/build.ts
- packages/unified-server/package.json
- packages/unified-server/src/server/main.ts
This reverts commit 9600786936f96091ecfac60668c69a2aa1151d75.
Broke tests because unified server wouldn't start up
Part of #3913
> Revert "[unified-server] Add board server to unified server (#4145)"

- .changeset/clever-spoons-draw.md
- package-lock.json
- packages/shared-ui/package.json
- packages/shared-ui/src/elements/google-drive/append-to-doc-using-drive-kit.ts
- packages/shared-ui/src/elements/llm-output/llm-output.ts
Adds a "Save to Drive" button to content displayed in the App view. Clicking it invokes the "Append to Doc" board from GoogleDriveKit, and pops up a link in a toast.
Does not support images yet.
> [shared-ui/llm-output] Add "Save to Drive" button to App view content

- .changeset/chatty-scissors-try.md
- packages/a2/bgl/text-workbench.bgl.json
- packages/breadboard/src/inspector/graph-store.ts
- packages/breadboard/src/inspector/types.ts
- packages/shared-ui/src/elements/chat/chat.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/shared-ui/src/index.ts
- packages/shared-ui/src/state/chat-controller.ts
- packages/shared-ui/src/state/index.ts
- packages/shared-ui/src/state/types.ts
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/runtime/board.ts
- packages/visual-editor/src/runtime/events.ts
- packages/visual-editor/src/runtime/run.ts
- **Sketch out `ChatController`.**
- **Plumb the icon infomation to `ChatController`.**
- **Plumb the `updating` flag.**
- **Simplify chat state data structure.**
- **Make `ChatController` update icons and titles when the underlying graph entries are updated.**
- **docs(changeset): Introduce ChatController, an abstraction to manage chat state.**
> chat controller

- .changeset/smooth-starfishes-scream.md
- packages/a2/bgl/chat-with-user-workbench.bgl.json
- packages/breadboard/src/inspector/graph-store.ts
- packages/breadboard/src/inspector/graph/describer-manager.ts
- packages/breadboard/src/inspector/run/describe-cache.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/src/utils/snapshot-updater.ts
- packages/shared-ui/src/state/chat-controller.ts
- **Properly propagate the state of the run in ChatController.**
- **Dispatch `GraphStore` "update" event after the snapshot values updated to latest.**
- **docs(changeset): Bug fixes in ChatController.**
> chat controller fixes

- packages/unified-server/vite.config.ts
This prevents the problem where the client-side build clobbers the server-side build
Part of #3913
> [unified-server] Change outDir for client-side code

- package-lock.json
- package.json
- packages/bbrt/package.json
- packages/board-server/package.json
- packages/build-code/package.json
- packages/build/package.json
- packages/connection-client/package.json
- packages/connection-server/package.json
- packages/google-drive-kit/package.json
- packages/jsandbox/package.json
- packages/python-wasm/package.json
- packages/types/package.json
- packages/unified-server/package.json
- packages/website/package.json
Brings in https://github.com/google/wireit/pull/1270 which does a better job at reporting errors relating to input/output files being unexpectedly deleted as wireit is executing.
> Update wireit version for better error reporting

- package.json
- packages/unified-server/package.json
This works around the error seen in #4249 by removing the tests from the CI run.
This is acceptable for now because the current unified server tests are just dummies that "assert true" to verify that they are run. We should add these tests back to the global run when #4249 is fixed.
> [unified-server] Remove tests from global test run

- packages/example-boards/package.json
- packages/google-drive-kit/package.json
Doesn't directly address https://github.com/breadboard-ai/breadboard/issues/4249, but should fix the failure from https://github.com/breadboard-ai/breadboard/actions/runs/13021227644/job/36322130934
```
src/example-board-server.ts:25:30 - error TS2307: Cannot find module '@breadboard-ai/example-boards/playground-boards.json' or its corresponding type declarations.
25 import playgroundBoards from "@breadboard-ai/example-boards/playground-boards.json" assert { type: "json" };
```
cc @timswanson-google
> Add a couple of missing wireit dependency graph edges

- package.json
- packages/board-server/.gitignore
- packages/board-server/package.json
- packages/board-server/tsconfig.test.json
Should fix https://github.com/breadboard-ai/breadboard/issues/4249
The `build:tests` and `build:esbuild` scripts in the `board-server` package were both writing to the same place (`dist/`), with each deleting the output of the other (in the case of `build:tests`, deleting the whole `dist/` folder).
https://github.com/google/wireit/issues/65 is a long-standing feature request for wireit that would let us detect cases like this automatically
> [board-server] [unified-server] Fix output clobbering bug

- packages/board-server/src/app/app.ts
- packages/visual-editor/src/index.ts
Follow up to https://github.com/breadboard-ai/breadboard/pull/4230 which subtly broke some places we were using the Lit context `@provide` decorator. There is currently a bug (in Lit context, probably?) that means values have to be initialized in the constructor, not in the property declaration. See https://github.com/lit/lit/issues/4675.
> [visual-editor] [board-server] Move `@provide` initial values to constructor due to accessor/lit bug

- .changeset/silly-bulldogs-flash.md
- packages/shared-ui/src/elements/editor/graph-node.ts
Since nodes are now 260px we have to mask any long-running ports in the collapsed port list. That said, we now also have the `main-port` behavior hint, which means we likely don't need to include all of the ports in the list, which will help.
> [shared-ui] Mask collapsed port list

- .changeset/odd-panthers-yawn.md
- packages/shared-ui/src/elements/editor/graph-node.ts
- packages/shared-ui/src/elements/editor/graph-port-label.ts
- packages/shared-ui/src/strings/en_US/editor.ts
This PR sets components to be gr(e|a)y when the `updating` flag is `true` and it hides their ports. It's probably something we want to revisit, but for now it does delineate the component from its loaded state pretty well.
Also fixes a bug where the icon doesn't show up in the port label.
> [shared-ui] Show updating status on components

- .changeset/silent-pugs-brush.md
- packages/board-server/package.json
- packages/board-server/tsconfig.lib.json
- **Add tsc build to board-server.**
- **docs(changeset): Add tsc build to the board server, so that its dependents (like `unified-server`) get the type information.**
> board server tsc build

- .changeset/warm-crabs-look.md
- package-lock.json
- packages/connection-client/src/token-vendor.ts
- packages/connection-client/src/types.ts
- packages/connection-server/package.json
- packages/connection-server/src/api/grant.ts
- packages/shared-ui/src/elements/connection/connection-common.ts
- packages/shared-ui/src/elements/connection/connection-signin.ts
- packages/visual-editor/src/runtime/auth.ts
- packages/visual-editor/src/runtime/runtime.ts
- **Plumb the profile data from connection server to client.**
- **Introduce `runtime.signin` to manage sign in.**
- **docs(changeset): Introduce sign in plumbing to Visuale Editor runtime.**
> sign in plumbing

- packages/unified-server/package.json
`docker-build` does not need `build` because the build is run when the image is built.
Forcing `docker-run` to depend on `docker-build` can take time when the caller might not want to build a new image. The user should just run `docker-build` and `docker-run` in sequence if they want to build a new image. As written, `docker-run` will just take whatever image is tagged with `unified-server:latest`.
Part of #4355
> [unified-server] Remove unneeded dependencies

- packages/unified-server/package.json
It's not necessary and adds an extra dependency. Not using wireit allows these commands to succeed in a clean repo without running npm install.
Part of #4355
> [unified-server] Don't use wireit for Docker commands

- packages/unified-server/package.json
This can be useful when a container is failing on startup. Removing it on shutdown erases the logs. Note that you'll need to remove it manually before docker-run can be run again.
Fixes #4355
> [unified-server] Add docker-run script that doesn't remove the container

- packages/shared-ui/src/elements/ui-controller/ui-controller.styles.ts
> Fix style such that share link does not overflow out of nav container

- packages/unified-server/tsconfig.json
The current tsconfig for unified server was mostly cargo-culted from other tsconfigs in the repo. In preparation for writing the bundling logic in #4442, I thought I'd take a look and see which options were necessary, and which seemed redundant.
In some cases, options seemed redundant. In some cases, they were set to their default values anyway.
Have confirmed that everything build and runs successfully with these changes.
> [unified-server] Clean up tsconfig

- .changeset/tough-frogs-do.md
- packages/breadboard/src/data/common.ts
- packages/breadboard/src/data/default-run-store.ts
- packages/breadboard/src/data/index.ts
- packages/breadboard/src/index.ts
- packages/breadboard/src/sandboxed-run-module.ts
- packages/shared-ui/src/elements/board-activity/board-activity.ts
- packages/shared-ui/src/elements/editor/graph-node-output.ts
- packages/shared-ui/src/elements/editor/graph-renderer.ts
- packages/shared-ui/src/elements/output/llm-output/llm-output-array.ts
- packages/shared-ui/src/elements/overlay/board-activity.ts
- packages/shared-ui/src/elements/overlay/node-configurator.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- **Teach DefaultRunStore to resolve stored data URLs relative to Graph URL.**
- **Teach LLM Outputs about relative blob URLs.**
- **Teach `graph-node-output` to preview blob assets.**
- **Provide proper URL when inflating data prior to running modules.**
- **docs(changeset): Additional plumbing to make assets work in all places.**
> assets and at

- .changeset/twelve-towns-study.md
- packages/board-server/src/router.ts
- packages/board-server/src/server.ts
- packages/board-server/src/server/errors.ts
- packages/board-server/src/server/home/index.ts
- packages/board-server/src/server/info/index.ts
- packages/board-server/src/server/info/me.ts
- packages/board-server/src/server/proxy/index.ts
Moves the handlers for root, /me, /proxy, and /info to express.
Get rid of the path and method matching logic in those handlers. That's not handled by the Express middleware.
Part of #3172
> [board-server] Use Express for routing

- packages/unified-server/package.json
- packages/unified-server/tsconfig.client.json
- packages/unified-server/tsconfig.server.json
Previously, the dev-mode unified-server would restart whenever any client-side code changed. Now, only changes to the implementation of the unified-server itself trigger a restart, not client-side changes. So client-side changes should get picked up more quickly with less page reloading.
The actual change here is to switch the server-to-static-assets dependencies from being regular wireit dependencies (which will cause a server to restart on any change), to non-cascading dependencies (which will keep that dependency fresh, but not restart on changes -- see also https://github.com/google/wireit?tab=readme-ov-file#execution-cascade).
And in order to do that, we also needed to split apart the client from server code a bit in the build graph, including 2 separate tsconfigs.
> [unified-server] Tease apart dependencies for faster reload loop

- .changeset/neat-boxes-read.md
- packages/board-server/src/server/boards/assets-drive.ts
- packages/board-server/src/server/boards/create.ts
- packages/board-server/src/server/boards/delete.ts
- packages/board-server/src/server/boards/describe.ts
- packages/board-server/src/server/boards/get.ts
- packages/board-server/src/server/boards/index.ts
- packages/board-server/src/server/boards/invite-list.ts
- packages/board-server/src/server/boards/invite-update.ts
- packages/board-server/src/server/boards/invoke.ts
- packages/board-server/src/server/boards/post.ts
- packages/board-server/src/server/boards/run.ts
Store the board info, extracted from the path, on the Response.locals object so that it doesn't need to be passed down to handler functions.
The goal is to eliminate as much logic as possible from boards/index, so that it's really just a router. This doesn't do the whole job, but is a step forward.
> [board-server] Use res.locals to store board info

- packages/unified-server/vite.config.ts
Previously when opening or editing a file in shared-ui/src/bgl through the visual editor, vite would notice a change and reload the browser. Now it doesn't, by way of vite watch ignore patterns.
> [unified-server] Tell vite to ignore shared-ui BGL changes

- .changeset/polite-kings-sip.md
- packages/board-server/src/server.ts
- packages/board-server/src/server/blobs/create.ts
- packages/board-server/src/server/boards/create.ts
- packages/board-server/src/server/boards/invite-update.ts
- packages/board-server/src/server/boards/invoke.ts
- packages/board-server/src/server/boards/post.ts
- packages/board-server/src/server/boards/run.ts
- packages/board-server/src/server/common.ts
- packages/board-server/src/server/proxy/index.ts
This is a partial re-revert of #4688 (reverted in #4699)
The original PR caused proxy requests to 400 because the middleware was not setting the `Request.body` attribute.
This is because the request to the proxy endpoint has `Content-Type: text/plain;charset=UTF-8`, so the Express middleware is not recognizing it as a JSON request.
This PR works around the issue by not using the middleware for that request. But the request body is JSON, so if we set the request header correctly, we could use the standard middleware for this endpoint.
> [board-server] Use express.json

- .changeset/common-sides-dress.md
- packages/shared-ui/src/sideboards/autoname.ts
- **Allow new affectedNodes to accumulate while task is running.**
- **docs(changeset): Fix the racing condition in autonaming machinery**
> autonaming racing

- packages/shared-ui/src/elements/output/llm-output/llm-output.ts
llm-output - rendering text/html in an iframe.
This currently doesn't differenciate between an html piece and an html page.
Depending how trustworthy the source is, the former may be rendered inside the widget.
- [ X ] Tests pass
> llm-output - rendering text/html in an iframe.

- packages/unified-server/.gitignore
The paths as written exclude matching files anywhere in the tree. We're explicitly trying to exclude files at the root level.
> [unified-server] Update .gitignore to use explicit root paths

- packages/board-server/src/server/storage-providers/firestore.ts
- packages/board-server/src/server/storage-providers/sqlite.ts
- packages/board-server/src/server/store.ts
- packages/board-server/src/server/types.ts
Gets rid of the generic BoardServerStore interface and replaces it explicitly with the Firestore version. This allows us to change the Firestore version without breaking the build or updating the SQLite version.
This is hopefully a temporary change. Have filed #4781 to get this hooked back up. But the whole storage layer will have changed in the meantime, so there will likely be some manual work to do to get it working again.
> [board-server] Unlink SQLite storage provider

- packages/unified-server/package.json
We were running visual editor's vite build step before the unified server one, even though its output was not used. Shaves about 9 seconds off the build:
```
Before: 🏁 [metrics] Executed 43 script(s) in 63.32 seconds
After:  🏁 [metrics] Executed 42 script(s) in 54.61 seconds
```
> [unified-server] Remove redundant visual-editor vite build step

- packages/breadboard/src/utils/template.ts
- packages/shared-ui/src/elements/fast-access-menu/fast-access-menu.ts
- packages/shared-ui/src/elements/input/text-editor/text-editor.ts
- packages/shared-ui/src/events/events.ts
Wiring asset's mimeType to TemplatePart #4605
> Asset mime types

- packages/shared-ui/src/styles/icons.ts
- Add `user-select: none` so that the text name of the symbol doesn't get selected
- Add `font-display: optional` so that while the icon font is still loading, it renders nothing instead of the name of the symbol in a fallback font
- Simplify the CSS by combining the two blocks that are almost identical
> [styles] Tweak styles for icon classes

- packages/board-server/src/server/boards/delete.ts
- packages/board-server/src/server/boards/invite-list.ts
- packages/board-server/src/server/boards/invite-update.ts
- packages/board-server/src/server/boards/invoke.ts
- packages/board-server/src/server/boards/loader.ts
- packages/board-server/src/server/boards/post.ts
- packages/board-server/src/server/boards/run.ts
- packages/board-server/src/server/storage-providers/firestore.ts
- packages/board-server/src/server/storage-providers/sqlite.ts
- packages/board-server/src/server/store.ts
- packages/board-server/src/server/types.ts
- packages/board-server/tests/integration/board-server.test.ts
Simplify the board storage logic and push logic out of the storage implementation layer and into the request haandlers. This should help reduce duplicated code between storage implementations.
In particular, security checks (i.e. user can only modify owned data) are made in the handler layer, not the storage layer.
Get rid of unneeded "result" types returned from the storage layer.
Get rid of the "fullPath" property in BoardId. This was always being immediately deconstructed into its component parts anyway.
> [board-server] Push logic out of the storage layer

- packages/shared-ui/src/flow-gen/flow-generator.ts
Bug in https://github.com/breadboard-ai/breadboard/pull/4908
> [flowgen] Bugfix: skip our own messages correctly when parsing response

- packages/shared-ui/src/styles/icons.ts
This way they will have a consistent intrinsic size even before the font has loaded.
> Fix the size of icons to 1em

- packages/board-server/src/server/blobs/create.ts
- packages/board-server/src/server/boards/invoke.ts
- packages/board-server/src/server/boards/run.ts
- packages/board-server/src/server/boards/utils/board-server-provider.ts
- packages/board-server/src/server/boards/utils/invoke-board.ts
- packages/board-server/src/server/boards/utils/run-board.ts
- packages/board-server/src/server/boards/utils/verify-key.ts
- packages/board-server/src/server/home/index.ts
- packages/board-server/src/server/info/index.ts
- packages/board-server/src/server/storage-providers/firestore.ts
- packages/board-server/src/server/store.ts
- packages/board-server/src/server/types.ts
- packages/board-server/tests/invoke-board.ts
- packages/board-server/tests/run-board.ts
Gets rid of almost all calls to `getStore` within the board server implementation. Store is created at server init and propagated downward as needed.
This doesn't matter when the store is stateless, but stateful providers -- like an in-memory provider for testing -- will break if the same object is not used everywhere.
Part of #4933
> [board-server] Propagate store through board server

- packages/board-server/scripts/accounts.ts
- packages/board-server/src/index.ts
- packages/board-server/src/server.test.ts
- packages/board-server/src/server.ts
- packages/board-server/src/server/boards/utils/board-server-provider.ts
- packages/board-server/src/server/config.ts
- packages/board-server/src/server/storage-providers/inmemory.test.ts
- packages/board-server/src/server/storage-providers/inmemory.ts
- packages/board-server/src/server/store.ts
- packages/unified-server/src/server/main.ts
- Update integration test to use in-memory provider
- Board and unified server start scripts use firestore provider
- Provider must always be explicitly given. No default.
Part of #4933
> [board-server] Allow specifying storage provider

- packages/board-server/src/server/boards/create.ts
- packages/board-server/src/server/boards/get.ts
- packages/board-server/src/server/boards/invoke.ts
- packages/board-server/src/server/boards/loader.ts
- packages/board-server/src/server/boards/run.ts
- packages/board-server/src/server/boards/utils/board-server-provider.ts
- packages/board-server/src/server/storage-providers/firestore.ts
- packages/board-server/src/server/storage-providers/inmemory.test.ts
- packages/board-server/src/server/storage-providers/inmemory.ts
- packages/board-server/src/server/storage-providers/sqlite.ts
- packages/board-server/src/server/store.ts
- packages/board-server/tests/firestore/firestore-storage-provider.test.ts
Previously we were only checking for board permissions in the `GET` handler(s) for the boards API. This change pushes that auth check down into the storage layer.
Prior to this change, the invoke handler could actually be used as a workaround for auth checks. Since it would load any board by name that was embedded in the owned board. As long as the initial board could be loaded, all others would succeed without checking permissions. This would allow private boards to be invoked via the invoked handler without permission.
Overall, we *need* to push the auth logic down into the storage layer, since a lot of our auth logic is specific to the storage mechanism. Different storage providers will have different ways to do auth.
Part of #4960
> [board-server] Require current user to get board

- package-lock.json
- packages/breadboard/package.json
- packages/breadboard/src/editor/history.ts
- packages/breadboard/src/editor/types.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/shared-ui/src/flow-gen/flow-diff.ts
- packages/shared-ui/src/revision-history/revision-history-panel.ts
- packages/shared-ui/src/utils/signin-adapter.ts
- packages/visual-editor/src/index.ts
Adds a "Revision history" panel to the right-hand-side of the editor. Visually modeled after the Google Docs history view. To support this, the existing graph history data structure is now signal-aware. Also, a timestamp has been added to history entries.  Also threw in a bug fix for jsonEqual. Major known issues:
- History is not preserved across reloads.
- Some operations don't update the backing graph history in a timely way, appearing only after some additional change is made.
- No visual distinction between human and AI edits.
- Many operations have labels that are UUIDs instead of something human-readable.
- We very likely want a treatment over the whole editor when anything other than the current revision is displayed, so that it is clear the user is viewing an older revision, and …
> [revision history] Initial revision history panel

- .changeset/gold-clubs-talk.md
- packages/shared-ui/src/elements/step-editor/graph-edge.ts
- packages/shared-ui/src/elements/step-editor/graph-node.ts
- packages/shared-ui/src/elements/step-editor/graph.ts
- packages/shared-ui/src/elements/step-editor/renderer.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/shared-ui/src/types/types.ts
- packages/shared-ui/src/utils/workspace.ts
Allows the creation of a highlight state independent of the current selection. To make a highlight state it goes something like this:
```typescript
const highlightState: HighlightStateWithChangeId = {
highlightState: createEmptyHighlightState(),
highlightChangeId: createHighlightId(),
/** "user" or "model" */
highlightType: "user",
};
highlightState.highlightState.graphs.set(MAIN_BOARD_ID, {
/** A set of node IDs to highlight */
nodes: new Set(["44e570f0-4535-437b-af65-c22c6c84205e"]),
/** Same for comments */
comments: new Set(),
/** The ID for the edge generated by `inspectableEdgeToString`, which is in the format below */
edges: new Set([
"907489d2-c4c3-41e0-833f-149fe8313197:context->771ea370-6147-4510-a8be-d32ce7189279:context",
]),
});
```
> Highlight state

- packages/breadboard/src/editor/history.ts
- packages/breadboard/src/editor/types.ts
- packages/shared-ui/src/elements/step-editor/graph-node.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/shared-ui/src/revision-history/revision-history-overlay.ts
- packages/shared-ui/src/revision-history/revision-history-panel.ts
Selecting any non-current revision now prevents interaction with the graph, and displays the selected date, with back and revert buttons.
Also tweaked the color and contrast of the node highlights, and made highlights appear/disappear more consistently.
> [revision history] Overlay with restore button

- packages/breadboard/src/editor/history.ts
- packages/breadboard/tests/editor/history.ts
Having two separate classes was adding complexity to understanding how history works, so now it's just one class. Also removed a few more bits that we don't need.
> [revision history] Combine history classes

- .changeset/fifty-fans-change.md
- packages/google-drive-kit/src/board-server/access.ts
- packages/shared-ui/src/elements/google-drive/google-drive-directory-picker.ts
- packages/shared-ui/src/elements/google-drive/google-drive-file-id.ts
- packages/shared-ui/src/elements/google-drive/google-drive-file-viewer.ts
- packages/shared-ui/src/elements/google-drive/google-drive-query.ts
- packages/shared-ui/src/elements/google-drive/google-drive-server-picker.ts
- packages/shared-ui/src/transforms/autowire-in-ports.ts
- **Don't use edge metadata for edge comparison.**
- **Make sure to load the GAPI client (which brings in `gapi.auth`) in file viewer.**
- **Switch to use `$sign-in` as the default connection id.**
- **docs(changeset): Various Fixes including GAPI client instantiation, default connection id change, and edge comparison.**
> even more fixes

- packages/shared-ui/src/elements/overlay/open-board.ts
- packages/shared-ui/src/elements/welcome-panel/gallery.ts
- packages/shared-ui/src/elements/welcome-panel/project-listing.ts
- packages/shared-ui/src/events/events.ts
The boardServerName and isCtrlCommand parameters aren't used anymore.
> Simplify GraphBoardServerLoadRequestEvent

- packages/shared-ui/src/elements/app-preview/app-preview.styles.ts
- packages/shared-ui/src/elements/app-preview/app-preview.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.styles.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/shared-ui/src/revision-history/revision-history-overlay.ts
- packages/shared-ui/src/revision-history/revision-history-panel.ts
Restores the edit history, but this time under the activity tab.
Also updates the edit history overlay to be a full width banner instead of floating. Probably not the final design, but looks less odd (previously it sat partially on top of the standard toolbar).
> Bring back edit history under Activity tab

- .changeset/cold-sites-buy.md
- packages/shared-ui/src/elements/welcome-panel/gallery.ts
Prefers `<button>` to `<div>` with an `aria-role` and keys the project thumbnail so we don't use stale images while new ones are loading.
> [share-ui] Use keyed placeholders

- packages/google-drive-kit/src/board-server/server.ts
We now find or create a top-level Google Drive folder called "Breadboard" at initialization. We'll make that a VITE_ configurable env var later.
Other fixes:
- Don't list files or folders that are in the trash.
- Fix the board URL we return when creating a board in Drive; it only have the file ID, not the parent folder ID.
> Automatically find or create a root folder in user's Google Drive

- package-lock.json
- packages/google-drive-kit/src/board-server/server.ts
- packages/shared-ui/package.json
- packages/shared-ui/src/elements/google-drive/google-drive-debug-panel.ts
- packages/shared-ui/src/elements/welcome-panel/project-listing.ts
On the homepage, you can now add the driveDebug URL parameter to show a debug panel that displays a bunch of internal data about Google Drive. Useful for understanding capability/debugging. Will probably remove eventually.
> Add temporary drive debug panel

- packages/shared-ui/src/flow-gen/flowgen-editor-input.ts
- packages/shared-ui/src/strings/en_US/editor.ts
It was confusing and weird and UX has a new idea.
> Stop showing the original intent in the edit box

- .changeset/olive-kings-wish.md
- packages/shared-ui/src/transforms/change-edge.ts
- **Switch to "chiclet" as a default at-wire behavior.**
- **docs(changeset): Switch to "chiclet" as the default at-wire behavior.**
> chiclet default

- .changeset/violet-weeks-shine.md
- packages/unified-server/src/init.ts
- packages/visual-editor/package.json
- packages/visual-editor/src/bootstrap.ts
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/init.ts
- packages/visual-editor/src/runtime/runtime.ts
- packages/visual-editor/src/runtime/types.ts
- **Move loading kits into the init module.**
- **Load Core kit only for unified server.**
- **Remove spurious exports.**
- **docs(changeset): Stop loading legacy kits in unified server.**
> stop loading legacy kits

- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
This is a hotfix that addresses the cutoff prompt
box in advance of more elegant solution. IMO it's
also nice to give the side nav a bit more default
real estate.
> Default to .7 and .3 split instead of .75 and .25

- packages/shared-ui/src/elements/input/expanding-textarea.ts
1. The measurement div needed `whitespace: pre-wrap` so that it doesn't collapse whitespace (this caused blank lines not to be accounted for in the height).
2. When the placeholder changes (which it now does on a rotation every few seconds), we also need to re-measure height.
> [flowgen] Fix expanding textarea height bugs

- .changeset/grumpy-falcons-dress.md
- packages/unified-server/.env.development
- packages/unified-server/.env.production
- packages/unified-server/src/init.ts
- packages/visual-editor/src/bootstrap.ts
- **Add `defaultBoardService`, so that we don't have to specify VITE_BOARD_SERVICE for default configuration.**
- **docs(changeset): Add `defaultBoardService` to remove the need for always specifying the BOARD_SERVICE.**
> default board service

- packages/a2/bgl/src/environment.d.ts
- packages/agent-kit/agent.kit.json
- packages/agent-kit/boards/specialist.bgl.json
- packages/breadboard/src/inspector/graph/ports.ts
- packages/breadboard/src/types.ts
- packages/jsandbox/src/environment.d.ts
- packages/jsandbox/src/type-declarations.ts
- packages/shared-ui/src/elements/input/text-editor/text-editor.ts
Not all callsites of this component make sense with the new copy, so reverting for now. Also adds a
"hint-no-prompt" we can use in A2 to reference
fields that don't have traditional prompt semantics. This hint is not yet used.
> Revert back to "Type your prompt here"

- .changeset/famous-hands-serve.md
- package-lock.json
- packages/board-server/src/server/boards/utils/board-server-provider.ts
- packages/breadboard/src/loader/default.ts
- packages/breadboard/src/loader/types.ts
- packages/embedded-board-server/src/index.ts
- packages/filesystem-board-server/src/filesystem-board-server.ts
- packages/google-drive-kit/package.json
- packages/google-drive-kit/src/board-server/api.ts
- packages/google-drive-kit/src/board-server/operations.ts
- packages/google-drive-kit/src/board-server/server.ts
- packages/remote-board-server/src/remote-board-server.ts
- packages/shared-ui/src/elements/google-drive/google-drive-debug-panel.ts
- **Make `BoardServer` an `EventTarget`.**
- **Factor out Drive operations.**
- **Introduce `DriveOperations` class that holds all drive operations.**
- **Narrow down the scope of `DriveOperations`.**
- **docs(changeset): Separate out `DriveOperations` in Drive Board Server.**
> save board server safely

- packages/agent-kit/src/index.ts
This pull request updates the URL for the `agentKit` in the `packages/agent-kit/src/index.ts` file to point to a new JSON file location. This change ensures the correct file path is used for the `agentKit` configuration.
* **URL Update for `agentKit`:**
* Updated the `url` property to reference `agent.kit.json` instead of `kit.json`, aligning with the new file structure. (`[packages/agent-kit/src/index.tsL21-R21](diffhunk://#diff-2d22ecbeb3542a59dd3cae09e1fb89d459731cc3736f0900c6307dfbecfcb86fL21-R21)`)
> Correct agent kit url

- .changeset/open-singers-crash.md
- packages/shared-ui/src/transforms/autowire-in-ports.ts
- packages/shared-ui/src/transforms/change-edge.ts
- packages/shared-ui/src/transforms/mark-in-ports-invalid-spec.ts
- packages/shared-ui/src/transforms/mark-in-ports-invalid.ts
- packages/shared-ui/src/transforms/transform-all-nodes.ts
- **Distinguish between deleted ports and edges when invalidating references.**
- **Un-invalidate port references when reconnecting.**
- **Allow adding more references to same node without adding wires.**
- **Leave invalid port refs invalid.**
- **docs(changeset): A slew of fixes around port reference editing**
> invalid chiclet fixes

- packages/shared-ui/src/flow-gen/flow-generator.ts
The backend always treats this step-constrained
edit case specially so there's no need to be
so adamant about not changing other aspects.
> Remove now unnecessary levels of cajoling

- packages/bbrt/src/bootstrap.ts
- packages/bbrt/src/test/playwright/main_test.ts
- packages/shared-ui/src/contexts/environment.ts
- packages/shared-ui/src/elements/elements.ts
- packages/shared-ui/src/elements/google-drive/google-drive-share-panel.ts
- packages/shared-ui/src/elements/share-panel/share-panel.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/unified-server/src/client/app/init.ts
- packages/visual-editor/src/index.ts
Clicking share now opens a modal with a simple publish toggle. Enabling/disabling the toggle adds/removes a fixed set of permissions configured per deployment via the `VITE_GOOGLE_DRIVE_PUBLISH_PERMISSIONS` variable.
> [drive] Custom share modal with publish toggle

- .changeset/six-fans-tell.md
- packages/breadboard/src/graph-based-node-handler.ts
- packages/breadboard/src/inspector/graph-store.ts
- packages/breadboard/src/inspector/graph/bubbled-node.ts
- packages/breadboard/src/inspector/graph/describe-cache.ts
- packages/breadboard/src/inspector/graph/describer-manager.ts
- packages/breadboard/src/inspector/graph/mutable-graph.ts
- packages/breadboard/src/inspector/graph/node-describer-manager.ts
- packages/breadboard/src/inspector/graph/node-type-describer-manager.ts
- packages/breadboard/src/inspector/graph/node.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/src/loader/loader.ts
- packages/breadboard/tests/inspector/observer-load.ts
- packages/shared-ui/src/elements/board-activity/board-activity.ts
- **Ensure latest MutableGraph in GrpahBasedNodeHandler.**
- **Stop passing `InputValue` to describers.**
- **Move classes out of `describer-manager` into their own files.**
- **Remove `sameCheck` and stop mutating graphs when adding them. Also, use `urlComponentsFromString` to correctly parse `module:` prefixed paths.**
- **docs(changeset): Reduce the number of times describers are called during the run.**
> describer once 2

- packages/shared-ui/src/elements/app-preview/app-preview.ts
We were trying to resolve splash image URLs relative to the _graph_ URL, which in the case of drive is `drive:<drive id>`, and so won't resolve to the blob API. Now we check for blob IDs explicitly, and always return a known good path to the blob API.
> [drive] Fix bad assumption about graph URL that broke splash images on drive

- .changeset/smart-wolves-hope.md
- packages/shared-ui/src/app-templates/basic/index.ts
- packages/shared-ui/src/elements/output/llm-output/llm-output.ts
Reverts breadboard-ai/breadboard#5680, because it made HTML views short.
> Revert "[shared-ui] Contain the height of html-view"

- packages/google-drive-kit/src/google-drive-client.ts
Unfortunately we can't suppress the 404 errors that appear in the console, but we can at least log to show that we detected and handled them.
> [drive] Add some logging to GoogleDriveClient to make 404 errors less concerning

- packages/shared-ui/src/elements/google-drive/google-drive-file-viewer.ts
We quite often get 429 Too Many Requests errors during development when rendering Google Drive preview images. Probably the Google Drive service has a very low throttle threshold when the Referrer is localhost.
> [drive] Render placeholder doc icon when preview image missing or errored

- packages/visual-editor/index.html
Reduces the size of the Google Symbols woff2 file from 9MB to 141KB by enumerating the symbols we are actually using.
There's a chance I missed some, but poked around the app a bunch and don't see anything missing. I looked at these 3 declaration styles:
- Static names inside g-icon elements
- ::before content on g-icon elements
- "icon" properties in the A2 BGL files
> [perf] Shrink Google Symbols font from 9MB to 141KB

- packages/shared-ui/src/elements/connection/connection-entry-signin.ts
- packages/shared-ui/src/elements/share-panel/share-panel.ts
- packages/unified-server/src/client/app/elements/app-view/app-view.ts
- packages/unified-server/src/client/app/init.ts
Also includes a fix to the share panel to allow it to display the app link for graphs not owned by the current user.
Note there are still some issues where the graph seems to have trouble executing, like an OAuth issue, but the same thing is happening with our Firebase-backed version too, so I'm treating that as a separate issue.
> [drive] Require immediate login in app view for Drive graphs

- packages/shared-ui/src/elements/google-drive/find-google-drive-assets-in-graph.ts
Splash images are not listed under assets, but they too need to be shared when sharing a graph.
> [sharing] Include splash images when sharing files

- packages/google-drive-kit/src/board-server/operations.ts
- packages/google-drive-kit/src/board-server/server.ts
- packages/shared-ui/src/elements/google-drive/google-drive-debug-panel.ts
note that this solves only one half of the problem of not refreshing after updating a gdrive board - the other half is because of debounce - will follow up.
> [gdrive] force refresh the project list when one changes

- .changeset/forty-bags-search.md
- packages/shared-ui/src/elements/step-editor/renderer.ts
- **Teach Renderer to produce less ambiguous step names.**
- **docs(changeset): Teach Renderer to produce unique-ish names for steps.**
> friendly names

- .changeset/nasty-weeks-itch.md
- packages/shared-ui/src/data/settings-store.ts
- packages/visual-editor/src/commands/commands.ts
- **Make Cmd+Shift+E sticky**
- **docs(changeset): Make Cmd+Shift+E sticky across reloads.**
> sticky experiments

- packages/google-drive-kit/src/board-server/operations.ts
This way the user can move their opals around, and it simplifies some deployment stuff around folder names too.
> [drive] Don't constrain the folder when searching for my boards

- packages/shared-ui/src/elements/app-preview/app-theme-creator.ts
- packages/unified-server/src/client/app/init.ts
- packages/visual-editor/src/runtime/board.ts
For security, to read the pixels out of an image (required for the new material theming logic), the image must be fetched with CORS enabled. Since we didn't have a cross-origin attribute, we were not sending any CORS headers. Now we do.
> [themes] Enable CORS for image requests so that we can read pixels

- packages/embed/src/index.ts
- packages/embed/src/types/types.ts
- packages/shared-ui/src/elements/entity-editor/entity-editor.ts
- packages/shared-ui/src/events/events.ts
- packages/shared-ui/src/utils/board-id.ts
- packages/shared-ui/src/utils/utils.ts
- packages/unified-server/package.json
- packages/visual-editor/src/index.ts
Implements the following three features in communicating between an iframed breadboard page and its embedder:
1. **Iterate on prompt**. Allows the embedder to send an `toggle_iterate_on_prompt` message which enables a new button in the title of the expanded node. Pressing this button emits a `iterate_on_prompt` message to the embedder conveying information about the board and node of origin, as well as the prompt at the time of button press.
1. **Create a new board.** Allows the parent to send a `create_new_board` message. If the requested board is succesfully created, the generated board ID is sent back as a message to the embedder.
1. **Home loaded.** Sends the embedder a message notifying it that Breadboard loaded, along with the user's signed-in status.
1.  **Handshake ready.** Sends …
> Use EmbedHandler to support iterate-on-prompt button, homepage loaded, and creating a new board message.

- packages/embed/src/types/types.ts
- packages/shared-ui/src/elements/entity-editor/entity-editor.ts
- packages/shared-ui/src/events/events.ts
- packages/visual-editor/src/index.ts
Small improvements to Iterate-on-prompt button.
With this change, the button only shows up on generative nodes, and is disabled if any tools are contained in the prompt. This change also includes the model ID in the message send to the embedder.
> Small improvements to Iterate-on-prompt button.

- packages/embed/src/types/types.ts
- packages/shared-ui/src/elements/entity-editor/entity-editor.ts
- packages/shared-ui/src/utils/board-id.ts
- packages/shared-ui/src/utils/utils.ts
- packages/visual-editor/src/index.ts
Small fixes for breadboard-embedder integration:
- Corrects logic to extract board URL/ID. The prior code treated `graph.raw().url` as an HTTP/HTTPS URL, where the "board ID" was the `tab0` search param within that URL. In actuality, the `graph.raw().url` is the board ID (or rather, board URL). If this is not available; then we extract the `tab0` value from the current window.location.
- Add "declare" for all interfaces shared between breadboard and embedder to ensure field don't get renamed by the compiler. This is not currently a problem, but as a precaution, making it explicit.
> Correct board URL logic and declare interfaces for Breadboard-embedder communication

- .changeset/eight-bobcats-enter.md
- packages/shared-ui/src/state/graph-asset.ts
- packages/shared-ui/src/state/organizer.ts
- packages/shared-ui/src/state/project.ts
- packages/shared-ui/src/state/types.ts
- packages/shared-ui/src/utils/image.ts
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/runtime/edit.ts
- packages/visual-editor/src/runtime/runtime.ts
- **Fold theming code into Edit where it belongs.**
- **Move managing of `Project` state to runtime.**
- **Remove unnecessary stored/inline data conversions.**
- **Rename `persistBlobs` to `persistDataParts`.**
- **Better error messages.**
- **Add try/catch around iamge fetching.**
- **docs(changeset): Clean up theme-creation code.**
> theming cleanups

- .changeset/polite-terms-prove.md
- packages/board-server/src/server/boards/assets-drive.ts
- packages/breadboard/src/data/inflate-deflate.ts
- packages/google-drive-kit/src/board-server/data-part-transformer.ts
- **Add try/catch around fetches in `GoogleDriveDataPartTransformer`**
- **Throw an error when can't inflate.**
- **Teach server to send a more precise error message.**
- **docs(changeset): Handle Drive errors a bit more gracefully.**
> fail gracefully

- packages/board-server/src/server/proxy/gcs-aware-fetch.ts
get passed around as GCS urls.
> Add generate_music to the set of outputs that

- packages/shared-ui/src/elements/google-drive/google-drive-picker.ts
Adds a small "No documents?" link underneath the picker which opens some help text.
> [sharing] Add "No documents?" help to drive picker modal

- packages/google-drive-kit/src/google-drive-client.ts
- packages/shared-ui/src/elements/elements.ts
- packages/shared-ui/src/elements/google-drive/find-google-drive-assets-in-graph.ts
- packages/shared-ui/src/elements/google-drive/google-drive-asset-share-dialog.ts
- packages/shared-ui/src/elements/share-panel/share-panel.ts
- packages/shared-ui/src/styles/button.ts
- packages/visual-editor/src/index.ts
If the graph is shared (either published or shared granularly), adding an asset from Drive will now display a dialog like this:
Clicking share will update the permissions of that asset to match the main graph.
> [sharing] Prompt to share asset when added to shared graph

- packages/google-drive-kit/src/board-server/api.ts
- packages/google-drive-kit/src/board-server/operations.ts
Run results are now saved with the "graphUrl" drive app property, and the new `listRunResultsForGraph` method can find them for a given graph URL.
> [sharing] Make drive run results listable with graphUrl app property

- packages/shared-ui/src/elements/share-panel/share-panel.ts
Should make the "Copy link" button in the sharing dialog work more consistently.
> [sharing] Be more lenient with detecting share permissions errors

- packages/google-drive-kit/src/board-server/operations.ts
- packages/shared-ui/src/elements/share-panel/share-panel.ts
This shouldn't be necessary, but if we don't do this, the copy will appear on the user's gallery page until the browser's site data is cleared because of our Drive caching infrastructure. This is a quick hack in lieu of understanding how to make the caching infrastructure handle this case better.
> [sharing] Invalidate user list cache so that shareable copies don't appear in the gallery

- .changeset/mean-seas-learn.md
- packages/shared-ui/src/app-templates/basic/index.ts
- packages/shared-ui/src/elements/app-preview/app-preview.ts
- packages/shared-ui/src/elements/output/console-view/console-view.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/shared-ui/src/state/app.ts
- packages/shared-ui/src/state/console-entry.ts
- packages/shared-ui/src/state/project-run.ts
- packages/shared-ui/src/state/project.ts
- packages/shared-ui/src/state/types.ts
- packages/shared-ui/src/state/work-item.ts
- packages/shared-ui/src/types/types.ts
- packages/unified-server/src/client/app/elements/app-view/app-view.ts
- packages/unified-server/src/client/app/init.ts
- packages/unified-server/src/client/app/types/types.ts
- packages/visual-editor/src/runtime/run.ts
- **Remove unused code path around `isInSelectionState`.**
- **Introduce `runnable` flag on `ProjectRun`.**
- **Introduce `App.state` and start using it.**
- **Get rid of node counting in basic app template.**
- **Remove the use of `TopGraphResult` from `render` in basic app template.**
- **Teach `ConsoleView` that run is always present.**
- **Introduce `ProjectRun.finalOutput` and use it.**
- **Make saved result work without TGR.**
- **docs(changeset): Wean <app-basic> off `TopGraphResult`.**
> reactive app view 3

- .changeset/little-lizards-shake.md
- packages/shared-ui/src/state/project-run.ts
- **Correctly wire `ProjectRun` when creating from saved result.**
- **docs(changeset): Correctly wire `ProjectRun` when loading saved results.**
> fix save results

- .changeset/tidy-items-check.md
- packages/shared-ui/src/state/project-run.ts
- packages/shared-ui/src/state/project.ts
- **Make `inspectable` a signal in `ProjectRun`.**
- **docs(changeset): Fix the bug where "Start" is disabled in a new flow**
> inspectable signal

- packages/shared-ui/src/config/client-deployment-configuration.ts
- packages/shared-ui/src/contexts/build-info.ts
- packages/shared-ui/src/elements/elements.ts
- packages/shared-ui/src/elements/feedback/feedback-panel.ts
- packages/shared-ui/src/elements/welcome-panel/project-listing.ts
- packages/visual-editor/src/bootstrap.ts
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/types/types.ts
If the ENABLE_GOOGLE_FEEDBACK deployment config flag is true, then we'll now open a full Google Feedback side panel with screenshot capability on the RHS instead of opening up the Google Form we have been using.
> [feedback] Integrate Google Feedback (feature flagged)

- packages/unified-server/src/server/main.ts
Redirect the old standalone app view to the new unified view with the app tab opened.
> Redirect old app view to new unified view

- packages/shared-ui/src/elements/connection/connection-entry-signin.ts
- packages/shared-ui/src/utils/action-tracker.ts
- add separate events related to sources, since google analytics can't breakdown the analysis
- add two new events: visiting sign-in page and signing in
> [unified-server] update events for google analytics

- packages/shared-ui/src/elements/google-drive/google-drive-file-id.ts
- packages/shared-ui/src/elements/input/add-asset/add-asset-modal.ts
- packages/shared-ui/src/elements/step-editor/editor-controls.ts
Previously, when opening the asset picker you would see both my files and all shared files. This would usually take a very long time to load.
Now, there are instead 2 tabs: my files, and shared files. Only when clicking shared files do things slow down as all the docs are loaded.
> [assets] Separate tabs for mine vs shared files in asset picker

- packages/google-drive-kit/src/board-server/operations.ts
- packages/google-drive-kit/src/google-drive-client.ts
- packages/shared-ui/src/elements/google-drive/google-apis.ts
- packages/shared-ui/src/elements/google-drive/google-drive-asset-share-dialog.ts
- packages/shared-ui/src/elements/google-drive/google-drive-debug-panel.ts
- packages/shared-ui/src/elements/google-drive/google-drive-file-id.ts
- packages/shared-ui/src/elements/google-drive/google-drive-share-panel.ts
- packages/shared-ui/src/elements/share-panel/share-panel.ts
- packages/visual-editor/src/index.ts
- New GoogleDriveClient methods: updateFileMetadata, deletePermission, listFiles
- Some renaming/cleanup/refactoring/documenting of GoogleDriveClient
- This should slightly improve reliability of publishing, since this gives us retry logic in some places we didn't have it before
- Completely removes usage of the GAPI drive API in favor of our own better API
> [cleanup] Replace all usage of GAPI drive API with GoogleDriveClient

- packages/shared-ui/src/elements/toast/snackbar.ts
- packages/shared-ui/src/types/types.ts
- packages/types/src/deployment-configuration.ts
- packages/visual-editor/src/index.ts
- Adds domains[].preferredUrl to ClientDeploymentConfiguration
- When present, show a message to users from the given domain telling them to go to the other url
- Also allows the snackbar to render HTML templates
> Show a message if the user should be on a different deployment

- .changeset/shy-areas-sleep.md
- packages/data/src/common.ts
- **Only allow some URLs in `retrieveAsBlob`.**
- **docs(changeset): Only allow a small set of URLs to be retrieved as blob**
> retrieve as blob

- .changeset/rich-cases-obey.md
- packages/particles-ui/src/elements/groups/particle-ui-list.ts
- packages/shared-ui/src/app-templates/shared/utils/app-screen-to-particles.ts
It turns out there are times where the run output isn't an LLMContent but is, in fact, text. So we need to wrap that into an LLMContent with a text part so it can be converted to a Particle.
> [particles-ui/shared-ui] Handle non-LLMContent conversions

- packages/breadboard/src/editor/operations/change-asset-metadata.ts
- packages/breadboard/src/inspector/graph/inspectable-asset.ts
- packages/google-drive-kit/src/board-server/utils.ts
- packages/schema/breadboard.schema.json
- packages/shared-ui/src/elements/share-panel/share-panel.ts
- packages/shared-ui/src/elements/step-editor/editor-controls.ts
- packages/shared-ui/src/elements/step-editor/renderer.ts
- packages/shared-ui/src/types/types.ts
- packages/types/src/graph-descriptor.ts
- packages/types/src/inspect.ts
- packages/visual-editor/src/event-routing/asset/asset.ts
- Drive picked assets are now storedData, instead of fileData, making them consistent with uploaded files and themes.
- Drive picked assets can now be sent to Gemini.
- Drive picked assets will now get copied when remixing/duplicating.
- There is a new "managed" asset metadata boolean to distinguish uploaded from picked assets in sharing.
> [assets] Treat picked files as storedData and add managed metadata boolean

- packages/board-server/src/server/boards/assets-drive.ts
We weren't passing the mime type of google workspace docs prior to  https://github.com/breadboard-ai/breadboard/pull/6368, and the gemini file upload server was using the absence of a mime type to decide when a file needed to be exported vs downloaded directly.
> [gemini asset upload] Fix get vs export bug when google workspace mime type is provided

- .changeset/cool-lies-dance.md
- packages/types/src/deployment-configuration.ts
- packages/unified-server/src/server/drive-proxy.ts
- packages/unified-server/src/server/main.ts
- **Repurpose old drive proxy code to implement `/files` API endpoint.**
- **A very simple cache.**
- **docs(changeset): Introduce `/files` endpoint for storing/caching gallery results.**
> files api endpoint

- packages/google-drive-kit/src/google-drive-client.ts
- packages/unified-server/src/server/main.ts
Disabling until we have more confidence. Right now when it starts up, it block developers from calling the drive API because of abuse detection.
> [drive] Temporarily disable the /files endpoint

- .changeset/kind-breads-smile.md
- packages/shared-ui/src/app-templates/basic/index.ts
- packages/shared-ui/src/types/types.ts
We now only allow resetting of the content warning when the app template has been unmounted and remounted, meaning that it remains dismissed rather than returning on re-render.
> [shared-ui] Fix content warning behavior

- packages/connection-client/src/token-vendor.ts
- packages/connection-client/src/types.ts
- packages/shared-ui/src/utils/signin-adapter.ts
- packages/unified-server/package.json
- packages/unified-server/src/landing/main.ts
- packages/unified-server/src/server/csp.ts
- packages/visual-editor/src/bootstrap.ts
We will now check that all required OAuth scopes are granted at bootstrap, and if one is missing we redirect the user to the "Additional access required" screen on the landing page.
We also now store scopes in the local signin storage. If, during the missing scopes check, we find that we don't have any scopes in local signin (because it is a signin from before this PR), then we call the https://oauth2.googleapis.com/tokeninfo endpoint to read the scopes, and automatically upgrade the local storage for next time.
> [signin] Check for required scopes and force signin when missing

- .changeset/wise-parts-hug.md
- packages/shared-ui/src/elements/input/item-select/item-select.ts
- **Select first non-hidden value in item select default.**
- **docs(changeset): Select first non-hidden value as bb-item-select default**
> item select default

- .changeset/wild-rats-accept.md
- packages/shared-ui/src/elements/input/text-editor/text-editor.ts
- packages/visual-editor/src/commands/types.ts
- packages/visual-editor/src/index.ts
To this point we have intercepted all context menu requests and prevented the default behavior. However, that prevents people from doing things like right-click and paste of – say – a prompt into the text area. This PR contains a quality-of-life improvement where the context menu is shown for right clicks on the Text Editor thereby allowing them to paste content (or access any other menu items they may wish).
> [ve/su] Allow pasting in text editor

- .changeset/lucky-eels-happen.md
- packages/google-drive-kit/src/board-server/operations.ts
- packages/google-drive-kit/src/board-server/server.ts
- packages/google-drive-kit/src/board-server/utils.ts
- packages/google-drive-kit/tests/board-server/operations.ts
- packages/shared-ui/src/strings/en_US/global.ts
- packages/types/src/loader.ts
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/runtime/board.ts
- packages/visual-editor/src/runtime/events.ts
- packages/visual-editor/src/runtime/types.ts
To this point a user doesn't know if an app they've opened has been updated by the author. This PR includes a quality-of-life improvement whereby the version of an opened app is retained in browser storage. If and when that same app is opened in future the version number is checked and, should the app have been updated, the user is shown a snackbar telling them as much.
> [various] Track opened versions for shared apps

- packages/shared-ui/package.json
- packages/shared-ui/src/app-templates/basic/index.ts
- packages/shared-ui/src/elements/share-panel/share-panel.ts
- packages/shared-ui/src/tests/urls.test.ts
- packages/shared-ui/src/utils/urls.ts
- packages/unified-server/src/landing/main.ts
- packages/visual-editor/src/bootstrap.ts
- packages/visual-editor/src/event-routing/board/board.ts
- packages/visual-editor/src/event-routing/host/host.ts
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/runtime/board.ts
- packages/visual-editor/src/runtime/router.ts
Adds new makeUrl and parseUrl functions which understand all of the kinds of URLs in our app, and updated every place (at least those I could find; there might be a few stragglers) where we create or parse URLs to use this.
One bug this fixes is that previously if you were signed-out but clicked on a link with a results file, the results parameter got dropped.
In general this should make it easier to create valid consistent URLs, and will make it easier to change our URL scheme if we want, too.
Also adds a test script to the shared-ui package. It's a node test, but that's the simplest/fastest way to run unit tests assuming it's not depending on any web-specific apis.
> [urls] Consolidate URL creation and parsing

- .changeset/giant-clubs-try.md
- packages/shared-ui/src/config/client-deployment-configuration.ts
- packages/shared-ui/src/elements/canvas-controller/canvas-controller.ts
- packages/shared-ui/src/elements/step-editor/entity.ts
- packages/shared-ui/src/elements/step-editor/graph-asset.ts
- packages/shared-ui/src/elements/step-editor/graph-edge.ts
- packages/shared-ui/src/elements/step-editor/graph-node.ts
- packages/shared-ui/src/elements/step-editor/graph.ts
- packages/shared-ui/src/elements/step-editor/renderer.ts
- packages/shared-ui/src/elements/step-editor/utils/to-css-matrix.ts
- packages/types/src/flags.ts
By default we use 3D matrices for rendering nodes & edges which creates compositor layers in Chromium-based browsers. For larger graphs particularly this can create memory pressure where the tab needs more memory than it can access, which in turn causes rendering bugs.
This PR enables an experimental flag for using 2D matrices (and bypassing `will-change`) on edges and nodes. The trade-off is this:
1. With this flag off (the default) everything is given its own compositor layer. This means we avoid re-rasterizing but for larger graphs we can see memory pressure/exhaustion.
2. With this flag on everything is drawn into the same compositor layer. This means that every pan & zoom action will cause re-rasterizing, but on the upside everything is on a single compositor layer so there's less to …
> [shared-ui] Enable experimental 2D matrix rendering of graph

- .changeset/thick-hairs-own.md
- packages/shared-ui/src/elements/step-editor/entity.ts
Reverts breadboard-ai/breadboard#6521
This starts throwing cycle as detected in signal machinery. Let's remove it for now.
> Revert "[shared-ui] Make Entity a SignalWatcher"

- .changeset/loose-poems-sleep.md
- packages/shared-ui/src/flow-gen/flowgen-in-step-button.ts
- **Dispatch event to clear editing state when using in-step flowgen.**
- **docs(changeset): Fix the bug where the in-step flowgen edits aren't reflected.**
> instep flowgen

- packages/shared-ui/src/tests/urls.test.ts
- packages/shared-ui/src/utils/urls.ts
The `makeUrl` and `parseUrl` functions now treat `"dev-"` prefixed url search parameters in a special way. Any search parameter that starts with `"dev-"` gets parsed into a new `{dev: { ... } }` object. E.g. `?dev-foo-bar=baz` becomes `{dev: {"foo-bar": "baz"} }` and vice-versa. And those parameters will be sticky in the URL (since in general, unknown URL search params get removed).
The idea is to provide a standard place to throw in special switches that are mostly useful for development, like for testing, debugging, cache-busting, etc.
> [urls] Add special handling for dev- prefixed url params

- .changeset/khaki-places-lay.md
- packages/shared-ui/src/state/project.ts
- packages/shared-ui/src/state/types.ts
- packages/shared-ui/src/utils/expand-chiclet.ts
This PR ensures that we use the subtype icon for steps and assets, so that they don't show a generic generative icon when they are – say – a generative audio step.
> [shared-ui] Refine icons in text editor

- packages/connection-client/package.json
- packages/connection-client/src/oauth-scopes.ts
- packages/connection-client/src/token-vendor.ts
- packages/connection-client/src/types.ts
- packages/connection-server/src/api/list.ts
- packages/google-drive-kit/src/google-drive-client.ts
- packages/shared-ui/src/elements/shell/sign-in-modal.ts
- packages/shared-ui/src/utils/signin-adapter.ts
- packages/visual-editor/src/index.ts
`SigninAdapter.token()` now takes an optional `scopes` argument, which is an array of scopes defined in the new `connection-client/src/oauth-scopes.ts` module. If `scopes` is set, and one or more of those scopes have not been granted by the user, a new dialog will popup asking the user to add that permission by going through the OAuth flow.
> [signin] Support incremental oauth scopes

- packages/visual-editor/src/index.ts
Was harmless, but showed in the console.
> Fix uncaught exception relating to reading domain config

- packages/shared-ui/src/elements/welcome-panel/project-listing.ts
One css block from https://github.com/breadboard-ai/breadboard/pull/6651 actually was used, oops.
> Restore some over-zealous css cleanup

- packages/types/src/deployment-configuration.ts
- packages/unified-server/src/server/csp.ts
- packages/unified-server/src/server/provide-config.ts
It's only used in unified-server. There's no need for it to be in common
types. This is a precursor to removing the type entirely.
> [unified-server] Move ServerDeploymentConfiguration out of common types

- packages/unified-server/src/server/csp.ts
- packages/unified-server/src/server/main.ts
- packages/unified-server/src/server/provide-config.ts
It only uses the endpoint URL. It doesn't need the whole config.
> [unified-server] Provide endpoint URL to CSP handler instead of whole config

- packages/unified-server/src/server/allow-list-checker.ts
- packages/unified-server/src/server/csp.ts
- packages/unified-server/src/server/flags.ts
- packages/unified-server/src/server/main.ts
Access it when necessary instead of passing it as an argument.
Also rename provide-config to flags. We are going to give this treatment
to all of the flags that we recognize, so that there's a single place to
access flag values.
> [unified-server] Make BACKEND_API_ENDPOINT a module-level flag

- packages/unified-server/src/server/flags.ts
- packages/unified-server/src/server/main.ts
Fixes "Error: GOOGLE_DRIVE_FEATURED_GALLERY_FOLDER_ID not set" in local dev
> [unified-server] Initialize dotenv in flags.js instead of main.js

- packages/google-drive-kit/src/board-server/operations.ts
- packages/google-drive-kit/src/board-server/server.ts
- packages/google-drive-kit/src/google-drive-client.ts
- packages/visual-editor/src/runtime/board.ts
This drops the user-perceived latency in creating a new graph from around 5 seconds to around 100 milliseconds.
It works like this:
- The create method now uses https://developers.google.com/workspace/drive/api/reference/rest/v3/files/generateIds to get a file ID from Drive in the quickest way possible, and returns it right away. From the caller's perspective, the graph is ready to display and edit at this time.
- Meanwhile, the rest of the create operation is backgrounded, and the initial blank graph descriptor is stored in memory. The full create operation could take up to 5 seconds, because it has to serially find the Drive folder ID, and then upload the data, and both of those calls are quite slow.
- A subsequent load() operation for that URL will return that blank graph directly from …
> Drop user-perceived latency for creating new graphs from ~5s to ~100ms

- packages/unified-server/src/server/config.ts
- packages/unified-server/src/server/flags.ts
Get rid of the GOOGLE_DRIVE_PUBLISH_PERMISSIONS_CONFIG environment variable, and parse the value directly from the environment variable (which contains JSON) instead of reading a file.
> [unified-server] Move drive permissions to a literal flag
