- seeds/graph-playground/docs/graphs/math.md
- seeds/graph-playground/graphs/math.json
- seeds/graph-playground/src/boards/math.ts
> [graph-playground] Fix a miswire in math.

- seeds/breadboard-web/docs/graphs/math.md
- seeds/breadboard-web/public/graphs/math.json
- seeds/breadboard-web/src/boards/math.ts
> [breadboard-web] Convert "The Calculator Recipe" to new syntax

- seeds/breadboard-cli/README.md
- seeds/breadboard-cli/src/commands/lib/utils.ts
- seeds/breadboard-cli/src/commands/make-graph.ts
Handle things that look like boards (lambda)
> [cli] Remove a superfluous log and fixes things that looks like Board JSON

- seeds/breadboard-cli/README.md
> Updating the CLI readme

- seeds/breadboard/src/new/recipe-grammar/node.ts
- seeds/breadboard/tests/new/recipe-grammar/recipe-as-code.ts
> [breadboard] Tweak async function regex.

- seeds/breadboard-web/docs/graphs/palm-text-generator.md
- seeds/breadboard-web/public/graphs/palm-text-generator.json
- seeds/breadboard-web/public/local-boards.json
- seeds/breadboard-web/src/boards/palm-text-generator.ts
> [breadboard-web] Add the actual PaLM Text Generator recipe.

- packages/breadboard-web/docs/graphs/openai-gpt-35-turbo.md
- packages/breadboard-web/docs/graphs/openai-gpt-4-vision.md
- packages/breadboard-web/public/graphs/openai-gpt-35-turbo.json
- packages/breadboard-web/public/graphs/openai-gpt-4-vision.json
- packages/breadboard-web/src/boards/openai-chunk-transformer.ts
- packages/breadboard-web/src/boards/openai-gpt-35-turbo.ts
- packages/breadboard-web/src/boards/openai-gpt-4-vision.ts
- packages/breadboard-web/src/make-graphs.ts
- Convert gpt-4-vision
- Convert gpt-35-turbo.
- Teach make-graphs to be chill about non-default exports.
- Share chunk transformer.
> [breadboard-web] Convert a few more boards to recipes.

- packages/breadboard-web/docs/graphs/gemini-generator.md
- packages/breadboard-web/docs/graphs/gemini-pro-vision.md
- packages/breadboard-web/public/graphs/gemini-generator.json
- packages/breadboard-web/public/graphs/gemini-pro-vision.json
- packages/breadboard-web/src/boards/gemini-generator.ts
- packages/breadboard-web/src/boards/gemini-pro-vision.ts
- Convert gemini-pro-vision to recipe.
- Use codeAsRecipe for in chunk transformer.
- Convert gemini-generator.
> [breadboard-web] Convert gemini boards to recipes.

- packages/breadboard-web/docs/graphs/gemini-generator.md
- packages/breadboard-web/docs/graphs/gemini-pro-vision.md
- packages/breadboard-web/public/graphs/gemini-generator.json
- packages/breadboard-web/public/graphs/gemini-pro-vision.json
- packages/breadboard-web/src/boards/gemini-generator.ts
> [breadboard-web] Use spread syntax in gemini-generator.

- packages/breadboard-web/docs/graphs/gemini-generator.md
- packages/llm-starter/src/nodes/xml-to-json.ts
- packages/llm-starter/tests/nodes/xml-to-json.ts
Also adds some tests
Fixes #240
> [llm-starter] Fixes #240 - finds first actual element

- package-lock.json
- packages/breadboard-ui/package.json
- packages/breadboard-ui/src/diagram.ts
So far as I can tell it works for us to dynamically import mermaid as with any other package. This PR removes the CDN import.
> [breadboard-ui] Move mermaid to internal dep

- packages/breadboard-ui/package.json
- packages/breadboard-ui/src/done.ts
- packages/breadboard-ui/src/error.ts
- packages/breadboard-ui/src/index.ts
- packages/breadboard-web/public/graphs/board-caller.json
- packages/breadboard-web/public/graphs/gemini-generator.json
- packages/breadboard-web/public/graphs/gemini-pro-vision.json
> [breadboard-ui] Migrate a few elements to Lit

- packages/breadboard-ui/src/events.ts
- packages/breadboard-ui/src/index.ts
- packages/breadboard-ui/src/input-multipart.ts
- packages/breadboard-ui/src/input.ts
- packages/breadboard-ui/src/types.ts
- packages/breadboard-ui/src/ui-controller.ts
- packages/breadboard-ui/src/utils/index.ts
- packages/breadboard-ui/src/utils/short-term-memory.ts
- packages/breadboard-ui/src/webcam.ts
#231 continues. This updates input to use Lit Element.
Note: it temporarily switches off Drawables. I'll land that back in as soon as I can.
> [breadboard-ui] Migrate input to lit-element

- packages/breadboard/src/new/runner/scope.ts
- packages/breadboard/tests/new/runner/pinning-scopes.ts
Test with invoke and serialize.
The test is also a nice example of just using the lower layer primitives to build a graph.
> [breadboard/new] Add ability to pin nodes to scopes

- packages/breadboard/src/new/recipe-grammar/node.ts
- packages/breadboard/src/new/recipe-grammar/scope.ts
- packages/breadboard/src/new/runner/node.ts
- packages/breadboard/src/new/runner/runner.ts
- packages/breadboard/src/new/runner/scope.ts
- packages/breadboard/src/new/runner/types.ts
and
- changed order expecting pinned scopes use to be more common
- made callbacks nested within dynamic scopes
> [breadboard/new] documented  scope methods

- packages/breadboard-ui/src/drawable.ts
- packages/breadboard-ui/src/index.ts
- packages/breadboard-ui/src/input-multipart.ts
- packages/breadboard-ui/src/input.ts
- packages/breadboard-ui/src/webcam.ts
> [breadboard-ui] Bring back Drawables!

- packages/breadboard/src/new/runner/runner.ts
- packages/breadboard/src/new/runner/scope.ts
- packages/breadboard/src/new/runner/types.ts
- packages/breadboard/tests/new/runner/abort-early-in-invokeOnce.ts
- packages/breadboard/tests/new/runner/pinning-scopes.ts
use it in invokeOnce to halt running after first output node
> [breadboard/new] add abort callback

- packages/breadboard-web/src/harness/index.ts
- packages/breadboard-web/src/harness/main-thread-harness.ts
- packages/breadboard-web/src/harness/proxy-server-harness.ts
- packages/breadboard-web/src/harness/receiver.ts
- packages/breadboard-web/src/harness/types.ts
- packages/breadboard-web/src/harness/worker-harness.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/remote/index.ts
- Adopt more flexible harness config format.
- Start using proxy server url in config.
- Remove harness 'type' distinction in config.
- Get rid of OldStyleHarnessConfig.
- Wean WorkerHarness.run off proxyNodes arg.
- Cleanup.
> [breadboard-web] Introduce HarnessConfig.

- packages/breadboard-ui/src/history-entry.ts
- packages/breadboard-ui/src/index.ts
- packages/breadboard-ui/src/ui-controller.ts
> [breadboard-ui] Move history entry to Lit Element

- packages/breadboard-ui/src/index.ts
- packages/breadboard-ui/src/load.ts
- packages/breadboard-ui/src/ui-controller.ts
> [breadboard-ui] Move load to Lit Element

- packages/breadboard-ui/src/index.ts
- packages/breadboard-ui/src/input-container.ts
- packages/breadboard-ui/src/progress.ts
- packages/breadboard-ui/src/result.ts
- packages/breadboard-ui/src/start.ts
- packages/breadboard-web/src/index.ts
> [breadboard-ui] Move more elements over to Lit Element

- packages/breadboard-web/src/harness/index.ts
- packages/breadboard-web/src/harness/local-harness.ts
- packages/breadboard-web/src/harness/receiver.ts
- packages/breadboard-web/src/harness/result.ts
- packages/breadboard-web/src/harness/secrets.ts
- packages/breadboard-web/src/harness/worker-harness.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard-web/tests/secrets.ts
- Teach WorkerHarness to handle secrets as events.
- Convert LocalHarness to use asyncGen.
- Tweak types a bit.
- Remove SecretHandler arg from createHarness.
- Share createOnSecret across harnesses.
> [breadboard-web] Emit secret as result."

- packages/breadboard/src/new/recipe-grammar/recipe.ts
- packages/breadboard/src/new/runner/node.ts
> [breadboard/new] remove nextNodeId export

- packages/breadboard/tests/new/recipe-grammar/lambdas.ts
- packages/breadboard/tests/new/recipe-grammar/serialize-and-run-with-old-runner.ts
Capturing a few corner-cases developers encountered.
> [breadboard/new] More tests for wiring

- packages/breadboard/docs/grammar/3-recipes-with-inputs.md
- packages/breadboard/docs/grammar/4-code-as-nodes.md
- packages/breadboard/docs/grammar/6-lambdas.md
- packages/breadboard/docs/grammar/TODO.md
e.g. introduce `code` and that recipe() no longer takes an async function.
> [breadboard/new] catching up docs with syntax changes

- packages/breadboard-web/src/index.ts
- packages/breadboard/src/harness/local-harness.ts
- packages/breadboard/src/harness/result.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/harness/worker-harness.ts
- packages/breadboard/src/remote/protocol.ts
- Tighten up the result types.
- Fix a bug I introduced in the last PR.
> [breadboard] Tighten up harness result types.

- packages/breadboard-ui/src/history-entry.ts
- packages/breadboard-ui/src/ui-controller.ts
- packages/llm-starter/src/nodes/run-javascript.ts
- packages/llm-starter/tests/convert-to-named-function.ts
- Loosen up convertToNamedFunction.
- Make history a tree.
> [breadboard-web] Render history as a tree of events.

- packages/breadboard-ui/src/board-list.ts
- packages/breadboard-ui/src/events.ts
- packages/breadboard-ui/src/index.ts
- packages/breadboard-ui/src/ui.ts
- packages/breadboard-web/src/index.ts
> [breadboard-ui/-web] Various small tweaks

- packages/breadboard-ui/src/ui.ts
> [breadboard-ui] Add node info back in

- package-lock.json
- packages/breadboard-cli/README.md
- packages/breadboard-cli/package.json
- packages/breadboard-cli/src/commands/boards/openapi.js
- packages/breadboard-cli/src/commands/import.ts
- packages/breadboard-cli/src/index.ts
- packages/breadboard-web/public/graphs/board-caller.json
`npx breadboard import <url to YAML or JSON Open API spec> -o ./`. It will spit out a set of boards for each API entry point.
> [breadboard-cli] Add the ability to import an Open API spec 

- packages/breadboard-ui/src/history-entry.ts
- packages/breadboard-ui/src/index.ts
- packages/breadboard-ui/src/json-tree.ts
- packages/breadboard-web/public/styles/global.css
I added a little JSON "renderer" so that we can expand and collapse JSON responses. I've rolled it into the history entries for now, but I'll add it elsewhere in time.
> [breadboard-ui] Add nicer JSON view ✨ 

- packages/breadboard-ui/src/ui.ts
I noticed that we have similar logic for both inserting and updating `nodestart` & `nodeend` entries in the history. This just tidies things up a bit so they have a unified approach. It also paves the way for some UI updates I'm cooking up... 😄
> [breadboard-ui] Tweak find & update logic

- packages/breadboard/src/remote/http.ts
- packages/breadboard/src/remote/proxy.ts
- packages/breadboard/src/stream.ts
- packages/breadboard/tests/remote/http.ts
- packages/breadboard/tests/remote/proxy.ts
- packages/breadboard/tests/stream.ts
- Add utils for parsing/stringifying StreamCapability.
- Teach HTTP transports to handle streams themselves.
- Teach portToStreams to find streams properly.
- Add a worker + stream test.
> [breadboard] Port stream-handling from Proxy to transport.

- packages/breadboard/src/stream.ts
- packages/breadboard/src/worker/controller.ts
- packages/breadboard/src/worker/worker-runtime.ts
- packages/node-nursery-web/src/nodes/transform-stream.ts
- Fix streaming. Sadly, stream transformers won't sent back diagnostics.
- Only transfer streams once.
> [breadboard] Fix various streaming boogers.

- packages/breadboard-ui/src/history-tree.ts
- packages/breadboard-ui/src/index.ts
- packages/breadboard-ui/src/types.ts
- packages/breadboard-ui/src/ui.ts
- packages/breadboard-web/public/styles/global.css
This tidies up the UI for the history, with some expand-collapse functionality and the ability to bring up the details as a JSON tree view.
> [breadboard-ui/-web] Overhaul the history log

- packages/breadboard-ui/src/history-tree.ts
Noticed that nested histories aren't that clear. Made some minor tweaks to account for it, but I suspect we'll need to revisit it at some stage.
> [breadboard-ui] Tweak to History Tree

- package-lock.json
- packages/breadboard-ui/src/history-tree.ts
Includes a passing update to the `package-lock.json`, which seems to be a little out of date at this point.
> [breadboard-ui] Enable Esc key for details

- packages/breadboard-cli/package.json
Seeing if this removes some of the flakiness from the build.
> [breadboard-cli] Update core-kit and llm-starter deps

- package-lock.json
- packages/breadboard-cli/package.json
Didn't add the deps in for `wireit` to know what it's doing.
> [breadboard-cli] fixing flakey build

- packages/breadboard-ui/src/history-tree.ts
- packages/breadboard-web/src/index.ts
This PR adds the "initiator" for a given node to this history list. This means you can see what "contains" the given node, which I hope helps with subgraphs a little.
> [breadboard-ui/-web] Add initiator

- packages/breadboard-ui/src/history-tree.ts
- packages/breadboard-ui/src/ui.ts
I thought it would be nice to be able to drag the divider between the top & bottom parts of the UI... so that's what this PR adds.
> [breadboard-ui/-web] Add resize ability

- packages/breadboard-ui/src/ui.ts
This PR makes @dglazkov happier ✨
> [breadboard-web] Support portrait orientation

- packages/breadboard-web/src/index.ts
- packages/breadboard-web/src/worker.ts
- packages/breadboard/src/harness/worker-harness.ts
- packages/breadboard/src/remote/protocol.ts
- packages/breadboard/src/remote/run.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/src/stream.ts
- packages/breadboard/src/types.ts
- packages/breadboard/src/worker/worker-runtime.ts
- packages/breadboard/tests/stream.ts
- Teach 'streamsToAsyncIterable' to start conversation.
- Switch RunClient to use 'streamsToAsyncIterable'.
- Switch harness over to use RunServer/Client.
- Plumb 'diagnostics' flag to the server.
> [breadboard] Switch harness to use RunServer/RunClient machinery.

- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/harness/worker-harness.ts
- packages/breadboard/src/remote/protocol.ts
- packages/breadboard/src/remote/run.ts
- packages/breadboard/src/run.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/src/serialization.ts
- packages/breadboard/src/types.ts
- packages/breadboard/tests/run.ts
- Extracted serialization bits into own file.
- Start passing state with nodestart.
- Plumb state through.
> [breadboard] Plumb state through for `nodestart`.

- packages/breadboard-ui/src/ui.ts
I was using the wrong ID to look up data from the state 😬 – this PR fixes that oversight.
> [breadboard-ui] Fix data lookup bug

- packages/breadboard-ui/src/input.ts
- packages/breadboard-ui/src/ui.ts
- packages/breadboard-ui/src/utils/index.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/types.ts
This does some pretty sizeable changes to the UI around inputs. In particular it attempts to render inputs & secrets based on whichever messages have come in. This should pave the way for us to traverse the messages we've received and for the UI to update accordingly.
I'll land this as-is, but there may be wrinkles that need to be ironed out!
> [breadboard-ui] Make inputs based on state

- packages/breadboard-ui/src/input.ts
- packages/breadboard-ui/src/ui.ts
It was getting a bit tricky to see which input node fields belonged to, so this PR just adds a slight visual tweak so they get grouped up by node.
> [breadboard-ui] Put borders around input groups

- packages/breadboard-ui/src/events.ts
- packages/breadboard-ui/src/index.ts
- packages/breadboard-ui/src/input-list.ts
- packages/breadboard-ui/src/input.ts
- packages/breadboard-ui/src/ui.ts
The UI controller is getting fairly large now, so I thought I'd at least move the input list to its own dedicated element. I've also added an extra feature that allows folks to toggle whether or not they see all inputs, or only those that required user interaction.
> [breadboard-ui] Move input list to dedicated element

- packages/breadboard-ui/src/events.ts
- packages/breadboard-ui/src/history-tree.ts
- packages/breadboard-ui/src/index.ts
- packages/breadboard-ui/src/input-list.ts
- packages/breadboard-ui/src/output-list.ts
- packages/breadboard-ui/src/traversal-controls.ts
- packages/breadboard-ui/src/types.ts
- packages/breadboard-ui/src/ui.ts
- packages/breadboard-web/public/styles/global.css
- packages/breadboard-web/public/third_party/icons/before.svg
- packages/breadboard-web/public/third_party/icons/next.svg
- packages/breadboard-web/src/index.ts
Because that's a fun thing to have!
> [breadboard-ui/-web] Add basic traversal controls

- packages/breadboard/src/new/recipe-grammar/recipe.ts
- packages/website/package.json
- packages/website/src/docs/concepts.md
- packages/website/src/docs/getting-started.md
- packages/website/src/js/pages/docs.ts
Adds a "getting started" page to the website skeleton.
Also fixes a typo in the new grammar, and fixes a race condition in the website build config.
> [website] Add a getting started page

- packages/breadboard-ui/src/input.ts
- packages/breadboard-web/docs/graphs/agent.md
- packages/breadboard-web/public/graphs/agent.json
- packages/breadboard-web/src/boards/agent.ts
- packages/breadboard/src/new/recipe-grammar/types.ts
- packages/breadboard/src/new/recipe-grammar/value.ts
- Declare input types more pretty.
- Make multiline format work.
- Improve agent a bit.
> [breadboard] Support format (for multiline) for new syntax.

- packages/breadboard-ui/src/input.ts
- packages/breadboard-web/src/config.ts
- packages/breadboard-web/src/worker.ts
- packages/breadboard/src/harness/index.ts
- packages/breadboard/src/harness/serve.ts
- Implement `serve` harness API.
- Add documentation.
> [breadboard/harness] Implement `serve` harness API.

- packages/breadboard-web/src/config.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/harness/local-harness.ts
- packages/breadboard/src/harness/serve.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/harness/worker-harness.ts
- Expose 'diagnostics' flag on ServeConfig.
- Clean up the use of HarnessRun.
- Remove 'HarnessRun' altogether.
- Remove 'load' method from 'Harness'.
- Clean up 'WorkerHarness' a bit.
> [breadboard/harness] Remove 'load' method from 'Harness'.

- packages/breadboard-ui/src/json-tree.ts
> [breadboard-ui] Add JSON copy button

- packages/breadboard-ui/src/input.ts
> [breadboard-ui] Tweak JSON Tree

- packages/breadboard-web/docs/graphs/agent.md
- packages/breadboard-web/docs/graphs/json-agent.md
- packages/breadboard-web/docs/graphs/team-builder.md
- packages/breadboard-web/public/graphs/agent.json
- packages/breadboard-web/public/graphs/gemini-generator.json
- packages/breadboard-web/public/graphs/json-agent.json
- packages/breadboard-web/public/graphs/team-builder.json
- packages/breadboard-web/src/boards/agent.ts
- packages/breadboard-web/src/boards/gemini-generator.ts
- packages/breadboard-web/src/boards/json-agent.ts
- packages/breadboard-web/src/boards/team-builder.ts
- Make team builder do some work.
- Some whitespace changes.
> [breadboard-web] Give Team Builder workflow chops.

- packages/breadboard-ui/src/timeline-controls.ts
- packages/breadboard-ui/src/ui.ts
Some of the timelines are rather lengthy - this adds a small UI tweak/option to allow for narrower timelines when desired.
> [breadboard-ui] Support narrower timeline

- packages/breadboard-web/preview.html
- packages/breadboard-web/public/styles/preview.css
- packages/breadboard-web/src/index.ts
- packages/breadboard-web/src/preview.ts
- packages/breadboard-web/vite.config.ts
This adds a relatively unstyled preview. Next stop is to make it look a little nicer.
> [breadboard-web] Add basic preview

- packages/breadboard-ui/src/elements/input/input.ts
- packages/breadboard-web/src/preview.ts
> [breadboard-web] Add a few more styles to the Preview

- packages/breadboard-web/docs/graphs/best-of-n.md
- packages/breadboard-web/public/graphs/best-of-n.json
- packages/breadboard-web/public/graphs/data-board.json
- packages/breadboard-web/public/graphs/json-agent.json
- packages/breadboard-web/public/local-boards.json
- packages/breadboard-web/src/boards/best-of-n.ts
- packages/breadboard-web/src/boards/data-board.ts
- packages/breadboard-web/src/boards/json-agent.ts
- Improve json agent a bit and use 'defaults' pattern for shared params.
- Add Best of N board.
> [breadboard-web] Add a few more interesting agenty boards.

- package.json
- packages/breadboard-cli/package.json
- packages/breadboard-web/src/preview.ts
> [breadboard-web] Add a little history read-out to the Preview

- packages/breadboard-web/src/index.ts
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/harness/secrets.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/remote/protocol.ts
- packages/breadboard/src/remote/proxy.ts
- packages/breadboard/src/remote/run.ts
- packages/breadboard/src/run.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/src/timestamp.ts
- packages/breadboard/src/types.ts
- packages/breadboard/tests/remote/transport.ts
- Plumb timestamp for all run results.
- Add timestamp.ts.
> [breadboard] Timestamp on emitted events."

- packages/breadboard-web/docs/graphs/blank.md
- packages/breadboard-web/public/graphs/agent.json
- packages/breadboard-web/public/graphs/blank.json
- packages/breadboard-web/public/local-boards.json
- packages/breadboard-web/src/boards/agent.ts
- packages/breadboard-web/src/boards/blank.ts
- packages/breadboard/docs/fodder/happy-path.md
- Tweak Agent board to use destructuring
- Add blank board.
- Add happy path sketch.
> [breadboard] Happy path sketch.

- packages/breadboard-cli/src/commands/lib/loaders/json.ts
- packages/breadboard-server/src/server.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard-web/src/new/cli.ts
- packages/breadboard-web/src/preview.ts
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/harness/run.ts
- packages/breadboard/src/harness/serve.ts
- packages/breadboard/src/harness/url.ts
- packages/breadboard/src/kits/graph-to-kit.ts
- packages/breadboard/src/loader.ts
- packages/breadboard/src/new/runner/runner.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/src/types.ts
- packages/breadboard/tests/helpers/_test-kit.ts
- packages/core-kit/src/nodes/import.ts
- packages/core-kit/src/nodes/include.ts
- packages/core-kit/src/nodes/invoke.ts
- packages/core-kit/tests/invoke.ts
- packages/graph-playground/src/index.ts
- Teach harness about base URLs.
- Fix all the build errors.
- Ensure that invoke supplies the right base URL.
- Fix jsdoc comments
> [breadboard] Plumb `base` URL for harness.

- packages/breadboard-python/README.md
- packages/breadboard-python/src/chat_gpt_3_5_turbo.py
- packages/breadboard-python/src/import_node.py
- packages/breadboard-python/src/main.py
Adds the breadboard-python package, which allows for breadboards to be defined in Python.
> Add breadboard-python package

- packages/breadboard-web/docs/graphs/ad-writer.md
- packages/breadboard-web/docs/graphs/best-of-n.md
- packages/breadboard-web/docs/graphs/data-board.md
- packages/breadboard-web/public/graphs/ad-writer.json
- packages/breadboard-web/public/graphs/agent.json
- packages/breadboard-web/public/graphs/best-of-n.json
- packages/breadboard-web/public/graphs/data-board.json
- packages/breadboard-web/public/graphs/json-agent.json
- packages/breadboard-web/public/local-boards.json
- packages/breadboard-web/src/boards/ad-writer.ts
- packages/breadboard-web/src/boards/agent.ts
- packages/breadboard-web/src/boards/best-of-n.ts
- packages/breadboard-web/src/boards/data-board.ts
- packages/breadboard-web/src/boards/json-agent.ts
- packages/json-kit/src/nodes/schemish.ts
- packages/json-kit/tests/schemish.ts
- Make generators and schema optional.
- Teach schemish to handle empty schema.
- make schema optional for realz.
- Make data-board the invocation of best of n.
> [breadboard-web] Play some more with large boards.

- package-lock.json
- packages/breadboard-extension/README.md
- packages/breadboard-extension/build.mjs
- packages/breadboard-extension/package.json
- packages/breadboard-extension/src/extension.ts
- packages/breadboard-extension/src/renderer.ts
- packages/breadboard/src/loader.ts
Cmd/Ctrl + Shift + P and choose "Breadboard: Render Board" ✨
> [breadboard-extension] Add support for rendering graphs

- .changeset/rotten-zoos-end.md
- packages/breadboard-extension/package.json
- packages/breadboard-extension/src/breadboard-debug-runtime.ts
- packages/breadboard-extension/src/breadboard-loader.ts
> [breadboard-extension] Support JS boards

- .changeset/proud-bears-tell.md
- packages/breadboard-ui/src/elements/output/error.ts
- packages/breadboard-ui/src/elements/output/output-list/output-list.ts
I think should make some headway on #461
> [breadboard-ui] Show errors in outputs list

- packages/breadboard-ui/src/elements/input/input-list/input-list.ts
- packages/breadboard-web/src/index.ts
> [breadboard-ui] Add download log button

- .changeset/gold-cougars-dress.md
- packages/breadboard-ui/src/elements/input/input-list/input-list.ts
- Dirty hack to make "Continue" button work.
- docs(changeset): Make "Continue" work for multi-turn (dirty hack)
> hack input

- .changeset/bright-guests-clean.md
- packages/breadboard-ui/src/elements/input/input-list/input-list.ts
- packages/breadboard-ui/src/elements/input/input.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.styles.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-ui/src/utils/index.ts
- packages/breadboard-web/src/preview.ts
> [breadboard-ui] Fix continue button issues

- packages/breadboard-python/README.md
- packages/breadboard-python/src/chat_gpt_3_5_turbo.py
- packages/breadboard-python/src/import_node.py
- packages/breadboard-python/src/main.py
> Add ability to import kits to breadboard-python

- .changeset/light-beers-crash.md
- .changeset/nervous-apricots-argue.md
- .changeset/quick-islands-cover.md
- packages/breadboard-cli/CHANGELOG.md
- packages/breadboard-cli/package.json
- packages/create-breadboard/CHANGELOG.md
- packages/create-breadboard/package.json
- packages/hello-world/CHANGELOG.md
- packages/hello-world/package.json
Releases:
@google-labs/create-breadboard@1.0.1
@google-labs/breadboard-cli@0.3.0
@google-labs/breadboard-hello-world@1.0.1
[skip ci]
> RELEASING: Releasing 3 package(s)

- .changeset/witty-timers-juggle.md
- package-lock.json
- packages/breadboard-cli/CHANGELOG.md
- packages/breadboard-cli/package.json
- packages/hello-world/CHANGELOG.md
- packages/hello-world/package.json
Releases:
@google-labs/breadboard-cli@0.3.2
@google-labs/breadboard-hello-world@1.0.3
[skip ci]
> RELEASING: Releasing 2 package(s)

- packages/website/src/static/docs.css
> [website] Unbold header anchors

- .changeset/old-pandas-scream.md
- packages/breadboard/package.json
- packages/breadboard/rollup.config.js
- packages/breadboard/src/runner.ts
- packages/breadboard/src/types.ts
- packages/breadboard/tests/board.ts
- packages/breadboard/tsconfig.json
dependant on https://github.com/breadboard-ai/breadboard/pull/581
> Add schema to serialised boards

- .changeset/breezy-rules-crash.md
- packages/breadboard-ui/src/elements/output/error.ts
- packages/breadboard-web/src/preview.ts
- Display errors that are objects.
- docs(changeset): Display structured errors in preview/debug views.
> error display

- packages/breadboard-web/public/graphs/healer.json
- packages/breadboard-web/public/graphs/json-generator.json
- packages/breadboard-web/public/graphs/json-validator.json
- packages/breadboard-web/public/graphs/list-files.json
- packages/breadboard-web/public/graphs/retry.json
Looks like the board JSON now get a schema. These are the files that regenerated when I ran `npm run dev`.
> [breadboard-web] Commit in changed JSON

- packages/website/src/_includes/docs.njk
- packages/website/src/_includes/navigation.njk
- packages/website/src/docs/concepts.md
- packages/website/src/docs/getting-started.md
- packages/website/src/docs/happy-path.md
- packages/website/src/docs/index.md
- packages/website/src/static/common.css
- packages/website/src/static/docs.css
> [website] Add doc listing

- .changeset/good-ways-wonder.md
- packages/breadboard-cli/src/commands/debug.ts
> [breadboard-cli] Reenable cleanUrls for root

- packages/website/src/static/docs.css
TIL about `scroll-margin-top` – wonderful stuff! ✨
> [website] Add some scroll margin

- packages/website/filter-toc.cjs
It wasn't working with punctuation. Now it does.
> [website] Tweak TOC

- .changeset/cyan-spies-roll.md
- .changeset/eight-insects-stare.md
- .changeset/funny-months-design.md
- .changeset/healthy-jokes-destroy.md
- packages/breadboard-web/CHANGELOG.md
- packages/breadboard-web/package.json
- packages/breadboard/CHANGELOG.md
- packages/breadboard/package.json
- packages/core-kit/CHANGELOG.md
- packages/core-kit/package.json
- packages/gemini-kit/CHANGELOG.md
- packages/gemini-kit/package.json
- packages/hello-world/CHANGELOG.md
- packages/hello-world/package.json
- packages/template-kit/CHANGELOG.md
- packages/template-kit/package.json
Releases:
@google-labs/template-kit@0.1.4
@google-labs/breadboard-hello-world@1.2.0
@google-labs/gemini-kit@0.1.0
@google-labs/core-kit@0.2.2
@google-labs/breadboard-web@1.1.0
@google-labs/breadboard@0.10.1
> RELEASING: Releasing 6 package(s)

- .changeset/few-ties-yell.md
- packages/gemini-kit/package.json
- Make Gemini Kit public
- docs(changeset): Make Gemini Kit public.
> make gemini public

- .changeset/beige-cobras-complain.md
- package-lock.json
- packages/breadboard-cli/package.json
- packages/create-breadboard-kit/package.json
- packages/create-breadboard/package.json
may resolve #633 needs deploying to test
> update dependencies for `npm exec` usage

- .changeset/beige-cobras-complain.md
- .changeset/blue-boats-rule.md
- packages/breadboard-cli/CHANGELOG.md
- packages/breadboard-cli/package.json
- packages/breadboard-web/CHANGELOG.md
- packages/breadboard-web/package.json
- packages/create-breadboard-kit/CHANGELOG.md
- packages/create-breadboard-kit/package.json
- packages/create-breadboard/CHANGELOG.md
- packages/create-breadboard/package.json
- packages/gemini-kit/package.json
- packages/hello-world/CHANGELOG.md
- packages/hello-world/package.json
Releases:
@google-labs/create-breadboard-kit@0.0.3
@google-labs/create-breadboard@1.0.2
@google-labs/breadboard-cli@0.4.1
@google-labs/breadboard-web@1.1.1
@google-labs/breadboard-hello-world@1.2.2
> RELEASING: Releasing 5 package(s)

- packages/website/src/_includes/docs.njk
- packages/website/src/static/docs.css
I noticed that on smaller screens the WIP banner didn't look quite right.
> [website] Fix WIP banner on mobile

- packages/breadboard-cli/vite.config.ts
This commit adds the `optimizeDeps` configuration to the `vite.config.ts` file. The `include` property specifies a list of dependencies that should be included in the optimized build.
continue tackling #633
> Add optimizeDeps configuration to vite.config.ts

- packages/breadboard/tests/helpers/_test-transport.ts
I could have sworn I fixed this
> add missing await

- .changeset/metal-elephants-check.md
- .changeset/thirty-avocados-breathe.md
- packages/agent-kit/src/boards/instruction.ts
- packages/agent-kit/src/boards/worker.ts
- packages/agent-kit/src/samples/summarizer.ts
- packages/breadboard-web/src/boards/ask-user.ts
- First sketch of the summarizer.
- Reshape worker to add instruction input.
- Sketch out a summarizer workflow
- Update input title.
- docs(changeset): Add licensing headers
- docs(changeset): Improve 'Worker' to take instructions and accept string as context.
> summarizer

- .changeset/perfect-socks-knock.md
- package-lock.json
- package.json
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-web/src/index.ts
Working on visual editing. This adds LiteGraph to proceedings, and paves the way for interacting with the graph within the debugger directly.
> [breadboard-ui] Add LiteGraph editor

- packages/breadboard-python/src/breadboard_python/accumulating_context.py
- packages/breadboard-python/src/breadboard_python/chat_gpt_3_5_turbo.py
- packages/breadboard-python/src/breadboard_python/import_node.py
- packages/breadboard-python/src/breadboard_python/main.py
> Breadboard python

- .github/workflows/labs-prototypes-ci.yml
quick temporary fix to https://github.com/breadboard-ai/breadboard/issues/629
> disable wireit cache on PR pipelines

- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-web/src/index.ts
When there's a blank board you can now drag nodes into the editor.
> [breadboard-ui] Teach editor how create new nodes

- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-web/src/index.ts
Now you can drop / double click on nodes and get a WIP configurator
> [breadboard-ui] Re-teach editor about updating configurations

- .changeset/forty-students-return.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-web/src/index.ts
I'll leave Mermaid in for the time being, just in case there are issues.
> [breadboard-ui] Promote editor to main

- .changeset/angry-boxes-jump.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-web/src/index.ts
Still a few rough edges, but this is now functional.
> [breadboard-ui] Add edge creation, deletion, and changing

- .changeset/ninety-items-fly.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-web/public/graphs/ad-writer.json
- packages/breadboard-web/public/graphs/agent-chain.json
- packages/breadboard-web/public/graphs/chat-bot-2.json
- packages/breadboard-web/src/boards/ad-writer.ts
- packages/breadboard-web/src/boards/agent-chain.ts
- packages/breadboard-web/src/boards/chat-bot-2.ts
- packages/breadboard/src/editor/graph.ts
- packages/breadboard/src/editor/types.ts
- packages/breadboard/src/inspector/node.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/src/new/grammar/node.ts
- packages/breadboard/src/new/runner/node.ts
- packages/breadboard/src/new/runner/types.ts
- packages/breadboard/tests/editor/metadata.ts
- packages/breadboard/tests/inspector/node.ts
- packages/schema/src/graph.ts
- packages/website/src/docs/editor.md
- packages/website/src/docs/happy-path.md
- packages/website/src/docs/inspector.md
- packages/website/src/docs/python.md
- **Add `NodeMetadata` to `NodeDescriptor`.**
- **Add `can/changeMetadata` to editor API.**
- **Add support for `title()` in `InspectableNode`.**
- **Add support for `NodeMetadata` in syntax.**
- **Plumb the title through to graph renderer.**
- **Start using `title()` in editor**
- **Update docs.**
- **Update a couple of boards to use `$metadata`.**
- **docs(changeset): Introduce `NodeMetadata`.**
- **Mention `$metadata` in happy path.**
> node metadata

- .changeset/soft-socks-brake.md
- packages/breadboard-ui/src/elements/input/input.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-ui/src/utils/highlights.ts
- **Make boolean properties bind correctly.**
- **Implement node highlight helper.**
- **docs(changeset): Make node highlighting reliable.**
> run graph editor

- .changeset/silent-flowers-applaud.md
- packages/breadboard/src/inspector/ports.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/tests/inspector/ports.ts
- packages/website/src/docs/inspector.md
- **Introduce `InspectablePort.edges()` method.**
- **Document `edges`.**
- **docs(changeset): Introduce the `InspectablePort.edges` property.**
> port edges

- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/elements.ts
- packages/breadboard-ui/src/elements/splitter/splitter.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.styles.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
It has bothered me for some time that I could resize between various panels on the right side of the debugger, but _not_ the graph and right side overall. This fixes that particular frustration.
> [breadboard-ui] Teach UI how to resize between graph and other panels

- packages/breadboard-ui/src/elements/timeline-controls/timeline-controls.ts
Random semicolon causing issues. 👋🏻 byyyyeee!
> [breadboard-ui] Remove semicolon

- packages/website/src/docs/getting-started.md
- packages/website/src/docs/io.md
+ Cleaning up the ports documentation.
+ Ordering so getting started is at the top.
> Updating happy path docs

- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
- packages/breadboard-ui/src/elements/editor/types.ts
I noticed some issues when the configuration of nodes changes; this PR fixes those issues.
> [breadboard-ui] Fix editor render bugs

- packages/breadboard-web/public/graphs/accumulating-context-python.json
- packages/breadboard-web/public/graphs/math-python.json
- packages/breadboard-web/public/local-boards.json
I think maybe I deleted them by accident in a previous PR. Anyway, they're back!
> [breadboard-web] Check in missing boards

- .changeset/few-schools-notice.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-web/public/graphs/accumulating-context-python.json
- packages/breadboard-web/public/graphs/math-python.json
> [breadboard-ui] Ensure we refresh the graph

- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/elements.ts
- packages/breadboard-ui/src/elements/history-tree/history-tree.styles.ts
- packages/breadboard-ui/src/elements/schema-editor/schema-editor.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.styles.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-web/public/graphs/accumulating-context-python.json
- packages/breadboard-web/public/graphs/math-python.json
Still a ways to go, but this gets us a bit nearer.
> [breadboard-ui] Teach editor how to edit schemas

- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
- packages/breadboard-ui/src/elements/schema-editor/schema-editor.ts
- packages/breadboard/src/inspector/node.ts
Includes a workaround for #845
> [breadboard-ui] Minor fixes to graph & node editing

- packages/breadboard-ui/src/elements/editor/editor.ts
I noticed that when we drag a new node on we automatically populate the properties with the examples/defaults, and this mistakenly gives the impression that the node is configured. This PR changes it so that you have to click the "use defaults" button for the form to be populated with the info. The additional benefit of this is that you can reset the configuration at any time with this, too.
> [breadboard-ui] Add "use defaults" button

- .changeset/silent-phones-complain.md
- packages/json-kit/src/nodes/validate-json.ts
- packages/json-kit/tests/validate-json.ts
- **Strip stuff outside of the json markdown block.**
- **docs(changeset): Strip out stuff outside of the markdown code block**
> better validate json

- .changeset/eight-knives-do.md
- packages/breadboard-web/public/graphs/agent-chain.json
- packages/breadboard-web/public/graphs/best-of-n.json
- packages/breadboard-web/public/graphs/board-caller.json
- packages/breadboard-web/public/graphs/json-agent.json
- packages/breadboard-web/public/graphs/summarize-single-iteration.json
- packages/breadboard-web/public/graphs/summarizer.json
- packages/breadboard-web/public/graphs/team-builder.json
- packages/core-kit/src/nodes/map.ts
- packages/core-kit/src/nodes/reduce.ts
- packages/core-kit/tests/map.ts
- packages/core-kit/tests/reduce.ts
- packages/json-kit/src/nodes/schemish.ts
- packages/json-kit/src/nodes/validate-json.ts
- packages/json-kit/src/nodes/xml-to-json.ts
- **Add describer for `validateJson`.**
- **Add describer to `schemish`.**
- **Tweak describer on `xmlToJson`.**
- **Add describer for `map`.**
- **Add describer for `reduce`.**
- **Update boards that changed with describer tweaks.**
- **docs(changeset): Add describers for a few nodes.**
> describers

- .changeset/young-moons-trade.md
- packages/breadboard-web/public/graphs/accumulating-context-python.json
- packages/breadboard-web/public/graphs/math-python.json
- packages/breadboard/src/editor/graph.ts
- packages/breadboard/src/editor/types.ts
- packages/breadboard/tests/editor/graph.ts
- **Add naive implementation (remove + add)**
- **Added a test.**
- **Leave edge identity intact.**
- **docs(changeset): Introduce `canChangeEdge` and `changEdge` to the Editor API.**
> change edge

- packages/breadboard-cli/package.json
- https://github.com/breadboard-ai/breadboard/issues/928
> resolve issue introduced by npm version bump

- .changeset/long-bags-play.md
- packages/breadboard/src/kits/graph-to-kit.ts
Teaches Breadboard to be able to describe Kits when they are Graphs.
> [breadboard] Add GraphToKitAdapter - describer

- .changeset/tidy-ads-rest.md
- packages/breadboard-cli/src/bundle/worker.ts
- packages/breadboard-cli/src/debugger/worker.ts
- packages/breadboard-web/src/config.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard-web/src/utils/kit-loader.ts
- packages/breadboard-web/src/worker.ts
- packages/breadboard/src/harness/serve.ts
- **Fix race condition in worker.**
- **docs(changeset): Fix a race condition in Worker transport.**
> fix race condition

- .changeset/spotty-dryers-punch.md
- packages/breadboard-cli/src/commands/lib/utils.ts
- packages/breadboard-web/public/kits.json
- packages/breadboard-web/src/config.ts
- packages/breadboard-web/src/core-kit.ts
- packages/breadboard-web/src/json-kit.ts
- packages/breadboard-web/src/node-nursery-web-kit.ts
- packages/breadboard-web/src/template-kit.ts
- packages/breadboard-web/vite.config.ts
- **Start loading Core Kit dynamically.**
- **Start loading JSON Kit dynamically.**
- **Start loading Template Kit dynamically.**
- **Start loading Node Nursery Web dynamically.**
- **docs(changeset): Start loading all heavy kits dynamically.**
> dynamic core kit

- packages/breadboard-ui/src/elements/editor/editor.ts
I noticed that we were mistakenly assuming the `headers` for a `fetch` node was a schema object. I've resolved that with this PR, but it does highlight the need for a dedicated object/array editor.
> [breadboard-ui] Handles objects slightly better

- .changeset/fair-poems-rhyme.md
- packages/agent-kit/package.json
- packages/breadboard-cli/src/commands/lib/debug-routes/board.ts
- packages/breadboard-cli/src/commands/lib/debug-server.ts
- packages/breadboard-cli/src/commands/lib/utils.ts
- packages/breadboard-web/package.json
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard-web/public/kits.json
- packages/breadboard-web/src/config.ts
- packages/breadboard-web/src/copy-light-kits.ts
- packages/breadboard-web/src/utils/kit-loader.ts
- **Write `copy-light-kits` and start loading agent kit dynamically.**
- **Update wireit deps.**
- **Start using `agent.kit.json` in `breadboard debug`.**
- **Make sure it loads correctly.**
- **Re-teach `debug` to handle `*.ts` files.**
- **docs(changeset): Load agent-kit via manifest dynamically.**
> dynamic agent kit

- packages/website/filter-toc.cjs
> [website] Fix the TOC

- packages/breadboard-ui/src/elements/board-list/board-list.ts
- packages/breadboard-web/src/index.ts
> [breadboard-web] Fix URL copying

- .changeset/late-roses-peel.md
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-node.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
- packages/breadboard-ui/src/elements/elements.ts
- packages/breadboard-ui/src/elements/input/input-list/input-list.ts
- packages/breadboard-ui/src/elements/input/input.ts
- packages/breadboard-ui/src/elements/node-info/node-info.ts
- packages/breadboard-ui/src/elements/splitter/splitter.ts
- packages/breadboard-ui/src/elements/switcher/switcher.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.styles.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-web/public/styles/global.css
- packages/breadboard-web/public/third_party/icons/arrow-back.svg
- packages/breadboard-web/src/index.ts
This is an update to the UI that simplifies it somewhat, both in terms of aesthetics and functionality that isn't used very much.
> [breadboard-ui] Simplify the UI

- .changeset/green-crews-grin.md
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/inspector/event.ts
- packages/breadboard/src/inspector/path-registry.ts
- packages/breadboard/src/remote/run.ts
- packages/breadboard/src/types.ts
- **Formalize the sidecars a bit more.**
- **Use string keys for sidecar tracker.**
- **Support bubbling outputs.**
- **Clean up secrets after they are entered.**
- **docs(changeset): Improved run inspector API to mostly work.**
> bubbling outputs

- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-ui/src/elements/input/input.ts
- packages/breadboard-ui/src/elements/input/webcam/webcam.ts
- packages/breadboard-ui/src/elements/json-tree/json-tree.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
> [breadboard-ui/-web] Support image inputs in the Activity Log

- .github/CODEOWNERS
- .gitignore
- package-lock.json
- packages/build/.eslintrc
- packages/build/CHANGELOG.md
- packages/build/README.md
- packages/build/package.json
- packages/build/src/define.ts
- packages/build/src/index.ts
- packages/build/src/test/define_test.ts
- packages/build/tsconfig.json
Start of https://github.com/breadboard-ai/breadboard/issues/1006
> Add new skeleton for @breadboard-ai/build package

- packages/breadboard/src/editor/types.ts
relates to https://github.com/breadboard-ai/breadboard/issues/941
> Update import path for InspectableGraph and InspectableGraphOptions.

- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- resolves https://github.com/breadboard-ai/breadboard/issues/926
> Investigate default zoom event on UI

- .changeset/mighty-onions-glow.md
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-web/public/graphs/openai-dall-e.json
- packages/breadboard-web/src/boards/openai-dall-e.ts
- **Handle image URLs in activity-log.**
- **docs(changeset): Teach `bb-activity-log` to handle image URLs.**
> image urls

- .changeset/stupid-beds-eat.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/human.ts
- packages/agent-kit/src/boards/repeater.ts
- packages/agent-kit/src/boards/structured-worker.ts
- packages/agent-kit/src/boards/tool-worker.ts
- packages/agent-kit/src/boards/worker.ts
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard-web/public/graphs/openai-dall-e.json
- packages/breadboard-web/public/local-boards.json
- packages/breadboard-web/src/boards/openai-dall-e.ts
- **Add better metadata for agent kit.**
- **docs(changeset): Add better metadata for Agent Kit.**
> agent kit descriptions

- .changeset/beige-apricots-sparkle.md
- package-lock.json
- packages/team-kit/package.json
- **Export team kit correctly.**
- **docs(changeset): Correctly export team.kit.json**
> fix team kit

- .changeset/khaki-pants-drive.md
- packages/breadboard/src/editor/graph.ts
- packages/breadboard/tests/editor/graph.ts
- **Disallow creation of non-start to start edges.**
- **docs(changeset): Disallow creation of non-star to star edges.**
> non star to star

- .changeset/young-goats-hope.md
- packages/breadboard-web/public/graphs/ad-writer-2.json
- packages/breadboard-web/src/boards/ad-writer-2.ts
- **Improve Ad Writer to write entire campaigns.**
- **docs(changeset): Update Ad Writer 2 to generate entire campaigns.**
> ad campaign writer

- .changeset/neat-berries-ring.md
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-ui/src/elements/board-list/board-list.ts
- packages/breadboard-ui/src/elements/editor/graph-node.ts
- packages/breadboard-web/public/styles/global.css
- packages/breadboard-web/public/styles/preview.css
There's now a color palette for Breadboard, which I'm going to start using for future patches. For now this brings the colors into the styles and uses them in a couple of key places
> [breadboard-ui/-web] Consolidate colors

- packages/breadboard-ui/src/elements/editor/editor.ts
Fixes a bug I created with the file drop behaviour. cc @Mearman
> [breadboard-ui] Fix node drop

- .changeset/shy-impalas-reflect.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-web/src/index.ts
> [breadboard-ui/-web] Emit node location info on first render

- .changeset/mighty-kings-joke.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-web/src/file-storage/file-storage.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/harness/run.ts
- packages/breadboard/src/index.ts
- packages/breadboard/src/inspector/graph.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/src/loader.ts
- packages/breadboard/src/loader/index.ts
- packages/breadboard/src/loader/types.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/src/types.ts
- packages/core-kit/src/nodes/invoke.ts
- **Sketch out `GraphProvider` type and have `FileStorage` implement it.**
- **GraphLoader works!**
- **Introduce `GraphProviderCapabilities`.**
- **docs(changeset): Introduce `GraphProvider` and make it pluggable.**
> graph provider

- packages/build/src/board.ts
- packages/build/src/define.ts
- packages/build/src/definition-monomorphic.ts
- packages/build/src/definition-polymorphic.ts
- packages/build/src/definition.ts
- packages/build/src/index.ts
- packages/build/src/instance.ts
- packages/build/src/json-schema.ts
- packages/build/src/port.ts
- packages/build/src/test/board_test.ts
- packages/build/src/test/monomorphic-primary_test.ts
- packages/build/src/test/monomorphic_test.ts
- packages/build/src/test/polymorphic-primary_test.ts
- packages/build/src/test/polymorphic_test.ts
> [build] Refactor and support primary outputs on polymorphic nodes

- .changeset/stale-eagles-tie.md
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/harness/serve.ts
- packages/breadboard/src/kits/load.ts
- packages/breadboard/src/loader/index.ts
- packages/breadboard/src/loader/loader.ts
- packages/breadboard/src/loader/types.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/tests/inspector/describe.ts
- packages/breadboard/tests/inspector/traversal.ts
- packages/breadboard/tests/loader/loader.ts
- packages/core-kit/src/nodes/invoke.ts
- **Change `GraphLoader` to take a path and a context.**
- **Move path resolution logic to `Loader`.**
- **Minor touch-ups.**
- **Add comments to types.**
- **docs(changeset): Shift more URL-resolution logic into the Loader.**
> better loader

- packages/breadboard-web/src/index.ts
- packages/breadboard-web/src/preview-run.ts
First pass at this behavior. Hopefully it prevents the case where folks accidentally lose work because of not saving.
> [breadboard-web] Warn when a user might lose changes

- .changeset/grumpy-hats-scream.md
- packages/breadboard-cli/src/commands/lib/utils.ts
- **Use less intimidating URLs in debugger.**
- **docs(changeset): Use simpler URLs in debugger.**
> simpler debug urls

- packages/breadboard-ui/src/elements/splitter/splitter.ts
- packages/breadboard-web/index.html
- packages/breadboard-web/public/styles/global.css
Noticed that we were already really close with the UI on iOS devices, but that a few small tweaks were necessary. This PR tries to sort those minor issues out.
> [breadboard-ui/-web] Fix minor issues on iOS

- packages/breadboard-web/src/providers/file-system.ts
Just a tidy up PR so that we don't store a Map to FS handles, but rather individual entries.
> [breadboard-ui] Flatten File System Map

- packages/breadboard-web/public/graphs/open-alex-entity-search-list.json
- packages/breadboard-web/public/local-boards.json
- packages/breadboard-web/src/boards/open-alex-entity-search-list.ts
closes https://github.com/breadboard-ai/breadboard/issues/1149
> 1149 extract OpenAlex single query board for use in tool worker

- packages/agent-kit/agent.kit.json
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard-web/public/graphs/ad-writer-2.json
- packages/breadboard-web/public/graphs/ad-writer.json
- packages/breadboard-web/public/graphs/agent-chain.json
- packages/breadboard-web/public/graphs/chat-bot-2.json
- packages/breadboard-web/public/graphs/json-agent.json
- packages/breadboard-web/public/graphs/summarize-single-iteration.json
- packages/breadboard-web/public/graphs/summarizer.json
- packages/breadboard-web/public/graphs/team-builder.json
- packages/breadboard/src/new/grammar/value.ts
> Specify behavior on items of array not, array itself.

- .changeset/perfect-toes-act.md
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-ui/src/elements/input/input.ts
- packages/breadboard/src/inspector/event.ts
- packages/breadboard/src/inspector/path-registry.ts
- packages/breadboard/src/inspector/schemas.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/src/schema.ts
- packages/breadboard/tests/inspector/describe.ts
- packages/build/src/test/compatibility_test.ts
- **Introduce `InspectableNode` to `InspectableRun`.**
- **Remember your parents.**
- **docs(changeset): Teach `InspectableRunNodeEvent` about `InspectableNode`.**
> input schema

- packages/build/src/index.ts
- packages/build/src/internal/type-system/array.ts
- packages/build/src/test/type_test.ts
closes https://github.com/breadboard-ai/breadboard/issues/1198
> 1198 [build] Add array utility to type system

- .changeset/sweet-bugs-pretend.md
- packages/breadboard-ui/src/elements/switcher/switcher.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.styles.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-web/src/index.ts
> [breadboard-ui/-web] Inform a user when a board load fails

- .changeset/brave-beers-greet.md
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-ui/src/elements/node-info/array-editor.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
> [breadboard-ui] Re-teach Activity Log to show event information

- .changeset/nervous-drinks-kiss.md
- packages/breadboard-web/src/index.ts
> [breadboard-web] Redirect users when active board is deleted

- .changeset/shiny-dryers-allow.md
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard/src/inspector/event-manager.ts
- packages/breadboard/src/inspector/nested-run.ts
- packages/breadboard/src/inspector/run-node-event.ts
- packages/breadboard/src/inspector/run.ts
- packages/breadboard/src/inspector/types.ts
- packages/website/src/docs/inspector/run.md
- **Introduce `InspectableRun.getEventById`.**
- **docs(changeset): Introduce `InspectableRun.getEventById` method.**
> get event by id

- packages/build/src/internal/board/board.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/test/serialize_test.ts
- Add a check for unreachable outputs
- Make configuration serialization deterministic
- Fix some typing issues with board signature
> [build] More incremental serialize work

- .changeset/eight-sloths-invent.md
- packages/breadboard/src/inspector/graph.ts
- packages/breadboard/src/inspector/schemas.ts
- packages/breadboard/src/schema.ts
- packages/breadboard/tests/inspector/describe.ts
- packages/build/src/test/compatibility_test.ts
- packages/core-kit/src/nodes/invoke.ts
- **Add back star ports when describing a graph.**
- **Teach invoke to describe itself correctly when it has no board specified.**
- **docs(changeset): Teach invoke to be more accepting of uncertainty.**
> star wires again

- .changeset/twenty-buses-pretend.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/boards/human.json
- packages/agent-kit/boards/repeater.json
- packages/agent-kit/boards/structured-worker.json
- packages/agent-kit/boards/tool-worker.json
- packages/agent-kit/boards/worker.json
- packages/breadboard-cli/src/commands/lib/debug-routes/board.ts
- packages/breadboard-cli/src/commands/lib/debug-server.ts
- packages/breadboard-web/src/index.ts
- **Update schema versions on Agent Kit boards.**
- **Implement naive soft-reload.**
- **Remove warning.**
- **Only refresh when the changed board is selected.**
- **docs(changeset): Implement soft-reload**
> soft reload

- .changeset/quiet-pugs-hang.md
- packages/gemini-kit/src/boards/gemini-generator.ts
- **Add `gemini-1.5-pro-latest` to the list.**
- **docs(changeset): Add gemini-pro-1.5 to the list of models.**
> gemini pro 1.5

- .changeset/rude-chicken-whisper.md
- package-lock.json
- packages/breadboard-web/src/config.ts
- packages/breadboard-web/src/index.ts
- packages/node-proxy-server/functions/package.json
- packages/node-proxy-server/functions/src/config.ts
- packages/node-proxy-server/package.json
- **Update node proxy server to work again.**
- **docs(changeset): Update node proxy server machinery**
- **Remove spurious comment.**
> node proxy server

- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
> [breadboard-ui] Use pre-line for outputs

- .changeset/shy-colts-compare.md
- package-lock.json
- packages/breadboard-ui/package.json
- packages/breadboard-ui/src/directives/markdown.ts
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
> [breadboard-ui] Teach Activity Log to render markdown outputs

- .changeset/lemon-plants-end.md
- packages/breadboard-ui/src/elements/node-info/array-editor.ts
- packages/breadboard-ui/src/elements/node-info/node-info.ts
- packages/breadboard-ui/src/elements/node-info/schema-editor.ts
Including:
* Slightly improved add logic for the array editor.
* Improved validation of the configuration for objects/LLM Content.
* Support for `format` and `examples`.
> [breadboard-ui] Various node info improvements

- packages/build/src/test/type_test.ts
- closes https://github.com/breadboard-ai/breadboard/issues/1203
> 1203 add test cases for unknown types

- packages/build/src/test/type_test.ts
Merge issue between https://github.com/breadboard-ai/breadboard/pull/1231 and https://github.com/breadboard-ai/breadboard/pull/1204.
> [build] Fix build type check

- packages/breadboard-ui/src/elements/node-info/node-info.ts
> [breadboard-ui] Fix node config

- .changeset/stupid-tools-rest.md
- packages/breadboard-cli/src/commands/lib/debug-server.ts
- **Don't crash on TS errors in hot reload.**
- **docs(changeset): Don't crash on TS errors in hot reload.**
> no crash reload

- .changeset/green-buttons-obey.md
- package-lock.json
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- **Make markdown text selectable.**
- **docs(changeset): Make Markdown text selectable.**
> selectable markdown

- .changeset/rare-oranges-hide.md
- packages/agent-kit/agent.kit.json
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard-web/public/graphs/ad-writer-2.json
- packages/breadboard-web/public/graphs/agent-chain.json
- packages/breadboard-web/public/graphs/ask-user.json
- packages/breadboard-web/public/graphs/best-of-n.json
- packages/breadboard-web/public/graphs/drawable.json
- packages/breadboard-web/public/graphs/gemini-pro-vision.json
- packages/breadboard-web/public/graphs/mock-text-generator.json
- packages/breadboard-web/public/graphs/nager.date/is-today-public-holiday.json
- packages/breadboard-web/public/graphs/nager.date/long-weekend.json
- packages/breadboard-web/public/graphs/open-alex-entity-search-list.json
- packages/breadboard-web/public/graphs/openai-dall-e.json
- packages/breadboard-web/public/graphs/palm-text-generator.json
- packages/breadboard-web/public/graphs/summarizer.json
- packages/breadboard-web/public/graphs/text-generator.json
- packages/breadboard-web/public/graphs/tour-guide-writer.json
- packages/breadboard-web/public/graphs/webcam.json
- packages/breadboard/src/new/grammar/node.ts
- packages/breadboard/tests/new/grammar/board-as-code.ts
- **Use `runJavascript` directly in `code` block.**
- **docs(changeset): Use `runJavascript` directly in `code` block.**
- **Update tests.**
> just run javascript

- packages/build/README.md
- packages/build/src/test/placeholder_test.ts
Document placeholders and add a test to check that they must be resolved with a matching type.
> [build] Placeholder followup

- .changeset/nice-otters-tell.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/boards/human.json
- packages/agent-kit/boards/repeater.json
- packages/agent-kit/boards/structured-worker.json
- packages/agent-kit/boards/tool-worker.json
- packages/agent-kit/boards/worker.json
- packages/agent-kit/src/boards/human.ts
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard-web/public/graphs/chat-bot-2.json
- packages/breadboard-web/public/graphs/choices.json
- packages/breadboard-web/public/local-boards.json
- packages/breadboard-web/src/boards/choices.ts
- packages/breadboard/src/inspector/graph.ts
- packages/breadboard/src/inspector/node.ts
- packages/breadboard/src/inspector/schemas.ts
- packages/breadboard/src/schema.ts
- **Don't show bubbled outputs in graph describer.**
- **Early sketch of feedback.**
- **Make sure config is overridden by inputs when describing nodes with values.**
- **Sketch out actionRecognizer.**
- **A somewhat working rejection.**
- **First working voting feedback loop.**
- **Working with actual structured worker.**
- **Update wording in schema.**
- **Clip out `voteRequest`.**
- **docs(changeset): Early support for voting (yes/no) in Human node.**
> smarter human

- packages/core-kit/src/index.ts
- packages/core-kit/src/nodes/fetch.ts
> Add more outputs to fetch node including status code and computing json schema

- .changeset/mean-pots-wink.md
- packages/breadboard/src/inspector/graph.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/tests/inspector/subgraphs.ts
- packages/website/src/docs/inspector/graph.md
- **Sketch out the API.**
- **Add a unit test.**
- **Document the `graphs` API.**
- **docs(changeset): Add `InspectableGraph.graphs` API.**
> inspectable subgraphs

- .changeset/spotty-otters-rest.md
- packages/breadboard/src/editor/graph.ts
- packages/breadboard/src/editor/types.ts
- packages/breadboard/tests/editor/graph.ts
- packages/website/src/docs/editor.md
- **Sketch out the API.**
- **Add docs.**
- **docs(changeset): Implement subgraph editing in Editor API.**
> editable subgraph

- package-lock.json
- packages/json-kit/package.json
- packages/json-kit/src/index.ts
- packages/json-kit/src/nodes/object-to-schema.ts
- packages/json-kit/tests/jsonata.ts
- packages/json-kit/tests/object-to-schema.ts
- packages/json-kit/tests/schemish.ts
- packages/json-kit/tests/validate-json.ts
- packages/json-kit/tests/xml-to-json.ts
- closes https://github.com/breadboard-ai/breadboard/issues/1259
> Add schema from object node to JSON kit and migrate JSON kit tests to Node test runner

- .changeset/new-icons-drop.md
- packages/breadboard/src/new/grammar/node.ts
- **Dirty fix.**
- **docs(changeset): A quick-and-dirty fix to the TS type system errors.**
> fix fix fix

- .changeset/long-rivers-vanish.md
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-ui/src/types/types.ts
- packages/breadboard-web/src/index.ts
- **Pass the entire SettingsStore to bb-ui-controller.**
- **docs(changeset): Pass the entire SettingsStore to the bb-ui-controller.**
> settings store

- .changeset/neat-maps-brake.md
- packages/breadboard/src/run.ts
- packages/breadboard/tests/new/grammar/serialize-and-run-with-old-runner.ts
- packages/build/src/test/compatibility_test.ts
- **Remove `schema` port from `output`.**
- **docs(changeset): Remove `schema` from `output` ports.**
> no schema in outputs

- packages/breadboard-web/src/index.ts
> [breadboard-web] Reset subGraphId when board changes

- .changeset/witty-chairs-prove.md
- packages/breadboard-web/public/graphs/accumulating-context.json
- packages/breadboard-web/public/graphs/agent.json
- packages/breadboard-web/public/graphs/best-of-n.json
- packages/breadboard-web/public/graphs/board-caller.json
- packages/breadboard-web/public/graphs/data-board.json
- packages/breadboard-web/public/graphs/math.json
- packages/breadboard-web/public/graphs/search-summarize.json
- packages/breadboard-web/public/graphs/simplest.json
- packages/breadboard-web/public/graphs/single-turn.json
- packages/breadboard-web/public/graphs/text-generator.json
- packages/breadboard-web/public/graphs/tour-guide-writer.json
- packages/breadboard-web/src/boards/accumulating-context.ts
- packages/breadboard-web/src/boards/agent.ts
- packages/breadboard-web/src/boards/best-of-n.ts
- packages/breadboard-web/src/boards/board-caller.ts
- packages/breadboard-web/src/boards/data-board.ts
- packages/breadboard-web/src/boards/math.ts
- packages/breadboard-web/src/boards/search-summarize.ts
- packages/breadboard-web/src/boards/simplest.ts
- packages/breadboard-web/src/boards/single-turn.ts
- packages/breadboard-web/src/boards/text-generator.ts
- packages/breadboard-web/src/boards/tour-guide-writer.ts
- packages/breadboard/src/inspector/ports.ts
- packages/breadboard/src/inspector/schemas.ts
- packages/breadboard/src/types.ts
- packages/core-kit/src/index.ts
- packages/core-kit/src/nodes/invoke.ts
- packages/gemini-kit/src/kit.ts
- packages/hello-world/src/card-maker.ts
- **Remove the uses of `path` of `core.invoke`.**
- **Teach port collector to discard deprecated ports.**
- **docs(changeset): Deprecate `path` on `core.invoke`.**
> deprecate path

- .changeset/witty-flowers-battle.md
- packages/core-kit/src/nodes/run-javascript.ts
- **Remove the warning about unknown format.**
- **docs(changeset): Remove the warning when encountering unknown function format.**
> no js errors

- .changeset/nine-bugs-drop.md
- packages/gemini-kit/src/boards/gemini-generator.ts
- **Add support for system instructions.**
- **Give systemInstruction a default.**
- **docs(changeset): Add system instruction support.**
> system instructions

- .changeset/sweet-trains-itch.md
- packages/breadboard-web/src/preview-run.ts
> [breadboard-ui] Teach Preview to use Settings & stored secrets

- .changeset/nice-cooks-guess.md
- package-lock.json
- packages/breadboard-ui/src/elements/editor/graph-edge.ts
- packages/breadboard/src/inspector/edge.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/tests/inspector/edge.ts
- **Introduce `InspectableEdge.type`.**
- **docs(changeset): Introduce `InspectableEdge.type`.**
> edge types

- .changeset/sweet-kids-tease.md
- packages/breadboard/src/inspector/ports.ts
- packages/breadboard/src/inspector/schemas.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/tests/inspector/ports.ts
- **Add control ports.**
- **Minor massage.**
- **docs(changeset): Add support for control edges.**
> control ports

- .changeset/chilled-lions-breathe.md
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
> [breadboard-ui] Centralize graph on resize

- .changeset/wicked-cobras-begin.md
- packages/breadboard-ui/src/elements/editor/graph-edge.ts
Minor fix because I noticed the edge curves were off in one particular case.
> [breadboard-ui] Adjust threshold for curve rendering on edges

- .changeset/wild-walls-jump.md
- package-lock.json
- packages/breadboard-ui/src/elements/elements.ts
- packages/breadboard-ui/src/elements/input/code-editor/code-editor.ts
- packages/breadboard-ui/src/elements/node-info/node-info.ts
- packages/breadboard-web/package.json
> [breadboard-ui] Teach node info about code

- .changeset/pretty-pants-jam.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/boards/human.json
- packages/agent-kit/boards/repeater.json
- packages/agent-kit/boards/structured-worker.json
- packages/agent-kit/boards/tool-worker.json
- packages/agent-kit/boards/worker.json
- packages/agent-kit/src/boards/tool-worker.ts
- packages/breadboard-web/public/agent.kit.json
- **Update bgls after runJavascript changes.**
- **Teach Tool Worker to use subgraphs.**
- **Teach Tool Worker to load all kinds of graphs.**
- **Update `agent.kit.json`.**
- **docs(changeset): Switch Tool Worker to use proper board loading (using `curry`).**
> cooler tool worker

- .changeset/heavy-phones-smell.md
- packages/breadboard-ui/src/elements/editor/graph-edge.ts
- packages/breadboard-ui/src/elements/editor/graph-node-port.ts
- packages/breadboard-ui/src/elements/editor/graph-node.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
- packages/breadboard-ui/src/elements/node-info/node-info.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-web/src/index.ts
> [breadboard-ui/-web] Add support for metadata editing

- .changeset/metal-cats-crash.md
- packages/breadboard-ui/src/elements/node-info/array-editor.ts
- packages/breadboard-ui/src/elements/node-info/schema-editor.ts
Hopefully improves things for #1414
> [breadboard-ui] Inform array editor about numbers

- packages/breadboard-ui/src/utils/board.ts
Changes things up for #1418 - @dglazkov not sure if this is the right fix or not, though!
> [breadboard-ui] Switch board selector cases

- .changeset/clean-carrots-behave.md
- packages/breadboard-ui/src/elements/node-info/array-editor.ts
- packages/breadboard-ui/src/elements/node-info/node-info.ts
> [breadboard-ui] Educate Array Editor about boards

- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
> [breadboard-ui] Support text selection in Activity Log outputs

- packages/breadboard-web/src/index.ts
Fixes some minor bugs I introduced earlier
> [breadboard-web] Handle untitled boards

- packages/breadboard-ui/src/elements/node-info/node-info.ts
> [breadboard-ui] Fix form submission bug

- packages/build/README.md
- packages/build/src/internal/define/define.ts
- packages/build/src/internal/define/instance.ts
- packages/build/src/test/define_test.ts
- Support invoke that returns promise
- Fix primary input assignment bug
- Document array and null type expression
- Improve test coverage for define
> [build] Add async invoke, fix primary input bug, document array and null types, improve test coverage

- boards/tools/openapi/openapi-toolworker.json
- boards/tools/openapi/openapi.js
- boards/tools/openapi/openapi.json
- boards/tools/openapi/request-builder.json
+ Tool Worker + Open API board
+ requestBuilder - takes a JSON schema and builds an JSON object that is valid
+ OpenAPI board integrated with requestBuilder
> [board] OpenAPI end to end run through

- .changeset/long-eggs-jam.md
- packages/agent-kit/boards/structured-worker.json
- packages/agent-kit/boards/worker.json
- packages/breadboard-web/public/graphs/gemini-simple.json
- packages/gemini-kit/src/boards/gemini-generator.ts
- **Add safety settings to gemini-generator.**
- **Convert request body building to JS.**
- **Properly implement system instruction.**
- **Fix my bugs in safetySettings.**
- **docs(changeset): Give gemini-generator an overhaul, adding proper system instruction support and safety settings.**
> gemini text

- packages/breadboard-ui/src/elements/node-info/node-info.ts
> [breadboard-ui] Save node state when clipboard is used

- .changeset/twelve-bottles-act.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/boards/super-worker.json
- packages/agent-kit/src/boards/super-worker.ts
- packages/agent-kit/src/context.ts
- packages/agent-kit/src/generate-kit-manifest.ts
- packages/agent-kit/src/index.ts
- packages/agent-kit/src/kit.ts
- packages/breadboard-ui/src/elements/input/input.ts
- packages/breadboard-ui/src/utils/index.ts
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard-web/public/graphs/super-worker-test.json
- packages/breadboard-web/public/local-boards.json
- packages/breadboard-web/src/boards/super-worker-test.ts
- packages/gemini-kit/src/boards/gemini-generator.ts
- **Stub out super worker board.**
- **Tweak input to handle non-string inputs more gracefully.**
- **Fix system instruction bugs in Gemini Generator.**
- **Working "Persona" input.**
- **Add task to the prompt.**
- **Mostly working.**
- **Add SuperWorker to the list of nodes.**
- **Add a sample board.**
- **docs(changeset): Introduce SuperWorker.**
> super worker

- .changeset/olive-items-change.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/super-worker.ts
- packages/agent-kit/src/context.ts
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard-web/public/graphs/super-worker-test.json
- packages/breadboard-web/public/local-boards.json
- packages/breadboard-web/src/boards/super-worker-test.ts
- **Assign proper roles when appending context.**
- **Better field descriptions.**
- **docs(changeset): Fix a problem with incorrect context appending.**
> two super workers

- .changeset/five-panthers-vanish.md
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/harness/run.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/src/types.ts
- packages/core-kit/src/nodes/fetch.ts
- **Implement `AbortSignal` support in Breadboard.**
- **docs(changeset): Implement `AbortSignal` support.**
> abort signal

- .changeset/khaki-countries-brush.md
- package-lock.json
- packages/template-kit/src/nodes/prompt-template.ts
- packages/template-kit/tests/nodes/prompt-template.ts
- **Allow undefined template args.**
- **docs(changeset): Allow undefined template in describer.**
> fix prompt template

- .changeset/fair-shrimps-fry.md
- packages/agent-kit/agent.kit.json
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard-web/public/graphs/agent-chain.json
- packages/breadboard-web/public/graphs/agent.json
- packages/breadboard-web/public/graphs/summarizer.json
- packages/breadboard/src/new/grammar/value.ts
- **Apply `format` to array items.**
- **docs(changeset): Apply `format` to array items.**
> format array

- .changeset/good-cats-share.md
- package-lock.json
- packages/breadboard-ui/src/types/types.ts
- packages/breadboard-web/src/data/inputs.ts
- packages/breadboard-web/src/data/settings-store.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/src/bubble.ts
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/harness/run.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/src/types.ts
- **Introduce and  plumb `RunConfig` inputs.**
- **Add inputs settings.**
- **Start using inputs settings.**
- **Explain inputs a bit more.**
- **docs(changeset): Make bubbled input values configurable.**
> input settings

- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
No idea why this didn't land with the last PR. Well, here we go...
> [breadboard-ui] Add quick expand/collapse

- .changeset/tall-pianos-switch.md
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- **Recognize that error object may not exist.**
- **docs(changeset): Recognize that Error object may not exist.**
> fix bugs 1000

- .changeset/nice-carpets-repeat.md
- package-lock.json
- packages/core-kit/src/nodes/fetch.ts
- **Do not stringify fetch body.**
- **docs(changeset): Do not stringify fetch body.**
> fetch body

- .changeset/real-suns-serve.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/boards/repeater.json
- packages/agent-kit/boards/super-worker.json
- packages/agent-kit/boards/tool-worker.json
- packages/agent-kit/src/boards/tool-worker.ts
- packages/agent-kit/src/context.ts
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard-web/src/data/inputs.ts
- packages/breadboard-web/src/data/node-proxy-servers.ts
- packages/breadboard/src/traversal/iterator.ts
- packages/core-kit/src/nodes/passthrough.ts
- packages/gemini-kit/src/boards/gemini-generator.ts
- **Teach Tool Worker to use system instruction.**
- **Expect null/undefined outputs.**
- **Update breadboard-web with system instruction-aware Tool Worker**
- **Add some error handling in response formatter.**
- **Remove spurious import.**
- **Remove old formatter.**
- **Handle string errors in activity logs.**
- **Remove gross hacks of passing "unused" text.**
- **Expect some settings sections not to be found.**
- **Update all the board BGLs.**
- **Modernize choosing method.**
- **Plumb through retry.**
- **Implement basic retry logic.**
- **Mark passthrough outputs as non-fixed.**
- **Add proper titles and descriptions to all nodes.**
- **Respond appropriately to different error codes.**
- **Update agent kit manifest.**
- **Make sure the error message travels to the user.**
- …
> tool journey

- .changeset/thick-eagles-cough.md
- packages/build/src/internal/board/input.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/test/input_test.ts
- packages/build/src/test/serialize_test.ts
Also tweaks the order of default vs description in input/output schemas
> [build] Add support for titles on inputs

- .changeset/mean-mayflies-fold.md
- packages/build/src/index.ts
- packages/build/src/internal/board/board.ts
- packages/build/src/internal/board/output.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/internal/common/serializable.ts
- packages/build/src/test/output_test.ts
- packages/build/src/test/serialize_test.ts
Add an output function for customizing a board's output node layout
> [build] Add output function

- packages/breadboard-web/public/graphs/best-of-n.json
- packages/breadboard-web/public/graphs/board-caller.json
- packages/breadboard-web/public/graphs/healer.json
- packages/breadboard-web/public/graphs/math.json
- packages/breadboard-web/public/graphs/nager.date/is-today-public-holiday.json
- packages/breadboard-web/public/graphs/nager.date/long-weekend.json
- packages/breadboard-web/public/graphs/nager.date/public-holidays.json
- packages/breadboard-web/public/graphs/open-alex-entity-search-list.json
- packages/breadboard-web/public/graphs/retry.json
- packages/breadboard-web/public/graphs/summarizer.json
- packages/breadboard-web/src/bgl-formatter.ts
Again for making it easier to compare new BGL serializer results.
> Sort input/output required field

- packages/breadboard-web/public/graphs/math.json
- packages/breadboard-web/public/local-boards.json
- packages/breadboard-web/src/boards/math.ts
> Convert the Calculator board to @breadboard-ai/build

- package-lock.json
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/context.ts
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard-web/src/providers/file-system.ts
- **Catch an exception when a directory is missing.**
- **Teach super-worker to take in a single LLM Content item.**
> Teach super-worker to take in a single LLM Content item.

- .changeset/lovely-crabs-destroy.md
- packages/breadboard-ui/src/elements/editor/graph-node.ts
> [breadboard-ui] Fix graph node padding

- packages/breadboard-ui/src/elements/input/drawable/drawable.ts
- packages/breadboard-ui/src/elements/input/llm-input/llm-input.ts
- packages/breadboard-ui/src/elements/input/webcam/webcam.ts
- packages/breadboard-ui/src/elements/node-info/schema-editor.ts
> [breadboard-ui] Tweak drawable & webcam styles in LLM Content

- packages/breadboard-ui/src/elements/editor/graph.ts
> [breadboard-ui] Redraw highlight when nodes expand/collapse

- packages/breadboard/docs/wires.md
> docs: update wires.md

- .changeset/witty-bugs-switch.md
- packages/breadboard-ui/src/elements/node-info/schema-editor.ts
> Remember format changes for string types.

- .changeset/funny-kiwis-cry.md
- packages/breadboard-ui/src/elements/input/llm-input/llm-input.ts
- packages/breadboard-ui/src/elements/node-info/node-info.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-web/public/styles/global.css
- packages/breadboard-web/public/third_party/icons/move-down.svg
- packages/breadboard-web/public/third_party/icons/move-up.svg
> [breadboard-ui] Add part controls for LLM Content

- packages/breadboard-ui/src/elements/input/llm-input/llm-input.ts
Fixes a small bug relating to re-rendering after a deletion.
> [breadboard-ui] Tweak LLM Content re-render

- .changeset/slow-coins-retire.md
- packages/breadboard-ui/src/elements/node-info/node-info.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
> [breadboard-ui] Hide wired ports in node info

- .changeset/heavy-donuts-grab.md
- packages/breadboard-ui/src/elements/activity-log/activity-log.styles.ts
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-ui/src/elements/input/llm-input/llm-input.ts
- packages/breadboard-ui/src/utils/llm-content.ts
> [breadboard-ui] Render LLM Content in Activity Log

- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
Noticed the node info wasn't adding the input when the schema changed. Fixed!
> [breadboard-ui] Update inputs when node config changes

- .changeset/selfish-paws-swim.md
- packages/build/src/internal/define/define.ts
- packages/build/src/internal/define/definition.ts
- packages/build/src/internal/define/instance.ts
- packages/build/src/test/define_test.ts
- packages/build/src/test/output_test.ts
Fix type system bug relating to primary input/output ports (it wasn't working quite right when there were more than one input or output ports).
> [build Fix type system bug relating to primary input/output ports

- .changeset/great-pots-accept.md
- packages/breadboard-ui/src/elements/input/input.ts
- **Add support for inputs from last run to llm-content.**
- **docs(changeset): Wire last run values into llm-content**
> last run llm content

- packages/breadboard-ui/src/elements/editor/graph-node.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
> [breadboard-ui] Bring back node types

- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
> [breadboard-ui] Only re-render node info when schema changes

- .changeset/beige-items-provide.md
- packages/breadboard-ui/src/elements/editor/graph-node-port.ts
- packages/breadboard-ui/src/elements/editor/graph-node.ts
- packages/breadboard-ui/src/elements/node-info/node-info.ts
- packages/breadboard-web/public/styles/global.css
> [breadboard-ui] Teach Graph Node & Node Info how to handle configuration & edges

- packages/breadboard-ui/src/elements/input/llm-input/llm-input.ts
> [breadboard-ui] Move LLM controls

- .changeset/nervous-owls-retire.md
- packages/breadboard-ui/src/elements/input/llm-input/llm-input.ts
- packages/breadboard-web/public/styles/global.css
> [breadboard-ui] Teach LLM Content to handle plain text a bit better

- .changeset/fluffy-vans-think.md
- packages/breadboard-ui/src/elements/input/input.ts
- packages/breadboard-ui/src/elements/input/llm-input/llm-input.ts
- packages/breadboard-ui/src/elements/node-info/schema-editor.ts
- packages/breadboard-ui/src/utils/llm-content.ts
> [breadboard-ui] Teach Schema Editor about LLM Content defaults

- .changeset/poor-rabbits-tell.md
- packages/breadboard-ui/src/elements/board-details/board-details.ts
- packages/breadboard-ui/src/elements/node-details/node-details.ts
> [breadboard-ui] Emit updates for node and board info

- packages/core-kit/tests/secrets.ts
Forgot to include this file in https://github.com/breadboard-ai/breadboard/pull/1653
> [core-kit] Add tests for secret utility

- .changeset/violet-olives-fix.md
- packages/breadboard-ui/src/elements/input/llm-input/llm-input.ts
- packages/breadboard-ui/src/elements/node-info/array-editor.ts
- packages/breadboard-ui/src/elements/node-info/node-info.ts
- packages/breadboard-ui/src/elements/node-info/schema-editor.ts
> [breadboard-ui] Update schema styles

- .changeset/eight-starfishes-lay.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/boards/looper.json
- packages/agent-kit/boards/super-worker.json
- packages/agent-kit/src/boards/looper.ts
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard-web/public/graphs/looper-test.json
- packages/breadboard-web/src/boards/looper-test.ts
- packages/gemini-kit/src/boards/gemini-generator.ts
- **Working todo-based plan.**
- **Tidy up.**
- **Add plan schema.**
- **Add support for `responseMimeType`.**
- **Add default to `responseMimeType`.**
- **Add auto-planning.**
- **Fix a typo in the schemish.**
- **docs(changeset): Teach Looper how to plan and add `responseMimeType` to Gemini API.**
> looper plan

- .changeset/pink-parrots-leave.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/human.ts
- packages/agent-kit/src/boards/looper.ts
- packages/agent-kit/src/boards/super-worker.ts
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard-web/public/graphs/looper-chat-test.json
- packages/breadboard-web/public/local-boards.json
- packages/breadboard-web/src/boards/looper-chat-test.ts
- **Give human an icon.**
- **Stub out the looper chat test.**
- **Teach superworker that tasks are optional.**
- **More dirty hacks in Activity Log (Sorryyy)**
- **Mega planner prompt**
- **Teach looper about off-by-one errors.**
- **First cut at looper chat.**
- **docs(changeset): Teach Looper Node a bit more about planning.**
> looper chat

- packages/core-kit/tests/passthrough.ts
Add passthrough tests in preparation for conversion to new API.
> [core-kit] Add passthrough tests

- .changeset/lemon-bananas-double.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/human.ts
- packages/agent-kit/src/boards/looper.ts
- packages/agent-kit/src/boards/super-worker.ts
- packages/agent-kit/src/context.ts
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard-web/public/graphs/looper-chat-test.json
- packages/breadboard-web/public/graphs/super-worker-test.json
- packages/breadboard-web/src/boards/looper-chat-test.ts
- **Pass looper tasks in metadata.**
- **Teach Looper that task is optional.**
- **docs(changeset): Start passing tasks via metadata.**
> pass looper tasks

- packages/breadboard-ui/src/elements/editor/graph-node.ts
- packages/breadboard-ui/src/elements/editor/graph-overflow-menu.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
> [breadboard-ui] Groundworks for edge management

- packages/build/src/internal/board/constant.ts
- packages/build/src/internal/board/input.ts
- packages/build/src/internal/define/json-schema.ts
- packages/build/src/test/serialize_test.ts
Follow up to https://github.com/breadboard-ai/breadboard/pull/1687, a case I forgot.
> [build] Allow inputs with default to be constant too

- packages/breadboard-cli/src/index.ts
Oops, forgot to include this in https://github.com/breadboard-ai/breadboard/pull/1713
> [cli] Add missing --format flag

- .changeset/quiet-turtles-obey.md
- package-lock.json
- packages/breadboard-ui/package.json
- packages/breadboard-ui/src/utils/schema.ts
- **Switch to use ajv instead of jsonschema.**
- **docs(changeset): Fix the bug with LLM Content changes not sticking.**
> fix llm content

- packages/breadboard-ui/src/elements/editor/graph.ts
> [breadboard-ui] Fix render bug

- .changeset/many-days-carry.md
- package-lock.json
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/super-worker.ts
- packages/agent-kit/src/boards/tool-worker.ts
- packages/agent-kit/src/function-calling.ts
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard-web/public/graphs/super-worker-test.json
- **Teach Super Worker to support tool-calling.**
- **Support tools that return LLM Content.**
- **docs(changeset): Teach Super Worker to use tools.**
> super tools

- .changeset/five-suns-shout.md
- .changeset/late-sheep-beam.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/human.ts
- packages/agent-kit/src/context.ts
- packages/agent-kit/src/function-calling.ts
- packages/breadboard-web/public/agent.kit.json
- packages/gemini-kit/src/boards/gemini-generator.ts
- **Teach human to display LLM Content.**
- **Teach super worker and gemini generator about "tool" role.**
- **docs(changeset): Teach Gemini Kit about "tool" role.**
- **docs(changeset): Teach Human to display LLM Content.**
> human llm content

- packages/breadboard-ui/src/elements/splitter/splitter.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
> [breadboard-ui] Clamp splitter size

- .changeset/three-impalas-remain.md
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
> [breadboard-ui] Add text/plain support to Activity Log

- packages/breadboard-ui/src/elements/editor/graph-edge.ts
- packages/breadboard-ui/src/elements/editor/graph-node.ts
> [breadboard-ui] Update selection colors

- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
> [breadboard-ui] Hide node highlight on stop

- packages/breadboard-ui/src/elements/activity-log/activity-log.styles.ts
- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-ui/src/elements/input/llm-input/llm-input.ts
> [breadboard-ui] Restyle LLM Content

- packages/breadboard-ui/src/elements/ui-controller/ui-controller.styles.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
> [breadboard-ui] Slight improvement to debug popover

- packages/breadboard-ui/src/elements/ui-controller/ui-controller.styles.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
> [breadboard-ui] Update details panel styles for portrait mode

- .changeset/spicy-eyes-roll.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/tool-worker.ts
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard/src/kits/load.ts
- **Deprecate toolWorker**
- **docs(changeset): Deprecate the Tool Worker.**
> deprecate tool worker

- packages/breadboard-ui/src/elements/input/llm-input/llm-input.ts
> [breadboard-ui] Update focus styles for LLM Input

- packages/breadboard-ui/src/elements/input/input.ts
- packages/breadboard-ui/src/elements/input/llm-input/llm-input-array.ts
- packages/breadboard-ui/src/elements/llm-output/llm-output-array.ts
> [breadboard-ui] Add mode toggle to LLM Output Array

- packages/breadboard-ui/src/elements/activity-log/activity-log.ts
- packages/breadboard-ui/src/elements/elements.ts
- packages/breadboard-ui/src/elements/event-details/event-details.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.styles.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-ui/src/utils/llm-content.ts
> [breadboard-ui] Update debug view

- packages/breadboard-ui/src/elements/llm-output/llm-output-array.ts
> [breadboard-ui] Keep LLM Content output heights in sync

- .changeset/forty-vans-wave.md
- package-lock.json
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- Ask Activity Log to re-render more often.
- docs(changeset): Fix the issue wit activity log not always showing outputs.
> activity log fix

- .changeset/fair-buses-search.md
- packages/breadboard-web/src/preview-run.ts
> [breadboard-ui] Teach Preview to use inputs in settings

- .changeset/forty-dancers-sing.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-edge.ts
- packages/breadboard-ui/src/elements/editor/graph-node-port.ts
- packages/breadboard-ui/src/elements/editor/graph-node.ts
- packages/breadboard-ui/src/elements/editor/graph-overflow-menu.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
- packages/breadboard-ui/src/elements/editor/utils.ts
- packages/breadboard-ui/src/elements/splitter/splitter.ts
- packages/breadboard-web/src/index.ts
> [breadboard-ui] Various UI tweaks

- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/utils.ts
- packages/breadboard-web/src/index.ts
> [breadboard-ui] Warn on potential unload data loss

- packages/breadboard-ui/src/elements/input/input.ts
- packages/breadboard-ui/src/elements/input/llm-input/llm-input-array.ts
- packages/breadboard-ui/src/elements/input/llm-input/llm-input.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-ui/src/utils/llm-content.ts
- packages/breadboard-web/src/index.ts
> [breadboard-ui] Teach LLM Content Input about minItems

- .changeset/good-snails-destroy.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/node-info/node-info.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard-web/src/preview-run.ts
It's been a long time coming, but I've _finally_ reduced all the `breadboard` prefixes on events to `bb` so it's a little less cumbersome.
> [breadboard-ui] Update event names

- packages/gemini-kit/.gitignore
- packages/gemini-kit/graphs/gemini-generator.json
- packages/gemini-kit/graphs/gemini-pro-vision.json
(These don't get published, just useful to keep in GitHub temporarily)
> [gemini-kit] Check in BGL files to help compare when converted to new API

- .changeset/grumpy-mayflies-impress.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/specialist.ts
- packages/breadboard-web/public/agent.kit.json
- **Pass more context along in Specialist.**
- **docs(changeset): Pass looper tasks to context in Specialist.**
> pass looper task

- .changeset/wild-pens-build.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-web/src/index.ts
> [breadboard-ui] Teach Visual Editor about copy-pasting nodes

- .changeset/dry-eagles-lie.md
- packages/breadboard-ui/src/elements/node-info/node-info.ts
- **Use shallow array copy on ports.**
- **docs(changeset): Use shallow array copy on ports to preserve methods.**
> shallow copy

- .changeset/beige-points-beam.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
- packages/breadboard-ui/src/elements/editor/utils.ts
> [breadboard-ui] Fix various UX issues with multiselect

- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
> [breadboard-ui] Teach VE about moving multiple nodes at once

- .changeset/thirty-waves-sit.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard/tests/editor/multi.ts
- packages/website/src/docs/editor.md
- **Add a test for self-conflicted multi-edit.**
- **Start using multi-edit. IT WORKS!**
- **docs(changeset): Start using multi-edit capability when pasting nodes.**
- **Update docs.**
> multi edit

- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-node.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
> [breadboard-ui] Undo/redo tweaks

- .changeset/silly-oranges-raise.md
- package-lock.json
- packages/breadboard/src/editor/operations/change-configuration.ts
- packages/breadboard/src/editor/operations/change-metadata.ts
- packages/breadboard/src/editor/types.ts
- packages/breadboard/tests/editor/configuration.ts
- packages/breadboard/tests/editor/metadata.ts
- **Make metadata and configuration changes incremental by default.**
- **docs(changeset): Make metadata/configration changes incremental by default.**
> incremental by default

- packages/website/src/updates/2024-05-20.md
Noticed one of the images wasn't the right one :)
> [website] Fix image in May update

- .changeset/lucky-rules-return.md
- packages/breadboard-ui/src/elements/input/llm-input/llm-input.ts
> [breadboard-ui] Remove part deletion confirm prompt

- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
> [breadboard-ui] Fix board detail bug

- packages/breadboard-web/src/index.ts
> [breadboard-ui] Switch to new board on creation

- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
> [breadboard-ui] Only honor "select all" in graph render

- .changeset/giant-rocks-fail.md
- packages/breadboard-ui/src/elements/node-info/node-configuration.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
> [breadboard-ui] Fix initial render

- .changeset/dirty-ears-taste.md
- packages/breadboard-ui/src/elements/overlay/settings-edit.ts
- packages/breadboard-ui/src/types/types.ts
- packages/breadboard-web/src/data/settings-store.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard-web/src/providers/remote.ts
> [breadboard-ui] Add RemoteGraphProvider and basic support for Board Servers

- package-lock.json
- packages/website/eleventy.config.cjs
- packages/website/package.json
- packages/website/src/static/updates/rss.xsl
- packages/website/src/updates/rss.njk
Been doing some playing around with xml stuff and saw this as a nice place to add a source of data.
Added, configured and styled the RSS feed but didn't put a link on the footer (or anywhere else).
> Add "Updates" RSS feed to website

- .changeset/happy-frogs-march.md
- package-lock.json
- package.json
- packages/board-server/.npmignore
- packages/board-server/README.md
- packages/board-server/package.json
- packages/board-server/src/api/delete.ts
- packages/board-server/src/api/get.ts
- packages/board-server/src/api/list.ts
- packages/board-server/src/api/post.ts
- packages/board-server/src/common.ts
- packages/board-server/src/errors.ts
- packages/board-server/src/index.ts
- packages/board-server/src/types.ts
- packages/board-server/tsconfig.json
- **Stub out `@breadboard-ai/board-server`.**
- **Add handy shortcuts.**
- **Point `dev` to the right place.**
- **Simplest possible server.**
- **Stub out the API.**
- **docs(changeset): Introduce Board Server.**
> board server

- .changeset/chatty-spies-think.md
- packages/breadboard-ui/src/elements/input/code-editor/code-editor.ts
> [breadboard-ui] Watch for deletions in the code editor

- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-node.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
- packages/breadboard-ui/src/elements/node-meta-details/node-meta-details.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-web/src/data/settings-store.ts
> [breadboard-ui] Repurpose node description setting

- .changeset/tidy-crabs-collect.md
- packages/agent-kit/src/function-calling.ts
- packages/agent-kit/tests/function-calling.ts
- **Teach `functionOrTextRouter` to work with multiple parts in response.**
- **docs(changeset): Teach Specialist about multi-part functionCalls.**
> function call multiple parts

- .changeset/stupid-donuts-change.md
- packages/agent-kit/agent.kit.json
- packages/breadboard-web/public/agent.kit.json
- packages/breadboard-web/public/graphs/agent.json
- packages/breadboard-web/public/graphs/best-of-n.json
- packages/breadboard-web/public/graphs/math.json
- packages/breadboard-web/public/graphs/tour-guide-writer.json
- packages/breadboard-web/src/boards/math.ts
- packages/core-kit/src/nodes/invoke.ts
- packages/core-kit/tests/invoke.ts
- **Change `$board` type to be `object`.**
- **Update agent-kit.**
- **docs(changeset): Change `invoke.$board` input to `object` type.**
> fix invoke board

- .changeset/nice-ligers-explain.md
- packages/breadboard-ui/src/elements/node-info/node-configuration.ts
- packages/breadboard-web/src/index.ts
- **Disable incremental configuration update.**
- **Remove spurious logging.**
- **docs(changeset): Disable incremental configuration edits.**
> disable incremental config

- .changeset/tender-bottles-shave.md
- package-lock.json
- packages/board-server/README.md
- packages/board-server/package.json
- packages/board-server/src/cors.ts
- **Add instructions to run board server locally.**
- **More sensible return value.**
- **docs(changeset): Better README.**
> board server dev

- .changeset/fifty-donuts-exist.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/ui-controller/ui-controller.ts
- packages/breadboard-ui/src/events/events.ts
> [breadboard-ui]: Tidy relationship between GraphRenderer and Graph

- .changeset/silly-queens-chew.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- **Start with graph visible by default.**
- **docs(changeset): Start with Graph being visible by default.**
> graph visible

- .changeset/many-laws-flash.md
- package-lock.json
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/specialist.ts
- packages/agent-kit/src/context.ts
- packages/agent-kit/src/function-calling.ts
- packages/agent-kit/tests/combine-contexts.ts
- packages/agent-kit/tests/function-calling.ts
- packages/breadboard-web/public/agent.kit.json
- **Start supporting multiple function calls.**
- **Teach Specialist about parallel function calling.**
- **docs(changeset): Teach Specialist about parallel function calls.**
> multiple function calls

- .changeset/shiny-pens-yell.md
- packages/breadboard/src/data.ts
- packages/breadboard/src/index.ts
- packages/breadboard/src/types.ts
- packages/core-kit/src/nodes/fetch.ts
- **Introduce `DataCapability` + handling multipart in `fetch`.**
- **docs(changeset): Introduce `DataCapability` and add support for multipart form data in `fetch`.**
> multipart form

- .changeset/gold-baboons-play.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/function-calling.ts
- packages/agent-kit/tests/boards/context-arg.json
- packages/agent-kit/tests/function-calling.ts
- packages/breadboard-web/public/agent.kit.json
- **Plumb board through `functionSignatureFromBoard`.**
- **Rename `context` arg to match the corresponding tool property.**
- **docs(changeset): No longer require property to be named `context`.**
- **Update kit manifests.**
> llm content yay

- .changeset/early-boxes-destroy.md
- package-lock.json
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/context.ts
- packages/breadboard-web/public/agent.kit.json
- **Only add a Looper task to the first Specialist after it.**
- **docs(changeset): Only add Looper task to the first Specialist after it.**
> only first specialist

- .changeset/rotten-hotels-sparkle.md
- packages/breadboard-ui/src/elements/activity-log/activity-log.styles.ts
- packages/breadboard-web/public/styles/global.css
- packages/breadboard-web/public/third_party/icons/arrow-drop-down.svg
- packages/breadboard-web/public/third_party/icons/arrow-right.svg
- packages/breadboard-web/src/providers/remote.ts
> [breadboard-ui] Fix missing icons

- .changeset/lovely-gorillas-pump.md
- packages/breadboard-ui/src/elements/node-info/schema-editor.ts
> [breadboard-ui] Restore ID to port spec

- .changeset/great-pears-sleep.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
Fixes #1945
FYI @dglazkov in case there are issues relating to visibility. (There aren't for me, but then again there weren't any issues last time, either!)
> [breadboard-ui] Use masking for hiding graphs

- .changeset/chilly-jars-accept.md
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
> [breadboard-ui] Attempt to default a name for dynamic ports

- .changeset/tidy-ladybugs-drop.md
- package-lock.json
- packages/board-server/.eslintrc
- packages/board-server/index.html
- packages/board-server/package.json
- packages/board-server/src/common.ts
- packages/board-server/src/index.ts
- packages/board-server/tsconfig.json
- packages/board-server/vite.config.ts
- **Basic vitejs setup for board-server.**
- **Something working.**
- **docs(changeset): Teach board-server about vitejs.**
> board vite

- packages/breadboard-web/src/index.ts
> [breadboard-ui] Remove dragstart handler

- packages/breadboard-web/src/providers/remote.ts
> [breadboard-ui] Only show Save for editable boards

- packages/breadboard-ui/src/elements/node-info/schema-editor.ts
Fixes #1953 a bit more. Also working on #2009, part 5.
> [breadboard-ui] Move ID to "more info"

- packages/breadboard-ui/src/elements/editor/editor.ts
> [breadboard-ui] Set default config for inputs & outputs

- .changeset/eight-students-rush.md
- packages/breadboard-ui/src/elements/node-info/schema-editor.ts
> [breadboard-ui] Default new port-spec properties to LLM Content

- packages/breadboard-ui/src/elements/activity-log/activity-log.styles.ts
> [breadboard-ui] Update user-select in Activity Log

- .changeset/long-zoos-call.md
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/events/events.ts
> [breadboard-ui] Convert node & edge deletion to multi-edit

- .changeset/shiny-socks-train.md
- packages/breadboard-web/public/graphs/agent.json
- packages/breadboard-web/public/graphs/best-of-n.json
- packages/breadboard-web/public/graphs/tour-guide-writer.json
- packages/core-kit/src/nodes/invoke.ts
- packages/core-kit/tests/invoke.ts
- **Mark `$board` as `config` port on `invoke` node.**
- **docs(changeset): Mark `$board` port as `config` on `invoke` node.**
> board config

- .changeset/green-bugs-repeat.md
- packages/breadboard-web/src/index.ts
- packages/breadboard-web/src/providers/file-system.ts
- packages/breadboard-web/src/providers/indexed-db.ts
- packages/breadboard-web/src/providers/remote.ts
- packages/breadboard/src/editor/blank.ts
- packages/breadboard/src/editor/index.ts
- packages/breadboard/src/index.ts
- **Introduce `blankLLMContent` method.**
- **docs(changeset): Use LLMContent types in blank graphs.**
> blank llm content

- .changeset/breezy-terms-buy.md
- packages/board-server/README.md
- packages/board-server/package.json
- packages/board-server/scripts/create-account.ts
- packages/board-server/src/index.ts
- **Make board-server deployable again.**
- **Give board server a way to add accounts.**
- **docs(changeset): Teach board-server to add accounts.**
> board account

- packages/board-server/app.yaml
- **WIP**
- **Tweak app.yaml**
> board server deploy

- .changeset/mighty-beds-worry.md
- package-lock.json
- packages/board-server/index.html
- packages/board-server/src/app/app.ts
- packages/board-server/src/index.ts
- **Teach board server about the `.app`**
- **docs(changeset): Teach board server about `.app`.**
> app extension

- .changeset/brown-garlics-guess.md
- packages/core-kit/src/nodes/run-javascript.ts
- **Teach runJavascript to run in Service Worker.**
- **docs(changeset): Actually commit the runJavascript change**
> service worker actually

- .changeset/four-gorillas-watch.md
- packages/board-server/src/server/auth.ts
- packages/board-server/src/server/boards/delete.ts
- packages/board-server/src/server/boards/index.ts
- packages/board-server/src/server/boards/post.ts
- packages/board-server/src/server/cors.ts
- packages/board-server/src/server/store.ts
- packages/board-server/src/server/types.ts
- packages/breadboard-web/src/providers/remote.ts
- **Store allowed CORS origins in board server configuration.**
- **Use simple requests.**
- **docs(changeset): Make board server deployable in more environments.**
> board server cors

- .changeset/many-dryers-guess.md
- package-lock.json
- packages/gemini-kit/src/boards/gemini-generator.ts
- **Update the list of useful models for Gemini Generator.**
- **docs(changeset): Added `flash`, removed `ultra` and `1.0-pro` (they don't have all the latest stuff).**
> gemini flash

- .changeset/yellow-jobs-breathe.md
- packages/build/src/index.ts
- packages/build/src/internal/board/optional.ts
- packages/build/src/internal/board/serialize.ts
Marks an edge as optional.
Also export a couple other functions I need.
> [build] Add optionalEdge function

- packages/google-drive-kit/src/get-file-content.ts
- packages/google-drive-kit/src/index.ts
- packages/google-drive-kit/src/kit.ts
It gets the raw content from a file in Google Drive. Different to export, which converts a Doc/Sheet/Presentation to some other format.
> [google-drive] Add getFileContent node

- .changeset/clean-coins-serve.md
- packages/core-kit/package.json
- packages/core-kit/src/nodes/map.ts
- packages/core-kit/tests/data/boards/map-throw-error.bgl.json
- packages/core-kit/tests/node/map.ts
- **Teach Core Kit to run node tests and add a failing test.**
- **Automatically handle errors in `map`.**
- **docs(changeset): Automatically handle errors in `map`.**
> error in map

- .changeset/mean-dingos-change.md
- .changeset/poor-cups-retire.md
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard/src/inspector/graph.ts
- packages/breadboard/src/inspector/schemas.ts
- packages/breadboard/tests/inspector/describe.ts
- **Expand ad-hoc wire pattern to include numbers.**
- **Teach `output` to be flexible by default.**
- **docs(changeset): Expand ad hoc input pattern to include numbers.**
- **docs(changeset): Teach `output` to be non-fixed by default.**
> ad hoc output

- .changeset/tender-crabs-wait.md
- package-lock.json
- packages/breadboard-ui/src/elements/editor/editor.ts
- packages/breadboard-ui/src/elements/editor/graph-node.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
- packages/website/package.json
- packages/website/src/js/board-embed.ts
- packages/website/src/static/common.css
- packages/website/web-dev-server.config.mjs
Fixes #2162
I've made the editor a little more suitable for mobile and multi-touch. This largely involved making a "readonly" flag for the website, adding a "view this in the Visual Editor" button, and making sure that, when there are multiple pointer events, we only observe the primary one.
> [website] Tweak the website graph view

- .changeset/wise-donkeys-lay.md
- packages/breadboard-ui/src/elements/input/llm-input/llm-input.ts
> [breadboard-ui] Add "quick add" to LLM Input

- packages/breadboard-cli/README.md
- packages/breadboard-cli/src/commands/lib/debug-server.ts
- packages/breadboard-cli/src/commands/lib/utils.ts
- packages/breadboard-cli/src/index.ts
> Allow customizing debug server port via PORT envrionment variable

- packages/breadboard-web/src/copy-pyodide-assets.ts
https://github.com/breadboard-ai/breadboard/issues/2163
> 2163 build fails when project exists in directory with space in the path

- .changeset/three-rabbits-brush.md
- packages/breadboard-ui/src/elements/overlay/first-run.ts
> [breadboard-ui] Set model as part of first run

- .changeset/great-news-sneeze.md
- packages/breadboard-web/src/data/settings-store.ts
> [breadboard-web] Switch settings defaults

- .changeset/tough-comics-warn.md
- packages/core-kit/src/index.ts
- packages/core-kit/src/nodes/map.ts
- packages/core-kit/tests/map.ts
Also includes a `map` utility function which preserves strong typing.
> [core-kit] Convert map to build API

- .changeset/gold-planets-rhyme.md
- .changeset/unlucky-kings-hope.md
- packages/board-server/src/server/store.ts
- packages/schema/breadboard.schema.json
- packages/schema/src/graph.ts
- **Send board titles and `mine` flag from board server.**
- **Introduce `tags` in `GraphMetadata`.**
- **Add "published" board tag and start respecting on the board server.**
- **docs(changeset): Add `tags` to `GraphMetadata`.**
- **docs(changeset): Add support for `published`, `title`, and `mine` metadata for board server.**
> board server acls

- .changeset/rotten-ravens-yawn.md
- packages/breadboard-web/src/providers/remote.ts
- packages/breadboard/src/editor/blank.ts
- **Add support for tags for `blankLLMContent` and start using it with `RemoveGraphProvider`.**
- **docs(changeset): Temporarily mark new board server boards as published.**
> published blank

- .changeset/plenty-ads-hunt.md
- packages/breadboard/src/loader/default.ts
- **Include credentials in default loader.**
- **docs(changeset): Add `credentials: include` to default loader's fetch.**
> default fetch

- .changeset/dirty-plants-care.md
- packages/board-server/src/index.ts
- packages/board-server/src/server/boards/post.ts
- packages/board-server/src/server/info/index.ts
- packages/board-server/src/server/store.ts
- **Teach board server to introduce itself.**
- **docs(changeset): Teach board server to tell a bit about itself.**
> board server info

- .changeset/spotty-paws-swim.md
- packages/breadboard-ui/src/elements/nav/nav.ts
- packages/breadboard-ui/src/elements/overlay/save-as.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-web/src/index.ts
> [breadboard-web/-ui] Add more support for "Save As..."

- packages/breadboard-web/src/providers/indexed-db.ts
> [breadboard-web] Rename storage

- .changeset/spotty-tools-burn.md
- packages/breadboard-web/iframe.html
- packages/breadboard-web/src/data/node-proxy-servers.ts
- packages/breadboard-web/src/index.ts
- packages/breadboard-web/src/proxy/iframe.ts
- packages/breadboard-web/vite.config.ts
- packages/breadboard/src/harness/run.ts
- packages/breadboard/src/harness/worker.ts
- **Stub out iframe.html.**
- **Plumb through proxy config.**
- **Introduce `CustomProxyConfig`.**
- **Plumb through a simple custom proxy config.**
- **Working iframe harness.**
- **docs(changeset): Introduce the `iframe.html` entry point for running Breadboard in an iframe.**
> iframe proxy

- .changeset/ninety-news-develop.md
- packages/breadboard-web/src/index.ts
> [breadboard-web] Add undo/redo to main header bar

- .changeset/rich-mayflies-sort.md
- packages/board-server/src/server/boards/create.ts
- packages/board-server/src/server/store.ts
- **Teach board server to find unique name.**
- **docs(changeset): Teach board server to find unique names for boards.**
> unique name

- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/port-tooltip.ts
> [ui] Show more things in the port tooltip

- .changeset/silver-icons-reflect.md
- packages/gemini-kit/src/boards/gemini-generator.ts
- packages/manifest/bbm.schema.json
- **Teach Gemini Generator to report errors.**
- **docs(changeset): Teach Gemini Generator to report errors correctly.**
> gemini errors yay

- .changeset/moody-dingos-shave.md
- packages/breadboard-ui/src/elements/editor/graph-edge.ts
- packages/breadboard-ui/src/elements/editor/graph-renderer.ts
- packages/breadboard-ui/src/elements/editor/graph.ts
- packages/breadboard-ui/src/elements/editor/utils.ts
- packages/breadboard-ui/src/events/events.ts
- packages/breadboard-ui/src/types/types.ts
- packages/breadboard/src/index.ts
- packages/breadboard/src/inspector/edge.ts
> [ui] [breadboard] Misc prep work for highlighting invalid wires

- packages/website/src/docs/kits/core.md
- packages/website/src/static/boards/kits/core-curry.bgl.json
- packages/website/src/static/boards/kits/core-deflate.bgl.json
- packages/website/src/static/boards/kits/core-fetch.bgl.json
- packages/website/src/static/boards/kits/core-inflate.bgl.json
- packages/website/src/static/boards/kits/core-invoke.bgl.json
- packages/website/src/static/boards/kits/core-map.bgl.json
- packages/website/src/static/boards/kits/core-passhtrough.bgl.json
- packages/website/src/static/boards/kits/core-passthrough.bgl.json
- packages/website/src/static/boards/kits/core-reduce.bgl.json
- packages/website/src/static/boards/kits/core-run-javascript.bgl.json
- packages/website/src/static/boards/kits/core-secrets.bgl.json
- packages/website/src/static/boards/kits/core-unnest.bgl.json
- **Add all the nodes to core kit reference.**
- **Add blank boards for all core nodes in the guide.**
- **Add the right node to each board.**
> core kit docs

- .changeset/perfect-cherries-exist.md
- packages/google-drive-kit/CHANGELOG.md
- packages/google-drive-kit/package.json
- packages/manifest/bbm.schema.json
- **Update bb schema**
- **Mark google-drive-kit as public.**
- **docs(changeset): Mark google-drive-kit as public.**
- **RELEASING: Releasing 1 package(s)**
> more release

- .changeset/green-roses-pull.md
- packages/build/src/internal/board/board.ts
- packages/build/src/internal/board/output.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/internal/common/serializable.ts
- packages/build/src/test/input_test.ts
Fixes https://github.com/breadboard-ai/breadboard/issues/2297
> [build] Allow wiring inputs directly as outputs

- .changeset/ten-shrimps-work.md
- package-lock.json
- packages/manifest/package.json
- packages/manifest/src/tests/index.test.ts
- **Fix unit tests.**
- **docs(changeset): Fix unit tests.**
> fix unit tests

- .changeset/tasty-starfishes-repeat.md
- packages/visual-editor/package.json
- packages/visual-editor/src/ui/elements/node-info/schema-editor.ts
> [visual-editor] Attempt to maintain property order in the schema editor

- .changeset/small-toys-cough.md
- packages/visual-editor/src/ui/elements/node-info/schema-editor.ts
> [visual-editor] Remove default when changing from array to anything else

- .changeset/red-baboons-yell.md
- packages/visual-editor/src/ui/elements/editor/graph.ts
> [visual-editor] Default node x & y to 0 if not set

- .changeset/weak-files-beg.md
- packages/visual-editor/package.json
- packages/visual-editor/src/ui/elements/editor/graph.ts
> [visual-editor] Release drag behavior when clicking on port

- packages/visual-editor/src/ui/elements/editor/fancy-json.ts
Forgot the comma, and also separate items by newlines/indent.
> [fancy-json] Render arrays more correctly

- .changeset/fast-fireants-confess.md
- package-lock.json
- packages/board-server/package.json
- packages/breadboard-cli/package.json
- packages/breadboard-cli/src/bundle/index.html
- packages/breadboard-cli/src/bundle/worker.ts
- packages/breadboard-cli/src/commands/bundle.ts
- packages/breadboard-cli/src/debugger/index.html
- packages/breadboard-cli/src/debugger/preview.html
- packages/breadboard-cli/src/debugger/settings.ts
- packages/breadboard-cli/vite.config.ts
- packages/visual-editor/package.json
- packages/website/src/js/board-embed.ts
`@google-labs/visual-editor` => `@breadboard-ai/visual-editor`
> [visual-editor] Update package name

- .changeset/tidy-wasps-talk.md
- package-lock.json
- package.json
- packages/breadboard/rollup.config.js
- **Start rolling up d.ts information.**
- **docs(changeset): Start rolling up .d.ts type information for the package.**
> rollup types

- .changeset/cyan-penguins-type.md
- packages/board-server/src/server/store.ts
- **Fix an off-by-one slice in board server.**
- **docs(changeset): Fix an off-by-one slice error.**
> off by one

- .changeset/kind-snakes-clap.md
- packages/connection-server/src/index.ts
Part of https://github.com/breadboard-ai/breadboard/issues/2031
> [connection-server] Suggest a command to find and kill the other process when port is in use

- package-lock.json
- package.json
- packages/board-server/package.json
- packages/build/package.json
- packages/connection-server/package.json
- packages/google-drive-kit/package.json
- packages/python-wasm/package.json
- packages/website/package.json
See https://github.com/google/wireit/pull/1123. Fixes https://github.com/breadboard-ai/breadboard/issues/2031
> Bump wireit version to bring in SIGTERM fix

- .changeset/little-olives-promise.md
- packages/visual-editor/src/ui/elements/editor/editor.ts
- packages/visual-editor/src/ui/elements/editor/graph-comment.ts
- packages/visual-editor/src/ui/elements/editor/graph-node-port.ts
- packages/visual-editor/src/ui/elements/editor/graph-node.ts
- packages/visual-editor/src/ui/elements/editor/graph-renderer.ts
- packages/visual-editor/src/ui/elements/editor/graph.ts
- packages/visual-editor/src/ui/elements/ui-controller/ui-controller.ts
> [visual-editor] Remove unused editable property

- .changeset/neat-beans-kick.md
- packages/visual-editor/src/index.ts
> [visual-editor] Use the filename from the board's URL when exporting

- .changeset/curly-balloons-grin.md
- packages/core-kit/src/index.ts
- packages/core-kit/src/nodes/cast.ts
Add cast node and helper to core-kit, for asserting some JSON schema as the type of some value.
> [core-kit] Add cast node

- .changeset/red-berries-glow.md
- packages/visual-editor/src/ui/elements/node-info/node-configuration.ts
Accounts for https://github.com/breadboard-ai/breadboard/issues/2498
> [visual-editor] Account for schema mismatch

- .changeset/calm-humans-behave.md
- packages/google-drive-kit/package.json
- packages/google-drive-kit/src/components/export-file.ts
- packages/google-drive-kit/src/components/get-file-content.ts
- packages/google-drive-kit/src/components/list-files.ts
- packages/google-drive-kit/src/kit.ts
Moves components into a `components/` folder, and fixes some names/descriptions.
> [google-drive-kit] Minor reorg

- .changeset/two-toys-call.md
- packages/build/src/internal/board/board.ts
- packages/build/src/internal/define/define.ts
- packages/build/src/internal/define/definition.ts
Also make it easier to tell when something is a discrete component
> [build] Add more metdaata to component definition classes

- packages/website/src/docs/reference/bse.md
> [website] Tweak BSE guide

- packages/visual-editor/src/ui/elements/activity-log/activity-log.ts
> [visual-editor] Change view scrolling to only affect parent

- packages/connection-server/.gcloudignore.external
- packages/connection-server/.gcloudignore.internal
- packages/connection-server/app.external.yaml
- packages/connection-server/app.internal.yaml
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/ui/elements/connection/connection-broker.ts
Some updated configs for the 2 deployments, and some updates to visual-editor to automatically pick the right deployment depending on the origin.
> [connections] [visual-editor] Set up external connections server

- .changeset/thin-papayas-hunt.md
- packages/agent-kit/agent.kit.json
- packages/core-kit/src/nodes/curry.ts
- packages/visual-editor/public/agent.kit.json
- packages/website/src/docs/kits/core.md
- packages/website/src/static/boards/kits/core-curry.bgl.json
- packages/website/src/static/boards/kits/example-simple-greeting.bgl.json
- **Document `curry` component.**
- **docs(changeset): Update titles in `curry` component.**
> curry docs

- .changeset/young-candles-hammer.md
- packages/build/src/internal/board/board.ts
- packages/build/src/test/serialize_test.ts
I think this was a regression from a recent refactoring I did. It was not covered by a test, but now it is.
> [build] Fix optional output serialization

- .changeset/tough-buses-perform.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/joiner.ts
- packages/agent-kit/src/boards/specialist.ts
- packages/visual-editor/public/agent.kit.json
- packages/visual-editor/public/example-boards/playground/super-worker-test.json
- **Return the right type for "Context out".**
- **Give Joiner output a good title.**
- **docs(changeset): Minor fixes to types and titles.**
> specialist polish

- packages/website/src/docs/kits/core.md
- packages/website/src/static/boards/kits/core-reduce.bgl.json
- packages/website/src/static/boards/kits/core-run-javascript.bgl.json
- packages/website/src/static/boards/kits/example-search-wikipedia.bgl.json
- **Document `reduce` component.**
- **Write an example for the `runJavascript` component.**
> core kit more docs

- .changeset/seven-geckos-whisper.md
- packages/core-kit/src/nodes/reduce.ts
- packages/core-kit/src/nodes/run-javascript.ts
- packages/core-kit/src/nodes/secrets.ts
- packages/core-kit/tests/run-javascript.ts
- packages/core-kit/tests/secrets.ts
- packages/template-kit/src/nodes/url-template.ts
- packages/website/src/docs/kits/core.md
- packages/website/src/docs/kits/json.md
- packages/website/src/docs/kits/template.md
- packages/website/src/static/boards/kits/core-secrets.bgl.json
- packages/website/src/static/boards/kits/example-simple-router.bgl.json
- **Add help link for `reduce`.**
- **Freshen up titles, etc. on `runJavascript`.**
- **Document `runJavascript` component.**
- **Document `secrets` component.**
- **`node` -> `component` in Template Kit docs.**
- **`node` -> `component` in JSON docs.**
- **docs(changeset): Update Template and Core Kit to jive with docs.**
- **Adjust unit tests.**
> core kit docs again

- .changeset/empty-candles-fry.md
- packages/visual-editor/src/ui/elements/input/user-input.ts
- packages/visual-editor/src/ui/elements/node-info/node-configuration.ts
- packages/visual-editor/src/ui/elements/ui-controller/ui-controller.ts
> [visual-editor] Fix bug where code editor fails to show up

- .changeset/mean-feet-wash.md
- packages/visual-editor/package.json
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/ui/elements/overflow-menu/overflow-menu.ts
> [visual-editor] Add copy-to-clipboard for board URL

- .changeset/slimy-eagles-pull.md
- packages/visual-editor/src/ui/elements/input/user-input.ts
> [visual-editor] Improve board support in unified input

- packages/breadboard-python/breadboard_colab/pyproject.toml
- packages/breadboard-python/breadboard_colab/src/breadboard_colab.py
> Fix iframepath and configId parameter in colab

- packages/visual-editor/package.json
- packages/visual-editor/src/ui/elements/node-info/node-configuration.ts
Not quite sure how the comment component input styles got messed up, but they did. So this PR fixes them.
> [visual-editor] Fix comment component styles

- .changeset/thirty-cars-sniff.md
- packages/core-kit/src/nodes/cast.ts
- packages/core-kit/src/nodes/unnest.ts
Part of https://github.com/breadboard-ai/breadboard/issues/2175
> [core-kit] Add metadata and jsdoc to the unnest and cast nodes

- packages/schema/src/tests/main.test.ts
- packages/website/src/docs/kits/core.md
- packages/website/src/static/boards/kits/core-unnest.bgl.json
Part of https://github.com/breadboard-ai/breadboard/issues/2175
> [website] Document the unnest component

- packages/core-kit/src/nodes/cast.ts
- packages/website/src/docs/kits/core.md
- packages/website/src/static/boards/kits/core-cast.bgl.json
Fixes https://github.com/breadboard-ai/breadboard/issues/2175
> [website] Document cast component

- .changeset/eleven-ducks-cross.md
- packages/core-kit/src/nodes/map.ts
- packages/core-kit/tests/data/boards/map-throw-error.bgl.json
- **Remove ability to bubble inputs/outputs in map.**
- **docs(changeset): Remove the ability to bubble up inputs from `map` component.**
> map bubbling

- .changeset/gentle-parrots-remain.md
- packages/breadboard/src/inspector/ports.ts
- packages/breadboard/src/types.ts
- packages/visual-editor/src/ui/elements/elements.ts
- packages/visual-editor/src/ui/elements/google-drive/google-drive-query.ts
- packages/visual-editor/src/ui/elements/input/user-input.ts
- packages/visual-editor/src/ui/utils/index.ts
> [breadboard] [visual-editor] Stub out google-drive-query component and behavior

- packages/visual-editor/src/ui/elements/connection/connection-input.ts
- packages/visual-editor/src/ui/elements/connection/connection-signin.ts
- packages/visual-editor/src/ui/elements/google-drive/google-drive-query.ts
Gets oauth token and client data. Temporarily renders itself as a signin component if necessary.
> [visual-editor] Integrate google-drive-query with OAuth infra

- packages/visual-editor/src/ui/elements/google-drive/google-drive-query.ts
> [visual-editor] Button that launches Google Drive Picker

- packages/visual-editor/src/ui/elements/google-drive/google-drive-query.ts
- packages/visual-editor/src/ui/elements/input/user-input.ts
> [visual-editor] Hook google-drive-query up to bb-input system, and style it

- .changeset/moody-seahorses-act.md
- .changeset/real-hats-drive.md
- packages/board-server/src/server/boards/utils/run-board.ts
- packages/board-server/tests/boards/invoke-board-with-bubbling-input.bgl.json
- packages/board-server/tests/run-board.ts
- packages/breadboard/src/bubble.ts
- packages/breadboard/src/harness/local.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/runner.ts
- packages/breadboard/src/types.ts
- packages/breadboard/tests/bubble.ts
- **wip**
- **Handle AbortController signal in bubbled inputs.**
- **Plumb RunState for bubbled inputs.**
- **Tighten the `BreadboardRunResult` type.**
- **Remove validator and slot related bits from BoardRunner.**
- **docs(changeset): Remove `validator` and `slot` bits from BoardRunner and allow bubbled inputs to abort gracefully.**
- **docs(changeset): Add a (failing so far) test for bubbling inputs from invoke.**
> board server run invoke

- .changeset/witty-squids-lie.md
- packages/breadboard/src/inspector/run/loader.ts
- packages/breadboard/src/inspector/run/past-run.ts
- packages/breadboard/src/inspector/run/run.ts
- packages/visual-editor/package.json
- packages/visual-editor/src/ui/elements/activity-log/activity-log.ts
Few minor issues from the run store work
> [breadboard] Fix replay of saved runs

- .changeset/old-bears-eat.md
- packages/board-server/src/server/boards/utils/run-board.ts
- **Fix build error in board server.**
- **docs(changeset): Fix build error.**
> fix build error

- packages/breadboard/src/data/common.ts
- packages/visual-editor/package.json
> [visual-editor] Be less strict with LLM Content check

- packages/visual-editor/src/ui/elements/ui-controller/ui-controller.ts
Got some feedback that it's a little confusing. And in any case right now things seem a bit broken (I suspect due to the runObserver changes); this removes it temporarily.
> Temporarily remove "Run Component"

- packages/website/src/docs/build/type-expressions.md
> [build] [website] Start documenting Breadboard Type Expressions

- packages/example-boards/playground-boards.json
- packages/example-boards/src/boards/playground/error.ts
- packages/visual-editor/public/example-boards/playground/error.json
Fixes #2650
Converted the Error board to the new Build API syntax.
> Converted Error board to Build API

- packages/example-boards/playground-boards.json
- packages/example-boards/src/boards/playground/search-summarize.ts
- packages/visual-editor/public/example-boards/playground/search-summarize.json
Fixes #2652 
Converted the Search Summarizer board to the new Build API syntax.
> Converted Search Summarizer board to Build API

- packages/visual-editor/src/index.ts
> Make pretty URLs

- .changeset/funny-ads-tell.md
- packages/agent-kit/src/context.ts
> [agent-kit] Finish converting types to Breadboard Type Expressions

- packages/visual-editor/src/index.ts
- packages/visual-editor/src/plugins/input-plugin.ts
- packages/visual-editor/src/ui/contexts/environment.ts
> [visual-editor] Create InputPlugin interface

- packages/website/src/docs/guides/breadboard-from-scratch.md
Progress on #2675
First commit of the docs for bringing up Breadboard from scratch. Details prerequisites and deploying the Visual Editor. Sections for Connection Server and Board Server are stubbed out.
> [docs] Breadboard from scratch, initial doc

- .changeset/brown-seahorses-knock.md
- .vscode/launch.json
- packages/breadboard/src/bubble.ts
- packages/breadboard/src/run/index.ts
- packages/breadboard/src/run/invoke-graph.ts
- packages/breadboard/src/run/lifecycle.ts
- packages/breadboard/src/run/manager.ts
- packages/breadboard/src/run/reanimator.ts
- packages/breadboard/src/run/registry.ts
- packages/breadboard/src/run/run-graph.ts
- packages/breadboard/src/run/types.ts
- packages/breadboard/tests/bgl/map-with-bubbling-inputs.bgl.json
- packages/breadboard/tests/node/run/interruptible-run-graph.ts
- packages/breadboard/tests/node/scripted-run.ts
- packages/breadboard/tests/node/test-kit.ts
- **Make list in test have two entries.**
- **Uncomment and reorganize logging.**
- **Mostly working.**
- **Re-enable all interruptible run tests.**
- **Cleanup.**
- **docs(changeset): Support sequences of nested graphs (like what `reduce` does).**
> interruptible run map

- .changeset/gentle-toys-happen.md
- packages/visual-editor/src/ui/elements/input/user-input.ts
> [visual-editor] Teach User Input to honor enums

- .changeset/strong-schools-applaud.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/human.ts
- packages/agent-kit/src/boards/looper.ts
- packages/agent-kit/src/boards/specialist.ts
- packages/visual-editor/public/agent.kit.json
- packages/visual-editor/public/example-boards/playground/chat-bot-2.json
- **Remove example inputs from Agent Kit.**
- **docs(changeset): Remove examples from Agent Kit components.**
> agent kit no examples

- .changeset/hip-houses-glow.md
- packages/agent-kit/agent.kit.json
- packages/gemini-kit/src/boards/gemini-generator.ts
- packages/visual-editor/public/agent.kit.json
- packages/visual-editor/src/ui/elements/input/user-input.ts
- **Remove example inputs from gemini-generator.**
- **docs(changeset): Remove example inputs from gemini-generator**
> remove gemini examples

- .changeset/swift-donkeys-move.md
- packages/board-server/src/server/boards/utils/run-board.ts
- **Check for empty object in run board.**
- **docs(changeset): Check for the empty object when supplying inputs.**
> run board empty object

- .changeset/neat-turtles-push.md
- packages/board-server/src/server/boards/index.ts
- packages/board-server/src/server/boards/utils/run-board.ts
- packages/board-server/src/server/cors.ts
- **Create a group to make inflateData work.**
- **Teach the CORS headers to parrot back the origin.**
- **docs(changeset): Various bug fixes.**
> board server fixes

- .changeset/olive-emus-jam.md
- packages/board-server/package.json
- packages/board-server/src/index.ts
- packages/board-server/src/server/home/index.ts
- **Add rudimentary home page.**
- **docs(changeset): Add a rudimentary home page.**
> board server home

- .changeset/fifty-cougars-laugh.md
- packages/breadboard/src/harness/events.ts
- packages/breadboard/src/harness/local-runner.ts
- packages/breadboard/src/harness/runner.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/src/utils/typed-event-target.ts
- packages/breadboard/tests/bgl/ask-for-secret.bgl.json
- packages/breadboard/tests/node/run/local-runner.ts
- **Sketch out Runner API.**
- **Rename to `LocalRunner`.**
- **Add test for `simple` bgl.**
- **Add test for `multi-level-invoke` bgl.**
- **Add `inputSchema` and `secretKeys` helpers.**
- **Remove unused imports.**
- **docs(changeset): Introduce HarnessRunner API (not yet exposed).**
> runner api again

- .changeset/nice-tools-shave.md
- packages/breadboard/src/harness/index.ts
- packages/breadboard/src/harness/local-runner.ts
- packages/breadboard/src/harness/types.ts
- packages/breadboard/tests/node/run/local-runner.ts
- packages/website/src/docs/reference/run-api.md
- **Add `HarnessRunner.addObserver`.**
- **Expose API and write docs.**
- **docs(changeset): Add the Run API.**
> harness runner

- .changeset/slow-rules-return.md
- packages/visual-editor/src/ui/elements/input/llm-input/llm-input.ts
> [visual-editor] Clear part cache when item changes

- .changeset/flat-tips-cough.md
- packages/breadboard/src/inspector/bubbled-node.ts
- packages/breadboard/src/inspector/graph.ts
- packages/breadboard/src/inspector/node.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/tests/inspector/index.ts
- packages/breadboard/tests/inspector/node.ts
- packages/website/src/docs/inspector/graph.md
- packages/website/src/docs/reference/run-api.md
- packages/website/src/docs/reference/runtime-semantics.md
- **Teach Inspector API about start tags.**
- **docs(changeset): Teach Inspector API about start tags.**
> start tags inspector

- packages/website/src/docs/kits/google-drive.md
Part of https://github.com/breadboard-ai/breadboard/issues/2177
> [google-drive] Document Google Drive Kit components

- packages/visual-editor/src/index.ts
- packages/visual-editor/src/ui/elements/google-drive/google-drive-file-id.ts
- packages/visual-editor/src/ui/elements/google-drive/google-drive-query.ts
- packages/visual-editor/src/ui/elements/input/user-input.ts
> [visual-editor] Use input plugins for google drive inputs

- packages/website/src/docs/guides/breadboard-from-scratch.md
> [docs] Remove duplicated sections (merge error)

- packages/website/src/docs/guides/breadboard-from-scratch.md
> [docs] Add Connection Server instructions

- packages/website/src/docs/guides/breadboard-from-scratch.md
> [docs] Add instructions for adding a Board Server to Visual Editor

- packages/website/src/docs/guides/breadboard-from-scratch.md
> [docs] Add instructions for linking Visual Editor to Connection Server

- packages/website/src/docs/guides/breadboard-from-scratch.md
> [docs] Add OAuth setup instructions

- packages/website/src/docs/guides/breadboard-from-scratch.md
> [docs] Properly indent sub-bullets

- packages/website/src/docs/guides/breadboard-from-scratch.md
> [docs] Add instructions to configure the Google Drive API in Connection Server

- packages/website/src/docs/guides/breadboard-from-scratch.md
> [docs] [BB from scratch] Update project creation

- packages/website/src/docs/guides/breadboard-from-scratch.md
> [docs] [BB from scratch] Add 'guide' tag

- .changeset/green-walls-confess.md
- packages/board-server/src/server/common.ts
- **Add proper mime types for CSS and JS.**
- **docs(changeset): Add proper MIME types for CSS and JS**
> mime types

- .changeset/three-taxis-sparkle.md
- packages/board-server/package.json
- packages/board-server/src/server/common.ts
- **docs(changeset): Register even more MIME types.**
- **Register even more MIME types.**
> more mime types

- .changeset/pretty-emus-cross.md
- packages/board-server/src/app/app.ts
- packages/board-server/src/server/boards/run.ts
- packages/board-server/tests/run-board.ts
- packages/breadboard/src/harness/remote-runner.ts
- packages/breadboard/src/remote/chunk-repair.ts
- packages/breadboard/src/remote/diagnostics-filter.ts
- packages/breadboard/src/remote/http.ts
- packages/breadboard/src/remote/run-graph-server.ts
- packages/breadboard/src/run/run-graph.ts
- packages/breadboard/tests/node/http/chunk-repair.ts
- packages/breadboard/tests/node/run/remote-runner.ts
- **Handle invalid or missing API key.**
- **Write a decent chunk repair transform.**
- **Add switchable remote config to app view.**
- **Correctly populate outputs for events.**
- **Stop sending `skip` events to client.**
- **docs(changeset): Teach app view to use RemoteRunner.**
> remote runner app

- .github/workflows/deploy-website.yml
- .github/workflows/labs-prototypes-ci.yml
- package-lock.json
- package.json
- packages/board-server/package.json
- packages/build/package.json
- packages/connection-server/package.json
- packages/google-drive-kit/package.json
- packages/python-wasm/package.json
- packages/website/package.json
Brings in the security improvement from https://github.com/google/wireit/pull/1146
> Update wireit and setup-github-caching action

- .changeset/polite-trainers-share.md
- packages/visual-editor/package.json
- packages/visual-editor/src/index.ts
> [visual-editor] Prevent multiple save calls happening in parallel

- .changeset/two-brooms-applaud.md
- packages/board-server/src/app/utils/light-observer.ts
- packages/breadboard/src/inspector/types.ts
- packages/breadboard/src/run/run-graph.ts
- packages/breadboard/src/types.ts
1. Adds `InspectableRunEdgeEvent`.
2. Adds in the current value to the `TraversalResult`.
> [breadboard/board-server] Add InspectableRunEdgeEvent

- packages/board-server/src/app/elements/activity-log/activity-log-lite.ts
- packages/shared-ui/src/elements/input/user-input.ts
- packages/shared-ui/src/elements/llm-output/llm-output-array.ts
A WIP for us to keep figuring out the edge stuff
> [board-server] Start using edge events

- .changeset/poor-knives-attack.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/human.ts
- packages/board-server/src/app/app.ts
- packages/board-server/src/app/elements/activity-log/activity-log-lite.ts
- packages/board-server/src/app/utils/content-schema.ts
- packages/board-server/src/app/utils/light-observer.ts
- packages/board-server/src/app/utils/types.ts
- packages/breadboard/src/harness/local-runner.ts
- packages/visual-editor/public/agent.kit.json
- **Prune LightObserver a bit.**
- **events -> log**
- **Fix a bug in Human where output was typed as LLMContent, but actual value was LLMContent array.**
- **Start inserting output edges before last node.**
- **Give access to pending result to Local Run input handlers.**
- **Functional bubbled inputs/outputs.**
- **Working inputs/outputs.**
- **docs(changeset): Implement edge-based UI in board-server (and fix a bunch of bugs elsewhere)**
> edges and nodes

- .changeset/tricky-bobcats-hope.md
- packages/board-server/src/app/app.ts
- packages/board-server/src/app/elements/activity-log/activity-log-lite.ts
- packages/board-server/src/app/utils/light-observer.ts
- packages/board-server/src/app/utils/types.ts
- packages/board-server/tests/run-board.ts
- packages/breadboard/src/remote/diagnostics-filter.ts
- **Remove unnecessary status-switching.**
- **Send less data to client.**
- **Render unknown objects as JSON.**
- **Teach LightObserver to use server data better.**
- **docs(changeset): Teach remote runner to send fewer bytes over the wire.**
> fewer bytes

- .changeset/stale-masks-clean.md
- packages/board-server/src/app/app.ts
- packages/board-server/src/app/elements/activity-log/activity-log-lite.ts
- packages/board-server/src/app/elements/elements.ts
- packages/board-server/src/app/elements/secret/secret.ts
- packages/board-server/src/app/events/events.ts
- packages/board-server/src/app/utils/light-observer.ts
- packages/shared-ui/src/elements/llm-output/llm-output-array.ts
> [board-server] Apply some polish to .app view

- packages/website/src/docs/reference/run-api.md
Fixes #2831
Just correcting a very minor typo.
> Corrected Run API example url typo

- .changeset/slimy-kids-train.md
- package-lock.json
- packages/board-server/src/app/app.ts
- packages/board-server/src/app/utils/light-observer.ts
- packages/visual-editor/public/example-boards/playground/openai-gpt-35-turbo.json
- **Catch up the jsons.**
- **Clone descriptor before modifying it, make run/stop actually work.**
- **Teach inputs to correctly set the end timestamp.**
- **Handle abort events in LightObserver.**
- **docs(changeset): Teach App view to stop/restart gracefully.**
> start stop app

- .changeset/kind-apes-cheat.md
- packages/board-server/src/app/app.ts
- **Handle multimodal content.**
- **docs(changeset): Teach App view to handle multimodal content.**
> app view multimodal

- .changeset/funny-plums-sneeze.md
- packages/board-server/package.json
- packages/board-server/src/app/app.ts
- packages/board-server/src/app/elements/nav/nav.ts
- packages/board-server/src/app/utils/invite.ts
- packages/board-server/src/app/utils/types.ts
- packages/board-server/src/server/boards/index.ts
- packages/board-server/src/server/boards/invite-list.ts
- packages/board-server/src/server/boards/invite-update.ts
- packages/board-server/src/server/boards/invoke.ts
- packages/board-server/src/server/boards/run.ts
- packages/board-server/src/server/boards/utils/board-api-parser.ts
- packages/board-server/src/server/boards/utils/verify-key.ts
- packages/board-server/src/server/home/index.ts
- packages/board-server/src/server/store.ts
- packages/board-server/src/server/types.ts
- packages/visual-editor/package.json
- packages/visual-editor/src/providers/remote.ts
- **Remember the board server key when users sign in.**
- **Start using board server key.**
- **Sketch out invite backend.**
- **Implement crappy UI for creating invite links.**
- **Somewhat working end-to-end.**
- **Organize invite-related code a bit.**
- **Make things prettier.**
- **Fix a bug with creating invite.**
- **Switch to use consistent query param in board server sign-in.**
- **docs(changeset): Introduce the invite links system for board server.**
- **Increment versions.**
> invite machinery

- packages/website/src/docs/build/build.md
> [website] A start on the build API docs

- package.json
Fixes #2749 
Thoughts? We could also plumb this into some automation or CI if we so wished, but would want some guidance on where to output the file.
> feat: adds a task to munge all markdown into a single file

- packages/website/src/docs/build/build.md
Documents how to express loops/cycles with the `loopback` function.
> [build] [website] Document loopback

- packages/website/src/docs/build/build.md
> [build] [website] Document converge function

- packages/website/src/docs/build/build.md
> [build] [website] Document constant function

- packages/website/src/docs/build/build.md
> [build] [website] Document polymorphism

- packages/build/README.md
- packages/website/src/docs/build/build.md
> [build] [website] Redirect build package README to website

- .changeset/chilled-deers-wait.md
- packages/board-server/package.json
- packages/shared-ui/src/directives/markdown.ts
- packages/shared-ui/src/elements/llm-output/llm-output.ts
- packages/visual-editor/package.json
- **Teach llm-output to display html preview instead of code.**
- **Set iframe height .**
- **Increment board-server and visual-editor versions.**
- **docs(changeset): Introduce HTML preview for llm-output.**
> html preview

- .changeset/shiny-panthers-tell.md
- packages/board-server/package.json
- packages/board-server/src/app/app.ts
- **Auto-start run.**
- **docs(changeset): Auto-start board run in app view.**
> auto start

- .changeset/real-terms-mix.md
- packages/board-server/package.json
- packages/board-server/src/app/app.ts
- packages/board-server/src/app/utils/visitor-state-manager.ts
- **Update package.json to track build deps correctly.**
- **Resolve the race condition with visitor state.**
- **docs(changeset): Fix a bug where visitor state raced with auto-run.**
> auto start actually

- .changeset/four-needles-perform.md
- packages/board-server/package.json
- packages/board-server/src/app/elements/nav/nav.ts
- packages/board-server/src/server/home/index.ts
- packages/visual-editor/package.json
- packages/visual-editor/src/providers/remote.ts
- **Remove the auto-sign in machinery (it can't work as-is).**
- **docs(changeset): Remove auto-sign-in machinery (it can't work as designed)**
> no auto sign in

- .changeset/wet-days-deliver.md
- packages/shared-ui/src/elements/connection/connection-broker.ts
- packages/shared-ui/tsconfig.json
- packages/visual-editor/.env.development
- packages/visual-editor/.env.production
- packages/visual-editor/src/index.ts
- packages/website/src/docs/guides/breadboard-from-scratch.md
> [visual-editor] Configure connection server URL via environment variable

- .changeset/light-needles-sparkle.md
- packages/visual-editor/package.json
> [visual-editor] Add environment files to wireit files group

- .changeset/five-crabs-unite.md
- packages/board-server/index.html
- packages/board-server/src/server/boards/get.ts
- packages/board-server/src/server/boards/index.ts
- packages/board-server/src/server/common.ts
- packages/board-server/src/server/types.ts
- **Add social preview tags.**
- **docs(changeset): Introduce social media previews for board server app view.**
> social preview

- .changeset/eight-ligers-check.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/specialist.ts
- packages/visual-editor/public/agent.kit.json
- packages/visual-editor/public/example-boards/playground/board-for-each.json
- packages/visual-editor/public/example-boards/playground/business-review-replier-demo.json
- packages/visual-editor/public/example-boards/playground/business-review-replier.json
- packages/visual-editor/public/example-boards/playground/object-manipulator.json
- **Make model selectable for Specialist.**
- **Update VE agent kit.**
- **Catch up jsons.**
- **docs(changeset): Teach Specialist to ask for a model.**
> specialist select model

- packages/board-server/src/router.ts
Should have been part of #2901
> [board-server] Delete unused var

- .changeset/eighty-pugs-explain.md
- packages/board-server/src/index.ts
- packages/board-server/src/server.ts
Part of #2889 and #2896 
This is a partial copy of this external branch, by @wfaithfull 
https://github.com/ExaDev/breadboard/blob/2889-board-server-sqlite/
This was done to avoid merge conflicts when this branch is pulled into local main.
> [board-server] Move server start into a separate module

- .changeset/gentle-colts-wash.md
- packages/board-server/package.json
Part of #2889 and #2896
Missed from #2905
> [board-server] Add new server.ts and router.ts to wireit file list

- .changeset/pretty-falcons-tan.md
- package-lock.json
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/looper.ts
- packages/visual-editor/public/agent.kit.json
- **Make Looper model switchable.**
- **docs(changeset): Make Looper model switchable.**
> looper switchable model

- .changeset/lemon-singers-rule.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/looper.ts
- packages/agent-kit/src/boards/specialist.ts
- packages/visual-editor/public/agent.kit.json
- **Deprecate bubbling `model` inputs.**
- **docs(changeset): Deprecate bubbling `model` inputs.**
> deprecate model inputs

- .changeset/itchy-badgers-eat.md
- .changeset/khaki-paws-melt.md
- packages/gemini-kit/src/index.ts
Missed a spot in previous PR, plus adding changeset files.
> [gemini-kit] Delete gemini-pro-vision (part 2)

- .changeset/khaki-panthers-fold.md
- packages/build/src/internal/common/value.ts
- packages/core-kit/src/nodes/code.ts
- packages/core-kit/tests/code_test.ts
Now you can do this:
```ts
const num = input({ type: "number" });
const nums = starInputs({ type: "number" })
code(
{ num, "*": nums },
{ sum: "number" },
({ num, ...nums }) => ({ /* ... */ })
);
```
> [core-kit] Support star ports in code helper

- .changeset/young-timers-reply.md
- .dockerignore
- packages/board-server/Dockerfile
- packages/board-server/README.md
- packages/board-server/src/server/proxy/secrets.ts
- **Teach dockerfile about firestore backend and slim down the build stage.**
- **Add a note about platform flag.**
- **docs(changeset): Teach dockerfile about firestore build and slim down the build process.**
> firestore dockerfile

- .changeset/mighty-hairs-destroy.md
- packages/breadboard/src/remote/http.ts
- **Include credentials in proxy client fetch.**
- **docs(changeset): Include credentials in proxy client fetch.**
> proxy credentials

- .changeset/kind-camels-love.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/package.json
- packages/agent-kit/src/boards/joiner.ts
- packages/agent-kit/src/generate-kit-manifest.ts
- packages/agent-kit/src/index.ts
- packages/agent-kit/src/kit.ts
- packages/visual-editor/public/agent.kit.json
- packages/visual-editor/public/example-boards/playground/board-for-each.json
- packages/visual-editor/public/example-boards/playground/business-review-replier-demo.json
- packages/visual-editor/public/example-boards/playground/business-review-replier.json
- packages/visual-editor/public/example-boards/playground/object-manipulator.json
Converts the first agent-kit board to the Build API.
> [agent-kit] Convert joiner to Build API

- .changeset/late-jobs-collect.md
- packages/shared-ui/src/elements/llm-output/llm-output.ts
> [shared-ui] Unclamp llm-output height

- .changeset/itchy-carpets-scream.md
- packages/board-server/package.json
- packages/board-server/src/server/proxy/index.ts
- packages/board-server/src/server/proxy/secrets.ts
- **Teach board server proxy about data store groups.**
- **Teach secrets that `STORAGE_BACKEND` may be empty.**
- **Bump the board server version.**
- **docs(changeset): Teach board server node proxy about data store groups.**
> board server proxy groups

- .changeset/unlucky-jokes-swim.md
- packages/breadboard/src/harness/events.ts
- packages/breadboard/src/harness/local-runner.ts
- packages/breadboard/src/harness/types.ts
- packages/shared-ui/src/elements/activity-log/activity-log.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/shared-ui/src/index.ts
- packages/shared-ui/src/utils/format-error.ts
- packages/shared-ui/src/utils/utils.ts
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/utils/secrets-helper.ts
- **Implement `next` event for Run API.**
- **Teach Run API to be re-entrant.**
- **Switch VE to use the Run API.**
- **Make stop work again.**
- **docs(changeset): Switch Visual Editor to use Run API.**
> ve run api

- packages/shared-ui/src/elements/editor/graph-node.ts
Helps with slightly bigger graphs
> [visual-editor] Tweak preview width

- .changeset/eight-lamps-visit.md
- packages/board-server/src/app/app.ts
- packages/board-server/src/app/elements/activity-log/activity-log-lite.ts
- packages/board-server/src/app/types/types.ts
- packages/board-server/src/app/utils/top-graph-observer.ts
- packages/board-server/src/app/utils/types.ts
- packages/breadboard/src/index.ts
- packages/shared-ui/src/types/types.ts
- packages/shared-ui/src/utils/top-graph-observer.ts
- packages/shared-ui/src/utils/utils.ts
- **Rename LightObserver to TopGraphObserver.**
- **Remove unused imports.**
- **Fix a gnarly deps.**
- **Move TopGraphObserver to `shared-ui`.**
- **docs(changeset): Move LightObserver to shared-ui as TopGraphObserver.**
> top graph observer

- packages/shared-ui/src/elements/editor/graph.ts
> [shared-ui] Add colors for joiner

- .changeset/thick-knives-sin.md
- packages/build/src/internal/board/board.ts
- packages/build/src/internal/board/serialize.ts
- packages/build/src/internal/define/definition.ts
- packages/build/src/internal/define/instance.ts
- packages/build/src/internal/kit.ts
- packages/build/src/test/kit_test.ts
This reverts commit f80e653037c5f14ac317012f8a88aaa7b8e6fa4a.
> Revert "[build] Serialize nested components with their kit-name if they are instantiated via a kit (#3015)"

- .changeset/bright-dogs-repeat.md
- packages/shared-ui/src/elements/editor/editor.ts
- packages/shared-ui/src/elements/editor/graph-renderer.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/shared-ui/src/types/types.ts
- packages/shared-ui/src/utils/top-graph-observer.ts
- packages/visual-editor/src/index.ts
- **Teach TGO to vend a TopGraphRunResult.**
- **Shift currentNode to TGO.**
- **Plumb edge values to GraphRenderer.**
- **docs(changeset): Plumb edge value data to the GraphRenderer.**
> tgo run result

- .changeset/yellow-shoes-bathe.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/worker.ts
- packages/agent-kit/src/context.ts
- packages/agent-kit/src/generate-kit-manifest.ts
- packages/agent-kit/src/kit.ts
- packages/visual-editor/public/agent.kit.json
> [agent-kit] Convert worker board to build API

- .changeset/eight-jobs-flash.md
- packages/board-server/src/app/app.ts
- packages/shared-ui/src/utils/top-graph-observer.ts
- **Unbreak App View.**
- **Only store top-level edge values in TGO.**
- **docs(changeset): Unbreak the app view and only store top graph edge values.**
> fix bugs again

- .changeset/few-poets-admire.md
- packages/shared-ui/src/elements/editor/editor.ts
- packages/shared-ui/src/elements/editor/graph-renderer.ts
- packages/shared-ui/src/elements/editor/graph.ts
- packages/shared-ui/src/types/types.ts
- packages/shared-ui/src/utils/top-graph-observer.ts
- packages/visual-editor/public/example-boards/playground/board-for-each.json
- packages/visual-editor/public/example-boards/playground/business-review-replier-demo.json
- packages/visual-editor/public/example-boards/playground/business-review-replier.json
- packages/visual-editor/public/example-boards/playground/chat-bot-2.json
- packages/visual-editor/public/example-boards/playground/object-manipulator.json
- **Add current edge so that it could be highlighted.**
- **Plumb through component activity.**
- **docs(changeset): Plumb through edge highlighting and inner activity.**
> better tgo

- .changeset/rude-bobcats-bake.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/boards/looper.bgl.json
- packages/agent-kit/boards/specialist.bgl.json
- packages/agent-kit/src/boards/looper.ts
- packages/agent-kit/src/boards/specialist.ts
- packages/gemini-kit/src/boards/gemini-generator.ts
- packages/visual-editor/public/agent.kit.json
- **Add "gemini-1.5-pro-exp-0827" model to the choices of Gemini-calling components.**
- **docs(changeset): Add "gemini-1.5-pro-exp-0827" to the choices in Gemini-calling components.**
> gemini 1.5 pro exp 0827

- .changeset/many-humans-mate.md
- packages/breadboard/src/inspector/run/conversions.ts
- packages/breadboard/src/inspector/run/event-manager.ts
- packages/breadboard/src/inspector/run/loader.ts
- packages/breadboard/src/inspector/run/nested-run.ts
- packages/breadboard/src/inspector/run/past-run.ts
- packages/breadboard/src/inspector/run/path-registry.ts
- packages/breadboard/src/inspector/run/replay.ts
- packages/breadboard/src/inspector/run/run-node-event.ts
- packages/breadboard/src/inspector/run/serializer.ts
- packages/breadboard/src/inspector/types.ts
- packages/shared-ui/src/elements/activity-log/activity-log-lite.ts
- packages/shared-ui/src/events/events.ts
- packages/visual-editor/src/index.ts
- **Plumb `bbrunselect` event.**
- **Remove prescient comment.**
- **Teach PastRun to be a real InspectableRun.**
- **Implement selecting runs.**
- **docs(changeset): Implement selecting runs and viewing them.**
> bb run select

- .changeset/tough-buses-pretend.md
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/runtime/board.ts
- packages/visual-editor/src/runtime/edit.ts
- packages/visual-editor/src/runtime/events.ts
- packages/visual-editor/src/runtime/run.ts
- packages/visual-editor/src/runtime/runtime.ts
- packages/visual-editor/src/runtime/types.ts
Includes a minor fix to runtime SPDX header dates
> [visual-editor] Restore Activity Log

- .changeset/funny-kids-deny.md
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/runtime/board.ts
- packages/visual-editor/src/runtime/events.ts
- **Start using runtime.run.getRunner everywhere in bb-main**
- **Teach bb-main to not freak out about the lack of SecretsHelper.**
- **Teach bb-main about tab close event.**
- **Close tabs before creating new runs.**
- **docs(changeset): Various fixes around the new runtime.**
> get runner bb main

- .changeset/wicked-jobs-switch.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/boards/human.bgl.json
- packages/agent-kit/src/boards/human.ts
- packages/agent-kit/src/generate-kit-manifest.ts
- packages/agent-kit/src/index.ts
- packages/agent-kit/src/kit.ts
- packages/agent-kit/tests/human.ts
- packages/visual-editor/public/agent.kit.json
- packages/visual-editor/public/example-boards/playground/board-for-each.json
- packages/visual-editor/public/example-boards/playground/business-review-replier-demo.json
- packages/visual-editor/public/example-boards/playground/business-review-replier.json
- packages/visual-editor/public/example-boards/playground/chat-bot-2.json
- packages/visual-editor/public/example-boards/playground/object-manipulator.json
> [agent-kit] Convert human board to Build API

- .changeset/wise-drinks-turn.md
- packages/shared-ui/src/elements/activity-log/activity-log.ts
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/utils/secrets-helper.ts
- **Teach SecretsHelper about timing of secret events arrival.**
- **docs(changeset): Teach SecretsHelper about the timing of secrets-related events.**
> secrets timing

- .changeset/three-lamps-explode.md
- packages/board-server/.env.development
- packages/board-server/.env.production
- packages/board-server/src/app/app.ts
- packages/board-server/src/app/elements/activity-log/activity-log-lite.ts
- packages/board-server/src/app/elements/secret/secret.ts
- packages/board-server/src/app/utils/settings-helper.ts
- packages/connection-server/package.json
- **Distinguish between app and shared activity log, for now.**
- **Teach app view about connection secrets.**
- **docs(changeset): Teach App View about OAuth connection secrets.**
> app connection secrets

- .changeset/strong-rocks-bow.md
- packages/shared-ui/src/elements/editor/editor.ts
- packages/shared-ui/src/elements/editor/graph-edge.ts
- packages/shared-ui/src/elements/editor/graph-renderer.ts
- packages/shared-ui/src/elements/editor/graph.ts
- packages/shared-ui/src/elements/overlay/edge-value.ts
- packages/shared-ui/src/events/events.ts
- packages/shared-ui/src/types/types.ts
- **Plumb edge value schema through to the overlay.**
- **docs(changeset): Plumb edge value schema to edge overlay**
> edge value schema

- .changeset/weak-coats-prove.md
- packages/shared-ui/src/elements/overlay/node-configurator.ts
- **Teach the sidebar not to jump in vertical mode.**
- **docs(changeset): Teach the sidebar not to jump in vertical mode.**
> no jump sidebar

- .changeset/pretty-jobs-watch.md
- packages/shared-ui/src/elements/editor/editor.ts
- packages/shared-ui/src/elements/editor/graph-renderer.ts
- packages/shared-ui/src/elements/editor/graph.ts
- packages/shared-ui/src/elements/overlay/edge-value.ts
- packages/shared-ui/src/elements/overlay/node-configurator.ts
- packages/shared-ui/src/types/types.ts
- packages/visual-editor/src/index.styles.ts
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/runtime/board.ts
> [visual-editor/shared-ui] Add multi-tab support

- .changeset/fuzzy-falcons-compare.md
- packages/shared-ui/src/elements/editor/editor.ts
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/runtime/board.ts
1. Re-uses tabs if they're already open.
2. Supports Cmd/Ctrl + click to create a new tab (instead of re-using tabs).
3. Fixes minor bug with tab closing.
> [shared-ui/visual-editor] Improve tab handling

- .changeset/honest-rings-knock.md
- packages/shared-ui/src/elements/editor/graph-node.ts
> [shared-ui] Account for output ports in node height calc

- packages/board-server/openapi.yaml
Fixes #3004
Created an OpenAPI spec for the board server.
> 3004 Board Server OpenAPI spec

- .changeset/nervous-cooks-impress.md
- packages/shared-ui/src/elements/activity-log/activity-log.ts
- packages/shared-ui/src/elements/input/user-input.ts
- packages/visual-editor/package.json
- packages/visual-editor/src/data/settings-store.ts
> [visual-editor/shared-ui] Add message for secrets and API keys

- .changeset/wicked-jobs-switch.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/boards/human.bgl.json
- packages/agent-kit/src/boards/human.ts
- packages/agent-kit/src/generate-kit-manifest.ts
- packages/agent-kit/src/index.ts
- packages/agent-kit/src/kit.ts
- packages/agent-kit/tests/human.ts
- packages/visual-editor/public/agent.kit.json
- packages/visual-editor/public/example-boards/playground/board-for-each.json
- packages/visual-editor/public/example-boards/playground/business-review-replier-demo.json
- packages/visual-editor/public/example-boards/playground/business-review-replier.json
- packages/visual-editor/public/example-boards/playground/chat-bot-2.json
- packages/visual-editor/public/example-boards/playground/object-manipulator.json
Redo of https://github.com/breadboard-ai/breadboard/pull/3082 to fix https://github.com/breadboard-ai/breadboard/issues/3099
The problem was that the output nodes were incorrectly arranged (the context and text outputs were supposed to go to one output node, but were going to two different ones). This happened because of an `id` assignment I shouldn't have included (actually setting output IDs this way is a feature I plan to remove from the build API since its confusing vs the newer way of using `outputNode`).
> [agent-kit] Convert human board to Build API (redo)

- .changeset/light-knives-turn.md
- packages/board-server/oauth/index.html
- packages/board-server/src/app/app.ts
- packages/board-server/src/server/common.ts
- packages/board-server/vite.config.ts
- **Teach board server to expose the oauth redirect.**
- **docs(changeset): Teach board server to expose oauth redirect.**
> board server oauth

- .changeset/grumpy-donuts-sleep.md
- packages/board-server/package.json
- packages/visual-editor/package.json
- **Update build deps to include env files.**
- **docs(changeset): Update build deps.**
> env files build deps

- .changeset/olive-frogs-lick.md
- packages/build/src/internal/type-system/json-schema.ts
- packages/build/src/test/input_test.ts
- packages/build/src/test/type-expressions/json-schema_test.ts
Oops, was passing a type expression instead of an actual JSON Schema.
> [build] Fix incorrect jsonSchema JSON Schema

- .changeset/silent-moles-study.md
- packages/shared-ui/src/elements/editor/editor.ts
- packages/shared-ui/src/elements/editor/graph-comment.ts
- packages/shared-ui/src/elements/editor/graph-node.ts
- packages/shared-ui/src/elements/editor/graph-renderer.ts
- packages/shared-ui/src/elements/editor/graph.ts
- packages/shared-ui/src/elements/editor/types.ts
- packages/shared-ui/src/elements/editor/utils.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/shared-ui/src/events/events.ts
- packages/shared-ui/src/utils/mode.ts
- **Make connected ports always show.**
- **Expand "collapse" to multistate for nodes and comments**
- **Introduce "advance" expansionState.**
- **Remove editor mode from editor.**
- **Teach overflow menu about expansion states.**
- **docs(changeset): Make "advanced ports" a per-component setting.**
> advanced advanced ports

- .changeset/chilled-singers-scream.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/src/boards/structured-worker.ts
- packages/agent-kit/src/generate-kit-manifest.ts
- packages/agent-kit/src/index.ts
- packages/agent-kit/src/kit.ts
- packages/visual-editor/public/agent.kit.json
> [agent-kit] Convert structured worker to build API

- .changeset/popular-doors-hug.md
- package-lock.json
- packages/breadboard/src/handler.ts
- packages/core-kit/src/nodes/run-javascript.ts
- packages/visual-editor/package.json
- **Properly terminate Workers in runJavascript.**
- **Throttle graph handler describer results.**
- **Increment VE version**
- **docs(changeset): Fix worker memory leak and throttle describers.**
> memory hunt

- .changeset/nasty-beers-boil.md
- packages/breadboard/src/editor/operations/add-edge.ts
- **Allow pasting star edges.**
- **docs(changeset): Allow pasting star edges.**
> paste star edges

- .changeset/mean-feet-shout.md
- packages/shared-ui/src/elements/overlay/node-configurator.ts
- packages/visual-editor/src/index.ts
> [shared-ui] Save pending configuration with board

- .changeset/cold-items-hang.md
- packages/shared-ui/src/elements/input/llm-input/llm-input.ts
- packages/visual-editor/src/index.ts
- **Remove spurious logging.**
- **Emit updates/re-render when adding a part.**
- **docs(changeset): Re-render and emit input event when adding parts in llm-input.**
> add part edit

- .changeset/pretty-dots-melt.md
- packages/shared-ui/src/elements/editor/graph-node-activity-marker.ts
- packages/shared-ui/src/elements/editor/graph-node.ts
- packages/shared-ui/src/elements/editor/graph-renderer.ts
- packages/shared-ui/src/elements/editor/graph.ts
- packages/shared-ui/src/elements/editor/types.ts
- packages/shared-ui/src/types/types.ts
- packages/shared-ui/src/utils/top-graph-observer/top-graph-observer.ts
- **Introduce TopGraphResult.nodeActivities.**
- **Start using nodeActivity**
- **docs(changeset): Provide node acitivities out of TopGraphObserver.**
> node activities

- .changeset/cuddly-experts-travel.md
- package-lock.json
- packages/breadboard/src/inspector/graph.ts
- **Catch up package-lock.json**
- **Feed static describer results to dynamic describer.**
- **docs(changeset): Feed static describer results to dynamic describer.**
> catch up package lock

- .changeset/cool-turtles-heal.md
- packages/breadboard/src/handler.ts
- packages/breadboard/src/inspector/graph.ts
- packages/breadboard/src/utils/hash.ts
- packages/breadboard/tests/node/utils/hash.ts
- **Add more robust error handling in dynamic describers.**
- **Add hash util**
- **Throttle describer results hashed by inputs.**
- **docs(changeset): Bug fixes for dynamic describers.**
> describer errors

- .changeset/spotty-kids-watch.md
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/runtime/board.ts
- packages/visual-editor/src/runtime/edit.ts
> [visual-editor] Create and use hashes for descriptor-based tabs

- .changeset/brown-actors-float.md
- packages/shared-ui/src/elements/overlay/edge-value.ts
- packages/shared-ui/src/elements/overlay/node-configurator.ts
> [shared-ui] Add minimize/maximize button to overlays

- .changeset/perfect-ties-design.md
- packages/shared-ui/src/utils/top-graph-observer/top-graph-observer.ts
- **Create node entry for the output component.**
- **docs(changeset): Ensure that the final node is included in TGO**
> highlight last

- .changeset/clean-trees-tan.md
- packages/schema/breadboard.schema.json
- packages/schema/src/graph.ts
- **Introduce `window` visual metadata to GraphMetadata.**
- **docs(changeset): Introduce GraphMetadata.visual.window.**
> graph metadata window

- .changeset/tough-kings-guess.md
- packages/shared-ui/src/elements/editor/editor.ts
- **Generate friendlier ID for Graph-based types.**
- **docs(changeset): Generate friendlier ID for Graph-based component types.**
> friendlier id

- .changeset/cold-ladybugs-argue.md
- packages/visual-editor/package.json
- packages/visual-editor/src/index.ts
- packages/visual-editor/src/runtime/board.ts
> [visual-editor] Teach editor about tab URLs

- .changeset/dry-carrots-clap.md
- packages/shared-ui/src/elements/nav/nav.ts
- packages/visual-editor/src/providers/indexed-db.ts
Now uses the title rather than the "file name"
> [visual-editor] Align IDB with Board Servers in nav

- .changeset/fuzzy-numbers-approve.md
- packages/shared-ui/src/elements/editor/graph-renderer.ts
> [shared-ui] Fix pinch zoom in read-only mode

- .changeset/silly-donkeys-clean.md
- packages/agent-kit/agent.kit.json
- packages/agent-kit/boards/looper.bgl.json
- packages/agent-kit/src/boards/looper.ts
- packages/visual-editor/public/agent.kit.json
- packages/visual-editor/public/example-boards/playground/looper-chat-test.json
- packages/visual-editor/public/example-boards/playground/looper-test.json
Fixes https://github.com/breadboard-ai/breadboard/issues/3210
> [agent-kit] Set titles for done and loop outputs of looper

- .changeset/old-dogs-tease.md
- packages/visual-editor/src/index.ts
> [visual-editor] Restore board URL copy

- .changeset/fast-pandas-jump.md
- packages/shared-ui/src/elements/editor/editor.ts
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/shared-ui/src/events/events.ts
- packages/visual-editor/src/index.ts
> [visual-editor/shared-ui] Recover from bad node types

- .changeset/hot-cycles-camp.md
- packages/shared-ui/src/elements/ui-controller/ui-controller.ts
- packages/visual-editor/src/index.ts
> [visual-editor] Update URL whenever a tab closes

- .changeset/popular-news-give.md
- packages/shared-ui/src/elements/editor/editor.ts
- packages/shared-ui/src/elements/editor/graph-node-activity-marker.ts
- packages/shared-ui/src/elements/editor/graph-node.ts
- packages/shared-ui/src/elements/editor/graph-renderer.ts
- packages/shared-ui/src/elements/editor/graph.ts
- packages/shared-ui/src/elements/editor/types.ts
- packages/shared-ui/src/elements/elements.ts
- packages/shared-ui/src/elements/tooltip/tooltip.ts
- packages/shared-ui/src/events/events.ts
- packages/visual-editor/src/data/settings-store.ts
- packages/visual-editor/src/index.ts
> [visual-editor/shared-ui] Add tooltip support

- packages/agent-kit/src/index.ts
- packages/agent-kit/src/samples/poet.ts
- packages/agent-kit/src/samples/summarizer.ts
Fixes https://github.com/breadboard-ai/breadboard/issues/2341
> [agent-kit] Convert samples to build API

- .changeset/sweet-starfishes-rescue.md
- packages/shared-ui/src/elements/editor/editor.ts
- **Remove the spurious null coalescing op.**
- **docs(changeset): Remove the spurious null-coalescing operator.**
> spurious nullish

- .changeset/dirty-dryers-refuse.md
- package-lock.json
- packages/breadboard/src/data/default-data-store.ts
- packages/breadboard/src/data/types.ts
- packages/breadboard/src/inspector/schemas.ts
- packages/breadboard/tests/inspector/describe.ts
- packages/core-kit/src/index.ts
- packages/core-kit/src/nodes/retrieveData.ts
- packages/core-kit/src/nodes/storeData.ts
- **Sketch out KV data store components.**
- **Capitalize "schema" in input/output compoennts.**
- **Add titles.**
- **Use schema to define values to store and retrieve.**
- **Return schema as notFound output.**
- **Mark components as experimental.**
- **Remove spurious logging.**
- **docs(changeset): Introduce experimental storeData and retrieveData components in Core Kit.**
> kv data store

- .changeset/silver-suits-sing.md
- packages/visual-editor/public/example-boards/examples/array-split-jsonata.bgl.json
- packages/visual-editor/public/example-boards/examples/blank.json
- packages/visual-editor/public/example-boards/examples/google-books-api.json
- packages/visual-editor/public/example-boards/examples/hello-specialist.bgl.json
- packages/visual-editor/public/example-boards/examples/librarian.bgl.json
- packages/visual-editor/public/example-boards/examples/novel-generator.bgl.json
- packages/visual-editor/public/example-boards/examples/rhyme-of-the-day.bgl.json
- packages/visual-editor/public/example-boards/examples/social-media-post-creator.bgl.json
- packages/visual-editor/public/example-boards/examples/tool-novel-developer.bgl.json
- packages/visual-editor/public/example-boards/examples/tool-novel-outliner.bgl.json
- packages/visual-editor/public/example-boards/examples/tool-todays-date.bgl.json
> [visual-editor] Update example graph layouts

- packages/shared-ui/src/elements/editor/editor.ts
- packages/shared-ui/src/elements/input/array/array-editor.ts
- packages/shared-ui/src/elements/input/board-selector/board-selector.ts
- packages/shared-ui/src/elements/input/llm-input/llm-input.ts
- packages/shared-ui/src/elements/overflow-menu/overflow-menu.ts
- packages/visual-editor/src/index.styles.ts
- packages/visual-editor/src/index.ts
> [shared-ui/visual-editor] Various small UI tweaks

- .changeset/selfish-radios-own.md
- packages/shared-ui/src/utils/top-graph-observer/top-graph-observer.ts
- **Account for error state in TGO status.**
- **docs(changeset): Account for "error" in TGO state.**
> tgo error stopped
