.changeset/strong-pianos-mate.md
packages/visual-editor/src/runtime/edit.ts

[visual-editor] Autosave board when top level info changes

---

.changeset/clever-colts-perform.md
packages/visual-editor/src/index.ts

- **Remove the spurious requestUpdate when asking for secrets, which now triggers the infinite loop of doom.**
- **docs(changeset): Remove the extra requestUpdate that triggered the loop of doom.**

loop of doom

---

.changeset/nine-ways-jog.md
packages/breadboard/src/inspector/run/past-run.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/providers/indexed-db.ts

A few small-but-good tidyings from when @dglazkov and I were looking for the fix for the [loop of doom](https://github.com/breadboard-ai/breadboard/pull/3291).

[visual-editor/breadboard] Tidy up

---

.changeset/twenty-spoons-rule.md
packages/shared-ui/src/elements/activity-log/activity-log.ts

- **Remove auto-submit machinery.**
- **docs(changeset): Remove auto-submit machinery**

no auto submit

---

.changeset/large-guests-smell.md
packages/breadboard/src/loader/types.ts
packages/idb-board-server/src/idb-board-server.ts
packages/idb-board-server/src/index.ts
packages/visual-editor/src/runtime/board.ts
packages/visual-editor/src/runtime/runtime.ts

[idb-board-server] Auto-migrate IDB `GraphProvider` boards

---

.changeset/wet-ears-relax.md
package-lock.json
packages/board-server-management/.eslintrc
packages/board-server-management/.gitignore
packages/board-server-management/README.md
packages/board-server-management/package.json
packages/board-server-management/src/index.ts
packages/board-server-management/tsconfig.json
packages/idb-board-server/README.md
packages/idb-board-server/src/idb-board-server.ts
packages/remote-board-server/.eslintrc
packages/remote-board-server/.gitignore
packages/remote-board-server/README.md
packages/remote-board-server/package.json
packages/remote-board-server/src/index.ts
packages/remote-board-server/tsconfig.json
packages/visual-editor/package.json
packages/visual-editor/src/runtime/runtime.ts
tsconfig.json

[board-server] Add board server management and remote board server packages

---

.changeset/mighty-ladybugs-care.md
package-lock.json
packages/board-server-management/package.json
packages/board-server-management/src/index.ts
packages/breadboard/src/loader/types.ts
packages/idb-board-server/src/idb-board-server.ts
packages/remote-board-server/src/index.ts
packages/remote-board-server/src/remote-board-server.ts
packages/remote-board-server/src/utils/kit-loader.ts
packages/visual-editor/src/providers/examples.ts
packages/visual-editor/src/providers/remote.ts

[board-server] Implement remote board server

---

.changeset/yellow-kids-design.md
packages/agent-kit/.gitignore
packages/agent-kit/agent.kit.json
packages/agent-kit/boards/specialist.bgl.json
packages/agent-kit/package.json
packages/agent-kit/src/boards/specialist.ts
packages/agent-kit/src/js-components/substitute.ts
packages/agent-kit/src/templating.ts
packages/agent-kit/src/util.ts
packages/agent-kit/tests/templating.ts
packages/agent-kit/tsconfig.json
packages/visual-editor/public/agent.kit.json

Demonstrates how to use the new build-code package to write `runJavascript` components which get automatically bundled + schema generated.

[agent-kit] Use new build-code package for substitute component

---

.changeset/clean-islands-drive.md
.gitignore
packages/board-server/scripts/create-accounts.ts
packages/board-server/src/server/storage-providers/firestore.ts
packages/board-server/src/server/store.ts

- **Allow creating multiple accounts in batch**
- **docs(changeset): Add a script for batch-creating accounts**

board server create accounts

---

.changeset/small-dingos-cough.md
packages/shared-ui/src/elements/overlay/overlay.ts

[shared-ui] Tweak corner radius

---

.changeset/thin-clouds-sell.md
packages/build/src/internal/kit.ts
packages/shared-ui/src/elements/editor/ribbon.ts
packages/visual-editor/src/index.ts

- **Add "Copy Preview URL" to the copy menu.**
- **Set URL on the component board.**
- **docs(changeset): Set url for the component board.**

fix client only

---

.changeset/curly-cheetahs-worry.md
packages/board-server/package.json
packages/board-server/src/server/boards/utils/board-server-provider.ts
packages/board-server/src/server/boards/utils/run-board.ts

- **Teach board server to serve own boards internally.**
- **docs(changeset): Teach board server to serve own boards internally.**

serve own boards

---

.changeset/perfect-eagles-bake.md
packages/shared-ui/src/elements/input/schema-editor/streamlined-schema-editor.ts

[shared-ui] Improve the Schema Editor

---

.changeset/wise-socks-breathe.md
packages/board-server-management/src/index.ts
packages/breadboard/src/loader/types.ts
packages/idb-board-server/src/idb-board-server.ts
packages/remote-board-server/src/remote-board-server.ts
packages/visual-editor/src/runtime/board.ts
packages/visual-editor/src/runtime/edit.ts
packages/visual-editor/src/runtime/events.ts
packages/visual-editor/src/runtime/runtime.ts

[board-server] Do some plumbing work for extensions

---

.changeset/witty-seals-rule.md
packages/shared-ui/src/elements/input/schema-editor/streamlined-schema-editor.ts

- **Add id to the schema editor (readonly for now)**
- **docs(changeset): Display ID of the property in the Schema editor.**

schema editor id

---

.changeset/rich-toes-enjoy.md
packages/breadboard/src/editor/blank.ts

- **Remove spurious `examples` field from the blank LLMContent config.**
- **docs(changeset): Remove spurious "examples" property from blank LLM Content config.**

refine blank llmcontent

---

.changeset/cyan-rice-sleep.md
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/editor/utils.ts

- **Make constant edge pasteable.**
- **docs(changeset): Teach paste machinery about constant edges.**

pasteable constant edges

---

packages/website/src/docs/reference/board-run-api-endpoint.md
samples/endpoint/browser/README.md

- **Fix the link on the sample**
- **Update docs.**
- **Add a "Human" component cheat sheet.**
- **Add the note about entire history.**

more samples

---

.changeset/tall-weeks-dance.md
package-lock.json
packages/agent-kit/tests/templating.ts
packages/board-server/package.json
packages/breadboard/src/data/common.ts
packages/breadboard/src/data/default-data-store.ts
packages/breadboard/src/data/index.ts
packages/breadboard/src/data/inflate-deflate.ts
packages/breadboard/src/data/types.ts
packages/breadboard/src/types.ts
packages/breadboard/tests/inspector/default-data-store.ts
packages/data-store/package.json
packages/data-store/src/run/idb-run-store.ts
packages/shared-ui/src/elements/input/audio/audio.ts
packages/shared-ui/src/elements/input/drawable/drawable.ts
packages/shared-ui/src/elements/input/llm-input/llm-input-array.ts
packages/shared-ui/src/elements/input/llm-input/llm-input.ts
packages/shared-ui/src/elements/input/schema-editor/schema-editor.ts
packages/shared-ui/src/elements/input/schema-editor/streamlined-schema-editor.ts
packages/shared-ui/src/elements/input/user-input.ts
packages/shared-ui/src/elements/input/webcam/webcam.ts
packages/shared-ui/src/elements/llm-output/llm-output-array.ts
packages/shared-ui/src/elements/llm-output/llm-output.ts
packages/types/src/index.ts
packages/types/src/llm-content.ts

- **Move LLMContent to `types` package.**
- **Clean up remaining references.**
- **More clean up.**
- **docs(changeset): Move LLMContent to types package.**

llmcontent types

---

packages/shared-ui/src/elements/editor/ribbon.ts
packages/visual-editor/src/index.styles.ts

Fixes https://github.com/breadboard-ai/breadboard/issues/3354
Fixes https://github.com/breadboard-ai/breadboard/issues/3355

[shared-ui] Minor fixes

---

.changeset/slow-masks-relax.md
packages/example-board-server/src/example-board-server.ts
packages/shared-ui/src/elements/nav/nav.ts

[visual-editor] Ensure nav copes with Provider -> BSS switch

---

packages/board-server-management/src/index.ts
packages/breadboard/src/loader/types.ts
packages/filesystem-board-server/src/filesystem-board-server.ts
packages/remote-board-server/src/remote-board-server.ts
packages/shared-ui/src/elements/nav/nav.ts
packages/shared-ui/src/elements/overlay/provider.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/board.ts
packages/visual-editor/src/runtime/events.ts
packages/visual-editor/src/runtime/runtime.ts

[board-server] Allow management of Board Servers

---

.changeset/swift-ducks-punch.md
packages/remote-board-server/src/remote-board-server.ts

[board-server] Remove log

---

.changeset/gold-vans-cover.md
packages/idb-board-server/src/idb-board-server.ts
packages/remote-board-server/src/remote-board-server.ts

[board-server] Add BSK to remote board server

---

.changeset/proud-rabbits-give.md
packages/board-server/src/server/storage-providers/firestore.ts
packages/board-server/src/server/store.ts

- **Provide description when listing boards.**
- **docs(changeset): Provide board descriptions when listing boards.**

boards descriptions

---

.changeset/twelve-snakes-join.md
packages/shared-ui/src/elements/editor/graph.ts

[shared-ui] Fix star port loop

---

.changeset/shaggy-lizards-glow.md
packages/shared-ui/src/elements/input/llm-input/llm-input.ts

Fixes #3437
I wish this weren't necessary, but transforms create containing blocks so here we are.

[shared-ui] Add location proxy to LLM Input

---

.changeset/blue-items-cheer.md
packages/shared-ui/src/elements/overlay/board-activity.ts
packages/shared-ui/src/elements/overlay/drag-dock-overlay.ts

[shared-ui] Add back button to board activity overlay

---

.changeset/gentle-mugs-build.md
packages/board-server/src/server/storage-providers/firestore.ts

- **Allow empty descriptions.**
- **docs(changeset): Allow undefined descriptions.**

empty descriptions

---

.changeset/twenty-tips-judge.md
packages/core-kit/src/nodes/fetch.ts

- **Teach fetch that body is a string sometimes.**
- **docs(changeset): Teach fetch that body can be a string.**

fetch string

---

.changeset/dirty-fans-lick.md
packages/shared-ui/src/elements/activity-log/activity-log.styles.ts
packages/shared-ui/src/elements/activity-log/activity-log.ts
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/editor/graph.ts
packages/shared-ui/src/elements/input/user-input.ts
packages/shared-ui/src/elements/overlay/board-activity.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/board.ts

Spent some time building out boards. These are some of the rougher edges I've tried to smooth out.

[shared-ui/visual-editor] Various QoL improvements

---

.changeset/tasty-goats-serve.md
package-lock.json
packages/board-server/package.json
packages/board-server/src/router.ts
packages/board-server/src/server.ts
packages/board-server/src/server/blobs/create.ts
packages/board-server/src/server/blobs/index.ts
packages/board-server/src/server/blobs/serve.ts
packages/board-server/src/server/boards/index.ts
packages/board-server/src/server/boards/utils/blob-store.ts
packages/board-server/src/server/common.ts
packages/board-server/src/server/config.ts
packages/board-server/src/server/types.ts
packages/breadboard/src/data/common.ts
packages/breadboard/src/data/inflate-deflate.ts

- **Sketch out the blobs API endpoint.**
- **Blob store working end to end.**
- **Short-circuit storedParts with https URLs.**
- **docs(changeset): Introduce board server blobs API endpoint**

blobs api endpoint

---

.changeset/twelve-emus-hunt.md
packages/breadboard/src/harness/local.ts
packages/breadboard/src/run/run-graph.ts
packages/breadboard/src/types.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/utils/run-node.ts

- **Plumb stopAfter, but not use it yet.**
- **docs(changeset): Implement "stopAfter" run argument (but not yet use it).**

stop after

---

.changeset/blue-students-develop.md
packages/shared-ui/src/elements/editor/graph-node.ts
packages/shared-ui/src/elements/overlay/node-configurator.ts
packages/shared-ui/src/types/types.ts
packages/visual-editor/src/data/settings-store.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/edit.ts

[visual-editor/shared-ui] Show node type descriptions by default

---

.changeset/flat-cameras-carry.md
packages/breadboard/src/run/run-graph.ts
packages/shared-ui/src/elements/overlay/board-activity.ts
packages/shared-ui/src/utils/top-graph-observer/node-information.ts
packages/shared-ui/src/utils/top-graph-observer/top-graph-observer.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/utils/run-node.ts

- **Split NodeInformation off into its own class.**
- **Roughly working step-by-step.**
- **Show current node highlight for input and output components.**
- **Remove last incomplete event entry from the activity log.**
- **Introduce initial TGO result state.**
- **docs(changeset): Teach Visual Editor to run step by step.**

step by step

---

.changeset/nine-peas-flash.md
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/events/events.ts
packages/visual-editor/src/index.ts

[visual-editor/shared-ui] Cancel any pending autosave when a user has interacted

---

.changeset/little-planes-lay.md
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/editor/graph-edge.ts
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/overlay/edge-value.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/types/types.ts
packages/visual-editor/src/index.ts

[shared-ui/visual-editor] Add "regenerate value" button

---

.changeset/silver-spiders-develop.md
packages/shared-ui/src/elements/editor/graph-node-activity-marker.ts

[shared-ui] Fix Activity Marker line height

---

.changeset/eighty-needles-fix.md
packages/shared-ui/src/utils/top-graph-observer/edge-value-store.ts

- **Add outgoing edges along with incoming edges.**
- **docs(changeset): Fix the problem where outgoing edges aren't cleared on edit.**

outgoing and incoming fix

---

.changeset/great-phones-attack.md
packages/shared-ui/src/elements/activity-log/activity-log.styles.ts
packages/shared-ui/src/elements/activity-log/activity-log.ts
packages/shared-ui/src/utils/format-error.ts
packages/visual-editor/src/index.ts

Fixes #3514
Applies to both the toast and the Activity Log

[shared-ui] Improve error rendering

---

.changeset/slimy-grapes-roll.md
packages/shared-ui/src/elements/input/user-input.ts
packages/shared-ui/src/utils/index.ts

Fixes #3209
Using the lesser-known-but-really-rather-good `<datalist>` element.

[shared-ui] Fix user choices

---

.changeset/curly-readers-sin.md
packages/shared-ui/src/utils/top-graph-observer/top-graph-observer.ts

- **Mark edge values as consumed at nodeend.**
- **docs(changeset): Set edge values to "consumed" on nodeend.**

run node polish

---

.changeset/poor-pants-think.md
packages/breadboard/src/inspector/run/loader.ts
packages/breadboard/src/inspector/run/serializer.ts
packages/breadboard/tests/inspector/observer-load.ts
packages/shared-ui/src/utils/top-graph-observer/top-graph-observer.ts

- **Make sure output component also updatee edge value state.**
- **Remove unused code.**
- **Remember node id when serializing nodeend.**
- **Update unit tests.**
- **docs(changeset): Unbreak serialization.**

fix bugs run node

---

.changeset/five-experts-suffer.md
package-lock.json
packages/agent-kit/package.json
packages/breadboard-cli/package.json
packages/google-drive-kit/.gitignore
packages/google-drive-kit/package.json
packages/google-drive-kit/src/components/context-to-slides.ts
packages/google-drive-kit/src/index.ts
packages/google-drive-kit/src/internal/context-to-slides.ts
packages/google-drive-kit/src/js-components/context-to-slides.ts
packages/google-drive-kit/src/js-components/context-to-title.ts
packages/google-drive-kit/src/js-components/get-deck-metadata.ts
packages/google-drive-kit/src/js-components/get-presentation-url.ts
packages/google-drive-kit/src/test/context-to-slides_test.ts
packages/google-drive-kit/tsconfig-code-build.json
packages/shared-ui/src/elements/overlay/component-selector.ts
packages/visual-editor/package.json
packages/visual-editor/public/styles/global.css

- **Start sketching out contextToSlides.**
- **Implement image parts.**
- **Build-code scaffolding in place**
- **Add node types dev deps.**
- **Working component.**
- **Give it icons.**
- **Fix a bug in title conversion.**
- **Tweaks/polish.**
- **docs(changeset): Introduce "Context To Slides" component.**
- **Fix up unit tests.**

context to slides

---

.changeset/lazy-toys-attack.md
package-lock.json
packages/breadboard-cli/package.json
packages/breadboard/src/handler.ts
packages/breadboard/src/inspector/kits.ts
packages/manifest/bbm.schema.json
packages/remote-board-server/src/remote-board-server.ts
packages/schema/breadboard.schema.json
packages/shared-ui/src/elements/board-details/board-details.ts
packages/shared-ui/src/elements/overlay/board-edit.ts
packages/shared-ui/src/events/events.ts
packages/types/src/graph-descriptor.ts
packages/visual-editor/package.json
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/edit.ts

- **Add a `component` GraphTag.**
- **Plumb "Component" UI (sorry Paul!)**
- **Add "components" kit for each user.**
- **docs(changeset): Introduce "component" tag and user custom kits.**

component tag

---

packages/core-kit/src/nodes/secrets.ts

Remove export declaration from types that are unused outside of this module.
Remove code that parses input as a JSON array.
Fixes #3574

Cleanup of secrets handler in core kit.

---

.changeset/swift-ducks-tickle.md
packages/shared-ui/src/elements/input/llm-input/llm-input.ts

[shared-ui] Fix LLM Input menu when items is disallowed

---

.changeset/twelve-keys-breathe.md
packages/google-drive-kit/src/components/get-breadboard-folder.ts
packages/google-drive-kit/src/components/list-files.ts
packages/google-drive-kit/src/index.ts
packages/google-drive-kit/src/types.ts

- **docs(changeset): Add an experimental "Get Breadboard Folder" component.**
- **Implement "Get Breadboard Folder".**

get breadboad folder

---

.changeset/sharp-experts-bathe.md
package-lock.json
packages/board-server-management/package.json
packages/board-server-management/src/index.ts
packages/google-drive-kit/src/board-server/server.ts
packages/google-drive-kit/src/index.ts
packages/shared-ui/src/elements/overlay/provider.ts
packages/visual-editor/src/data/settings-store.ts
packages/visual-editor/src/index.ts

- **Don't collapse nodes by default.**
- **Add "Google Drive Board Server" setting.**
- **Plumb through adding new Google Drive server.**
- **Introduce (entirely stubbed out) GoogleDriveBoardServer.**
- **docs(changeset): Introduce (entirely stubbed out) Google Drive board server.**

drive board server

---

.changeset/selfish-owls-check.md
packages/board-server-management/src/index.ts
packages/google-drive-kit/src/board-server/access.ts
packages/google-drive-kit/src/board-server/api.ts
packages/google-drive-kit/src/board-server/server.ts
packages/shared-ui/src/elements/google-drive/google-drive-server-picker.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/board.ts
packages/visual-editor/src/runtime/runtime.ts

- **Don't pass connection id to google drive -- it's always the same.**
- **Split off Drive API to separate file.**
- **Store board titles, descriptions, and tags.**
- **docs(changeset): Teach Google Drive Board Server to save board metadata.**

google drive again

---

.changeset/new-buttons-unite.md
packages/shared-ui/src/elements/connection/connection-input.ts
packages/shared-ui/src/elements/connection/connection-signin.ts
packages/shared-ui/src/elements/google-drive/google-drive-server-picker.ts
packages/shared-ui/src/elements/overlay/provider.ts
packages/shared-ui/src/events/events.ts
packages/visual-editor/src/index.ts

Working on https://github.com/breadboard-ai/breadboard/issues/3595

[shared-ui] Improve UX of GDrive Board Server

---

.changeset/eighty-tips-look.md
packages/google-drive-kit/src/board-server/server.ts

[board-server] Remove GDrive from list if folder 404s

---

.changeset/sixty-worms-greet.md
packages/google-drive-kit/src/board-server/server.ts
packages/google-drive-kit/src/components/get-breadboard-folder.ts
packages/google-drive-kit/src/components/load-context-from-drive.ts
packages/google-drive-kit/src/components/save-context-to-drive.ts
packages/google-drive-kit/src/index.ts
packages/google-drive-kit/src/internal/headers.ts

- **Sketch out Save Context To Drive.**
- **Narrow down the board server list to retrieve only application/json.**
- **Working Save Context to Drive**
- **Working "Save Context to Drive".**
- **Add explicit "Not Found" output.**
- **docs(changeset): Introduce "Save Context to Drive" and "Load Context from Drive" components.**

save context to drive

---

.changeset/dry-moose-film.md
packages/core-kit/src/index.ts
packages/core-kit/src/nodes/run-module.ts

- **Stub out `runModule` component.**
- **Working runModule in browser.**
- **Meh error handling**
- **Mark runModule as experimental.**
- **docs(changeset): Introduce `runModule` component (experimental).**

run module

---

.changeset/tasty-gifts-swim.md
packages/board-server-management/src/index.ts

[board-server] Handle non-existent legacy database

---

packages/shared-ui/src/elements/overlay/node-configurator.ts
packages/visual-editor/src/index.ts

[shared-ui] Prevent edits when looking at readonly node configurations

---

.changeset/weak-cherries-lay.md
packages/shared-ui/src/elements/input/llm-input/llm-input-array.ts
packages/shared-ui/src/elements/input/llm-input/llm-input.ts
packages/shared-ui/src/elements/input/user-input.ts

[shared-ui] Attempt autofocus when running boards

---

.changeset/three-dolphins-yawn.md
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/input/schema-editor/schema-editor.ts
packages/shared-ui/src/elements/input/schema-editor/streamlined-schema-editor.ts

Allow underscores in IDs and ad-hoc port names

---

.changeset/slimy-avocados-rule.md
packages/shared-ui/src/elements/editor/ribbon.ts
packages/shared-ui/src/elements/overflow-menu/overflow-menu.ts
packages/shared-ui/src/events/events.ts

[shared-ui] Add support for secondary actions on overflow menus

---

.changeset/ten-squids-talk.md
packages/shared-ui/src/elements/input/user-input.ts

[shared-ui] Show board selector when needed

---

.changeset/little-tips-pull.md
packages/shared-ui/src/elements/input/llm-input/llm-input.ts
packages/shared-ui/src/elements/overflow-menu/overflow-menu.ts

[shared-ui] Fix stale LLM Input data

---

.changeset/itchy-brooms-swim.md
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/input/schema-editor/schema-editor.ts
packages/shared-ui/src/elements/input/schema-editor/streamlined-schema-editor.ts

[shared-ui] Prevent leading numbers at the start of IDs

---

.changeset/chatty-gifts-sell.md
packages/core-kit/src/nodes/run-module.ts
packages/visual-editor/src/sandbox/index.ts

- **Populate node descriptor correctly when setting up capabilities.**
- **Make built-in runModule throw an error.**
- **docs(changeset): Fixes to jsandbox run**

jsandbox fixes

---

.changeset/smooth-years-provide.md
packages/jsandbox/src/node.ts
packages/jsandbox/src/types.ts
packages/jsandbox/src/web.ts
packages/jsandbox/tests/console.ts
packages/jsandbox/tests/describe.ts
packages/jsandbox/tests/index.ts
packages/jsandbox/tests/modules.ts
packages/visual-editor/src/runtime/board.ts
packages/visual-editor/src/sandbox/index.ts

- **Pass modules as part of invoke/describe.**
- **Switch to pass module spec during invoke/describe.**
- **docs(changeset): Pass module spec at invoke/describe time.**

runmodule component

---

.changeset/great-bees-hear.md
packages/breadboard/src/editor/graph.ts
packages/breadboard/src/inspector/graph.ts
packages/breadboard/src/inspector/node.ts
packages/breadboard/src/inspector/run/describe-cache.ts
packages/breadboard/src/inspector/types.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts
packages/visual-editor/src/index.ts

- **Start caching describer results.**
- **docs(changeset): Start caching describer results.**

cache describer results

---

packages/gemini-kit/src/boards/nano-generator.ts

Fixed the code to adhere to the latest API.
P.S: Not able to build the app on node v20.

fix: use languageModel

---

.changeset/thirty-waves-shake.md
package-lock.json
packages/breadboard/src/inspector/graph.ts
packages/breadboard/src/inspector/run/describe-cache.ts
packages/breadboard/src/inspector/types.ts
packages/visual-editor/src/index.ts

- **Make cache actually async.**
- **Skip visualOnly events.**
- **docs(changeset): Make describer cache async.**

async describer cache

---

.changeset/smooth-pears-listen.md
packages/google-drive-kit/boards/readFromDoc.bgl.json
packages/google-drive-kit/google-drive.kit.json
packages/google-drive-kit/src/bgl/read-from-doc.bgl.json
packages/visual-editor/public/google-drive.kit.json

- **Fix schema for "Read from doc".**
- **docs(changeset): Fix up schema in "Read From Doc".**

fix schema read from doc

---

.changeset/tidy-toys-shop.md
packages/shared-ui/src/elements/input/code-editor/code-editor.ts
packages/shared-ui/src/elements/module-editor/module-editor.ts
packages/shared-ui/src/events/events.ts

[shared-ui] Teach Module Editor to format on save

---

.changeset/rotten-dragons-help.md
packages/shared-ui/src/elements/input/code-editor/code-editor.ts
packages/shared-ui/src/elements/input/user-input.ts

[shared-ui] Minor fixes for runJavascript rendering

---

.changeset/tough-buttons-relax.md
packages/shared-ui/src/elements/module-editor/module-editor.ts
packages/shared-ui/src/elements/module-editor/ribbon.ts
packages/shared-ui/src/events/events.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/edit.ts

[shared-ui/visual-editor] Teach Visual Editor how to change module language

---

.changeset/tiny-vans-train.md
packages/visual-editor/src/index.ts
packages/visual-editor/src/utils/default-module-content.ts

[shared-ui] Set module source based on default type

---

.changeset/dirty-elephants-suffer.md
packages/shared-ui/src/elements/module-editor/module-editor.ts

[shared-ui] Add support for JS sources

---

.changeset/eighty-beans-exist.md
packages/shared-ui/src/elements/input/code-editor/code-editor.ts
packages/shared-ui/src/elements/module-editor/built-ins.ts
packages/shared-ui/src/elements/module-editor/module-editor.ts
packages/shared-ui/src/elements/module-editor/ribbon.ts
packages/shared-ui/src/elements/module-editor/ts-library.ts
packages/shared-ui/src/events/events.ts

[shared-ui] More tweaks to module editor

---

.changeset/tasty-yaks-attack.md
packages/shared-ui/src/elements/module-editor/module-editor.ts

Actively call `transpileModule` for each file

[shared-ui] Fix compilation

---

.changeset/nice-dolphins-do.md
packages/breadboard/src/editor/graph.ts
packages/breadboard/src/index.ts
packages/breadboard/src/inspector/graph.ts
packages/breadboard/src/inspector/types.ts
packages/breadboard/src/run/run-graph.ts
packages/breadboard/src/run/run-imperative-graph.ts
packages/breadboard/src/sandboxed-run-module.ts
packages/breadboard/src/types.ts
packages/jsandbox/src/telemetry.ts
packages/manifest/bbm.schema.json
packages/schema/breadboard.schema.json
packages/shared-ui/src/elements/board-activity/board-activity.ts
packages/shared-ui/src/elements/module-editor/ribbon.ts
packages/shared-ui/src/elements/overlay/save-as.ts
packages/types/src/graph-descriptor.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/board.ts
packages/visual-editor/src/runtime/run.ts

- **Sketch out Declarative and Imperative graph concepts.**
- **Teach `EditableGraph` about imperative graphs.**
- **Can run imperative graph.**
- **Imperative graph describer now works.**
- **Expose `imperative` and `main` props on `InspectableGraph`.**
- **Hide "main board" for imperative graphs.**
- **Hide board view for imperative graphs.**
- **Make it possible to create imperative boards.**
- **docs(changeset): Introduce Imperative Graphs.**

imperative graph

---

.changeset/chilly-tables-drum.md
packages/jsandbox/src/environment.d.ts
packages/jsandbox/src/type-declarations.ts
packages/shared-ui/src/elements/board-activity/board-activity.ts
packages/shared-ui/src/elements/json-tree/json-tree.ts
packages/visual-editor/src/index.ts

- **Skip inputs if none requested.**
- **Show escape cahracters in JSON tree.**
- **Add `console` declaration.**
- **Be okay with resuming from secrets.**
- **docs(changeset): A few more fixes while working with imperative modules.**

more fixes

---

.changeset/tough-bobcats-wash.md
package-lock.json
packages/shared-ui/package.json
packages/shared-ui/src/elements/elements.ts
packages/shared-ui/src/elements/input/code-editor/code-editor.ts
packages/shared-ui/src/elements/module-editor/command-palette.ts
packages/shared-ui/src/elements/module-editor/module-editor.ts
packages/shared-ui/src/elements/overlay/save-as.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/types/types.ts
packages/visual-editor/public/styles/global.css

[shared-ui] Various improvements to the Module Editor

---

.changeset/yellow-zoos-thank.md
packages/shared-ui/src/elements/editor/ribbon.ts
packages/shared-ui/src/elements/module-editor/command-palette.ts
packages/shared-ui/src/elements/module-editor/module-editor.ts
packages/shared-ui/src/elements/module-editor/ribbon.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts

[shared-ui] Add controls for imperative boards

---

.changeset/wicked-crabs-matter.md
packages/shared-ui/src/elements/input/code-editor/code-editor.ts
packages/shared-ui/src/elements/module-editor/module-editor.ts
packages/shared-ui/src/elements/module-editor/ribbon.ts
packages/shared-ui/src/elements/overflow-menu/overflow-menu.ts
packages/shared-ui/src/events/events.ts

[shread-ui] Add error menu

---

.changeset/rare-chairs-happen.md
packages/shared-ui/src/elements/input/code-editor/code-editor.ts

[shared-ui] Fix completion navigation

---

.changeset/thick-horses-tickle.md
packages/shared-ui/src/elements/editor/ribbon.ts
packages/shared-ui/src/elements/input/user-input.ts
packages/shared-ui/src/elements/module-editor/module-editor.ts
packages/shared-ui/src/elements/module-editor/ribbon.ts
packages/shared-ui/src/utils/module-id.ts

[shared-ui] Recreate env when module list changes

---

.changeset/happy-ants-glow.md
packages/manifest/bbm.schema.json
packages/shared-ui/src/elements/overlay/open-board.ts

Includes bb-schema; not sure why it was missing 🤔

[shared-ui] Always show Example & Playground boards

---

.changeset/green-wasps-jump.md
packages/agent-kit/agent.kit.json
packages/agent-kit/boards/specialist.bgl.json
packages/breadboard/src/inspector/bubbled-node.ts
packages/breadboard/src/inspector/kits.ts
packages/breadboard/src/inspector/node.ts
packages/breadboard/src/inspector/ports.ts
packages/breadboard/src/inspector/types.ts
packages/breadboard/src/inspector/virtual-node.ts
packages/breadboard/src/run/invoke-graph.ts
packages/breadboard/src/run/node-invoker.ts
packages/breadboard/src/types.ts
packages/core-kit/src/nodes/invoke.ts
packages/shared-ui/src/elements/editor/graph-node.ts
packages/shared-ui/src/elements/editor/graph.ts
packages/shared-ui/src/utils/mode.ts
packages/visual-editor/public/agent.kit.json
tsconfig.json

- **Introduce `side` behavior.**
- **Introduce `side` port list.**
- **Plumb side ports to `GraphNode`.**
- **Make no-input/no-output boards invokable.**
- **docs(changeset): Expose side wires in `InspectableGraph`.**

side wires

---

.changeset/great-needles-rest.md
packages/shared-ui/src/constants/constants.ts
packages/shared-ui/src/elements/command-palette/command-palette.ts
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/elements.ts
packages/shared-ui/src/elements/module-editor/module-editor.ts
packages/shared-ui/src/elements/overflow-menu/overflow-menu.ts
packages/shared-ui/src/elements/overlay/board-details.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/types/types.ts
packages/shared-ui/src/utils/utils.ts
packages/visual-editor/src/index.styles.ts
packages/visual-editor/src/index.ts

[visual-editor/shared-ui] Migrate command palette to root

---

.changeset/fluffy-countries-care.md
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/editor/graph.ts
packages/shared-ui/src/elements/editor/types.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts
packages/shared-ui/src/events/events.ts
packages/visual-editor/src/data/settings-store.ts

[shared-ui] Start subgraph work

---

.changeset/metal-knives-deny.md
packages/breadboard/src/editor/transforms/configure-sidewire.ts
packages/breadboard/src/editor/transforms/sidewire-to-new-graph.ts
packages/breadboard/src/index.ts
packages/breadboard/tests/node/editor/configure-sidewire.ts
packages/breadboard/tests/node/editor/merge-graph.ts
packages/breadboard/tests/node/editor/move-to-graph.ts
packages/breadboard/tests/node/editor/move-to-new-graph.ts
packages/breadboard/tests/node/editor/sidewire-to-new-graph.ts
packages/breadboard/tests/node/editor/test-graph.ts
packages/website/src/docs/editor.md

- **Fix typo in docs**
- **Introduce `ConfigureSidewireTransform`.**
- **Introduce `SidewireToNewGraphTransform`.**
- **docs(changeset): Introduce sidewire transforms.**

sidewire transforms

---

.changeset/hungry-cycles-relate.md
packages/shared-ui/src/elements/editor/graph.ts
packages/shared-ui/src/elements/editor/types.ts

- **Add `computeSideEdges` helper.**
- **docs(changeset): Add `#computSideEdges` helper to compute side edges.**

compute side edges

---

.changeset/witty-files-hammer.md
package-lock.json
packages/agent-kit/agent.kit.json
packages/agent-kit/boards/specialist.bgl.json
packages/agent-kit/src/function-calling.ts
packages/visual-editor/public/agent.kit.json

- **Ignore blank tools in Model (Specialist).**
- **docs(changeset): Ignore blank tools in Model (Specialist).**

ignore blank tools

---

.changeset/early-plums-argue.md
packages/jsandbox/package.json

- **Add `sandbox.wasm` to list of published fiels.**
- **docs(changeset): Add `sandbox.wasm` to the list published files.**

publish sandbox

---

.changeset/three-radios-trade.md
packages/board-server/src/server/boards/utils/create-kits.ts

- **Put overrides in correct order.**
- **docs(changeset): Put kit overrides in the right order.**

board server kit overrides

---

.changeset/thin-carpets-talk.md
packages/board-server/src/server/boards/post.ts
packages/remote-board-server/src/remote-board-server.ts

- **Catch and report fetch errors.**
- **Teach board server about imperative boards.**
- **docs(changeset): Teach board-server to work with imperative graphs.**

create code fix

---

.changeset/tame-candles-divide.md
packages/breadboard/src/capability.ts
packages/breadboard/src/types.ts
packages/shared-ui/src/elements/input/board-selector/board-selector.ts
packages/shared-ui/src/elements/input/user-input.ts

- **Correctly set the BreadboardCapability for subgraphs in `bb-board-selector`.**
- **Teach BreadboardCapability resolver about arrays.**
- **docs(changeset): Teach VE and Breadboard to invoke sub-boards properly.**

board selector subgraphs

---

.changeset/wise-carrots-pay.md
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/editor/graph.ts

[shared-ui] Unstick graph renderer when hierarchy is enabled

---

.changeset/unlucky-spies-fetch.md
packages/manifest/bbm.schema.json
packages/schema/breadboard.schema.json
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/editor/graph.ts
packages/shared-ui/src/elements/editor/ribbon.ts
packages/shared-ui/src/elements/elements.ts
packages/shared-ui/src/elements/module-editor/module-editor.ts
packages/shared-ui/src/elements/module-editor/ribbon.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.styles.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts
packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/utils/subgraph-color.ts
packages/shared-ui/src/utils/utils.ts
packages/types/src/graph-descriptor.ts
packages/visual-editor/src/index.styles.ts
packages/visual-editor/src/index.ts

[shared-ui] Add various improvements to board navigation

---

.changeset/red-shrimps-peel.md
packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts

Working on https://github.com/breadboard-ai/breadboard/issues/3836

[shared-ui] Improve handling of imperative boards

---

.changeset/fast-mayflies-promise.md
packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts
packages/shared-ui/src/events/events.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/edit.ts

[shared-ui/visual-editor] Teach runtime and UI to duplicate boards & mods

---

.changeset/cool-eggs-impress.md
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/editor/ribbon.ts
packages/shared-ui/src/elements/elements.ts
packages/shared-ui/src/elements/input/user-input.ts
packages/shared-ui/src/elements/overflow-menu/overflow-menu.ts
packages/shared-ui/src/elements/overlay/new-workspace-item.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.styles.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts
packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/types/types.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/board.ts
packages/visual-editor/src/runtime/edit.ts
packages/visual-editor/src/runtime/events.ts

[shared-ui] Improve side nav behaviors

---

.changeset/famous-files-brake.md
packages/shared-ui/src/elements/editor/graph-renderer.ts

[shared-ui] Fix main graph zooming

---

.changeset/spicy-moles-scream.md
packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts
packages/visual-editor/src/runtime/edit.ts

[shared-ui] Switch moduleId on deletion

---

.changeset/poor-oranges-prove.md
packages/visual-editor/src/index.styles.ts
packages/visual-editor/src/index.ts

[visual-editor] Fix tab rendering

---

.changeset/hip-queens-swim.md
packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts

[shared-ui] Improve the workspace outline filter

---

.changeset/thirty-games-cover.md
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/editor/graph.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts
packages/visual-editor/src/runtime/board.ts

#3836 
Also involves tracking subgraphs in the URL too.

[shared-ui/visual-editor] Improve graph zoom behaviors

---

.changeset/pink-horses-speak.md
packages/shared-ui/src/elements/overlay/new-workspace-item.ts

[shared-ui] Further tweaks to new item overlay

---

.changeset/nervous-pumpkins-cheer.md
packages/shared-ui/src/utils/top-graph-observer/top-graph-observer.ts
packages/visual-editor/src/runtime/board.ts
packages/visual-editor/src/runtime/runtime.ts

- **Remove the use of `inspect` in TGO.**
- **Move adding sandboxed runModule to runtime.**
- **docs(changeset): Bring back side wire computation.**

get side wire back

---

.changeset/gentle-hairs-switch.md
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/editor/graph-node.ts
packages/shared-ui/src/elements/editor/graph-port-label.ts
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/editor/graph.ts
packages/shared-ui/src/elements/editor/types.ts
packages/shared-ui/src/elements/input/user-input.ts
packages/shared-ui/src/elements/module-editor/module-editor.ts

[shared-ui] Teach user input & graph about module titles

---

.changeset/stupid-cooks-cheer.md
packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts

[shared-ui] Improve subgraph quick jump in workspace outline

---

.changeset/cuddly-socks-switch.md
packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts

[shared-ui] Teach Workspace Outline about module titles

---

package-lock.json
packages/board-server/experimental/bbrt/index.html
packages/board-server/package.json
packages/board-server/vite.config.ts
packages/visual-editor/.gitignore
packages/visual-editor/app.test.yaml
packages/visual-editor/app.yaml
packages/visual-editor/experimental/bbrt/index.html
packages/visual-editor/package.json
packages/visual-editor/src/copy-bbrt-assets.ts
packages/visual-editor/vite.config.ts

Retry of #3881. There was a missing dependency between `board-server` and `bbrt`.

[bbrt] Attempt 2: Serve at <visual-editor>/experimental/bbrt/

---

package-lock.json
packages/visual-editor/.gitignore
packages/visual-editor/app.test.yaml
packages/visual-editor/app.yaml
packages/visual-editor/experimental/bbrt/index.html
packages/visual-editor/package.json
packages/visual-editor/src/copy-bbrt-assets.ts
packages/visual-editor/vite.config.ts

Another retry of https://github.com/breadboard-ai/breadboard/pull/3881. Don't actually think I needed to modify board-server, just visual-editor.

[bbrt] Attempt 3: Serve at <visual-editor>/experimental/bbrt/ 

---

.changeset/serious-pianos-arrive.md
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/editor/graph.ts
packages/shared-ui/src/elements/editor/ribbon.ts
packages/shared-ui/src/elements/editor/types.ts
packages/shared-ui/src/elements/editor/utils.ts
packages/shared-ui/src/elements/module-editor/module-editor.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts
packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/types/types.ts
packages/visual-editor/src/commands/commands.ts
packages/visual-editor/src/commands/types.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/edit.ts
packages/visual-editor/src/runtime/events.ts
packages/visual-editor/src/runtime/runtime.ts
packages/visual-editor/src/runtime/select.ts
packages/visual-editor/src/runtime/types.ts
packages/visual-editor/src/runtime/util.ts

[shared-ui/visual-editor] Revamp selection model

---

.changeset/long-pugs-lay.md
packages/breadboard/src/inspector/graph/describer-manager.ts
packages/breadboard/src/inspector/graph/event.ts
packages/breadboard/src/inspector/graph/graph.ts
packages/breadboard/src/inspector/types.ts
packages/breadboard/src/utils/schema-differ.ts
packages/breadboard/src/utils/snapshot-updater.ts
packages/breadboard/tests/node/utils/schema-differ.ts
packages/breadboard/tests/node/utils/snapshot-updater.ts

- **Introduce `SchemaDiffer`.**
- **Start diffing describer results.**
- **Teach `SnapshotUpdater` to cache latest unless asked to refresh.**
- **Start dispatching `update` event.**
- **docs(changeset): Start dispatching `update` event on InspectableGraph.**

inspectable graph update event

---

packages/shared-ui/src/elements/editor/graph-renderer.ts

Again a temp fix – I know what the root cause is it's just a bit of work to refactor.

[shared-ui] Add initial move

---

package-lock.json
package.json
packages/unified-server/.npmignore
packages/unified-server/README.md
packages/unified-server/package.json
packages/unified-server/src/index.ts
packages/unified-server/src/server.ts
packages/unified-server/tests/dummy/test.ts
packages/unified-server/tsconfig.json

[unified-server] Create dummy package definition

---

.changeset/rich-lions-give.md
packages/breadboard/src/inspector/graph/mutable-graph.ts
packages/visual-editor/src/index.ts

- **Document `graphTopologyUpdateId`.**
- **Dispatch topology updates on edits.**
- **docs(changeset): Dispatch topology events on edits.**

graph topology update

---

.changeset/gold-timers-unite.md
packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts

[shared-ui] Make subitems a little more subtle

---

.changeset/selfish-moons-fly.md
packages/shared-ui/src/elements/module-editor/module-editor.ts
packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts

[shared-ui] Bring back the module preview

---

.changeset/two-lobsters-film.md
packages/shared-ui/src/elements/module-editor/module-editor.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts
packages/shared-ui/src/utils/top-graph-observer/top-graph-observer.ts
packages/visual-editor/package.json
packages/visual-editor/src/commands/commands.ts
packages/visual-editor/src/index.ts

- **Make component preview work**
- **Make sure backspace behaves when editing modules.**

module preview

---

.changeset/wet-dogs-think.md
packages/board-server-management/src/index.ts
packages/breadboard/src/inspector/graph-store.ts
packages/breadboard/src/inspector/graph/kits.ts
packages/breadboard/src/inspector/types.ts
packages/example-board-server/src/example-board-server.ts
packages/filesystem-board-server/src/filesystem-board-server.ts
packages/google-drive-kit/src/board-server/server.ts
packages/idb-board-server/src/idb-board-server.ts
packages/remote-board-server/src/remote-board-server.ts
packages/shared-ui/src/elements/component-selector/component-selector.ts
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/module-editor/module-editor.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/board.ts
packages/visual-editor/src/runtime/runtime.ts

- **Change the meaning of BoardServer.kits to mean "extra kits supplied by board server."**
- **Make board server kits show up in component selector.**
- **docs(changeset): Make board server components show in component selector.**

board server kits

---

.changeset/clever-pandas-sniff.md
packages/shared-ui/src/elements/module-editor/module-editor.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts

- **Adjust the sidebar splitter width.**
- **Account for moduleId when creating preview URL**
- **docs(changeset): Account for moduleId when creating stable URL for Module Preview.**

fix module bug

---

.changeset/fast-spoons-design.md
packages/shared-ui/src/elements/ui-controller/ui-controller.styles.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts

[shared-ui] Restore back button in Activity details

---

.changeset/tall-pumpkins-trade.md
packages/bbrt/src/components/board-visualizer.ts
packages/manifest/bbm.schema.json
packages/schema/breadboard.schema.json
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/editor/graph.ts
packages/shared-ui/src/elements/editor/types.ts
packages/shared-ui/src/elements/module-editor/module-editor.ts
packages/shared-ui/src/elements/overflow-menu/overflow-menu.ts
packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/types/types.ts
packages/types/src/graph-descriptor.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/edit.ts
packages/visual-editor/src/runtime/types.ts

[shared-ui] Improve subgraph visual controls

---

.changeset/soft-cherries-leave.md
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/editor/graph.ts
packages/shared-ui/src/types/types.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/events.ts
packages/visual-editor/src/runtime/select.ts
packages/visual-editor/src/runtime/types.ts

[shared-ui] Add control over when to animate

---

.changeset/breezy-spoons-love.md
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/editor/graph.ts
packages/shared-ui/src/elements/editor/types.ts
packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts
packages/shared-ui/src/utils/workspace.ts

[shared-ui] Support drag-move on sub graphs

---

packages/bbrt/src/app-state.ts
packages/bbrt/src/bootstrap.ts
packages/bbrt/src/breadboard/breadboard-tool.ts
packages/bbrt/src/components/main.ts
packages/bbrt/src/components/tool-palette.ts
packages/bbrt/src/config.ts
packages/bbrt/src/llm/conversation.ts
packages/bbrt/src/tools/activate-tool.ts
packages/bbrt/src/tools/list-tools.ts
packages/bbrt/src/tools/tool.ts
packages/bbrt/src/util/connected-effect.ts
packages/bbrt/src/util/wait-for-state.ts

Persists all UI state except for the conversation itself, which will come in a followup.
Also some related refactoring and a new connectedEffect utility lit controller.

[bbrt] Persist state to session storage (partially)

---

.changeset/afraid-chairs-beg.md
packages/bbrt/src/components/board-visualizer.ts
packages/breadboard/src/index.ts
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/editor/graph-node-reference-container.ts
packages/shared-ui/src/elements/editor/graph-node-reference.ts
packages/shared-ui/src/elements/editor/graph-node.ts
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/editor/graph.ts
packages/shared-ui/src/elements/editor/types.ts
packages/shared-ui/src/elements/input/user-input.ts
packages/shared-ui/src/elements/module-editor/module-editor.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/utils/index.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/edit.ts

[shared-ui] Introduce chiclets for board capabilities

---

packages/bbrt/src/components/chat-message.ts

Something smarter for a cool visual effect would be nice, but for now it's just annoying that it slows down the rendering, and in the restore-from-history case you don't want it at all.

[bbrt] Remove typing effect

---

packages/bbrt/src/components/chat.ts
packages/bbrt/src/components/scroll-controller.ts

Much easier to work with when the auto-scrolling logic is separated into a lit controller, plus it's reusable.

[bbrt] Move auto-scrolling logic into re-usable controller

---

.changeset/fair-points-dream.md
packages/breadboard/src/inspector/graph-store.ts
packages/breadboard/src/inspector/graph/graph.ts
packages/breadboard/src/inspector/run/event-manager.ts
packages/breadboard/src/inspector/run/past-run.ts
packages/breadboard/src/inspector/run/replay.ts
packages/breadboard/src/inspector/run/run.ts
packages/breadboard/src/inspector/types.ts
packages/breadboard/tests/inspector/observer-load.ts

- **Make edits after runs not crash.**
- **docs(changeset): Make edits after runs not crash**

edits no crash

---

.changeset/polite-ducks-hide.md
packages/shared-ui/src/elements/editor/graph-comment.ts
packages/shared-ui/src/elements/editor/graph-edge.ts
packages/shared-ui/src/elements/editor/graph-node-activity-marker.ts
packages/shared-ui/src/elements/editor/graph-node-port-list.ts
packages/shared-ui/src/elements/editor/graph-node-reference-container.ts
packages/shared-ui/src/elements/editor/graph-node-reference.ts
packages/shared-ui/src/elements/editor/graph-node.ts
packages/shared-ui/src/elements/editor/graph-port-label.ts
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/editor/graph.ts
packages/visual-editor/src/index.ts

[shared-ui] Clean graph entities more readily

---

.changeset/eighty-glasses-call.md
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/editor/graph-node.ts
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/editor/graph.ts
packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts

[shared-ui] Add node highlight for references

---

packages/website/src/docs/guides/breadboard-from-scratch.md

[website] Update typo in path

---

packages/bbrt/src/artifacts/idb-artifact-store.ts
packages/bbrt/src/breadboard/breadboard-server.ts
packages/bbrt/src/components/board-visualizer.ts
packages/bbrt/src/components/chat-message.ts
packages/bbrt/src/components/chat.ts
packages/bbrt/src/components/main.ts
packages/bbrt/src/components/scroll-controller.ts

- Board is the full RHS
- When restoring a previous log, scroll to the bottom instantly instead of smoothly

[bbrt] Make board more prominent, and a few misc fixes

---

.changeset/eight-colts-cheat.md
packages/shared-ui/src/elements/drag-connector/drag-connector.ts
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/editor/graph-node-reference-container.ts
packages/shared-ui/src/elements/editor/graph-node-reference.ts
packages/shared-ui/src/elements/editor/graph-node.ts
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/editor/graph.ts
packages/shared-ui/src/elements/editor/types.ts
packages/shared-ui/src/elements/elements.ts
packages/shared-ui/src/elements/input/code-editor/code-editor.ts
packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/types/types.ts
packages/visual-editor/src/commands/commands.ts
packages/visual-editor/src/commands/types.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/events.ts
packages/visual-editor/src/runtime/select.ts
packages/visual-editor/src/runtime/types.ts

[shared-ui] Improve drag and drop of sub boards

---

.changeset/orange-toes-decide.md
packages/breadboard/src/loader/loader.ts
packages/breadboard/src/run/run-graph.ts
packages/breadboard/src/types.ts
packages/shared-ui/src/elements/editor/editor.ts

- **Teach loader and runner about `[graphurl]#module:{id}` URLs.**
- **docs(changeset): Support `[graphurl]#module:{moduleId}` URL syntax.**

module urls

---

packages/bbrt/src/app-state.ts
packages/bbrt/src/artifacts/artifact-interface.ts
packages/bbrt/src/artifacts/artifact-store-interface.ts
packages/bbrt/src/artifacts/idb-artifact-store.ts
packages/bbrt/src/artifacts/reactive-artifact-store.ts
packages/bbrt/src/breadboard/breadboard-tool-provider.ts
packages/bbrt/src/breadboard/breadboard-tool.ts
packages/bbrt/src/components/artifact-display.ts
packages/bbrt/src/components/main.ts
packages/bbrt/src/tools/add-node.ts
packages/bbrt/src/tools/create-board.ts
packages/bbrt/src/tools/display-artifact.ts
packages/bbrt/src/util/weak-cache.ts

Just proving out the end-to-end, so can't create anything useful yet, but can make boards, display them, and add input/output nodes (with temporary fixed wiring).

[bbrt] Model can create toy boards

---

.changeset/clever-comics-battle.md
packages/shared-ui/src/elements/editor/graph-port-label.ts
packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts

[shared-ui] Tidy up labels for boards & board arrays

---

.changeset/stale-gifts-drum.md
packages/agent-kit/src/index.ts

- **Remove mention of legacyKits.**
- **docs(changeset): Remove mention of `legacyKit` in Agent Kit.**

agent legacy remove

---

.changeset/giant-chairs-eat.md
packages/shared-ui/src/elements/editor/graph-node-reference-container.ts

[shared-ui] Prevent reference bubbles from stomping one another

---

.changeset/perfect-bananas-wink.md
packages/breadboard/src/inspector/graph/describer-manager.ts
packages/breadboard/src/loader/loader.ts
packages/breadboard/src/sandboxed-run-module.ts
packages/breadboard/src/types.ts
packages/breadboard/tests/node/utils/handler.ts
packages/jsandbox/src/environment.d.ts
packages/jsandbox/src/type-declarations.ts

- **Handle generated module URLs gracefully.**
- **Start passing graph/module metadata as describer result.**
- **Teach static describer to return metadata.**
- **docs(changeset): Fix various bugs with describer capability**

handle generated module urls

---

.changeset/dirty-chicken-decide.md
package-lock.json
packages/bbrt/package.json

Brings in https://github.com/proposal-signals/signal-utils/pull/88
Also a catchup changeset for recent changes.

[bbrt] Update signal-utils to bring in a bugfix

---

.changeset/rare-penguins-smoke.md
packages/visual-editor/src/runtime/edit.ts

[visual-editor] Ensure comments are retained when shifting graphs

---

.changeset/spicy-seas-invent.md
packages/shared-ui/src/elements/editor/graph-edge.ts
packages/shared-ui/src/elements/editor/graph.ts

[shared-ui] Include edges in bounds calculations

---

.changeset/lucky-knives-attack.md
packages/visual-editor/src/runtime/util.ts

[visual-editor] Fix removal of single references

---

.changeset/tidy-ladybugs-appear.md
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/editor/graph.ts

[shared-ui] Teach transform matrix to account for comments

---

.changeset/orange-moose-occur.md
packages/shared-ui/src/elements/llm-output/llm-output.ts

A quick fix for #4060 - I'd rather we did this conversion once rather than on demand, though.

[shared-ui] Handle PCM audio

---

.changeset/twelve-mails-float.md
package-lock.json
packages/board-server/package.json
packages/breadboard-cli/package.json
packages/breadboard/src/remote/chunk-repair.ts
packages/breadboard/tests/node/http/chunk-repair.ts
packages/visual-editor/package.json

- **Don't delete completed chunk.**
- **Update versions.**
- **docs(changeset): Don't delete completed chunk.**

retain completed chunk

---

.changeset/unlucky-gorillas-appear.md
package-lock.json
packages/bbrt/package.json
packages/bbrt/src/components/chat.ts
packages/bbrt/src/components/driver-selector.ts
packages/bbrt/src/components/main.ts
packages/bbrt/src/components/prompt.ts
packages/bbrt/src/components/session-picker.ts
packages/bbrt/src/components/tool-call.ts
packages/bbrt/src/components/tool-palette.ts
packages/bbrt/src/llm/conversation.ts
packages/bbrt/src/state/app-persistence.ts
packages/bbrt/src/state/app.ts
packages/bbrt/src/state/session-persistence.ts
packages/bbrt/src/state/session-store.ts
packages/bbrt/src/state/session.ts
packages/bbrt/src/test/node/conversation_test.ts
packages/bbrt/src/test/node/state_test.ts
packages/bbrt/src/tools/activate-tool.ts

Multiple sessions now supported, and persistence moved from session storage to local storage.

[bbrt] Support multiple sessions

---

.changeset/rare-starfishes-clap.md
packages/board-server/package.json
packages/board-server/src/server/boards/utils/invoke-board.ts
packages/visual-editor/public/example-boards/playground/nager.date/long-weekend.json
packages/visual-editor/public/example-boards/playground/nager.date/public-holidays.json

- **Initialize GraphStore for board invoke.**
- **docs(changeset): Initialize GraphStore for board server invoke API.**

graph store board invoke

---

.changeset/rotten-dodos-wave.md
packages/board-server/src/server/boards/utils/create-kits.ts
packages/board-server/src/server/boards/utils/format-run-error.ts
packages/board-server/src/server/boards/utils/invoke-board.ts
packages/board-server/src/server/boards/utils/run-board.ts
packages/breadboard/src/kits/index.ts
packages/breadboard/src/kits/load.ts

- **Produce useful errors from invoke API.**
- **Register Google Drive and Agent Kit urls with the GraphStore to ensure they load correctly.**
- **docs(changeset): Ensure that Graph-based Kits are registered before run starts.**

board server invoke bugs

---

package-lock.json

[unified-server] update package-lock

---

packages/bbrt/src/components/chat-message.ts
packages/bbrt/src/components/session-picker.ts
packages/bbrt/src/components/tool-call.ts
packages/bbrt/src/llm/conversation.ts
packages/bbrt/src/style/button.ts
packages/bbrt/src/style/icon-button.ts
packages/bbrt/src/util/presentable-error.ts

Fix some layout issues, a basic presentability sweep, try to show JSON error messages with consistent indentation.

[bbrt] Quick style sweep

---

packages/bbrt/src/components/artifact-display.ts
packages/bbrt/src/components/main.ts
packages/bbrt/src/components/prompt.ts

Up to 10 lines, parametrizable with css custom prop.

[bbrt] Make the input box grow up to fit size of prompt

---

.changeset/thick-horses-pull.md
packages/breadboard/src/loader/types.ts
packages/filesystem-board-server/src/filesystem-board-server.ts
packages/visual-editor/src/runtime/runtime.ts

- **Teach FileSystemBoardServer to preload boards.**
- **docs(changeset): Teach FSAPI Board Server to show published boards.**

file system server preload

---

packages/bbrt/src/components/artifact-display.ts
packages/bbrt/src/components/main.ts
packages/bbrt/src/components/resizer.ts
packages/bbrt/src/util/draggable.ts

Trying out a pattern with a draggable lit directive (drop it on any element, and easily track drag gestures) and a resizer element (stick it anywhere, and tell it thing to measure, and which css custom property to set with the new width).

[bbrt] Resizable panels

---

.changeset/rotten-llamas-burn.md
packages/shared-ui/src/elements/editor/graph-assets.ts
packages/shared-ui/src/elements/input/code-editor/code-editor.ts
packages/visual-editor/index.html
packages/visual-editor/public/styles/global.css

Switches on the dark theme when someone puts `&dark=1` on the URL, and light theme when they put `&light=1` on it.

[shared-ui] Only enable dark theme when requested

---

.changeset/four-keys-collect.md
packages/shared-ui/src/elements/activity-log/activity-log.styles.ts
packages/shared-ui/src/elements/editor/graph-node-reference.ts
packages/shared-ui/src/elements/editor/graph.ts
packages/shared-ui/src/elements/input/array/array-editor.ts
packages/shared-ui/src/elements/input/llm-input/llm-input.ts
packages/shared-ui/src/elements/overflow-menu/overflow-menu.ts
packages/shared-ui/src/elements/overlay/first-run.ts
packages/shared-ui/src/elements/overlay/new-workspace-item.ts
packages/shared-ui/src/elements/overlay/provider.ts
packages/shared-ui/src/elements/overlay/save-as.ts
packages/shared-ui/src/elements/overlay/settings-edit.ts
packages/visual-editor/public/styles/global.css

[shared-ui] Fix some dark theme UI colors

---

.changeset/plenty-dingos-joke.md
packages/shared-ui/src/utils/top-graph-observer/top-graph-observer.ts

- **Comment out logic that causes transient outputs to be eaten in TGO.**
- **docs(changeset): Comment out the logic that causes transient outputs to be eaten.**

tgo no eat outputs

---

.changeset/fluffy-ducks-swim.md
package-lock.json
packages/bbrt/package.json
packages/bbrt/src/bootstrap.ts
packages/bbrt/src/breadboard/breadboard-component-tool.ts
packages/bbrt/src/breadboard/breadboard-invocation.ts
packages/bbrt/src/breadboard/breadboard-tool.ts
packages/bbrt/src/components/main.ts
packages/bbrt/src/config.ts
packages/bbrt/src/secrets/indexed-db-secrets.ts
packages/bbrt/src/test/playwright/main_test.ts
packages/visual-editor/experimental/bbrt/index.html

Using the same infrastructure as visual editor

[bbrt] Support for connections/oauth

---

package-lock.json
packages/unified-server/Dockerfile
packages/unified-server/package.json

[unified-server] Add @types-express to dev deps

---

packages/bbrt/src/components/chat-message.ts
packages/bbrt/src/components/resizer.ts
packages/bbrt/src/components/session-picker.ts
packages/bbrt/src/drivers/gemini.ts
packages/bbrt/src/drivers/openai.ts
packages/bbrt/src/llm/conversation.ts
packages/bbrt/src/util/draggable.ts
packages/bbrt/src/util/event-factories.ts

- Errors from drivers are now properly captured & displayed
- Various minor style tweaks

[bbrt] Improved error handling

---

.changeset/brave-pots-cross.md
packages/bbrt/src/breadboard/breadboard-component-tool.ts
packages/bbrt/src/breadboard/breadboard-tool.ts
packages/bbrt/src/components/artifact-display.ts
packages/bbrt/src/components/chat-message.ts
packages/bbrt/src/components/chat.ts
packages/bbrt/src/components/error-message.ts
packages/bbrt/src/components/markdown.ts
packages/bbrt/src/components/prompt.ts
packages/bbrt/src/components/tool-call.ts
packages/bbrt/src/drivers/gemini.ts
packages/bbrt/src/drivers/openai.ts
packages/bbrt/src/instructions/system-instruction.ts
packages/bbrt/src/style/loading-ellipsis.ts

Tool calls are now one concise line, with an expander to see all the details.
Also:
- Ellipsis loading indication on completions/tool calls
- The prompt now shakes if you try and send a message but the chat is not ready to receive it.
- System prompt improvements.
- Improved error handling.
- Various CSS improvements/cleanup.

[bbrt] Compact/expandable tool calls

---

package-lock.json
packages/connection-server/package.json
packages/unified-server/package.json
packages/unified-server/src/server/main.ts

[unified-server] Package the connection server as a subpath of the unified server

---

package-lock.json
packages/board-server/package.json
packages/board-server/scripts/build.ts
packages/unified-server/package.json
packages/unified-server/src/server/main.ts

[unified-server] Add board server to unified server

---

packages/website/src/docs/guides/breadboard-from-scratch.md

[website] Update WIP tag on Breadboard From Scratch

---

packages/unified-server/README.md

[unified-server] Update README with current project state

---

packages/unified-server/README.md

[unified-server] Update readme

---

.changeset/itchy-turtles-joke.md
packages/breadboard/src/graph-based-node-handler.ts
packages/breadboard/src/inspector/graph-store.ts
packages/breadboard/src/inspector/graph/bubbled-node.ts
packages/breadboard/src/inspector/graph/kits.ts
packages/breadboard/src/inspector/graph/node.ts
packages/breadboard/src/inspector/graph/ports.ts
packages/breadboard/src/inspector/graph/virtual-node.ts
packages/breadboard/src/inspector/types.ts
packages/breadboard/src/types.ts
packages/breadboard/src/utils/snapshot-updater.ts
packages/shared-ui/src/elements/workspace-outline/workspace-outline.ts
packages/shared-ui/src/utils/isolated-node-board.ts
packages/shared-ui/src/utils/mode.ts

- **Plumb `updating` to `currentPorts` and `currentMetadata`.**
- **docs(changeset): Plumb `updating` flag to both `currentPorts` and `currentMetadata`.**

updating flag

---

.changeset/swift-crabs-fetch.md
packages/breadboard/src/inspector/run/replay.ts

- **Teach Replay about subgraphs**
- **docs(changeset): Teach replay about subgraphs.**

fix replay

---

.changeset/little-lemons-promise.md
packages/board-server/src/server/boards/utils/board-server-provider.ts
packages/board-server/src/server/boards/utils/invoke-board.ts

- **Teach BoardServerProvider to load from same server.**
- **docs(changeset): Teach BoardServerProvider to load from same server (again).**

issue 4089

---

.changeset/clean-months-burn.md
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/strings/helper.ts
packages/website/src/js/board-embed.ts

Fixes #4176
Turns out the language pack was missing.

[website] Re-enable embeds

---

.changeset/blue-peaches-ring.md
packages/shared-ui/src/elements/chat/chat.ts
packages/shared-ui/src/state/chat-controller.ts
packages/shared-ui/src/state/types.ts

- **Teach `ChatController` about errors.**
- **docs(changeset): Teach `ChatController` about errors.**

chat controller errors

---

.changeset/brown-forks-count.md
packages/a2/bgl/template-test.bgl.json
packages/breadboard/src/data/file-system/assets.ts
packages/breadboard/src/editor/graph.ts
packages/breadboard/src/editor/operations/add-asset.ts
packages/breadboard/src/editor/operations/change-asset-metadata.ts
packages/breadboard/src/editor/operations/remove-asset.ts
packages/breadboard/src/editor/types.ts
packages/breadboard/tests/node/editor/assets.ts
packages/manifest/bbm.schema.json
packages/schema/breadboard.schema.json
packages/types/src/graph-descriptor.ts

- **Make assets have metadata.**
- **Add editing operations for assets.**
- **docs(changeset): Teach Edit API about editing assets.**

edit asset api

---

.changeset/flat-penguins-talk.md
packages/shared-ui/src/elements/editor/graph-port-label.ts
packages/shared-ui/src/elements/elements.ts
packages/shared-ui/src/elements/fast-access-menu/fast-access-menu.ts
packages/shared-ui/src/elements/input/llm-input/llm-input-array.ts
packages/shared-ui/src/elements/input/llm-input/llm-input-chat.ts
packages/shared-ui/src/elements/input/llm-input/llm-input.ts
packages/shared-ui/src/elements/input/text-editor/text-editor.ts
packages/shared-ui/src/elements/input/user-input.ts
packages/shared-ui/src/elements/overlay/node-configurator.ts
packages/shared-ui/src/events/events.ts
packages/visual-editor/public/styles/global.css

[shared-ui] Introduce basic Fast Access support

---

.changeset/curly-flies-shout.md
packages/shared-ui/src/elements/fast-access-menu/fast-access-menu.ts
packages/shared-ui/src/elements/input/text-editor/text-editor.ts
packages/shared-ui/src/events/events.ts

#4207 vibes
- Fixes a few issues around undo/redo, cut and paste, etc
- Enables keyboard navigation for selecting the item from the Fast Access menu
- Cleans the output

[shared-ui] Fast Access Improvements

---

.changeset/smooth-donuts-count.md
packages/shared-ui/src/elements/editor/graph-port-label.ts
packages/shared-ui/src/elements/fast-access-menu/fast-access-menu.ts
packages/shared-ui/src/elements/input/text-editor/text-editor.ts
packages/shared-ui/src/events/events.ts

[shared-ui] Update Fast Access item encoding

---

.changeset/shaggy-jokes-sing.md
packages/shared-ui/src/elements/input/user-input.ts

[shared-ui] Tidy Node Configurator

---

.changeset/poor-parrots-raise.md
packages/shared-ui/src/elements/input/text-editor/text-editor.ts
packages/visual-editor/src/index.ts

[shared-ui] Enable text pasting in text-editor

---

.changeset/soft-squids-protect.md
packages/a2/bgl/organizer-demo.bgl.json
packages/breadboard/tests/node/editor/assets.ts
packages/manifest/bbm.schema.json
packages/schema/breadboard.schema.json
packages/types/src/graph-descriptor.ts

- **Distinguish between files and content in graph assets.**
- **docs(changeset): Add asset type to distinguish between different kinds of graph assets.**

asset types

---

.changeset/hungry-coats-yawn.md
packages/a2/bgl/a2.bgl.json
packages/a2/bgl/combine-outputs-workbench.bgl.json
packages/visual-editor/src/runtime/edit.ts

- **Return port name when main-port is found.**
- **The simplest possible "Combine Outputs" implementation.**
- **docs(changeset): Introduce Combine Outputs component.**

a2 combine outputs

---

.changeset/loud-birds-ring.md
packages/shared-ui/src/elements/editor/graph-assets.ts
packages/shared-ui/src/elements/editor/graph-button.ts
packages/shared-ui/src/elements/editor/graph-node.ts
packages/shared-ui/src/elements/input/text-editor/text-editor.ts
packages/shared-ui/src/strings/en_US/editor.ts
packages/visual-editor/public/third_party/icons/graph/add-48px.svg
packages/visual-editor/public/third_party/icons/graph/add-inverted-48px.svg

[shared-ui] Teach graph node to show a message when details are missing

---

.changeset/sweet-mails-boil.md
packages/shared-ui/src/elements/asset-organizer/asset-organizer.ts
packages/shared-ui/src/elements/board-activity/board-activity.styles.ts
packages/shared-ui/src/elements/board-activity/board-activity.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.styles.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts
packages/shared-ui/src/strings/en_US/global.ts
packages/shared-ui/src/strings/en_US/ui-controller.ts
packages/shared-ui/src/styles/icons.ts
packages/visual-editor/index.html

#4221 
And also a few other smaller UX changes

[shared-ui] Update test project pane

---

packages/shared-ui/src/elements/board-activity/board-activity.ts
packages/shared-ui/src/elements/editor/graph-node-output.ts

[shared-ui] Fixes for test output

---

packages/board-server/src/app/app.ts
packages/shared-ui/src/elements/app-preview/app-preview.ts

Some styles to make the standalone app view look cleaner in mobile

[board-server] [shared-ui] Mobile app view styles

---

.changeset/tricky-flies-wait.md
packages/shared-ui/src/elements/fast-access-menu/fast-access-menu.ts

- **Make fast access menu work with no tools.**
- **docs(changeset): Make Fast Access menu work with no tools.**

fast access no tools

---

packages/board-server/src/app/app.ts

Fixes some minor scrolling and background color issues.

[board-server] Minor style tweaks for standalone desktop mode

---

packages/board-server/src/app/app.ts
packages/shared-ui/src/elements/chat/chat.ts
packages/shared-ui/src/elements/llm-output/export-toolbar.ts
packages/shared-ui/src/state/chat-controller.ts
packages/shared-ui/src/state/types.ts

Also show toasts from preview, and fix minor style issue.

[board-server] [shared-ui] Add status detail to chat state

---

.changeset/clean-rivers-raise.md
packages/shared-ui/src/elements/editor/graph-node-output.ts
packages/shared-ui/src/elements/editor/graph-node.ts

[shared-ui] Prevent placeholders from sticking

---

.changeset/strange-suits-compete.md
packages/shared-ui/src/elements/asset-organizer/asset-organizer.ts
packages/shared-ui/src/elements/board-activity/board-activity.styles.ts
packages/shared-ui/src/elements/editor/graph-node-output.ts
packages/shared-ui/src/elements/overlay/node-configurator.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.styles.ts

[shared-ui] Various UI fixes

---

.changeset/friendly-rivers-study.md
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/strings/en_US/editor.ts
packages/shared-ui/src/strings/en_US/ui-controller.ts

[shared-ui] Add a few tooltips

---

.changeset/strange-tomatoes-watch.md
packages/shared-ui/src/elements/editor/graph-node.ts
packages/shared-ui/src/strings/en_US/editor.ts

[shared-ui] Only show "missing details" on components where it is expected

---

.changeset/quick-eggs-cheer.md
packages/shared-ui/src/elements/overlay/node-configurator.ts

[shared-ui] Prevent dblclick from expanding configurator

---

packages/unified-server/vite.config.ts

[unified-server] Add an empty ASSET_PACK_ICONS attribute

---

packages/unified-server/vite.config.ts

[unified-server] Add exports for kits

---

.changeset/silent-emus-retire.md
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/edit.ts

- **Move most logic into createWorkspaceItem.**
- **docs(changeset): Move most board constructing code to runtime.**

create board cleanup

---

.changeset/lucky-schools-help.md
packages/board-server/src/server/boards/get.ts
packages/manifest/bbm.schema.json
packages/remote-board-server/src/remote-board-server.ts
packages/schema/breadboard.schema.json
packages/shared-ui/src/elements/overlay/board-details.ts
packages/shared-ui/src/events/events.ts
packages/types/src/graph-descriptor.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/edit.ts

- **Make all board server load request come with the board API key.**
- **Add support for "private" tag in `GraphDescriptor`.**
- **docs(changeset): Add support for private boards.**

board server private

---

packages/unified-server/src/index.ts

[unified-server] Add explanatory comment for module re-export

---

.changeset/nervous-tips-joke.md
packages/board-server/src/server/boards/index.ts
packages/remote-board-server/src/remote-board-server.ts
packages/unified-server/src/server/main.ts

- **Teach VE about non-root board servers.**
- **Give reasonable initial values to unified server to make it run.**
- **docs(changeset): Teach visual editor about non-root board servers.**

non root board servers

---

.changeset/lemon-mice-poke.md
packages/board-server/package.json
packages/board-server/scripts/build.ts

- **Remove now-redundant builds.**
- **docs(changeset): Remove now-redundant build steps in board server.**

board server cleanup

---

packages/unified-server/Dockerfile
packages/unified-server/package.json

[unified-server] Update dockerfile to build from monorepo

---

package-lock.json
packages/jsandbox/package.json

This reverts commit 715e20d310eb807325ab7da3cb219f96db235ac8.

Revert "build(deps): bump @bjorn3/browser_wasi_shim from 0.3.0 to 0.4.0 (#4384)"

---

.changeset/selfish-flies-prove.md
packages/board-server/src/router.ts

- **Fix a typo.**
- **docs(changeset): Fix a typo and unbreak board server.**

board server typo

---

packages/unified-server/app.yaml

[unified-server] Add build env vars to app.yaml

---

packages/unified-server/Dockerfile

[unified-server] Add CONNECTIONS_FILE to Dockerfile

---

.changeset/late-fishes-attend.md
packages/shared-ui/src/elements/connection/connection-broker.ts
packages/unified-server/.env.development
packages/unified-server/.env.production

- **Account for relative URLs in connection-broker.**
- **docs(changeset): Account for relative connection server URL in connection-broker**

relative connection server url

---

.changeset/many-mugs-invent.md
packages/unified-server/Dockerfile

- **Point backend at a different firestore db for unified server.**
- **docs(changeset): Point Firestore backend to a different db for unified server.**

firestore unified

---

.changeset/tall-horses-guess.md
packages/shared-ui/src/strings/en_US/activity-log.ts
packages/shared-ui/src/strings/en_US/component-selector.ts
packages/shared-ui/src/strings/en_US/editor.ts
packages/shared-ui/src/strings/en_US/global.ts
packages/shared-ui/src/strings/en_US/kit-selector.ts
packages/shared-ui/src/strings/en_US/project-listing.ts
packages/shared-ui/src/strings/en_US/ui-controller.ts

- **Do a terminology refresh.**
- **docs(changeset): Update terminology**

terminology refresh

---

.changeset/dirty-lemons-float.md
package-lock.json
package.json
packages/unified-server/package.json
packages/unified-server/vite.config.ts

- **Teach unified server to compress the output.**
- **docs(changeset): Teach unified server to compress its static files.**

unified server compress output

---

.changeset/giant-games-compete.md
packages/shared-ui/src/elements/asset-organizer/asset-organizer.ts
packages/shared-ui/src/elements/output/multi-output/multi-output.ts
packages/shared-ui/src/strings/en_US/asset-organizer.ts
packages/visual-editor/src/index.ts

[shared-ui] Add ability to organize assets

---

.changeset/brave-trains-crash.md
packages/unified-server/src/server/main.ts

- **Enable Brotli compression.**
- **docs(changeset): Enable Brotli compression.**

unified server brotli

---

.changeset/mean-bananas-tap.md
packages/shared-ui/src/elements/overlay/save-as.ts
packages/visual-editor/src/index.ts

- **Don't show board server selector by default.**
- **docs(changeset): Don't show board server selector by default.**

hide board server selector

---

.changeset/itchy-lobsters-guess.md
packages/board-server/src/server/blob-store.ts
packages/board-server/src/server/blobs/create.ts
packages/board-server/src/server/blobs/serve.ts
packages/board-server/src/server/types.ts

- **Switch to Outcome.**
- **Add `BlobStore.deflateContent`.**
- **docs(changeset): Prepare blob store to be more widely used.**

blobs refactor

---

.changeset/blue-humans-sing.md
packages/unified-server/package.json

- **Set FIRESTORE_DB_NAME in dev mode.**
- **docs(changeset): Set FIRESTORE_DB_NAME in dev mode.**

unified server dev

---

packages/unified-server/app.yaml

We are not going to be deploying to app engine
Part of #4390

[unified-server] Remove app.yaml

---

.changeset/polite-carrots-admire.md
packages/visual-editor/src/index.ts

- **Just reload on sign in.**
- **docs(changeset): Reload on sign-in**

reload on sign in

---

.changeset/cold-moose-cough.md
package-lock.json
packages/breadboard/src/data/common.ts
packages/breadboard/src/data/default-data-store.ts
packages/breadboard/src/data/index.ts
packages/breadboard/src/data/inflate-deflate.ts
packages/breadboard/src/data/types.ts
packages/breadboard/src/index.ts
packages/breadboard/src/loader/types.ts
packages/breadboard/src/remote/proxy.ts
packages/breadboard/src/utils/relative-path.ts
packages/breadboard/tests/node/utils/relative-path.ts
packages/remote-board-server/package.json
packages/remote-board-server/src/remote-board-server.ts
packages/remote-board-server/src/remote-part-transformer.ts
packages/remote-board-server/src/types.ts
packages/shared-ui/src/elements/asset-organizer/asset-organizer.ts
packages/shared-ui/src/elements/output/llm-output/llm-output.ts
packages/shared-ui/src/state/organizer.ts
packages/shared-ui/src/state/project.ts
packages/shared-ui/src/state/types.ts
packages/unified-server/package.json
packages/visual-editor/src/runtime/runtime.ts
packages/visual-editor/src/runtime/state.ts

- **Sketch out `DataPartTransformer` and friends.**
- **Plumb asset blob persistence end-to-end.**
- **Make asset URLs relative to graph URL.**
- **docs(changeset): Store assets as references to blobs.**

asset blobs

---

.changeset/spicy-years-carry.md
packages/a2/bgl/file-url-test.bgl.json
packages/jsandbox/src/environment.d.ts
packages/jsandbox/src/type-declarations.ts
packages/types/src/llm-content.ts
packages/unified-server/package.json

- **Catch up to the latest Gemini API types.**
- **docs(changeset): CAtch up to the latest Gemini LLMContent types.**

latest gemini llm content

---

.changeset/warm-laws-wink.md
packages/shared-ui/src/transforms/update-node-title.ts
packages/shared-ui/src/transforms/update-node.ts
packages/shared-ui/src/utils/template.ts

- **Propagate title updates to "@" references**
- **docs(changeset): Propagate node title changes to "@" references.**

at reference titles

---

.changeset/three-pianos-explode.md
packages/shared-ui/src/elements/asset-organizer/asset-organizer.ts
packages/shared-ui/src/elements/overflow-menu/overflow-menu.ts
packages/shared-ui/src/strings/en_US/asset-organizer.ts

[shared-ui] Allow users to create blank content assets

---

.changeset/strong-files-tie.md
packages/shared-ui/src/elements/input/text-editor/text-editor.ts

[shared-ui] Allow plain `@` symbols

---

.changeset/thin-onions-trade.md
packages/shared-ui/src/utils/template.ts

- **Add a helper to easily get placeholders.**
- **docs(changeset): Add `Template.placeholders` to easily get all placeholders in a template.**

template placeholders

---

.changeset/perfect-peaches-sort.md
packages/shared-ui/src/elements/welcome-panel/project-listing.ts
packages/visual-editor/src/bootstrap.ts
packages/visual-editor/src/build-info.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/vite-env.d.ts
packages/visual-editor/vite.config.ts

Fixes #4499
Also includes the git hash of the most recent commit.

[visual-editor] Restore version to bottom of home view

---

.changeset/mean-chicken-drop.md
packages/board-server/src/server/auth.ts
packages/board-server/src/server/blobs/file-info.ts
packages/board-server/src/server/boards/assets-drive.ts
packages/board-server/src/server/boards/index.ts
packages/board-server/src/server/boards/utils/board-api-parser.ts
packages/board-server/src/server/types.ts
packages/breadboard/src/data/common.ts
packages/breadboard/src/data/inflate-deflate.ts
packages/breadboard/src/data/types.ts
packages/remote-board-server/src/google-drive-to-gemini.ts
packages/remote-board-server/src/remote-part-transformer.ts

- **Sketch out the client side of Drive-to-File API conversion.**
- **Working end to end, uploading on each conversion.**
- **Implement a simplest possible caching strategy.**
- **docs(changeset): Implement support for consuming Google Drive documents**

drive to file api

---

.changeset/giant-rocks-notice.md
packages/shared-ui/src/elements/google-drive/google-drive-file-id.ts
packages/shared-ui/src/elements/google-drive/google-drive-file-viewer.ts
packages/shared-ui/src/elements/output/llm-output/llm-output.ts

[shared-ui] Teach LLM Output about all GDrive mime types

---

.changeset/little-moles-admire.md
packages/breadboard/src/editor/blank.ts
packages/remote-board-server/src/remote-board-server.ts
packages/shared-ui/src/elements/welcome-panel/project-listing.ts
packages/shared-ui/src/strings/en_US/global.ts
packages/visual-editor/src/index.ts

[shared-ui/visual-editor] Streamline new flow creation

---

.changeset/sweet-cobras-end.md
packages/shared-ui/src/elements/asset-organizer/asset-organizer.ts

[shared-ui] Reset edit status on asset change

---

.changeset/hip-snails-clean.md
packages/shared-ui/src/elements/editor/graph-port-label.ts
packages/shared-ui/src/elements/input/text-editor/text-editor.ts

[shared-ui] Escape HTML entities

---

.changeset/perfect-students-live.md
packages/visual-editor/src/build-info.ts

Fixes issue where CI doesn't have git.

[visual-editor] Update build info

---

.changeset/odd-ravens-carry.md
packages/shared-ui/src/elements/fast-access-menu/fast-access-menu.ts
packages/shared-ui/src/elements/input/text-editor/text-editor.ts
packages/shared-ui/src/elements/overlay/focus-editor.ts

[shared-ui] Small fixes for the Focus Editor and Text Editor

---

.changeset/happy-teeth-search.md
packages/shared-ui/src/elements/asset-organizer/asset-organizer.ts
packages/shared-ui/src/elements/input/llm-input/llm-input.ts
packages/shared-ui/src/elements/output/llm-output/llm-output.ts

[shared-ui] Improve keyboard handling in Asset Organizer

---

.changeset/some-breads-reply.md
packages/shared-ui/src/elements/input/text-editor/text-editor.ts

- **Hack-fix the peekaboo menu problem.**
- **docs(changeset): Hack-fix the peekaboo "@" menu bug.**

hack fix peekaboo

---

package-lock.json
packages/board-server/package.json

Necessary to run the integration test with the firestore emulator.
Part of #3172

[board-server] Add firebase-tools to dev deps

---

packages/visual-editor/src/index.ts

Small fix for a bug in https://github.com/breadboard-ai/breadboard/pull/4616

Remove error about non-connection sideboard secrets

---

packages/board-server/package.json

[board-server] Use tsx to run integration test

---

.changeset/tangy-dots-fail.md
packages/shared-ui/src/app-templates/basic/index.ts
packages/shared-ui/src/app-templates/shared/utils/utils.ts
packages/shared-ui/src/elements/output/llm-output/llm-output.ts

[shared-ui] Handle errors in app view

---

.changeset/common-dancers-poke.md
packages/shared-ui/src/app-templates/basic/index.ts
packages/shared-ui/src/elements/elements.ts
packages/shared-ui/src/elements/input/speech-to-text/speech-to-text.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/types/types.ts

[shared-ui] Add speech-to-text to app view

---

.changeset/cold-pets-call.md
packages/shared-ui/src/elements/app-preview/app-preview.ts
packages/shared-ui/src/elements/board-activity/board-activity.styles.ts
packages/visual-editor/src/index.styles.ts

[shared-ui] Various styling improvements

---

packages/shared-ui/src/app-templates/basic/index.ts

[shared-ui] Tweak to app view activity

---

packages/shared-ui/src/elements/app-preview/app-theme-creator.ts

[shared-ui] Tweaks to app theme creator

---

.changeset/dirty-toes-behave.md
packages/shared-ui/src/app-templates/basic/index.ts
packages/shared-ui/src/elements/asset-organizer/asset-organizer.ts
packages/shared-ui/src/elements/elements.ts
packages/shared-ui/src/elements/input/add-asset/add-asset-button.ts
packages/shared-ui/src/elements/input/add-asset/add-asset-modal.ts
packages/shared-ui/src/elements/input/add-asset/asset-shelf.ts
packages/shared-ui/src/elements/overflow-menu/overflow-menu.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/state/project.ts
packages/shared-ui/src/utils/youtube.ts

[shared-ui] Teach app view about assets

---

.changeset/sour-berries-rhyme.md
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/runtime.ts
packages/visual-editor/src/runtime/sideboard-runtime.ts
packages/visual-editor/src/runtime/types.ts

- **Move sideboard runtime into its own class.**
- **docs(changeset): Move SideboardRuntime into its own class.**

sideboard grown up

---

packages/board-server/src/server/boards/index.ts

[board-server] Look up board ID on invite

---

.changeset/gentle-sides-clap.md
packages/board-server/src/server/boards/index.ts
packages/board-server/src/server/boards/invite-update.ts
packages/board-server/src/server/boards/invoke.ts
packages/board-server/src/server/boards/post.ts
packages/board-server/src/server/boards/run.ts
packages/board-server/src/server/common.ts

Pushes all logic down into the handlers themselves.

[board-server] Remove logic from boards/index

---

packages/breadboard/src/editor/operations/replace-graph.ts

It was updating the UI, but not the underlying graph.

[board generation] Fix the replace graph operation

---

.changeset/pretty-sloths-taste.md
packages/shared-ui/src/elements/ui-controller/ui-controller.styles.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts
packages/shared-ui/src/utils/side-board-runtime.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/sideboard-runtime.ts

- **Sketch out `runTask`.**
- **Plumb "canRun" and attach it to task state.**
- **docs(changeset): Introduce `SideBoardRuntime.runTask`.**

sideboard tasks

---

.changeset/tired-goats-fold.md
packages/shared-ui/src/elements/input/add-asset/add-asset-button.ts
packages/shared-ui/src/elements/input/add-asset/add-asset-modal.ts
packages/shared-ui/src/elements/input/add-asset/asset-shelf.ts
packages/shared-ui/src/elements/overflow-menu/overflow-menu.ts

[shared-ui] Teach app about drawables

---

.changeset/huge-trees-own.md
packages/shared-ui/src/elements/input/add-asset/add-asset-modal.ts
packages/shared-ui/src/elements/input/add-asset/asset-shelf.ts
packages/shared-ui/src/elements/input/drawable/drawable.ts
packages/shared-ui/src/elements/output/llm-output/llm-output.ts
packages/shared-ui/src/elements/output/pdf-viewer/pdf-viewer.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/edit.ts

[shared-ui] Teach app view about various input modalities

---

.changeset/polite-kings-sip.md
packages/board-server/src/server.ts
packages/board-server/src/server/blobs/create.ts
packages/board-server/src/server/boards/create.ts
packages/board-server/src/server/boards/invite-update.ts
packages/board-server/src/server/boards/invoke.ts
packages/board-server/src/server/boards/post.ts
packages/board-server/src/server/boards/run.ts
packages/board-server/src/server/common.ts
packages/board-server/src/server/proxy/index.ts

Instead of manually parsing the body

[board-server] Use express.json

---

.changeset/stale-mice-live.md
packages/board-server/src/server/storage-providers/firestore.ts
packages/board-server/src/server/store.ts
packages/remote-board-server/src/remote-board-server.ts
packages/shared-ui/src/elements/welcome-panel/project-listing.ts
packages/visual-editor/public/styles/global.css

[board-server] Teach listing about thumbnails

---

.changeset/polite-kings-sip.md
packages/board-server/src/server.ts
packages/board-server/src/server/blobs/create.ts
packages/board-server/src/server/boards/create.ts
packages/board-server/src/server/boards/invite-update.ts
packages/board-server/src/server/boards/invoke.ts
packages/board-server/src/server/boards/post.ts
packages/board-server/src/server/boards/run.ts
packages/board-server/src/server/common.ts
packages/board-server/src/server/proxy/index.ts

Causes 400s in proxy endpoints
This reverts commit 5064e41dcb7f9a9fd6a1a6d230dbf7627ee50d1f.

Revert "[board-server] Use express.json (#4688)"

---

.changeset/fluffy-gifts-find.md
packages/shared-ui/src/app-templates/basic/index.ts
packages/shared-ui/src/elements/output/multi-output/multi-output.ts

[shared-ui] More app view tweaks

---

packages/board-server/src/server.ts

[board-server] Boost POST content limit to 2GB

---

.changeset/tall-bushes-peel.md
packages/board-server/src/server/proxy/index.ts
packages/breadboard/src/harness/types.ts

- **Temporarily remove auth from the proxy request.**
- **docs(changeset): Temporarily remove auth check from proxy requests.**

proxy auth

---

.changeset/slick-insects-grow.md
packages/shared-ui/src/elements/asset-organizer/asset-organizer.ts
packages/shared-ui/src/elements/editor/describe-edit-button.ts
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.styles.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/strings/en_US/editor.ts
packages/shared-ui/src/styles/fab.ts
packages/shared-ui/src/styles/floating-panel.ts

[shared-ui] Move assets to header & convert to overlay

---

.changeset/puny-news-build.md
packages/shared-ui/src/elements/ui-controller/ui-controller.styles.ts

[shared-ui] Move test flow UI

---

.changeset/puny-cycles-show.md
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/elements/overflow-menu/overflow-menu.ts
packages/shared-ui/src/elements/overlay/new-workspace-item.ts
packages/visual-editor/src/index.styles.ts
packages/visual-editor/src/index.ts

[shared-ui] Show custom steps in selector

---

.changeset/legal-facts-repair.md
packages/shared-ui/src/elements/component-selector/component-selector-overlay.ts
packages/shared-ui/src/elements/editor/editor.ts
packages/shared-ui/src/strings/en_US/editor.ts

[shared-ui] Improve custom step selection

---

.changeset/bumpy-points-follow.md
packages/shared-ui/src/elements/fast-access-menu/fast-access-menu.ts
packages/shared-ui/src/elements/input/llm-input/llm-input.ts
packages/shared-ui/src/elements/input/text-editor/text-editor.ts
packages/shared-ui/src/elements/overlay/focus-editor.ts
packages/shared-ui/src/strings/en_US/activity-log.ts

[shared-ui] Update styles for focus-/text-editor

---

.changeset/free-bats-change.md
packages/shared-ui/src/data/settings-store.ts
packages/visual-editor/src/index.ts

[visual-editor] Promote Focus Editor to main

---

packages/unified-server/.gitignore
packages/unified-server/app/index.html
packages/unified-server/src/client/app/init.ts
packages/unified-server/vite.config.ts

[unified-server] Add a stub page for app view

---

.changeset/big-trams-unite.md
packages/shared-ui/src/sideboards/autoname.ts

- **Handle errors more thoroughly.**
- **docs(changeset): Handle errors a bit more thoroughly.**

autonaming errors

---

packages/board-server/src/server/boards/get.ts
packages/board-server/src/server/boards/loader.ts
packages/board-server/src/server/storage-providers/firestore.ts
packages/board-server/src/server/store.ts

Not really needed, and we may want to run this middleware in situations where the board may not exist (or even when the board is expected not to exist)

[board-server] Get rid of custom error

---

.changeset/stupid-dragons-fall.md
packages/shared-ui/src/app-templates/basic/index.ts
packages/shared-ui/src/app-templates/shared/styles/animations.ts
packages/shared-ui/src/app-templates/shared/styles/icons.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.styles.ts
packages/visual-editor/src/index.styles.ts

[shared-ui] Teach app view about thoughts

---

packages/board-server/tests/integration/board-server.test.ts

[board-server] Get rid of redundant tests

---

packages/board-server/src/index.ts
packages/board-server/src/server.ts
packages/board-server/src/server/config.ts
packages/board-server/tests/integration/board-server.test.ts
packages/unified-server/src/server/main.ts

Usage removed in #4801
Part of #4798

[board-server] Get rid of unused rootPath

---

packages/shared-ui/src/elements/input/expanding-textarea.ts
packages/shared-ui/src/elements/welcome-panel/describe-flow-panel.ts

It automatically grows as lines are typed, within configured limits. Allows slotting an image to be inlaid on the right.

[generation] Add expanding-textarea component

---

.changeset/afraid-pugs-sort.md
packages/a2/bgl/parameters-workbench.bgl.json
packages/manifest/bbm.schema.json
packages/schema/breadboard.schema.json
packages/shared-ui/src/elements/asset-organizer/asset-organizer.ts
packages/shared-ui/src/elements/fast-access-menu/fast-access-menu.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/state/fast-access.ts
packages/shared-ui/src/state/organizer.ts
packages/shared-ui/src/state/project.ts
packages/shared-ui/src/state/types.ts
packages/shared-ui/src/transforms/change-parameter-metadata.ts
packages/shared-ui/src/transforms/index.ts
packages/shared-ui/src/transforms/update-node.ts
packages/shared-ui/src/transforms/update-parameter-metadata.ts
packages/types/src/graph-descriptor.ts

- **Add `parameters` to FastAccess menu.**
- **Introduce graph parameters metadata and start populating it.**
- **Show params in "@" menu.**
- **Show params in organizer.**
- **Add ability to change graph metadata.**
- **docs(changeset): Start showing parameters in various UI surfaces.**

show parameters

---

.changeset/large-mirrors-fry.md
packages/shared-ui/src/elements/asset-organizer/asset-organizer.ts
packages/shared-ui/src/elements/fast-access-menu/fast-access-menu.ts
packages/shared-ui/src/elements/input/llm-input/llm-input.ts
packages/shared-ui/src/elements/input/text-editor/text-editor.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.styles.ts
packages/shared-ui/src/strings/en_US/asset-organizer.ts

[shared-ui] Teach asset organizer to add/edit parameter metadata

---

packages/board-server/src/server/boards/index.ts
packages/board-server/src/server/boards/loader.ts

[board-server] Create a board ID loader

---

packages/board-server/src/server/boards/index.ts
packages/board-server/tests/integration/board-server.test.ts

[board-server] Add alterntative routes for suffixed versions

---

.changeset/true-places-ask.md
packages/a2/bgl/parameters-workbench.bgl.json
packages/breadboard/src/inspector/graph/virtual-node.ts
packages/breadboard/src/run/node-invoker.ts
packages/shared-ui/src/elements/asset-organizer/asset-organizer.ts
packages/shared-ui/src/elements/fast-access-menu/fast-access-menu.ts
packages/shared-ui/src/strings/en_US/asset-organizer.ts
packages/shared-ui/src/transforms/change-parameter-metadata.ts

- **Properly change parameter titles.**
- **Show proper description when asking for params.**
- **Uppercase param title when creating new.**
- **Show the value in console.**
- **docs(changeset): Polish parameters a bit.**

parameters polish

---

packages/shared-ui/src/elements/input/expanding-textarea.ts
packages/shared-ui/src/elements/welcome-panel/describe-flow-panel.ts
packages/shared-ui/src/elements/welcome-panel/project-listing.ts
packages/shared-ui/src/strings/en_US/project-listing.ts

New styling for the home page hero section, especially affecting the title/background, as well as the look and placeholder text for the "describe a flow" input, which also no longer is hidden behind a button.

[home page] Rework the home page hero section

---

.changeset/smart-parts-share.md
packages/a2/bgl/parameters-workbench.bgl.json
packages/breadboard/src/run/node-invoker.ts
packages/manifest/bbm.schema.json
packages/schema/breadboard.schema.json
packages/shared-ui/src/elements/asset-organizer/asset-organizer.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts
packages/shared-ui/src/state/organizer.ts
packages/shared-ui/src/strings/en_US/asset-organizer.ts
packages/types/src/graph-descriptor.ts

- **Teach params about modalities and sample values.**
- **Persist parameter sample value blobs.**
- **docs(changeset): Teach params about modalities and sample values.**

params enhanced

---

packages/board-server/scripts/accounts.ts
packages/board-server/scripts/create-account.ts
packages/board-server/scripts/create-accounts.ts
packages/board-server/src/server/storage-providers/firestore.ts
packages/board-server/src/server/storage-providers/sqlite.ts
packages/board-server/src/server/store.ts
packages/board-server/src/server/types.ts
packages/board-server/tests/integration/board-server.test.ts

Users are only created in scripts and tests. The code for creating API keys doesn't need to be in server code.

[board-server] Simplify user creation

---

packages/board-server/src/server.ts
packages/unified-server/app/index.html
packages/unified-server/src/server/main.ts

[unified-server] Add the board title to the app view HTML

---

.changeset/all-pots-dress.md
packages/shared-ui/src/app-templates/basic/index.ts

- **Teach basic app view about OAuth secrets.**
- **docs(changeset): Teach app view about OAuth secrets.**

oauth app view

---

packages/a2/bgl/audio-generator.bgl.json
packages/a2/bgl/image-generator-workbench.bgl.json

This hits the backend which will give us a bit more control over which voices we can use, etc.

Add new Audio generator BGL

---

.changeset/eighty-times-hope.md
packages/shared-ui/src/elements/board-activity/board-activity.ts
packages/shared-ui/src/elements/module-editor/module-editor.ts
packages/visual-editor/src/index.ts

[shared-ui] Allow running of imperative graph

---

.changeset/happy-lands-pump.md
packages/shared-ui/src/app-templates/basic/index.ts

- **Let secrets inputs take precedence over other inputs in app view.**
- **docs(changeset): Check for secrets input first in app view.**

secrets over inputs

---

packages/board-server/src/server/boards/describe.ts
packages/board-server/src/server/boards/index.ts
packages/board-server/src/server/boards/loader.ts
packages/board-server/src/server/boards/utils/board-server-provider.ts
packages/board-server/src/server/storage-providers/firestore.ts

Replace all usages with `loadBoard`

[board-server] Get rid of store.get

---

packages/shared-ui/src/app-templates/basic/index.ts
packages/shared-ui/src/elements/app-preview/app-preview.ts
packages/shared-ui/src/elements/app-preview/app-theme-creator.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts
packages/shared-ui/src/events/events.ts

[shared-ui] Teach designer about theme options

---

packages/shared-ui/src/flow-gen/flow-generator.ts

Bug fix for https://github.com/breadboard-ai/breadboard/pull/4908

[flowgen] Bug fix for AppCatalyst response expectation

---

packages/board-server/src/server/auth.ts
packages/board-server/src/server/blobs/create.ts
packages/board-server/src/server/boards/create.ts
packages/board-server/src/server/boards/delete.ts
packages/board-server/src/server/boards/invoke.ts
packages/board-server/src/server/boards/list.ts
packages/board-server/src/server/boards/loader.ts
packages/board-server/src/server/boards/post.ts
packages/board-server/src/server/boards/run.ts
packages/board-server/src/server/boards/utils/board-server-provider.ts
packages/board-server/src/server/boards/utils/verify-key.ts
packages/board-server/src/server/home/index.ts
packages/board-server/src/server/info/index.ts
packages/board-server/src/server/storage-providers/firestore.ts
packages/board-server/src/server/store.ts
packages/board-server/src/server/types.ts
packages/board-server/tests/firestore/board-server.test.ts
packages/board-server/tests/firestore/firestore-storage-provider.test.ts

[board-server] Extract provider interface and add tests

---

packages/shared-ui/src/elements/elements.ts
packages/shared-ui/src/elements/welcome-panel/project-listing.ts
packages/shared-ui/src/flow-gen/describe-edit-button.ts
packages/shared-ui/src/flow-gen/describe-flow-panel.ts

Just makes it a little easier to work on.

[flowgen] Move flowgen components into flow-gen folder

---

packages/shared-ui/src/flow-gen/describe-edit-button.ts
packages/shared-ui/src/flow-gen/flow-generator.ts

[flowgen] Add ability to apply a constraint when generating a flow

---

.changeset/honest-geckos-eat.md
packages/shared-ui/src/elements/asset-organizer/asset-organizer.ts
packages/shared-ui/src/elements/editor/graph-renderer.ts
packages/shared-ui/src/elements/fast-access-menu/fast-access-menu.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/state/project.ts
packages/shared-ui/src/strings/en_US/asset-organizer.ts
packages/shared-ui/src/transforms/create-param.ts
packages/shared-ui/src/transforms/delete-param.ts
packages/shared-ui/src/transforms/index.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/edit.ts

[shared-ui] Teach Asset Organizer about unused params

---

packages/board-server/src/server/storage-providers/firestore.ts
packages/board-server/tests/firestore/firestore-storage-provider.test.ts

We're parsing it anyway, we may as well. Also update tests.

[board-server] Return graph from list

---

packages/board-server/src/server/boards/create.ts
packages/board-server/src/server/boards/loader.ts
packages/board-server/src/server/boards/utils/board-server-provider.ts
packages/board-server/src/server/storage-providers/firestore.ts
packages/board-server/src/server/storage-providers/inmemory.test.ts
packages/board-server/src/server/storage-providers/inmemory.ts
packages/board-server/src/server/store.ts
packages/board-server/tests/firestore/firestore-storage-provider.test.ts

[board-server] Add storage provider method to look up boards by name

---

packages/board-server/src/server/boards/create.ts
packages/board-server/src/server/boards/loader.ts
packages/board-server/src/server/boards/utils/board-server-provider.ts
packages/board-server/src/server/storage-providers/firestore.ts
packages/board-server/src/server/storage-providers/inmemory.test.ts
packages/board-server/src/server/storage-providers/inmemory.ts
packages/board-server/src/server/store.ts
packages/board-server/tests/firestore/firestore-storage-provider.test.ts

[board-server] Update the board loader to make the owner optional

---

packages/board-server/src/server/storage-providers/firestore.ts
packages/board-server/tests/firestore/firestore-storage-provider.test.ts

[board-server] Allow looking up boards by name in Firestore

---

packages/board-server/src/server.test.ts
packages/board-server/src/server/boards/delete.ts
packages/board-server/src/server/boards/index.ts
packages/board-server/src/server/boards/post.ts

[board-server] Add support for name-only routes

---

.changeset/eleven-games-jam.md
packages/a2/scripts/push.ts

- **Add URL-adjustment to the push script.**
- **docs(changeset): Adjust tool URLs in push.**

better push

---

.changeset/solid-oranges-flow.md
packages/breadboard/src/editor/graph.ts
packages/breadboard/src/editor/operations/change-edge-metadata.ts
packages/breadboard/src/editor/types.ts
packages/breadboard/src/inspector/graph/edge.ts
packages/breadboard/src/inspector/types.ts
packages/manifest/bbm.schema.json
packages/schema/breadboard.schema.json
packages/types/src/graph-descriptor.ts

- **Introduce edge metadata.**
- **docs(changeset): Introduce Edge metadata.**

edge metadata

---

.changeset/purple-boats-sink.md
packages/breadboard/src/harness/secrets.ts

- **Stop mutating handlers array when asking for secrets.**
- **docs(changeset): Fix the bug where secrets are always asked for.**

fix secrets bug

---

.changeset/evil-ducks-wave.md
packages/shared-ui/src/elements/step-editor/graph-node.ts
packages/shared-ui/src/elements/step-editor/renderer.ts
packages/shared-ui/src/elements/step-editor/utils/to-grid-size.ts

Teach DOM Renderer to emit location data on settle

---

.changeset/early-knives-obey.md
packages/shared-ui/src/elements/step-editor/renderer.ts

[shared-ui] Teach DOM Renderer about spacebar-dragging

---

.changeset/some-hounds-kneel.md
packages/shared-ui/src/elements/step-editor/graph-node.ts
packages/shared-ui/src/elements/step-editor/graph.ts
packages/shared-ui/src/elements/step-editor/renderer.ts

[shared-ui] Small fixes to DOM Renderer

---

.changeset/wise-islands-do.md
packages/shared-ui/src/elements/step-editor/drag-connector.ts
packages/shared-ui/src/elements/step-editor/events/events.ts
packages/shared-ui/src/elements/step-editor/graph-node.ts
packages/shared-ui/src/elements/step-editor/renderer.ts

[shared-ui] Teach DOM Renderer to edit nodes

---

.changeset/beige-worlds-tease.md
packages/shared-ui/src/elements/step-editor/graph-edge.ts
packages/shared-ui/src/elements/step-editor/graph-node.ts
packages/shared-ui/src/elements/step-editor/graph.ts
packages/shared-ui/src/elements/step-editor/renderer.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts

Teach DOM Renderer about run activity

---

.changeset/eager-singers-flash.md
packages/shared-ui/src/elements/welcome-panel/project-listing.ts

[shared-ui] Fix project listing search

---

.changeset/slow-mangos-speak.md
packages/shared-ui/src/elements/step-editor/box.ts
packages/shared-ui/src/elements/step-editor/entity.ts
packages/shared-ui/src/elements/step-editor/events/events.ts
packages/shared-ui/src/elements/step-editor/graph-node.ts
packages/shared-ui/src/elements/step-editor/renderer.ts

[shared-ui] Various DOM Renderer fixes

---

.changeset/lemon-hairs-share.md
packages/shared-ui/src/elements/step-editor/editor-controls.ts
packages/shared-ui/src/elements/step-editor/renderer.ts

[shared-ui] Teach DOM Renderer about "Add Step"

---

.changeset/ready-poets-wonder.md
packages/shared-ui/src/elements/step-editor/graph.ts
packages/shared-ui/src/elements/step-editor/renderer.ts

[shared-ui] Teach DOM Renderer about moving subgraphs

---

.changeset/afraid-bees-like.md
packages/shared-ui/src/elements/step-editor/renderer.ts

[shared-ui] Make some small UI tweaks

---

.changeset/stale-spoons-jam.md
packages/shared-ui/src/elements/step-editor/drag-connector.ts
packages/shared-ui/src/elements/step-editor/editor-controls.ts
packages/shared-ui/src/elements/step-editor/events/events.ts
packages/shared-ui/src/elements/step-editor/graph-node.ts
packages/shared-ui/src/elements/step-editor/renderer.ts

[shared-ui] Add drag-to-add from node (part 1)

---

.changeset/large-kings-turn.md
packages/shared-ui/src/elements/step-editor/renderer.ts

[shared-ui] Add pinch zoom to DOM Renderer

---

.changeset/sixty-teeth-itch.md
packages/shared-ui/src/elements/step-editor/graph-node.ts

[shared-ui] Add missing icons for steps in DOM Renderer

---

packages/shared-ui/src/revision-history/revision-history-panel.ts

Adds keyboard select (tab, enter) and a hover effect

[revision history] Accessibility improvements

---

.changeset/dark-dragons-warn.md
packages/shared-ui/src/elements/step-editor/graph-edge.ts

Fixes #5071
Fixes #5085
I am once again astounded at the amount of stuff SVG supports.

[shared-ui] Improve box-edge intersection

---

.changeset/nine-yaks-give.md
packages/shared-ui/src/elements/step-editor/graph-edge.ts
packages/shared-ui/src/elements/step-editor/graph-node.ts
packages/shared-ui/src/elements/step-editor/graph.ts
packages/shared-ui/src/elements/step-editor/renderer.ts

[shared-ui] DOM Renderer tidying

---

.changeset/upset-pans-wear.md
packages/shared-ui/src/elements/step-editor/drag-connector.ts
packages/shared-ui/src/elements/step-editor/graph.ts
packages/shared-ui/src/elements/step-editor/renderer.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/transforms/change-edge.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/edit.ts

[shared-ui] Improve edge management

---

.changeset/free-meals-open.md
packages/shared-ui/src/elements/step-editor/drag-connector.ts
packages/shared-ui/src/elements/step-editor/events/events.ts
packages/shared-ui/src/elements/step-editor/graph-node.ts
packages/shared-ui/src/elements/step-editor/graph.ts
packages/shared-ui/src/elements/step-editor/renderer.ts

[shared-ui] Add drag-to-add from node (part 2)

---

packages/board-server/src/server/auth.ts

...instead of unexpired ones
Fixes #5116

[board-server] Purge expired entries from access token cache

---

.changeset/thirty-birds-run.md
packages/shared-ui/src/transforms/change-edge.ts

- **Teach `ChangeEdge` to correctly pick the in port.**
- **docs(changeset): Teach `ChangeEdge` to correctly pick the in port.**

change edge in port

---

packages/agent-kit/agent.kit.json
packages/agent-kit/boards/specialist.bgl.json
packages/breadboard/src/inspector/graph/ports.ts
packages/breadboard/src/types.ts
packages/jsandbox/src/environment.d.ts
packages/jsandbox/src/type-declarations.ts
packages/visual-editor/public/agent.kit.json

Not yet used nor respected by the UI

Add hint-single-line for smaller text fields

---

.changeset/wicked-baths-lay.md
packages/shared-ui/src/elements/component-selector/component-selector-overlay.ts
packages/shared-ui/src/elements/step-editor/editor-controls.ts
packages/shared-ui/src/elements/step-editor/renderer.ts

[shared-ui] Add missing icons & tweak empty graph check

---

.changeset/green-books-hammer.md
packages/shared-ui/src/elements/step-editor/drag-connector.ts
packages/shared-ui/src/elements/step-editor/graph-node.ts

[shared-ui] Tweaks to renderer

---

.changeset/itchy-foxes-repeat.md
packages/shared-ui/src/elements/step-editor/constants.ts
packages/shared-ui/src/elements/step-editor/events/events.ts
packages/shared-ui/src/elements/step-editor/graph-node.ts
packages/shared-ui/src/elements/step-editor/graph.ts
packages/shared-ui/src/elements/step-editor/renderer.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/transforms/move-nodes-to-graph.ts
packages/visual-editor/src/commands/commands.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/board.ts
packages/visual-editor/src/runtime/edit.ts

[shared-ui] Teach DOM Renderer about moving nodes

---

.changeset/early-bikes-strive.md
packages/shared-ui/src/elements/step-editor/entity.ts
packages/shared-ui/src/elements/step-editor/renderer.ts

[shared-ui] Improve selection behavior in DOM Renderer

---

.changeset/ninety-pears-roll.md
packages/shared-ui/src/elements/step-editor/events/events.ts
packages/shared-ui/src/elements/step-editor/graph-edge.ts
packages/shared-ui/src/elements/step-editor/graph-node.ts
packages/shared-ui/src/elements/step-editor/graph.ts
packages/shared-ui/src/elements/step-editor/renderer.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/transforms/change-edge-attachment-point.ts
packages/shared-ui/src/transforms/index.ts
packages/shared-ui/src/types/types.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/edit.ts

[shared-ui] Teach DOM Renderer about edge attachment moving

---

.changeset/slimy-garlics-clap.md
packages/shared-ui/src/data/settings-store.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts

[shared-ui] Update default renderer to DOM

---

.changeset/wide-aliens-worry.md
packages/shared-ui/src/data/settings-store.ts
packages/shared-ui/src/elements/step-editor/graph-edge.ts
packages/shared-ui/src/elements/step-editor/renderer.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts

[shared-ui] Promote edge point reparenting from experimental

---

.changeset/giant-eels-happen.md
packages/shared-ui/src/elements/input/llm-input/llm-input.ts
packages/shared-ui/src/elements/input/text-editor/text-editor.ts
packages/shared-ui/src/elements/input/user-input.ts
packages/shared-ui/src/utils/behaviors.ts

[shared-ui] Teach text-editor & llm-input about single line hint

---

.changeset/vast-words-flow.md
packages/breadboard/src/inspector/graph/graph-queries.ts
packages/breadboard/src/inspector/graph/graph.ts
packages/breadboard/src/inspector/graph/inspectable-asset.ts
packages/breadboard/src/inspector/types.ts
packages/manifest/bbm.schema.json
packages/schema/breadboard.schema.json
packages/types/src/graph-descriptor.ts

- **Add `assets` and `assetEdges` to `InspectableGraph`.**
- **docs(changeset): Add `assets` and `assetEdge` to `InspectableGraph`.**

asset edges

---

.changeset/little-mails-say.md
packages/breadboard/src/data/common.ts
packages/breadboard/src/data/default-data-store.ts
packages/breadboard/tests/inspector/default-data-store.ts
packages/shared-ui/src/elements/output/llm-output/llm-output.ts

- **Teach deflate and llm-output to handle `text/html`.**
- **docs(changeset): Teach deflate and llm-output to handle text/html mimeType**

text html inline data

---

packages/board-server/src/server.test.ts
packages/board-server/src/server/boards/create.ts
packages/board-server/src/server/boards/post.ts
packages/board-server/src/server/storage-providers/firestore.ts
packages/board-server/src/server/storage-providers/inmemory.test.ts
packages/board-server/src/server/storage-providers/inmemory.ts
packages/board-server/src/server/store.ts

This refactoring is a step towards gdrive storage implementation.

Refactoring create/post request handler to rely on more unified interface (with gdrive)

---

.github/workflows/deploy-website.yml
.github/workflows/labs-prototypes-ci.yml

https://github.com/google/wireit/issues/1297

Disable wireit caching temporarily

---

.changeset/kind-paws-film.md
packages/breadboard/src/sandbox/capabilities-manager.ts
packages/jsandbox/src/capabilities.ts

- **Add a bit more robust error handling around invoking capabilities.**
- **docs(changeset): Add a bit more robust error handling around capabilities.**

capability errors

---

.changeset/chatty-hotels-shake.md
packages/shared-ui/src/elements/board-activity/board-activity.ts

- **Unbreak params**
- **docs(changeset): Unbreak parameters.**

params params

---

packages/board-server/src/server.test.ts
packages/board-server/src/server/boards/create.ts
packages/board-server/src/server/boards/delete.ts
packages/board-server/src/server/boards/invoke.ts
packages/board-server/src/server/boards/list.ts
packages/board-server/src/server/boards/post.ts
packages/board-server/src/server/boards/run.ts
packages/board-server/src/server/boards/utils/board-server-provider.ts
packages/board-server/src/server/storage-providers/sqlite.ts
packages/board-server/src/server/store.ts

Reverts breadboard-ai/breadboard#5271, because it broke unified-server

Revert "[server] changed board.path to = name (without userid)"

---

.changeset/cool-roses-sin.md
packages/shared-ui/src/elements/app-preview/app-preview.styles.ts
packages/shared-ui/src/elements/app-preview/app-preview.ts
packages/shared-ui/src/elements/entity-editor/entity-editor.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts

[shared-ui] Adjust app / console output

---

.changeset/rich-seas-buy.md
packages/shared-ui/src/elements/entity-editor/entity-editor.ts
packages/shared-ui/src/utils/behaviors.ts

[shared-ui] Only show port label when not `hint-controller`

---

.changeset/stale-lands-arrive.md
packages/shared-ui/src/elements/overlay/board-details.ts

[shared-ui] Simplify board details pane

---

.changeset/evil-windows-refuse.md
packages/shared-ui/src/elements/step-editor/graph-node.ts
packages/shared-ui/src/elements/step-editor/utils/create-truncated-value.ts

[shared-ui] Update empty step message

---

.changeset/clever-cooks-glow.md
packages/shared-ui/src/elements/overflow-menu/overflow-menu.ts
packages/shared-ui/src/strings/en_US/global.ts
packages/visual-editor/src/index.ts

[shared-ui] Simplify main overflow menu

---

.changeset/odd-plants-wink.md
packages/shared-ui/src/elements/entity-editor/entity-editor.ts
packages/shared-ui/src/elements/fast-access-menu/fast-access-menu.ts
packages/shared-ui/src/elements/input/text-editor/text-editor.ts
packages/shared-ui/src/flow-gen/describe-edit-button.ts
packages/shared-ui/src/styles/fab.ts
packages/visual-editor/src/index.ts

[shared-ui] Add basic UI support for `hint-controller`

---

.github/workflows/deploy-website.yml
.github/workflows/labs-prototypes-ci.yml
package-lock.json
package.json
packages/bbrt/package.json
packages/board-server/package.json
packages/build-code/package.json
packages/build/package.json
packages/connection-client/package.json
packages/connection-server/package.json
packages/google-drive-kit/package.json
packages/jsandbox/package.json
packages/python-wasm/package.json
packages/types/package.json
packages/unified-server/package.json
packages/website/package.json

See https://github.com/google/wireit/issues/1297

Update wireit version and restore caching

---

.changeset/puny-streets-boil.md
packages/breadboard/src/inspector/graph/graph-queries.ts

- **Filter `@@thumbnail` and `@@splash` assets from InspectableAssets.**
- **docs(changeset): Filter assets that start "@@": these are internal to BGL.**

filter at at

---

.changeset/true-cloths-know.md
packages/a2/bgl/ask-user-workbench.bgl.json
packages/breadboard/src/harness/local-runner.ts

- **Clear pending results after replying and resuming the run.**
- **docs(changeset): Clear pending result in LocalRunner after resuming**

clear pending result

---

.changeset/real-pears-attend.md
packages/a2/bgl/tri-mind-example.bgl.json

- **Add a multi-step example.**
- **docs(changeset): Add an example with multiple steps.**

tri mind example

---

.changeset/light-sloths-stare.md
packages/shared-ui/src/elements/step-editor/renderer.ts

[shared-ui] Disallow moving while dragging nodes

---

.changeset/tidy-ravens-show.md
packages/shared-ui/src/elements/step-editor/graph-node.ts
packages/shared-ui/src/elements/step-editor/renderer.ts

[shared-ui] Restore highlight on run

---

.changeset/funny-moose-dig.md
packages/shared-ui/src/elements/step-editor/graph-edge.ts

[shared-ui] Fix edge rendering

---

.changeset/fast-buses-grin.md
packages/shared-ui/src/elements/step-editor/graph.ts

[shared-ui] Teach MegaStep about subtypes in graph

---

.changeset/bumpy-hairs-swim.md
packages/a2/bgl/generate-workbench.bgl.json
packages/shared-ui/src/state/project.ts

- **Use the right board server filter for tools.**
- **docs(changeset): Bring back tools**

bring back tools

---

.changeset/fast-ends-bet.md
packages/shared-ui/src/elements/google-drive/google-drive-file-id.ts

- **Remove "ownedByMe" view restriction on Google Drive.**
- **docs(changeset): Remove "owned by me" view restriction in Google Drive picker.**

see all in drive picker

---

packages/shared-ui/src/elements/input/expanding-textarea.ts
packages/shared-ui/src/elements/welcome-panel/project-listing.ts
packages/shared-ui/src/flow-gen/describe-flow-panel.ts
packages/shared-ui/src/flow-gen/flow-generator.ts
packages/shared-ui/src/strings/en_US/project-listing.ts

It is now more fluid to continue interacting with flowgen when the backend asks for clarification etc.

[flowgen] Support more fluid N-turn flowgen on homepage

---

.changeset/wet-doodles-chew.md
packages/board-server-management/src/board-server-aware-data-store.ts
packages/unified-server/src/client/app/utils/runner.ts
packages/visual-editor/src/runtime/run.ts
packages/visual-editor/src/runtime/runtime.ts
packages/visual-editor/src/runtime/sideboard-runtime.ts

- **Teach BoardServerAwareDataStore to choose the main graph URL for finding the board server.**
- **docs(changeset): Teach BoardServerAwareDataStore to choose the main graph URL to find the right board server.**

board server graph url

---

.changeset/vast-lamps-stick.md
packages/board-server-management/src/board-server-aware-data-store.ts
packages/breadboard/src/loader/types.ts
packages/remote-board-server/src/remote-board-server.ts
packages/remote-board-server/src/remote-part-transformer.ts
packages/shared-ui/src/state/project.ts

- **Teach `RemotePartTransformer` to use main graph URL.**
- **docs(changeset): Teach `RemotePartTransformer` to use main graph URL.**

remote part transformer main graph

---

.changeset/tangy-toes-drum.md
packages/shared-ui/src/elements/app-preview/app-preview.styles.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts

- **Remove an extra board-activity instance.**
- **Make board activity scrollable.**
- **docs(changeset): Make activity panel scrollable again.**

board activity polish

---

.changeset/bright-dancers-throw.md
packages/visual-editor/src/index.ts

- **Remove spurious "Run Stopped" on finished runs.**
- **docs(changeset): Remove spurious "Run Stopped" on finished run.**

no run stopped

---

packages/shared-ui/src/elements/input/expanding-textarea.ts
packages/shared-ui/src/flow-gen/describe-flow-panel.ts
packages/shared-ui/src/strings/en_US/project-listing.ts

Typing tab completes them (no icon to indicate this yet, will add in followup).

Replace homepage NL suggestion chips with rotating placeholders

---

packages/shared-ui/src/flow-gen/flow-generator.ts

The original issue was hard to reproduce so I'm
not confident in fix, but have confirmed it is not a regression.

Handle non-ascii characters in the flow JSON

---

packages/shared-ui/src/flow-gen/flowgen-homepage-panel.ts

Small tweaks and one swap out.

Update the set of intents that we cycle through

---

packages/shared-ui/src/elements/entity-editor/entity-editor.ts

Just let the graph replace event propagate.

Fix broken in-step flowgen

---

.changeset/heavy-meals-invite.md
packages/unified-server/scripts/deploy-to-gcp.sh

- **Make it possible to deploy to another service.**
- **docs(changeset): Allow passing a service name to deploy script**

cr service

---

.changeset/small-games-beam.md
packages/visual-editor/.env.development
packages/visual-editor/.env.production
packages/visual-editor/src/bootstrap.ts
packages/visual-editor/src/runtime/board.ts

- **Teach board server switch machinery that board server is optional.**
- **docs(changeset): Teach board server machinery that BOARD_SERVICE might be optional.**

optional board server

---

.changeset/old-eels-float.md
packages/visual-editor/src/index.ts

- **Remove "Unable to connecto to board server" error for new users.**
- **docs(changeset): Remove the "Unable to connect to board server" error for newcomers.**

happy new user

---

.changeset/fruity-spies-bow.md
packages/shared-ui/src/elements/welcome-panel/project-listing.ts
packages/shared-ui/src/strings/en_US/project-listing.ts

- **Use a constant label for main page list of flows**
- **docs(changeset): Use a constant label for project list.**

your flows constant

---

.changeset/four-groups-invent.md
packages/shared-ui/src/elements/component-selector/component-selector-overlay.ts

- **Only show main three steps in selector.**
- **docs(changeset): Only show three steps in component selector.**

tiny selector

---

.changeset/solid-pillows-check.md
packages/visual-editor/src/index.ts

- **Teach blank boards to get properly localized title.**
- **docs(changeset): Properly localize titles for untitled boards.**

localize untitled titles

---

.github/workflows/deploy-website.yml

Disabled since this started failing in CI, but is not currently being maintained

Disable website deploy

---

packages/shared-ui/src/elements/input/expanding-textarea.ts
packages/shared-ui/src/elements/welcome-panel/gallery.ts
packages/shared-ui/src/elements/welcome-panel/project-listing.ts
packages/visual-editor/public/styles/global.css

- Allow gallery items to grow in width
- Fix line height and alignment of title
- Resize observer to allow the flowgen textarea to grow if needed when window size changed

Homepage polish

---

packages/manifest/bbm.schema.json
packages/schema/breadboard.schema.json
packages/shared-ui/src/edit-history/edit-history-overlay.ts
packages/shared-ui/src/edit-history/edit-history-panel.ts
packages/shared-ui/src/elements/app-preview/app-preview.styles.ts
packages/shared-ui/src/elements/app-preview/app-preview.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.styles.ts
packages/shared-ui/src/elements/ui-controller/ui-controller.ts
packages/types/src/graph-descriptor.ts
packages/visual-editor/src/runtime/board.ts

Also renames all code from "revision history" to "edit history"

New compact design for edit history, and show intent as tooltip

---

packages/breadboard/src/data/inflate-deflate.ts

Remove image_generation from the ready for GCS list

---

packages/shared-ui/src/elements/input/expanding-textarea.ts
packages/shared-ui/src/elements/step-editor/editor-controls.ts
packages/shared-ui/src/flow-gen/flowgen-editor-input.ts

Show original intent as placeholder for in-editor flowgen input

---

.changeset/fuzzy-clubs-buy.md
packages/breadboard/src/graph-based-node-handler.ts

- **Perf: make describe use a faster path.**
- **docs(changeset): Make describer use a faster path for graphs with URLs.**

perf describer

---

.changeset/six-buckets-fall.md
package-lock.json
packages/a2/bgl/google-slides-workbench.bgl.json
packages/breadboard/src/editor/operations/change-asset-metadata.ts
packages/shared-ui/package.json
packages/shared-ui/src/connectors/types.ts
packages/shared-ui/src/elements/asset-organizer/asset-organizer.ts
packages/shared-ui/src/elements/entity-editor/entity-editor.ts
packages/shared-ui/src/elements/google-drive/google-apis.ts
packages/shared-ui/src/elements/google-drive/google-drive-file-id.ts
packages/shared-ui/src/elements/google-drive/google-drive-file-viewer.ts
packages/shared-ui/src/elements/input/delegating-input.ts
packages/shared-ui/src/plugins/input-plugin.ts
packages/shared-ui/src/state/connector-instance.ts
packages/shared-ui/src/state/graph-asset.ts
packages/shared-ui/src/state/organizer.ts
packages/shared-ui/src/state/project.ts
packages/shared-ui/src/state/types.ts
packages/shared-ui/src/transforms/edit-connector.ts
packages/shared-ui/src/transforms/transform-all-nodes-all-graphs.ts
packages/shared-ui/src/transforms/update-asset-refs.ts
packages/shared-ui/src/transforms/update-asset-with-refs.ts
packages/visual-editor/package.json

- **Add "Create New Document" button to Google Drive picker.**
- **Use asset title to name new doc.**
- **Detect visual-only changes in `ChangeAssetMetadata`.**
- **Teach step editor to update connector titles.**
- **Properly update connector refs.**
- **Add `GraphAsset.updateTitle` method and start using it.**
- **docs(changeset): Add "Create New Document" to Google Drive file picker and many other fixes.**

google drive new

---

.changeset/tender-kiwis-train.md
packages/board-server/src/server/proxy/gcs-aware-fetch.ts
packages/board-server/src/server/proxy/index.ts

- **docs(changeset): Add a `GcsAwareFetch` that nests Core Kit's fetch and does nothing (for now).**
- **Add a `GcsAwareFetch` that nests Core Kit's fetch and does nothing (for now).**

gcs aware fetch

---

.changeset/curly-masks-bathe.md
packages/breadboard/src/editor/graph.ts
packages/breadboard/src/editor/types.ts
packages/breadboard/src/harness/local.ts
packages/breadboard/src/harness/types.ts
packages/breadboard/src/utils/promise-queue.ts
packages/breadboard/tests/node/utils/promise-queue.ts
packages/shared-ui/src/sideboards/autoname.ts
packages/shared-ui/src/sideboards/types.ts
packages/visual-editor/src/runtime/sideboard-runtime.ts

- **Teach graph editor to apply top-level edits sequentially relative to each other.**
- **Discard autonaming task when user makes edits.**
- **Add "silent" diagnostics mode where not even errors are reported.**
- **docs(changeset): Make autoname more polite to user.**

deconflict autoname

---

.changeset/forty-drinks-run.md
packages/shared-ui/src/elements/entity-editor/entity-editor.ts

- **Teach `bb-entity-editor` to remember the right forms and values.**
- **docs(changeset): Teach entity editor to about remembering the right values.**

entity editor fix

---

.changeset/honest-zebras-march.md
packages/breadboard/src/sandboxed-run-module.ts
packages/unified-server/.env.production
packages/unified-server/src/init.ts
packages/visual-editor/src/bootstrap.ts
packages/visual-editor/src/index.ts

- **Introduce `RunModuleInvocationFilter` and start using it.**
- **docs(changeset): Only allow invoking modules in A2.**

only allow a2 modules

---

.changeset/fruity-dryers-jam.md
packages/shared-ui/src/elements/entity-editor/entity-editor.ts

- **Hide advanced settings when there aren't any.**
- **docs(changeset): Hide advanced settings when there aren't any.**

hide advanced

---

packages/shared-ui/src/elements/google-drive/google-apis.ts
packages/shared-ui/src/elements/google-drive/google-drive-debug-panel.ts

[drive] Prove out integration of the official share dialog

---

.changeset/moody-pandas-press.md
packages/shared-ui/src/elements/ui-controller/ui-controller.styles.ts

[shared-ui] Prevent button wraps

---

.changeset/open-birds-draw.md
packages/visual-editor/src/index.styles.ts
packages/visual-editor/src/index.ts

[shared-ui] Remove edit pencil

---

.changeset/early-kings-work.md
packages/shared-ui/src/app-templates/basic/index.ts
packages/shared-ui/src/elements/welcome-panel/project-listing.ts

Includes a in-flight fix for some types, too

[shared-ui] Add restart button to app view

---

.changeset/calm-chairs-remain.md
packages/shared-ui/src/elements/toast/toast.ts

[shared-ui] Prevent toasts from overlapping

---

.changeset/stupid-women-tease.md
packages/shared-ui/src/elements/step-editor/renderer.ts

[shared-ui] Teach added step to show Default Add

---

.changeset/happy-streets-worry.md
packages/unified-server/Dockerfile
packages/unified-server/scripts/deploy-to-gcp.ts

- **Introduce `deploy-to-gcp.ts`, which allows passing variables to docker build.**
- **docs(changeset): Introduce `deploy-to-gcp.ts`, which allows passing env vars to build.**

deploy env vars

---

packages/shared-ui/src/elements/connection/connection-broker.ts

We had an un-sanitized interpolation plus innerHTML assignment. Removed interpolation (didn't really need it), and replaced all error rendering with textContent assignment.

[oauth] Fix XSS issue in connection broker

---

.changeset/orange-melons-attack.md
packages/unified-server/src/server/main.ts

- **Clamp down the origin value to `.googleapis.com`.**
- **docs(changeset): Clamp down the origin value to `.googleapis.com`.**

clamp down allowlist

---

.changeset/wicked-maps-train.md
packages/shared-ui/src/app-templates/basic/index.ts

- **Handle the case with no text input.**
- **docs(changeset): Handle the case of user input with no text.**

ask user no text input

---

.changeset/early-words-strive.md
packages/a2/bgl/generate-workbench.bgl.json
packages/shared-ui/src/elements/entity-editor/entity-editor.ts

- **When reactive value changes, auto-save.**
- **docs(changeset): When reactive value changes, auto-save.**

reactive auto save

---

.changeset/witty-files-rhyme.md
packages/google-drive-kit/src/board-server/operations.ts
packages/google-drive-kit/src/board-server/save-debouncer.ts
packages/google-drive-kit/src/board-server/server.ts

- **Introduce a simple save debouncer to Drive board server.**
- **Better logging.**
- **docs(changeset): Introduce a simple save debouncer to Google Drive board server.**

save debouncer

---

.changeset/stale-radios-smash.md
package-lock.json
packages/breadboard/src/loader/types.ts
packages/google-drive-kit/package.json
packages/google-drive-kit/src/board-server/events.ts
packages/google-drive-kit/src/board-server/save-debouncer.ts
packages/google-drive-kit/src/board-server/server.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/board.ts
packages/visual-editor/src/runtime/events.ts
packages/visual-editor/src/runtime/types.ts

- **Remove unused methods.**
- **Add missing dependency to google-drive-kit.**
- **Introduce "savestatuschange" event on BoardServer and start using it.**
- **docs(changeset): Introduce "savestatuschange" event on `BoardServer` and start using it.**

eventful saves

---

.changeset/mighty-candles-push.md
packages/breadboard/src/loader/types.ts
packages/google-drive-kit/src/board-server/save-debouncer.ts
packages/google-drive-kit/src/board-server/server.ts
packages/shared-ui/src/events/events.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/board.ts

- **Differentiate between user-intiated save and auto-save**
- **docs(changeset): Distinguish between user-initiated save and autosave.**

user initiated save

---

.changeset/twenty-turtles-slide.md
packages/board-server/src/server/storage-providers/firestore.ts

- **Only load the user's boards.**
- **Add a separate query for featured boards.**
- **docs(changeset): Only load user's boards and featured boards.**

split out featured

---

.changeset/five-yaks-visit.md
packages/visual-editor/src/runtime/board.ts

- **Correcly close the current tab when remixing.**
- **docs(changeset): Correctly close the tab when remixing.**

remix close tab

---

.changeset/brave-wombats-hide.md
packages/shared-ui/src/app-templates/basic/index.ts

- **docs(changeset): Fix chat with user.**
- **Fix chat with user.**

fix chat with user

---

.changeset/fifty-drinks-fold.md
packages/jsandbox/src/module.ts
packages/jsandbox/src/web.ts

- **Add time and size logging to module invocation.**
- **docs(changeset): Add time and size logging to module invocation.**

module logging

---

.changeset/ripe-games-worry.md
packages/shared-ui/src/elements/connection/connection-input.ts

- **Stop `bb-connection-input` from hammering at the server asking for list of connections.**
- **docs(changeset): Stop `bb-connection-input` from hammering connection server**

list connections less

---

.changeset/crazy-poets-think.md
packages/board-server/src/server/storage-providers/firestore.ts

- **Don't require published flag to be set to list boards.**
- **docs(changeset): Show all featured items on home page.**

ignore published flag firestore

---

packages/google-drive-kit/src/board-server/server.ts

tested manually on several gen related tasks

Enable proxy for google driver board service

---

.changeset/legal-phones-eat.md
packages/shared-ui/src/elements/fast-access-menu/fast-access-menu.ts

- **Hide parameters in "@" menu.**
- **docs(changeset): Hide parameters in "@" menu by default.**

hide params

---

.changeset/smooth-buckets-grin.md
packages/shared-ui/src/app-templates/basic/index.ts
packages/shared-ui/src/utils/signin-adapter.ts
packages/visual-editor/src/index.ts

- **Don't bring up secrets input dialog for `connection:$sign-in`.**
- **docs(changeset): Don't bring up sign in dialog for `connection:$sign-in`.**

dont ask for sign in secret

---

packages/shared-ui/src/elements/welcome-panel/gallery.ts

The prev/next buttons are always visible, the middle can scroll, and we automatically scroll the middle on interaction to ensure the current page is visible.

[homepage] Handle having more pages than fit on the screen

---

.changeset/witty-mammals-scream.md
packages/shared-ui/src/elements/board-activity/board-activity.ts
packages/visual-editor/src/index.ts

- **Unbreak inputs**
- **docs(changeset): Unbreak inputs after describe refactoring.**

unbreak inputs

---

.changeset/fresh-bears-grow.md
packages/google-drive-kit/src/board-server/server.ts

- **docs(changeset): Make failure to load gallery non-fatal**
- **Make failure to load gallery non-fatal.**

non fatal gallery load failure

---

.changeset/polite-coats-fix.md
packages/google-drive-kit/src/board-server/data-part-transformer.ts
packages/google-drive-kit/src/board-server/server.ts

- **Introduce `GoogleDriveDataPartTransformer`.**
- **docs(changeset): Introduce `GoogleDriveDataPartTransformer`.**

drive data part transformer

---

.changeset/loose-beers-itch.md
packages/google-drive-kit/src/board-server/data-part-transformer.ts
packages/jsandbox/src/module.ts
packages/jsandbox/src/web.ts

- **Move debugging messages to `console.debug`.**
- **docs(changeset): Move many debugging messages to `console.debug`.**

console debug

---

packages/google-drive-kit/src/google-drive-client.ts

This probably doesn't quite work yet, since the API is not actually available yet to test with, but hopefully it is very close.

[drive] Call the Drive proxy if other attempts fail

---

.changeset/spotty-dots-jog.md
packages/shared-ui/src/elements/app-preview/app-preview.ts

- **Show splash screen if it's a data URL.**
- **docs(changeset): Show splash image if it's a data URL.**

show data url splash

---

packages/shared-ui/src/elements/share-panel/share-panel.ts

Not the final design, just getting something working

[share] Add a link to open the app in a new tab when published

---

.changeset/some-crews-like.md
packages/a2/scripts/pull-featured.ts

- **Add `.bgl.json` to exported BGLs.**
- **docs(changeset): Add `.bgl.json` to exported files.**

pull featured bgl json

---

.changeset/nasty-ants-hunt.md
packages/google-drive-kit/src/board-server/server.ts

- **docs(changeset): Teach GoogleDriveBoardServer to differentiate between user's and featured items.**
- **Teach GoogleBoardServer to differentiate between user's and gallery items.**

user gallery access

---

.changeset/soft-pets-sleep.md
packages/google-drive-kit/src/board-server/server.ts

- **Fix item URL resolution**
- **docs(changeset): Fix item URL resolution**

fix url resolution

---

.changeset/poor-corners-lead.md
packages/shared-ui/src/elements/app-preview/app-preview.ts

- **Make absolute URL theme image display in app preview**
- **docs(changeset): Show absolute theme image URLs.**

theme image again

---

.changeset/swift-turtles-attend.md
packages/a2/scripts/api.ts
packages/a2/scripts/pull-featured.ts
packages/a2/scripts/update-props.ts
packages/google-drive-kit/src/board-server/operations.ts
packages/google-drive-kit/src/board-server/server.ts

- **Display thumbnails in gallery view.**
- **docs(changeset): Show gallery thumbnails**

show thumbnails

---

.changeset/tiny-donuts-mate.md
packages/board-server-management/src/index.ts
packages/visual-editor/src/index.ts
packages/visual-editor/src/runtime/board.ts
packages/visual-editor/src/runtime/runtime.ts

- **Don't try loading a graph when not signed in**
- **Ensure that first-time sign in propagates GoogleDriveClient.**
- **docs(changeset): Fix a couple of first-time Drive backend sign-in issues.**

polish first sign in

---

.changeset/orange-bats-cough.md
packages/visual-editor/index.html

- **Add checkbox outline to the list of symbols to download.**
- **docs(changeset): Fix the "always-checked checkbox" problem in entity editor.**

add checkbox

---

packages/google-drive-kit/src/board-server/operations.ts
packages/shared-ui/src/elements/app-preview/app-theme-creator.ts
packages/shared-ui/src/elements/welcome-panel/gallery.ts
packages/shared-ui/src/utils/image.ts

Also deleted bunch of code, switch to existing asBase64, which turns out to be 2x faster

[gdrive] load thumbnails asynchronously, not blocking the list. 

---

.changeset/dull-moose-call.md
packages/shared-ui/src/app-templates/basic/index.ts
packages/unified-server/src/client/app/elements/app-view/app-view.ts

- **Teach AppView to handle $sign-in secrets**
- **docs(changeset): Teach AppView to handle "$sign-in" secrets.**

unbreak app view

---

packages/shared-ui/src/elements/share-panel/share-panel.ts

Publishing doesn't always mean Public in the sense of world-readable.

[sharing] Use term "Published" instead of "Public"

---

.changeset/clear-drinks-admire.md
packages/board-server/src/server/boards/assets-drive.ts
packages/google-drive-kit/src/board-server/data-part-transformer.ts
packages/shared-ui/src/elements/output/llm-output/llm-output.ts

- **Route all "drive:/" assets through the Gemini Flie API.**
- **docs(changeset): Route all `drive:` assets through Gemini File API.**

make assets work

---

.changeset/light-wasps-refuse.md
packages/google-drive-kit/src/board-server/server.ts

- **Remove title disambiguation in gallery view**
- **docs(changeset): Remove title disambiguiation**

no title disambiguation

---

.changeset/smooth-adults-build.md
packages/google-drive-kit/src/board-server/operations.ts

- **Catch CORS errors in retryableFetch.**
- **docs(changeset): Catch CORS errors in retryableFetch.**

cors retryable

---

.changeset/empty-grapes-look.md
packages/board-server-management/src/index.ts
packages/google-drive-kit/src/board-server/server.ts

- **Remove spurious Drive file list call.**
- **docs(changeset): Remove spurious Drive file list call.**

faster drive

---

packages/google-drive-kit/src/board-server/api.ts
packages/google-drive-kit/src/board-server/operations.ts

As a side effect removing code duplication in operations.ts

[gdrive] Caching files list and applying kinda If-Modified-Since semantic to the search

---

.changeset/smooth-lemons-hear.md
packages/shared-ui/src/elements/app-preview/app-theme-creator.ts
packages/theme/src/index.ts
packages/unified-server/src/client/app/init.ts
packages/visual-editor/src/runtime/board.ts

- **Catch errors from palette generator.**
- **docs(changeset): Catch errors from palette generator.**

catch palette generator errors

---

packages/board-server/src/server/boards/assets-drive.ts

As needed by a subsequent change.

Factor out drive client initialization for reuse

---

.changeset/social-ideas-sneeze.md
packages/visual-editor/src/runtime/board.ts

- **Load google drive files when creating palettes**
- **docs(changeset): Load Drive files when creating palettes**

palette fix 2

---

packages/board-server/src/server/storage-providers/inmemory.test.ts
packages/breadboard/src/editor/blank.ts
packages/google-drive-kit/src/board-server/api.ts
packages/google-drive-kit/src/board-server/operations.ts
packages/google-drive-kit/src/board-server/server.ts

Reverts breadboard-ai/breadboard#5797
Breaks saving boards

Revert "[gdrive] Showing board descriptions in the list."

---

packages/board-server/src/server/storage-providers/inmemory.test.ts
packages/breadboard/src/editor/blank.ts
packages/google-drive-kit/src/board-server/api.ts
packages/google-drive-kit/src/board-server/operations.ts
packages/google-drive-kit/src/board-server/server.ts

Reverts breadboard-ai/breadboard#5801
Oops, this patch was not at fault.

Revert "Revert "[gdrive] Showing board descriptions in the list.""

---

packages/embed/src/types/types.ts
packages/shared-ui/src/elements/entity-editor/entity-editor.ts
packages/shared-ui/src/events/events.ts
packages/shared-ui/src/utils/board-id.ts

Runs prettifier on files I previously changed to avoid superfluous changes in future PRs.
Also tweaks iterate-on-prompt button disabling logic to also be disabled when assets present in prompt template.

Prettifies changed files & disables iterate-on-prompt button when assets present.

---

.changeset/cruel-lemons-cut.md
packages/a2/bgl/errors-workbench.bgl.json
packages/breadboard/src/sandbox/capabilities-manager.ts

- **Remove vestigial checks when unwrapping errors.**
- **docs(changeset): Remove vestigial checks when unwrapping errors.**

unwrap errors properly

---

.changeset/fair-squids-count.md
package-lock.json
packages/board-server-management/src/index.ts
packages/unified-server/package.json
packages/unified-server/src/client/app/init.ts
packages/unified-server/src/client/app/types/types.ts
packages/unified-server/src/client/app/utils/run-config.ts

- **Teach app view about GoogleDriveBoardServer**
- **docs(changeset): Teach app view about Google Drive board server.**

app view drive server

---

packages/a2/bgl/music-generator-workbench.bgl.json
packages/a2/bgl/music-generator.bgl.json
packages/a2/bgl/src/music-generator/main.ts

Add Lyria 2 Music Generation Step

---

.changeset/dry-candles-obey.md
packages/shared-ui/src/elements/google-drive/google-drive-file-id.ts
packages/shared-ui/src/elements/input/text-editor/text-editor.ts
packages/shared-ui/src/elements/output/llm-output/llm-output.ts

With a couple of small fixes elsewhere, too

[shared-ui] Improve Drive picker a little

---

.changeset/puny-swans-cry.md
packages/a2/scripts/update-props.ts

- **Gracefully skip files that don't exist.**
- **docs(changeset): Gracefully skip files that don't exist in update-props**

update props tweak

---

.changeset/wild-places-camp.md
packages/visual-editor/src/runtime/edit.ts

- **Only rename titles with autoname.**
- **Turn autoname on by default.**
- **docs(changeset): Turn autoname on by default.**

autoname on

---

packages/visual-editor/src/index.ts

Currently, Breadboard will throw an error if an embedder passes a `create_new_board` message with no prompt. With this change, that in should create an empty board that the user can populate.
Additionally, this sends the "back_clicked" message when the user clicks on the homepage logo from within a board.

[embed] Handle empty Create-new-board message & send message when home logo pressed

---

.changeset/dull-lands-exist.md
packages/shared-ui/src/state/connectors.ts
packages/shared-ui/src/state/console-entry.ts
packages/shared-ui/src/state/project-run.ts
packages/shared-ui/src/state/project.ts
packages/shared-ui/src/state/types.ts
packages/visual-editor/src/runtime/run.ts
packages/visual-editor/src/runtime/runtime.ts

- **Start sketching out Console state.**
- **Plumb to runtime.**
- **Start filling out details.**
- **Add insightful comments.**
- **Add another insightful comment.**
- **Introduce `ReactiveConsoleEntry`.**
- **docs(changeset): Sketch out Console state.**

console state

---

.changeset/petite-cases-trade.md
packages/shared-ui/src/state/console-entry.ts
packages/shared-ui/src/state/project-run.ts
packages/shared-ui/src/state/project.ts
packages/shared-ui/src/state/types.ts
packages/shared-ui/src/state/work-item.ts
packages/visual-editor/src/runtime/run.ts

- **Plumb inputs**
- **Teach console about clearing last run.**
- **Add `ProjectRun.estimatedEntryCount`.**
- **docs(changeset): Teach console to clear, plumb inputs, and add `estimatedEntryCount`.**

console moar

---

.changeset/nice-ghosts-divide.md
packages/shared-ui/src/elements/output/console-view/console-view.ts
packages/shared-ui/src/state/console-entry.ts
packages/shared-ui/src/state/project-run.ts
packages/shared-ui/src/state/types.ts

- **Implement `project.input`.**
- **Implement `ConsoleEntry.completed` flag.**
- **Add `ConsoleEntry.current`.**
- **docs(changeset): Add a few more APIs to ProjectRun.**

project input

---

.changeset/twelve-pants-bake.md
packages/shared-ui/src/transforms/update-node.ts
packages/visual-editor/src/runtime/edit.ts

- **Autoname only once.**
- **docs(changeset): Autoname only once**

autoname once

---

.changeset/tame-taxis-grow.md
package-lock.json
packages/shared-ui/package.json
packages/shared-ui/src/app-templates/basic/index.ts
packages/shared-ui/src/elements/share-panel/share-panel.ts
packages/shared-ui/src/elements/welcome-panel/gallery.ts
packages/shared-ui/src/elements/welcome-panel/project-listing.ts
packages/shared-ui/src/flow-gen/flowgen-editor-input.ts
packages/shared-ui/src/flow-gen/flowgen-homepage-panel.ts
packages/shared-ui/src/utils/action-tracker.ts
packages/shared-ui/tsconfig.json

- **Introduce `ActionTracker`.**
- **docs(changeset): Introduce `ActionTracker`.**

action tracker

---

packages/unified-server/src/client/app/elements/app-view/app-view.ts

We were initializing the app template every render, instead of once ever. So, we were accumulating lots of redundant event listeners, etc.

[app] Only initialize the app view once instead of every render

---

packages/shared-ui/src/app-templates/basic/index.ts

Reverts breadboard-ai/breadboard#5932 because of some errors in dev

Revert "[sharing] Unflag saving & sharing results"

---

.changeset/loud-mugs-refuse.md
packages/breadboard/src/data/default-run-store.ts
packages/breadboard/src/remote/http.ts
packages/breadboard/src/remote/proxy.ts
packages/breadboard/tests/inspector/default-run-store.ts

- **Don't inflate stored data parts for in-memory run store.**
- **Throw an error instead of reporting it controller.**
- **docs(changeset): Fixes around better handling of data and error reporting.**

fix empty proxy response

---

.changeset/swift-lights-smoke.md
packages/shared-ui/src/elements/elements.ts
packages/shared-ui/src/elements/output/console-view/particle-view.ts
packages/shared-ui/src/elements/output/console-view/particles/update.ts

- **Make particle viewer a switcher.**
- **docs(changeset): Make particle viewer switchable.**

switch particle views

---

.changeset/four-birds-deny.md
packages/shared-ui/src/elements/output/console-view/particles/links.ts
packages/shared-ui/src/elements/output/console-view/particles/update.ts

- **Remove spurious comments.**
- **docs(changeset): Remove spurious comments.**

particle cleanup

---

packages/google-drive-kit/src/board-server/api.ts
packages/google-drive-kit/src/board-server/operations.ts
packages/google-drive-kit/tests/board-server/operations.ts

Reads from both but writes to properties only.

[gdrive] Storing values in properties instead of appProperties

---

.changeset/sour-weeks-wait.md
package-lock.json
packages/particles-ui-demo/.npmignore
packages/particles-ui-demo/README.md
packages/particles-ui-demo/index.html
packages/particles-ui-demo/package.json
packages/particles-ui-demo/src/index.ts
packages/particles-ui-demo/tsconfig.json

- **Create `particles-ui-demo` package.**
- **docs(changeset): Create a new `particles-ui-demo` package.**

particles ui demo

---

.changeset/gentle-papers-marry.md
package-lock.json
packages/particles-ui-demo/package.json
packages/particles-ui-demo/src/state/item.ts
packages/particles-ui-demo/src/state/list.ts

- **Add state bits.**
- **docs(changeset): [particle-ui-demo] Add state bits.**

particles demo state bits

---

.changeset/better-planets-give.md
package-lock.json
packages/particles-ui-demo/package.json
packages/particles-ui-demo/src/generator.ts
packages/particles-ui-demo/src/particles/index.ts
packages/particles-ui-demo/src/receiver.ts
packages/particles-ui-demo/src/state/list.ts
packages/particles-ui-demo/src/types/types.ts
packages/particles/package.json
packages/shared-ui/package.json

- **Start stubbing out the particle bits.**
- **Fix circular deps (whoops)**
- **docs(changeset): Start stubbing out particle bits.**

particle demo particles

---

.changeset/dark-kids-agree.md
packages/particles-ui-demo/src/generator.ts
packages/particles-ui-demo/src/index.ts
packages/particles-ui-demo/src/receiver.ts
packages/particles-ui-demo/src/types/types.ts
packages/particles-ui-demo/src/ui/todo-list.ts
packages/particles-ui-demo/src/ui/ui-receiver.ts

- **Sketch out more of receiver/generator.**
- **docs(changeset): Sketch out more of receiver/generator**

receiver generator

---

packages/google-drive-kit/src/board-server/operations.ts
packages/shared-ui/src/elements/share-panel/share-panel.ts

Sets isShareableCopy to true so that we can query it.

[sharing] Add an isShareableCopy property for querying

---

packages/shared-ui/src/elements/google-drive/google-drive-share-panel.ts

If the user clicks "View Share Permissions" and then very presses "Escape" before the granular sharing dialog (which is a component that we don't control that provides no events relating to opening and closing, so we have to resort to a weird MutationObserver hack to figure out what it's doing), we previously would get in a weird state where the dialog never loads, but we're stuck waiting for it.
Now we handle this by adding a capturing keydown listener for Escape so that we can catch this condition.

[sharing] Add special escape key race handling for granular sharing dialog

---

packages/particles-ui-demo/src/gemini.ts
packages/particles-ui-demo/src/index.ts
packages/particles-ui-demo/src/prompts/codegen-si.ts
packages/particles-ui-demo/src/prompts/si-preamble.md
packages/particles-ui-demo/src/prompts/si.md
packages/particles-ui-demo/src/prompts/si.ts
packages/particles-ui-demo/src/prompts/specgen-si.ts
packages/particles-ui-demo/src/state/item.ts
packages/particles-ui-demo/src/state/list.ts
packages/particles-ui-demo/src/types/particles.ts
packages/particles-ui-demo/src/types/types.ts
packages/particles-ui-demo/src/ui/elements/card.ts
packages/particles-ui-demo/src/ui/elements/list.ts
packages/particles-ui-demo/src/ui/elements/segment.ts
packages/particles-ui-demo/src/ui/ui-receiver.ts

- **Working particle generator.**
- **Add spec-gen.**

particle generator

---

packages/particles-ui-demo/src/demo.ts
packages/particles-ui-demo/src/prompts/codegen-si.ts
packages/particles-ui-demo/src/prompts/spec-guide.md
packages/particles-ui-demo/src/prompts/specgen-si.ts
packages/particles-ui-demo/src/state/item.ts
packages/particles-ui-demo/src/types/particles.ts
packages/particles-ui-demo/src/workbench.ts
packages/particles-ui-demo/vite.config.ts
packages/particles-ui-demo/workbench.html

- **Pre-populate item's presentation if missing.**
- **Add `/workbench` page.**
- **Moar better spec.**

demo demo demo

---

.changeset/grumpy-taxes-bow.md
packages/a2/bgl/bubbled-input-workbench.bgl.json
packages/a2/bgl/src/bubbled-input-workbench/main.ts
packages/breadboard/src/sandbox/capabilities-manager.ts

- **Pass schema correctly into bubbled input handler.**
- **docs(changeset): Pass inputs correctly into bubbled input handler**

bubbled inputs cap

---

.changeset/empty-parts-enter.md
packages/shared-ui/src/app-templates/basic/index.ts
packages/shared-ui/src/elements/output/console-view/console-view.ts
packages/shared-ui/src/state/app-screen.ts
packages/shared-ui/src/state/common.ts
packages/shared-ui/src/state/project-run.ts
packages/shared-ui/src/state/types.ts

- **Add `ProjectRun.progress`.**
- **Somewhat working app view.**
- **Fix the default splash screen not rendering.**
- **docs(changeset): Start using reactive App for rendering activity in App View.**

reactive app view 2

---

.changeset/bumpy-windows-smash.md
packages/shared-ui/src/elements/output/console-view/console-view.ts
packages/shared-ui/src/state/project-run.ts
packages/shared-ui/src/state/types.ts
packages/shared-ui/src/state/work-item.ts

- **Somewhat display elapsed time dynamically.**
- **docs(changeset): Somewhat display elapsed time dynamically.**

elapsed time

---

.changeset/tender-cows-clean.md
packages/shared-ui/src/state/common.ts
packages/shared-ui/src/state/work-item.ts

- **Extract `ParticleReader`.**
- **docs(changeset): Extract `ParticleReader`.**

particlify

---

.changeset/fine-carpets-speak.md
packages/particles/package.json
packages/particles/src/tree.ts
packages/particles/src/types.ts
packages/particles/src/utils.ts
packages/particles/tests/tree.ts
packages/shared-ui/src/state/common.ts

- **Introduce `ParticleOperation`.**
- **Switch to JSON-RPC frames.**
- **Sketch out `ParticleTree.apply`.**
- **docs(changeset): Start implementing particle operations.**

particle operation

---

.changeset/lazy-dodos-wash.md
packages/particles/src/tree.ts
packages/particles/src/types.ts
packages/particles/tests/tree.ts

- **Consolidate insert/append/replace to `upsert`.**
- **Implement `before` support.**
- **Implement `insert` + `replace` semantics.**
- **Better testing, fix bugs.**
- **docs(changeset): Refactor operations to use `upsert` and `remove`.**

particle upsert

---

.changeset/proud-dragons-sit.md
packages/particles-ui-demo/src/ui/ui-receiver.ts
packages/particles-ui/src/types/types.ts
packages/shared-ui/src/state/utils/decorate-particles.ts
packages/shared-ui/src/state/utils/llm-content-to-particles.ts

- **Move `GeneratorProxy` to demo.**
- **Introduce `llmContentToParticles`.**
- **Sketch out `decorateParticle`.**
- **docs(changeset): Start introducing LLM Content -> Particle transformation.**

llm content to particles

---

.changeset/nice-banks-burn.md
packages/shared-ui/src/state/project-run.ts
packages/shared-ui/src/state/types.ts

- **Teach console about multiple active entries**
- **docs(changeset): Teach console about parallelism**

parallel baby

---

packages/visual-editor/src/bootstrap.ts

- Remove a redundant init() function inside of bootstrap()
- Clarify bootstrapArgs vs mainArgs variable names

[cleanup] More minor simplification/clarification on bootstrap

---

.changeset/sour-hoops-win.md
packages/runtime/src/static/orchestrator.ts
packages/runtime/src/static/types.ts
packages/runtime/tests/node/orchestrator.ts

- **Robustify skip-propagation logic.**
- **docs(changeset): Make skip-propagation logic more robust.**

skip propagation

---

.changeset/red-cougars-give.md
packages/runtime/src/harness/plan-runner.ts
packages/runtime/src/static/orchestrator.ts
packages/runtime/src/static/types.ts
packages/runtime/tests/node/orchestrator.ts

- **Add more states to `NodeOrchestratorState`.**
- **Teach orchestrator about processing lifecycle.**
- **Teach PlanRunner about node lifecycle states.**
- **Rename to `NodeLifecycleState`.**
- **docs(changeset): Introduce a more coherent node lifecycle.**

node lifecycle

---

.changeset/stale-dryers-report.md
packages/shared-ui/src/elements/canvas-controller/canvas-controller.styles.ts

Sweating the details on a Friday afternoon. Because it's wot we do.

[shared-ui] Animate theme editor entry

---

.changeset/bumpy-actors-reply.md
packages/visual-editor/src/index.ts

- **Unbreak visual editor.**
- **docs(changeset): Unbreak visual editor.**

unbreak visual editor

---

.changeset/empty-moose-rule.md
packages/runtime/src/static/orchestrator.ts

- **Account for all processing states when checking for completeness.**
- **docs(changeset): Account for all processing states when checking for doneness.**

all processing states

---

packages/visual-editor/src/index.ts

This is caused by the way we try and coordinate board servers via IDB. On the very first sign in, you won't have any IDB state, and we did not have a mechanism for updating the main page once the initialization of the Drive server finishes. That meant on first load, we rendered the home page as though there were no board servers, and then never update, so nothing would work until you reload the whole page again.

[init] Fix bug where on first load galleries would be empty

---

.changeset/plain-mammals-call.md
packages/shared-ui/src/utils/action-tracker.ts
packages/unified-server/src/init.ts
packages/unified-server/src/landing/main.ts
packages/visual-editor/src/index.ts

- **Move initializing analytics into a separate function.**
- **Implement supplying randomly-generated user id to analytics.**
- **Don't send userId at all when not signed-in.**
- **docs(changeset): Send randomly generated user id to Google Analytics for signed-in users.**

better analytics

---

.changeset/strong-lizards-slide.md
packages/types/src/deployment-configuration.ts
packages/unified-server/src/init.ts

- **Implement `ALLOW_3P_MODULES` configuration setting.**
- **docs(changeset): Add `ALLOW_3P_MODULES` configuration setting (off by default).**

allow 3p modules

---

.changeset/grumpy-cobras-notice.md
packages/breadboard/tests/node/run/handler.ts
packages/runtime/src/handler.ts

- **Disallow 3P describer invocations.**
- **docs(changeset): Disallow 3P describer invocations.**

disallow 3p describers

---

.changeset/shaky-vans-fly.md
package-lock.json
packages/ui-tests/package.json

- **Rename ui-tests package to `@breadboard-ai/ui-tests` and mark as private.**
- **docs(changeset): Mark ui-tests as private.**

ui tests private

---

.changeset/chatty-coats-vanish.md
packages/filesystem-board-server/src/filesystem-persistent-backend.ts
packages/visual-editor/src/index.ts

- **Teach file system to ask permission**
- **docs(changeset): Teach file system to ask permission**

fs ask permission

---

.changeset/moody-heads-relate.md
packages/unified-server/src/landing/main.ts

- **Track signInPageView on landing page.**
- **docs(changeset): Track sign in page view on the landing page.**

sign in page view landing

---

.changeset/real-breads-double.md
packages/types/src/deployment-configuration.ts
packages/unified-server/src/server/drive-proxy.ts
packages/unified-server/src/server/main.ts

- **Get only some headers.**
- **Fold router configuration into the handler.**
- **Add GOOGLE_DRIVE_FEATURED_GALLERY_FOLDER_ID deployment config**
- **docs(changeset): Incremental progress toward gallery cache**

gallery cache

---

.changeset/solid-bees-rule.md
docs/updates.json
packages/unified-server/src/server/main.ts
packages/unified-server/src/server/upates.ts

- **Introduce `/updates` endpoint.**
- **docs(changeset): Introduce `/updates` endpoint.**

updates endpoint

---

packages/board-server/src/server/boards/assets-drive.ts
packages/board-server/src/server/boards/index.ts
packages/board-server/src/server/proxy/gcs-aware-fetch.ts
packages/google-drive-kit/src/board-server/drive-list-cache.ts
packages/google-drive-kit/src/board-server/operations.ts
packages/google-drive-kit/src/google-drive-client.ts
packages/unified-server/src/server/drive-proxy.ts
packages/unified-server/src/server/main.ts
packages/visual-editor/src/index.ts

[drive] Opt-in experiment for public drive files proxy

---

packages/unified-server/src/server/main.ts

[drive] Disable the FE server drive proxy

---

packages/shared-ui/src/utils/signin-adapter.ts

Let's just store the scopes exactly as they come back from the servers.

[signin] Only do scope canonicalization when we're checking scopes

---

packages/google-drive-kit/src/google-drive-client.ts
packages/unified-server/src/server/main.ts

Temporary test that tries to do some Google Drive reads at startup. For testing service accounts.

[drive] Add temporary drive read test to unified-server

---

.changeset/bitter-symbols-open.md
packages/shared-ui/src/elements/step-editor/renderer.ts

This is a tweak PR to change the styles & icon used in the duplicate menu on graph

[shared-ui] Tweak styles & icon for duplicate

---

.changeset/plain-gifts-run.md
packages/unified-server/landing/styles/landing.css

- **Adjust the z-index of Sign in button.**
- **docs(changeset): Make Sign in button clickable on narrow screens.**

clickable sign in

---

.changeset/soft-breads-heal.md
packages/visual-editor/src/commands/commands.ts

This is a quality-of-life PR that, when a user pastes plain text, will create for them a new Generate step with the content from the clipboard.

[visual-editor] Allow pasting of plain text content

---

.changeset/social-hounds-attend.md
packages/shared-ui/src/elements/shell/header.ts
packages/shared-ui/src/state/utils/decode-error.ts
packages/shared-ui/src/utils/action-tracker.ts
packages/visual-editor/src/index.ts

- **Start tracking errors in GA.**
- **Track more flavors of remix.**
- **docs(changeset): Track remix events more precisely and start tracking error events.**

track more

---

.changeset/tired-friends-behave.md
packages/shared-ui/src/flow-gen/flow-generator.ts

- **Don't pass empty graph to flowgen.**
- **docs(changeset): Fix "Untitled Flow" bug in flowgen.**

flowgen title

---

.changeset/heavy-taxis-swim.md
package-lock.json
packages/shared-ui/src/elements/shell/header.ts
packages/visual-editor/src/event-routing/board/board.ts
packages/visual-editor/src/index.ts

There is a little flakiness / inconsistency when using the Remix button. This PR neatens things up in a few ways:
1. It enables the `inert` attribute on the header whenever there is a blocking action. This means that when there's something blocking (like remixing a board) it should now prevent multiple clicks of the button.
2. The checks in the remix button are slightly more relaxed since the `inert` takes place of the former behavior that disabled the button when clicked (also in an attempt to avoid multiple clicks).
3. We show the remix acknowledgment right at the start of the handler before any work begins so that the user is assured that the action has begun.

[su/ve] Improve behavior of Remix button

---

.changeset/flat-loops-boil.md
packages/shared-ui/src/app-templates/basic/index.ts
packages/shared-ui/src/directives/markdown.ts
packages/shared-ui/src/elements/input/text-editor/text-editor.ts
packages/utils/src/sanitizer.ts
packages/utils/tests/node/sanitizer.test.ts

[shared-ui] Rename functions for clarity

---

.changeset/clear-rocks-film.md
packages/shared-ui/src/flow-gen/flowgen-in-step-button.ts

The step's inline NL editor was inconsistent with the styles of the graph NL editor. This PR updates the styling so that they match more closely.

[shared-ui] Update flowgen in step styles

---

.changeset/violet-news-sip.md
packages/google-drive-kit/src/google-drive-client.ts

- **Bring back retryableFetch.**
- **docs(changeset): Bring back retryableFetch.**

retryable fetch again

---

.changeset/bitter-olives-sleep.md
packages/unified-server/package.json

- **Update bucket name.**
- **docs(changeset): Update the bucket name.**

update bucket name

---

.changeset/thick-hairs-own.md
packages/shared-ui/src/elements/step-editor/entity.ts

Smallest tweak to make `Entity`s able to watch `Signal`s

[shared-ui] Make Entity a SignalWatcher

---

.changeset/metal-pillows-eat.md
packages/unified-server/src/server/csp.ts

- **Add cloudflare CDN to CSP script allowlist**
- **docs(changeset): Add Cloudflare CDNJS to CSP script allow list**

csp cloudflare

---

.changeset/tired-points-burn.md
package-lock.json
packages/data/package.json
packages/data/src/index.ts
packages/data/src/inline-all-content.ts
packages/data/src/save-outputs-as-file.ts
packages/shared-ui/src/app-templates/basic/index.styles.ts
packages/shared-ui/src/app-templates/basic/index.ts

- **Extract `inlineAllContent` and place it into `data` package.**
- **Add "Export Outputs" button.**
- **Working save outputs end-to-end.**
- **Rename to "Download file".**
- **docs(changeset): Implement "Download file" option**

export outputs

---

.changeset/olive-comics-film.md
packages/runtime/src/harness/plan-runner.ts
packages/runtime/src/static/orchestrator.ts
packages/runtime/tests/node/orchestrator.ts
packages/shared-ui/src/elements/step-editor/graph-node.ts
packages/shared-ui/src/elements/toast/snackbar.ts
packages/shared-ui/src/events/node/node.ts
packages/shared-ui/src/state/project-run.ts
packages/shared-ui/src/state/types.ts
packages/types/src/harness.ts
packages/visual-editor/src/event-routing/node/node.ts
packages/visual-editor/src/index.ts

- **Plumb action back to ProjectRun.**
- **Write out state transitions (no impl)**
- **Plumb state transitions to HarnessRunner.**
- **Stub out new PlanRunner APIs.**
- **Record success after failures in orchestrator.**
- **Teach orchestrator about ad-hoc node running.**
- **Handle error dismissal nicely.**
- **docs(changeset): Initial support for action buttons in Visual Editor**

working action buttons

---

.changeset/common-bears-leave.md
packages/runtime/src/harness/plan-runner.ts
packages/runtime/src/harness/run.ts
packages/runtime/src/remote/http.ts
packages/runtime/src/remote/proxy.ts
packages/runtime/src/remote/types.ts
packages/runtime/src/static/orchestrator.ts
packages/shared-ui/src/state/project-run.ts
packages/types/src/harness.ts

- **Teach runtime about stop action.**
- **Stop actually works now.**
- **Get latest config when invoking a node.**
- **docs(changeset): Teach runtime about stop actions.**

runtime stop action

---

packages/google-drive-kit/src/board-server/server.ts
packages/shared-ui/src/utils/urls.ts
packages/unified-server/src/init.ts
packages/visual-editor/src/index.ts

And update a few spots to allow as much of the UI to render as possible (currently with various errors if you try and do something that requires signin).

[signed out experience] Add dev-allow-anonymous url param for testing future signed out experience

---

.changeset/silver-readers-shout.md
packages/runtime/src/harness/events.ts
packages/runtime/src/harness/plan-runner.ts
packages/runtime/src/static/orchestrator.ts
packages/runtime/tests/node/orchestrator.ts
packages/shared-ui/src/elements/step-editor/graph-node.ts
packages/shared-ui/src/elements/step-editor/graph.ts
packages/shared-ui/src/state/project-run.ts
packages/shared-ui/src/state/types.ts
packages/types/src/harness.ts
packages/types/src/orchestration.ts
packages/types/src/run-status.ts

- **Map NodeRunStatus to NodeLifecycleState**
- **Do not skip when processing.**
- **Propagate node state changes to renderer.**
- **Make breakpoints actually work.**
- **Types clean-up.**
- **Correctly update app view progress.**
- **Stop progress when hitting breakpoint.**
- **docs(changeset): Properly display status and react to actions.**

runtime status improved

---

.changeset/strong-beers-invite.md
packages/breadboard/src/editor/events.ts
packages/breadboard/src/editor/graph.ts
packages/breadboard/src/editor/operations/add-edge.ts
packages/breadboard/src/editor/operations/add-node.ts
packages/breadboard/src/editor/operations/change-edge.ts
packages/breadboard/src/editor/operations/remove-edge.ts
packages/breadboard/src/editor/operations/remove-node.ts
packages/breadboard/src/inspector/graph-store.ts
packages/breadboard/src/inspector/graph/event.ts
packages/breadboard/src/inspector/graph/mutable-graph.ts
packages/breadboard/src/inspector/graph/node-describer-manager.ts
packages/breadboard/src/inspector/graph/node-type-describer-manager.ts
packages/runtime/src/harness/plan-runner.ts
packages/runtime/src/static/create-plan.ts
packages/runtime/src/static/orchestrator.ts
packages/runtime/tests/node/create-plan.ts
packages/shared-ui/src/state/project-run.ts
packages/shared-ui/src/state/project.ts
packages/types/src/edit.ts
packages/types/src/harness.ts
packages/types/src/inspect.ts

- **Mostly working topology-aware ProjectRun.**
- **Write "graphchange" to ProjectRun.**
- **Working reactive runner.**
- **Add orchestrator update to preserve outputs.**
- **Add the logic to weed out standalone nodes.**
- **docs(changeset): Teach new runtime to respond to graph topology changes.**

topology aware

---

.changeset/quick-roses-sell.md
packages/shared-ui/src/elements/step-editor/graph-node.ts
packages/shared-ui/src/elements/tooltip/tooltip.ts

This PR is a tweak to add tooltips for the graph node actions so that the user knows what to expect when they click on the button.

[su] Add tooltips for graph node actions

---

packages/shared-ui/src/elements/shell/modal.ts
packages/shared-ui/src/elements/shell/sign-in-modal.ts

Also adds a new "basic" vs "complex" distinction to bb-modal, where "basic" has a larger & centered title, more padding, and rounder corners.

[signin] Update new sign-in modal design (initial state)

---

packages/shared-ui/src/elements/shell/header.ts
packages/shared-ui/src/elements/shell/sign-in-modal.ts

Also improve hover contrast of the remix/share button.

[new signin] A few more signin design tweaks

---

packages/runtime/src/harness/plan-runner.ts
packages/runtime/src/static/orchestrator.ts
packages/runtime/tests/node/orchestrator.ts
packages/shared-ui/src/app-templates/basic/index.ts
packages/shared-ui/src/state/app.ts
packages/shared-ui/src/state/project-run.ts
packages/shared-ui/src/state/types.ts
packages/shared-ui/src/utils/top-graph-observer/top-graph-observer.ts
packages/types/src/harness.ts

- **Rename `App.current` to `App.last`.**
- **Introduce `App.current` again.**
- **Teach Orchestrator to recognize working/waiting states when advancing stages.**
- **Add more tests.**
- **Better tests.**
- **Fix typo.**
- **Remove unused code.**
- **Distinguish between successful and unsuccessful finish.**
- **Make pause and resume events dispatch properly**

app view runtime

---

packages/shared-ui/src/elements/welcome-panel/project-listing.ts
packages/visual-editor/src/index.ts

Mostly stuff relating to handling multiple board servers.

[cleanup] Delete a bunch of unused code on homepage

---

package-lock.json
packages/connection-client/src/oauth-scopes.ts
packages/mcp-gmail/package.json
packages/mcp-gmail/src/gmail-client.ts

- **Implement listing threads and emails.**
- **Change Gmail scopes to `.modify`.**
- **Add ability to send messages and create drafts.**

mcp gmail part 2

---

packages/a2/src/a2/common.ts
packages/a2/src/a2/gemini-prompt.ts
packages/a2/src/a2/gemini.ts
packages/a2/src/generate-text/main.ts
packages/a2/src/mcp/connector-tools.ts
packages/a2/src/mcp/mcp-client.ts
packages/a2/src/mcp/types.ts
packages/mcp/src/built-in/gcal-client.ts
packages/mcp/src/built-in/gdrive-client.ts
packages/mcp/src/built-in/gmail-client.ts
packages/mcp/src/builtin-server-store.ts
packages/mcp/src/client-manager.ts
packages/mcp/src/manager.ts
packages/mcp/src/mcp-fs-backend.ts
packages/mcp/src/types.ts
packages/shared-ui/src/app-templates/shared/utils/app-screen-to-particles.ts
packages/visual-editor/src/index.ts

- **Send retry reports on 500 et al. errors.**
- **Add `retrievalMode` to GDrive client and introduce built-in client context.**
- **Implement "save outputs" functionality.**
- **Fix particle conversions.**

mcp gdrive 2

---

packages/shared-ui/src/elements/share-panel/share-panel.ts

Same exact bug as https://github.com/breadboard-ai/breadboard/pull/6741, but manifesting in an even-more subtle way, and I didn't catch all the spots before.
Also fixes/expands a couple log statements that would have been helpful in debugging this.

Fix bug relating to permissions when publishing featured opals
